### ISSUE TITLE
谷歌搜索跳转百度搜索的改进意见

### ISSUE THREAD

**Issue by pluveto** [F9y4ng/GreasyFork-Scripts#1]
希望可以直接获取搜索框的实时值，不然打开发现是旧的搜索词会很麻烦

**Comment by F9y4ng** [comment]
Google 搜索框存在新的动态遮罩层，获取input的value时是旧的搜索词，这个问题应该会在下个版本更新中修正。

**Comment by F9y4ng** [comment]
@Version 2.3.20210517.1 已修正该Bug.
