### ISSUE TITLE
请问能否在不修改字体的情况下单独修改描边和阴影？

### ISSUE THREAD

**Issue by Jed-Z** [F9y4ng/GreasyFork-Scripts#10]
有些网页内嵌了字体，该脚本似乎会将其强制修改为自己设置的字体（如微软雅黑）。
能否再保留网页原本字体的情况下，只用该脚本修改描边和阴影呢？

**Comment by F9y4ng** [comment]
嗯，我有注意到这个问题，因为涉及到多网站数据的存储问题没有很好的处理办法，所以一直没修改。

下个版本的更新可暂时性将字体选择与字体重写复用，关闭字体重写即关闭字体的整体替换功能。

**Comment by F9y4ng** [comment]
version 2021.07.11.2 已实现字体替换关闭功能。
