### ISSUE TITLE
英文网站不美观

### ISSUE THREAD

**Issue by Yumega** [F9y4ng/GreasyFork-Scripts#100]
作者的脚本对中文网站支持非常好，很舒服
mactype助手脚本对英文网站支持非常好，看起来很舒服

**Comment by F9y4ng** [comment]
这本就是优化中文字体显示效果的脚本，你在纯英文网站用中文字体进行渲染肯定效果不好，这毫无疑问。

## 建议
在纯英文网站关闭字体替换功能，即：把字体重写开关关闭，保存为站点独享。

遇到问题建议你先仔细看看使用文档WIKI，如果没有解决办法再发起ISSUES.
