### ISSUE TITLE
[发现错误] NGA论坛帖子正文文字渲染不正常

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [F9y4ng/GreasyFork-Scripts#105]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

NGA帖子正文不渲染

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_ https://bbs.nga.cn/read.php?tid=32584576
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

恢复之前的渲染效果。
帖子正文文字渲染 v2022.07.03.1 正常

![2](https://user-images.githubusercontent.com/101876873/178190346-ed3572cc-636f-4f4f-ac96-565d209f1782.png)

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

v2022.07.09.1 不正常

![1](https://user-images.githubusercontent.com/101876873/178190365-bf532608-9710-4865-a112-6a68a029e1d9.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器 [_如 Chrome_]：chrome
- 版本 [_如 93.0.4577.63_]：103.0.5060.114
- 脚本扩展 [_如 TamperMonkey_]：暴力猴
- 脚本扩展版本 [_如 4.13.6138_]：v2.13.0
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染（自用脚本）
- 运行的脚本版本 [_如 V3.8.20210101.1_]：v2022.07.09.1
- 其他信息：无

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

已排除

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

已排除

**附加信息**  （在此处添加有关此问题的任何附加信息）

无

**Comment by F9y4ng** [comment]
在 **排除渲染的HTML标签** 中，找到并删除 `,pre,pre *,code,code *`，保存为站点独享即可。
