### ISSUE TITLE
[发现错误] Courier New is applied when '字體重寫' is not enabled

### ISSUE THREAD

**Issue by ICHx** [F9y4ng/GreasyFork-Scripts#106]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
 Courier New is applied to the style-less webpage when '字體重寫' is not enabled.

In the browser, Consolas is used by default.  When the script is enabled while '字體重寫' is disabled, the very thin font 'Courier New' is used instead.  This hurt readability a lot.

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_ https://esbenp.gallerycdn.vsassets.io/extensions/esbenp/prettier-vscode/9.5.0/1648513363698/Microsoft.VisualStudio.Services.Content.License

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
![image](https://user-images.githubusercontent.com/11556527/179146967-ec443881-a4a9-4adc-aa3a-304bbbcb5243.png)

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/11556527/179146948-eaf735b5-ed7e-45ba-821f-30d0f3791ad7.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：WIn10
- 浏览器 [_如 Chrome_]：Edge
- 版本 [_如 93.0.4577.63_]：103.0.1264.49 (Official build) (64-bit) 
- 脚本扩展 [_如 TamperMonkey_]：Violentmonkey
- 脚本扩展版本 [_如 4.13.6138_]：v2.13.0
- 运行的脚本名称 [_如 Font Rendering_]： Font Rendering
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.07.09.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ 

uBlock Origin

- 是否同时运行了其他油猴脚本？

nope

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
控制英文等宽字体的设置不在“**字体重写**”开关（脚本中字体重写是针对中文字体或非等宽英文字体设定的），需要排除对英文等宽字体的设定，要在**排除渲染的HTML标签**中，查到并删除`,pre,pre *,code,code *`
