### ISSUE TITLE
在 Brave 上字体渲染效果随机失效

### ISSUE THREAD

**Issue by Fujiwara-Chika** [F9y4ng/GreasyFork-Scripts#109]
电脑是新的，系统是新的，脚本是新的。
Edge 上正常渲染，Brave 上随机失效，大概重启个几十次有个一两次可以正常渲染几个网站，然后就变成微软雅黑。
设置的字体是鸿蒙黑体，现在选项里直接没了
手动添加了`{"ch":"鸿蒙黑体", "en":"HarmonyOS Sans SC", "ps":"HarmonyOS_Sans_SC"}`
还是没有。
字体已正确安装。

**Comment by F9y4ng** [comment]
抱歉，因精力有限，仅对主流浏览器及主流脚本管理器扩展（稳定/正式版本）进行兼容测试，小众（或国内魔改）浏览器及小众脚本管理器扩展不做兼容处理。如有特别需求请尝试其他同类扩展或浏览器脚本使用。

> 不同内核的浏览器对字体的解析是不同的，尤其某些小众、或魔改的浏览器对字体的兼容性及其糟糕，所以不会花费更多的精力在此。

## 自定义字体的添加判断逻辑
1. 内置字体表中的字体优先级最高（不会删除），自定义字体表优先级最低（会被删除）；
2. 与内置字体表重复的字体、或自定义字体表中有重复添加的字体会在保存时自动删除；
3. 判断字体重复的逻辑是同时判断中文字体名称与英文字体名称，如有其一相同即判定重复；

**Comment by Fujiwara-Chika** [comment]
> 抱歉，因精力有限，仅对主流浏览器及主流脚本管理器扩展（稳定/正式版本）进行兼容测试，小众（或国内魔改）浏览器及小众脚本管理器扩展不做兼容处理。如有特别需求请尝试其他同类扩展或浏览器脚本使用。
> 
> > 不同内核的浏览器对字体的解析是不同的，尤其某些小众、或魔改的浏览器对字体的兼容性及其糟糕，所以不会花费更多的精力在此。
> 
> ## 自定义字体的添加判断逻辑
> 1. 内置字体表中的字体优先级最高（不会删除），自定义字体表优先级最低（会被删除）；
> 2. 与内置字体表重复的字体、或自定义字体表中有重复添加的字体会在保存时自动删除；
> 3. 判断字体重复的逻辑是同时判断中文字体名称与英文字体名称，如有其一相同即判定重复；

Brave 是 Chromium 内核

**Comment by F9y4ng** [comment]
> Brave 是 Chromium 内核

与chrome++这个插件道理相同，都对浏览器内核有过较大的改动或hook操作，仅仅是内核名字一样而已。

建议：如要使用非主流浏览器，请尝试其他扩展或脚本。

**Comment by F9y4ng** [comment]
使用Brave浏览器开启“**Brave Shields**”在某些站点上会因其某些屏蔽功能造成脚本失效，处理办法如下：

1. 全局关闭
打开浏览器`设置`-->`屏蔽`-->`阻止指纹识别`-->选择 `已停用`。

2. 手动关闭
在脚本失效的网站，点击“**Brave Shields**”图标，打开 `高级控制` 菜单，将`阻止指纹识别` 改为 `允许指纹识别`。
