### ISSUE TITLE
在Safari上显示错误（如图所示）

### ISSUE THREAD

**Issue by Easonnnone** [F9y4ng/GreasyFork-Scripts#11]
在Safari上使用该功能后，很多网站显示出了问题（如下图所示）
![Snipaste_2021-07-14_08-57-40](https://user-images.githubusercontent.com/8055993/125545498-a13200bf-8177-4ec2-846a-dfaeb4f45f08.jpg)
![Snipaste_2021-07-14_08-57-59](https://user-images.githubusercontent.com/8055993/125545501-585760bb-6cba-464f-b89b-28dc63db70e2.jpg)

**Comment by F9y4ng** [comment]
那是因为你更换的新字体的字符宽度比网站本身定义的字体字符宽度大，且该网站网页样式又对容器宽度做了限制，所以才会出现文字换行，重叠的情况。这种情况你只能选择使用其他适当的字体，或者把该网站加入排除列表，不进行字体渲染。同样，使用描边、阴影也会增加字符宽度，有几率出现你遇到的问题。
