### ISSUE TITLE
请支持下brave浏览器，brave浏览器不能读取安装的字体

### ISSUE THREAD

**Issue by 194328373** [F9y4ng/GreasyFork-Scripts#112]
请支持下brave浏览器，brave浏览器不能读取安装的字体

**Comment by F9y4ng** [comment]
该问题属于Brave浏览器自身的兼容性问题，由于精力有限，只对主流浏览器进行兼容性测试，其他小众或魔改浏览器不做过多处理。如需使用该浏览器请尝试其他扩展或脚本。

**Comment by F9y4ng** [comment]
使用Brave浏览器，参阅 #109 处理办法。
