### ISSUE TITLE
[新增功能]  根据语种替换字体

### ISSUE THREAD

**Issue by m3lab-zzl** [F9y4ng/GreasyFork-Scripts#113]
首先多谢作者开发的这个脚本！🎉

但是目前似乎无法根据网页文字的语种来分别替换字体（WIKI和已有issue未找到此问题）。
我尝试在自定义字体表里设置 {"ch":"微软雅黑",""en":"Arial"}但是无效，这个表的意思不是我理解的中英文分别设置，而是同一个字体的中英文名称。

建议参考Microsoft 365的功能，中文设置微软雅黑，英文可设置为Arial或类似字体。 

如果可以的话，最好还能提供其他语种的选择权。

**Comment by F9y4ng** [comment]
你需要的答案在Discussions中。😅

**Comment by m3lab-zzl** [comment]
多谢，已成功设置
