### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by yaoxiaobo** [F9y4ng/GreasyFork-Scripts#115]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":".Not/A)Brand","version":"99"},{"brand":"Google Chrome","version":"103"},{"brand":"Chromium","version":"103"}],"mobile":false,"model":"","platform":"Windows","platformVersion":"8.0.0","uaFullVersion":"103.0.5060.53"}
脚本扩展信息：Tampermonkey 4.16.1
脚本版本信息：2022.07.16.1
当前访问域名：
错误信息：[Redundant Scripts]: 发现冗余安装的“字体渲染（自用脚本）”脚本，请删除重复脚本保留其一。

**错误再现**  （重现行为的步骤）

1. _在不同网页都出现了同样的报错。有些网页打开就报错，有些网页并没有报错。
2. 按照报错信息提示，查看油猴脚本，没有发现重复安装的现象。

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
希望能给出解决方案，感谢！

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：
- 浏览器 [_如 Chrome_]：
- 版本 [_如 93.0.4577.63_]：
- 脚本扩展 [_如 TamperMonkey_]：
- 脚本扩展版本 [_如 4.13.6138_]：
- 运行的脚本名称 [_如 Font Rendering_]：
- 运行的脚本版本 [_如 V3.8.20210101.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
同时运行了很多油猴脚本。所有脚本截图所下所示。

**附加信息**  （在此处添加有关此问题的任何附加信息）
![image](https://user-images.githubusercontent.com/33094915/181222591-67b75c31-2662-49ce-9500-fb948539d5e9.png)
![image](https://user-images.githubusercontent.com/33094915/181222714-2632bd1b-6893-41cf-a458-76422d15f1e3.png)
![image](https://user-images.githubusercontent.com/33094915/181222771-e21d47cc-d686-4285-973e-60d6dee36118.png)

**Comment by F9y4ng** [comment]
1. 你先需要排除本地的脚本、扩展的冲突问题，逐一关闭脚本或仅打开“字体渲染（自用脚本）”脚本后重新尝试。
2. 排除本地冲突问题后，如问题依旧，参阅 #58 排查问题。

**Comment by Fujiwara-Chika** [comment]
把油猴扩展（不是脚本）禁用再启用就会这么报错

**Comment by F9y4ng** [comment]
> 把油猴扩展（不是脚本）禁用再启用就会这么报错

那是页面缓存造成的问题，扩展的重复开启会使脚本多次加载，刷新页面即可解决。
