### ISSUE TITLE
[发现错误] firefox 103.0出错

### ISSUE THREAD

**Issue by whjkd2005** [F9y4ng/GreasyFork-Scripts#116]
浏览器信息：mozilla/5.0 (windows nt 10.0; win64; x64; rv:103.0) gecko/20100101 firefox/103.0
脚本扩展信息：Violentmonkey 2.13.0
脚本版本信息：2022.07.16.1
当前访问域名：github.com
错误信息：[Fonts shadowColor]: TypeError: window.frColorPicker is not a constructor

**Comment by F9y4ng** [comment]
1. 我本地不能复现你的所遇到的问题。
2. 从错误报告上看，是由于拾色器相关部分代码加载不成功所致。尝试单独访问 [https://greasyfork.org/](https://greasyfork.org/) 是否能正确打开。
3. 稍候一段时间，再重新尝试。
