### ISSUE TITLE
大佬,,,修改字体和大小之后,整体向右偏...咋整.

### ISSUE THREAD

**Issue by zeled520** [F9y4ng/GreasyFork-Scripts#118]
就是起点的个人书架比较显眼,他正居中,放大后就整体偏右了

**Comment by F9y4ng** [comment]
我没有起点中文网的账户，不过大部分因脚本缩放而出现不水平居中的都是通过padding-left,margin-left等方式强制居中的，而非自动居中排版。正常通过自动居中排版的网站不会发生此问题。

所以，遇到此类网站只能建议你不使用脚本级的缩放控制，而使用浏览器级缩放(ctrl+或ctrl-)。

**Comment by F9y4ng** [comment]
起点的问题竟然是width定义为100vw造成的，首次遇到此类问题，下个周更新会处理此问题。
