### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [F9y4ng/GreasyFork-Scripts#12]
希望增加360、搜狗等搜索引擎。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by F9y4ng** [comment]
暂无此计划。

**Comment by AisinGioroKiIoi** [comment]
日后可以考虑一下，不限于以上，多一种引擎多一种选择。尤其是对我们这种谷歌无法访问，百度间歇性无法使用的用户。ᠪᠠᠨᡳᡥᠠ（巴尼哈/谢谢）

**Comment by HumanMus1c** [comment]
确实，对搜狗和夸克有需求，但是目前不急用
