### ISSUE TITLE
[新增功能] 能否增设“只在指定某些域名生效，其他所有域名均不渲染”的功能

### ISSUE THREAD

**Issue by DRNeunzehn** [F9y4ng/GreasyFork-Scripts#121]
**您的功能请求是否与问题有关？请描述。** （清晰简明地描述遇到的问题是什么)
使用本插件只为了解决某些特定网站的字体显示等问题，但在其他所有网站上都并不需要它的功能生效

**描述您想要的解决方案** （清晰简明地描述您想要发生的事情）
能否增加一个功能，“仅在指定的某些域名生效，其他任何域名默认不启动该插件功能”
例如一个开关，打开之后“仅在下方框内输入的网址才会生效”

**Comment by F9y4ng** [comment]
凡事皆在变通，不是么？😀

1. 将所有设置项目关闭，保存为全局数据。
2. 在你需要的站点进行参数配置，保存为站点独享，这不就是你想要的效果了么？

**Comment by DRNeunzehn** [comment]
原来如此，多谢指导！
不过建议可以把这条顺便写进说明里，“只想在特定网页生效的解决策略”，也就不容易再有人问类似问题，要一一解答了
