### ISSUE TITLE
为啥必应是cn.bing去搜索，而不是bing？

### ISSUE THREAD

**Issue by mx4994** [F9y4ng/GreasyFork-Scripts#123]
我自己分流规则里，bing.com是走代理，所以不会被重定向到CN，今天用了这个脚本，发现bing.com居然有了国内版、国际版之分，才发现脚本里面是用cn.bing去搜索的，希望解答一下。

第二个疑问，字体渲染脚本里面的更新提示功能，我一直没收到过更新提示，都是自己点击脚本主页去更新的，油猴管理器有自带的更新检查，为啥不用管理器的呢？

还有一个建议，能不能给谷歌添加一个页面居中选项，大屏幕左边显示太不利于阅读了。（虽然现在有现成的脚本，但我还是希望能直接集成）

字体渲染这个脚本做的蛮不错的，可以放个打赏二维码，收点饮料钱。

**Comment by F9y4ng** [comment]
> 我自己分流规则里，bing.com是走代理，所以不会被重定向到CN，今天用了这个脚本，发现bing.com居然有了国内版、国际版之分，才发现脚本里面是用cn.bing去搜索的，希望解答一下。

因为没考虑过bing通过代理访问的情况。国内IP基本都是被跳转到cn.bing，之前的www4.bing, globle.bing 也统统被强制跳转到cn.bing了，所以直接就cn.bing了。如果你走代理可以将cn.bing手动改为www.bing，或者以后的某个更新中我会默认走www.bing，这会使国内IP访问增加一次302跳转。

> 第二个疑问，字体渲染脚本里面的更新提示功能，我一直没收到过更新提示，都是自己点击脚本主页去更新的，油猴管理器有自带的更新检查，为啥不用管理器的呢？

字体渲染脚本的更新提示，是在脚本成功更新后发出的通知，代码本身并没有添加自动更新功能。你所看到的更新就是通过脚本管理的更新检查完成的。脚本只是检测到完成新更新后，提示新的更新内容：如修正哪些错误，新增哪些功能，或者额外需要特别注意的操作等等。

> 还有一个建议，能不能给谷歌添加一个页面居中选项，大屏幕左边显示太不利于阅读了。（虽然现在有现成的脚本，但我还是希望能直接集成）

你知道的，我很懒的。

> 字体渲染这个脚本做的蛮不错的，可以放个打赏二维码，收点饮料钱。

自由、平等、分享  才是我们这些老家伙的互联网世界观。

**Comment by mx4994** [comment]
我记得之前cn.bing重定向过多会停止服务，感觉还是得增加一个bing.com的选项，或者手动改。

就是脚本都没有收到过更新提醒，才感到疑惑，以为功能失效了；今天删掉重新安装了，可能是以前手动降级了，导致不会主动检测更新。

>自由、平等、分享 🤑

肃然起敬了😂

**Comment by F9y4ng** [comment]
> 就是脚本都没有收到过更新提醒，才感到疑惑，以为功能失效了；今天删掉重新安装了，可能是以前手动降级了，导致不会主动检测更新。

在 Tampermonkey 中，任何修改保存脚本的行为都会使脚本管理器的对该脚本的自动更新功能失效，需要手动恢复。

**Comment by mx4994** [comment]
😂确实手动改过，我还以为我降过级呢。
又是一个冷知识。
