### ISSUE TITLE
[发现错误] 显示错误

### ISSUE THREAD

**Issue by pkudeader** [F9y4ng/GreasyFork-Scripts#124]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
https://booklink.me/book-1-1033893441.html
该页面使用微软雅黑渲染后，后方日期位置换行出现错误，之前版本（无法确定是哪一版）无错误。

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_   https://booklink.me/book-1-1033893441.html
2. _使用字体渲染_
3. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
换行无误

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器 [_如 Chrome_]：Chromium 
- 版本 [_如 93.0.4577.63_]：102.0.5005.167
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：4.16.1
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.08.27.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
参阅 #83
