### ISSUE TITLE
[发现错误] 开启“字体阴影尺寸”功能后，网页字体会有彩边

### ISSUE THREAD

**Issue by is-hejun** [F9y4ng/GreasyFork-Scripts#126]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
开启“字体阴影尺寸”功能后，网页字体会有彩边

**错误再现**  （重现行为的步骤）

1. https://www.zhihu.com/question/29290583
2. 使用截图软件对“Chrome 字体发虚模糊是因为什么？”进行截图，然后放大“字”的部分，会发现彩边
3. 相关参数：
苹方-简
字体重写（默认：开）ON
字体平滑（默认：开）ON
字体描边尺寸（粗体修正）0.05
字体阴影尺寸 0.05
阴影颜色
#7B7B7BCC
需要渲染的网页元素：默认
排除渲染的HTML标签：默认
4.取消“字体阴影尺寸”，即设置为0后，就没有彩边

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
消除彩边
**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/31362942/188087005-56fa80a8-824e-4d5c-8aa8-e7ca9cc9efa4.png)
**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器 [_如 Chrome_]：chrome
- 版本 [_如 93.0.4577.63_]：版本 104.0.5112.102（正式版本） （64 位）
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：
- 运行的脚本名称 [_如 Font Rendering_]：
- 运行的脚本版本 [_如 V3.8.20210101.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
uBlock Origin
- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
你可以自行调整**阴影颜色**的值（包含但不限于颜色、深浅、透明度等参数），来满足你的视觉需求。

## 小提示
将**阴影颜色**设置为FFFFFFFF等纯白色代码可以使用默认currentcolor来定义阴影颜色。

**Comment by is-hejun** [comment]
谢谢大佬回复。
将字体阴影尺寸设置为 0.05 阴影颜色currentcolor后，彩边减轻。
但是仍然比设置为0严重。

**Comment by F9y4ng** [comment]
> 谢谢大佬回复。 将字体阴影尺寸设置为 0.05 阴影颜色currentcolor后，彩边减轻。 但是仍然比设置为0严重。

你将页面放大至500%，然后查看字体边缘，那根本就不存在什么色差，你所看到的色差是因为图片压缩造成的。所以不要以截图来判断你的渲染结果。

![test](https://user-images.githubusercontent.com/15855068/188098972-bc4e5c5a-ec1c-479f-9642-10412ac69a90.png)

**Comment by is-hejun** [comment]
1.我发现彩边现象是首先眼睛感觉不舒服，然后使用截图放大查看进行验证
2.按照大佬的将网页放大至500%，彩边现象肉眼可见的消失，进行截图后放大，发现彩边现象也消失了
3.在Firefox里同样的网页同样的位置进行截图，没有彩边，截图如下：
![image](https://user-images.githubusercontent.com/31362942/188101127-4746b8c6-cb35-4657-8d6a-f89163d0c6df.png)
肉眼也没有感觉到彩边
4.将大佬的脚本关闭后也能发现彩边，截图如下：
![image](https://user-images.githubusercontent.com/31362942/188102165-cd1b26c8-98bb-467a-941b-92c3830b2674.png)
只是要比脚本开启减轻一些，
5.所以，彩边现象与大佬的脚本应该没有关系，是chrome的锅
6.感谢大佬百忙之中的回复
