### ISSUE TITLE
[发现错误] 字体渲染脚本会导致Google相关网站的按钮控件显示异常

### ISSUE THREAD

**Issue by Sostay** [F9y4ng/GreasyFork-Scripts#129]
![image](https://user-images.githubusercontent.com/6897274/188438950-506b3653-b86a-4b33-b0f6-0b0a7115c0e2.png)

目前已发现受影响的两个地方（上图左侧为开启脚本效果，右侧为关闭效果）

https://play.google.com
`<span aria-hidden="true">google_logo Play</span>`

https://podcasts.google.com
`<span class="DPvwYc" aria-hidden="true">playlist_add</span>`

**客户端信息：
- 操作系统 [_Windows 11_]：
- 浏览器 [_Edge 版本 105.0.1343.27 (正式版本) (64 位)_]：
- 脚本扩展 [_TamperMonkey_]：
- 脚本扩展版本 [_2022.09.03.1_]：

**Comment by Sostay** [comment]
是字体冲突吗？在开发者工具里关掉字体css就能正常显示~

**Comment by F9y4ng** [comment]
你已经自己找到的样式问题的所在位置，只是需要通过一些样式过滤的方式来实现。

## 解决办法：

https://play.google.com/
在**需要渲染的网页元素**中，追加 `:not(a.f0UV3d,a.f0UV3d>span)`，保存为站点独享即可。

https://podcasts.google.com/
在**需要渲染的网页元素**中，追加 `:not(span[class][aria-hidden='true'])`，保存为站点独享即可。

**Comment by Sostay** [comment]
好的 已解决，感谢！
