### ISSUE TITLE
[发现错误] 自定义字体安装后保存刷新无效

### ISSUE THREAD

**Issue by bangkibang** [F9y4ng/GreasyFork-Scripts#130]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
安装了OPPO SANS，字体选择框显示正常，开启了预览功能后正常预览，但是一旦点击保存按钮刷新页面后恢复微软雅黑

**错误再现**  （重现行为的步骤）

1. 打开知乎 _ ..."_
2. 点击油猴，进入脚本
3. 选择OPPO SANS，点击“预览”（目前字体渲染正常）
4. 点击“保存”，页面刷新
5. 脚本字体渲染失效

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
预览显示正常
![image](https://user-images.githubusercontent.com/48706717/188810951-74d4c15c-d5dd-4909-b360-e19e706bb24b.png)
保存刷新后失效
![image](https://user-images.githubusercontent.com/48706717/188811109-bba94d98-7f0b-475f-b983-f713cded9c36.png)
![image](https://user-images.githubusercontent.com/48706717/188811219-2f7b8355-88dc-46cd-aa5e-6c1d2288ffc3.png)

**客户端信息：**  （请填写以下信息）
- Win10
- Chrome105.0.5195.54
- 运行的脚本版本2022.09.03.1

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

无
- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
无

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by bangkibang** [comment]
现尝试使用“保存到网站数据“后，显示正常

**Comment by F9y4ng** [comment]
> 现尝试使用“保存到网站数据“后，显示正常
> 

如果你之前保存过网站独享数据，那么修改后也应保存为独享数据。因为独享数据优先级比全局数据要高。

**Comment by bangkibang** [comment]
> > 现尝试使用“保存到网站数据“后，显示正常
> 
> 如果你之前保存过网站独享数据，那么修改后也应保存为独享数据。因为独享数据优先级比全局数据要高。

是我这边理解出了问题，字面上习惯认为全局大于网站数据。若后续有同样误解，建议着重描述这部分选项。非常感谢您！
