### ISSUE TITLE
[新增功能] 自定义搜索引擎

### ISSUE THREAD

**Issue by 300g-BoHeYou** [F9y4ng/GreasyFork-Scripts#132]
**您的功能请求是否与问题有关？请描述。** 
我希望可以在除去内置的搜索引擎中跳转（包括其他搜索，例如bilibili）

**描述您想要的解决方案**
在搜索引擎选择时新增一个（多个更好）“自定义搜索引擎”的选项，自定义方法可以是用特定符号（如*）代替搜索内容

**Comment by F9y4ng** [comment]
新增自定义搜索引擎的功能应该不会做出来：
1. 同类脚本太多，重复造轮子着实没必要；
2. **优雅的搜索引擎跳转助手** 应该只针对搜索引擎，不针对某个信息孤岛网站；
3. 自定义搜索引擎，需要添加的东西太多（如按钮样式、去广告、去重定向、搜索类辨识等等），一般用户搞不定，那就不折腾，省的给自己找麻烦😛；
4. 我一直认为脚本功能越专一越简单越好，如果你有自定义的需要，可以选择其他有你需求功能的脚本替代。

**Comment by bowencool** [comment]
能不能这样：自定义搜索引擎不需要添加按钮，不需要高亮，能跳过去就行了

**Comment by F9y4ng** [comment]
> 能不能这样：自定义搜索引擎不需要添加按钮，不需要高亮，能跳过去就行

其实更重要的不是如何实现这些功能，而是同类脚本太多了，重复造轮子没必要。

这个脚本维护了近十年，基本是按我自己的使用习惯而定，也可以理解为自用脚本。简单高效是我看重的，大而全臃肿的工具集合不是我的菜。

**Comment by bowencool** [comment]
> > 能不能这样：自定义搜索引擎不需要添加按钮，不需要高亮，能跳过去就行
> 
> 其实更重要的不是如何实现这些功能，而是同类脚本太多了，重复造轮子没必要。
> 
> 这个脚本维护了近十年，基本是按我自己的使用习惯而定，也可以理解为自用脚本。简单高效是我看重的，大而全臃肿的工具集合不是我的菜。

理解，感谢！
