### ISSUE TITLE
[发现错误] 20220917更新完后 小米兰亭pro VF字体设置失效了，之前一直好好的

### ISSUE THREAD

**Issue by yangchaoyue980731** [F9y4ng/GreasyFork-Scripts#133]
20220917更新完后 小米兰亭pro VF字体设置失效了，之前一直好好的

**错误再现**  （重现行为的步骤）

1 打开浏览器，“字体增强”脚本自动更新
2 页面显示字体恢复成原样，原“小米兰亭pro VF”字体设置失效

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器 [_如 Chrome_]：360极速版
- 版本 [_如 93.0.4577.63_]：13.5.2022.0
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：4.16.1
- 运行的脚本名称 [_如 Font Rendering_]：
- 运行的脚本版本 [_如 V3.8.20210101.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
没有使用类似的字体处理扩展

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
没有使用类似的字体处理脚本

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by yangchaoyue980731** [comment]
进一步发现字体描边和字体阴影也全部失效

**Comment by F9y4ng** [comment]
chromium内核浏览器低于88.0的浏览器将不支持最新的样式规则。
