### ISSUE TITLE
chrome浏览器开启该脚本后，油猴扩展面板不显示插件了

### ISSUE THREAD

**Issue by hnotcold** [F9y4ng/GreasyFork-Scripts#134]
hello，大佬，最近一直有一个问题困扰，导致没有开启您的这个插件，就是我开启您这个插件之后，在油猴扩展那里，点击图标，安装的所有插件都不展示了，只有禁用掉您这款插件之后，点击油猴图标，其他的插件才能显示出来进行操作，请问能修复一下吗

**Comment by F9y4ng** [comment]
> 请反馈问题的朋友注意：反馈脚本错误或样式显示问题，请把仅使用本脚本的情况下发生问题的具体访问网址、使用的浏览器版本、脚本运行器版、相关错误的截图、以及具体操作流程或错误提示（如果有的话）发出来，你遇到的问题不一定能在其他地方复现。

建议你提问之前先认真阅读一下脚本说明和注意事项。

**Comment by F9y4ng** [comment]
> Tampermoney 4.18.0 or Beta版本均存在一个menu issue，参见 [Tampermonkey#1607](https://github.com/Tampermonkey/tampermonkey/issues/1607)。
> 
> 下个更新会临时修复此问题，最终需等待Tampermonkey修复该issue发布新版本。

Tampermonkey BETA 4.19.6170 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi)) 修复了该issue，正式版本预计在11月发布。
