### ISSUE TITLE
[发现错误] 网站“猫眼电影”里的数字不能正常显示

### ISSUE THREAD

**Issue by yangchaoyue980731** [F9y4ng/GreasyFork-Scripts#135]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
如题

**错误再现**  （重现行为的步骤）

1 打开网站https://www.maoyan.com/films/1433654
2 数字显示错误（不能正常显示），关闭字体重写或插件后恢复正常

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
[https://i.postimg.cc/qRFxBJQq/20220925165731.png](url)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器 [_如 Chrome_]：360极速64位
- 版本 [_如 93.0.4577.63_]：95.0.4638
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：4.13
- 运行的脚本名称 [_如 Font Rendering_]：
- 运行的脚本版本 [_如 V3.8.20210101.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
无

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
无

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
在 **需要渲染的网页元素** 中，追加 `:not([class~='stonefont'])`，保存为站点独享。
