### ISSUE TITLE
[发现错误] 在能关掉DW而且用了mactype的电脑浏览器上，开启关闭脚本变不回原来的网站默认字体

### ISSUE THREAD

**Issue by weavers1f** [F9y4ng/GreasyFork-Scripts#138]
之前随便开关此脚本的话，是不会有啥特别影响的，就字体、描边和阴影全部会变回正常渲染。但是这两天我关闭了此脚本后，网站字体回不去原来的默认字体。

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
图一，原来正常的显示（以下分别都是CNBETA和语雀）：
![VeryCapture_20221008181136](https://user-images.githubusercontent.com/19663899/194732365-b9e4c087-f471-4523-a999-f553319fa6ad.jpg)
![VeryCapture_20221009084443](https://user-images.githubusercontent.com/19663899/194732426-470d7777-7fd1-4423-8903-9ab71cc4d628.jpg)

图二，开启然后又关掉脚本后：
![VeryCapture_20221008181149](https://user-images.githubusercontent.com/19663899/194732374-18d54947-02e7-4f32-b9e2-e6ff791f2146.jpg)
![VeryCapture_20221009084457](https://user-images.githubusercontent.com/19663899/194732427-1ce27dea-4c55-4f6c-a853-9aef6341e29a.jpg)

可以看到关掉脚本后，字体变不回原来的默认字体，现在只能重新开启脚本然后全部设置成0来变回图一的样子。为了测试我又在360极速X浏览器上测试了一下发现也是这样，然后这个浏览器这些网站的字体也变不回去了。都是关闭了DW然后有用MACTYPE，再测试了下发现其他网站也会这样，比如百度、IT之家那些。

**客户端信息：**  （请填写以下信息）
- 操作系统 [_ Win10_]：
- 浏览器 [百分_版本 5.0.1002.182（正式版本） （64 位） (Chromium 102.0.5005.167)]：
- 浏览器 [360极速浏览器X_版本号：21.0.1150.0 内核版本：95.0.4638.69]：
- 脚本扩展 [_如 TamperMonkey_]：
- 脚本扩展版本 [_如 4.16.1_]：
- 运行的脚本名称 [_如 字体渲染（自用脚本）_]：
- 运行的脚本版本 [_最新_]：

**Comment by F9y4ng** [comment]
通过你的描述，大致可以判断出，你在脚本管理器中关闭了字体渲染脚本，但脚本管理器仍然在执行已关闭的脚本，是这个意思么？

1. 以上操作应该能判断出这与脚本本身应该没关系，关闭动作不是脚本发出的（如屏蔽某个域名的渲染），而是脚本管理器发出的。

2. TM关闭脚本后，有时需要强制刷新（Ctrl+F5）才能使页面重新从服务端获取新的信息。这是TM本身的缓存问题（其默认是不刷新页面的），你可能需要到TM反馈ISSUE。

3. TM脚本管理器从4.14版本开始，各种兼容性不是很稳定。如有必要，建议你更换其他脚本管理器再试试，如Violentmonkey。


## 注意
任何脚本加载、暂停、关闭的动作都需要刷新页面才能使设定生效。必要时检查排除浏览器、脚本管理器的缓存问题。
