### ISSUE TITLE
[发现错误] onlinelibrary.wiley.com网站公式渲染有问题

### ISSUE THREAD

**Issue by huphGit** [F9y4ng/GreasyFork-Scripts#139]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
脚本在onlinelibrary.wiley.com上的论文网页公式渲染有问题。
**错误再现**  （重现行为的步骤）

1. [例如进入这篇论文网站](https://onlinelibrary.wiley.com/doi/10.1002/nme.6448)
2. 打开此脚本
3. _向下滚动到公式（2）位置 "..."_
4.可以看到公式渲染有问题

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
公式渲染没问题。

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
打开脚本如下（公式渲染有问题）：
<img width="388" alt="脚本渲染" src="https://user-images.githubusercontent.com/86786299/195082705-85f34fcb-c94a-45e8-b034-0fd15516bd64.png">
关闭脚本如下（正常显示）：
<img width="371" alt="脚本未渲染" src="https://user-images.githubusercontent.com/86786299/195082948-83da3396-5a3f-44db-a3f2-965d13de7555.png">

**客户端信息：**  （请填写以下信息）
- 操作系统 [_ Win10_]：
- 浏览器 [_ Chrome_]：
- 版本 [_106.0.5249.103（正式版本） （64 位）_]：
- 脚本扩展 [_TamperMonkey_]：
- 脚本扩展版本 [_4.16.1_]：
- 运行的脚本名称 [_字体渲染（自用脚本）_]：
- 运行的脚本版本 [_2022.10.05.1_]：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
否

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
否

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
似乎需要账户登录才可阅读论文全文，请提供相关的测试账号。

**Comment by huphGit** [comment]
感谢回复！不好意思，我这不方便提供测试账号，我下载了网页的html文件（[下载链接](https://filedoge.com/download/02a034ffb6234dd7471adbb612cb6e8eb269f2036a04907acd6f87d7974d33e9dc13486bc8ded43356ef)）不知道行不行，不行就算了。
再次感谢。

**Comment by F9y4ng** [comment]
## 尝试一下
在 **需要渲染的网页元素** 中，追加 `:not(mjx-container *)`，保存为站点独享数据。

**Comment by huphGit** [comment]
有用！感谢！
