### ISSUE TITLE
我来中的公式经渲染后出现错乱

### ISSUE THREAD

**Issue by Alex-wangwang** [F9y4ng/GreasyFork-Scripts#14]
在我来网站中打开本插件，公式显示会错乱。
渲染前的截图：
![截图_20214331114330](https://user-images.githubusercontent.com/60033603/127727707-ef1d9c11-ea6d-42b4-ac23-77491b45528a.png)

渲染后的截图：
![截图_20214231114220](https://user-images.githubusercontent.com/60033603/127727698-8f942c76-f54a-4030-82f9-8bdf57e49a26.png)

**Comment by F9y4ng** [comment]
在“排除渲染的HTML标签：”中补充添加```,span *[class*='math']```，保存为该站点独享。

**Comment by Alex-wangwang** [comment]
> 在“排除渲染的HTML标签：”中补充添加`,span *[class*='math']`，保存为该站点独享。

谢谢解答，数学应该公式目前没问题了。但是在在显示化学方程式上面，还是出现了渲染错误。比如：
渲染前：
![image](https://user-images.githubusercontent.com/60033603/127731814-df5393c5-61b0-4e6e-a02c-b06d684eca21.png)
渲染后：
![截图_20210331030321](https://user-images.githubusercontent.com/60033603/127731840-63b0eb8f-942a-49d7-9ca2-8560f3536d39.png)
以上示例是官方文档中的示例。

**Comment by F9y4ng** [comment]
将上面的添加的语句替换为 ```,span *[class*='mord']```

似乎该站点有脚本禁用了删除键[Backspace]，可以使用delete来代替删除。

[反馈个别站点问题时最好把网址一起发出来，你截图我未必能找得到这个页面。](#)

**Comment by Alex-wangwang** [comment]
> 将上面的添加的语句替换为 `,span *[class*='mord']`
> 
> 似乎该站点有脚本禁用了删除键[Backspace]，可以使用delete来代替删除。
> 
> [反馈个别站点问题时最好把网址一起发出来，你截图我未必能找得到这个页面。](#)

好的，谢谢。下次注意。

**Comment by Alex-wangwang** [comment]
> 将上面的添加的语句替换为 `,span *[class*='mord']`
> 
> 似乎该站点有脚本禁用了删除键[Backspace]，可以使用delete来代替删除。
> 
> [反馈个别站点问题时最好把网址一起发出来，你截图我未必能找得到这个页面。](#)

再反馈个问题，谢谢你的解惑。
网站：https://fanyi.atman360.com/text
问题描述：输入一段长英文文本，点击立即翻译，此时文本显示都是正常的。然后删除英文文本中删除某个英语字母，显示的某某些英语字母出现错乱
删除某些字母前：
![截图_20212831102818](https://user-images.githubusercontent.com/60033603/127742994-93212399-b5ca-4624-b95e-3f2a00e44fc3.png)
删除某些字母后：
![截图_20212931102944](https://user-images.githubusercontent.com/60033603/127743035-43c7e206-1942-4e17-8667-4330f555e83b.png)

**Comment by F9y4ng** [comment]
1、我没有该网站注册账户无法使用。
2、此类工具型网站建议排除渲染。

**Comment by Alex-wangwang** [comment]
![截图_20210812100826](https://user-images.githubusercontent.com/60033603/141480108-76e58c14-961f-4682-92c6-79ee3610c40a.png)
网站：LaTeX数学公式语法
https://www.wolai.com/qingming/fNBg3m5ry5qjygZgvqK4BE?theme=light
问题：图标中fontawesome列表因为渲染的关系显示错误，请开发者帮忙看看如何排除掉。谢谢

**Comment by F9y4ng** [comment]
> 网站：LaTeX数学公式语法
> https://www.wolai.com/qingming/fNBg3m5ry5qjygZgvqK4BE?theme=light 
> 问题：图标中fontawesome列表因为渲染的关系显示错误，请开发者帮忙看看如何排除掉。谢谢

你这是登录状态么？我没有这个网站的账户，看不到你截图里的编辑界面。

**Comment by Alex-wangwang** [comment]
> > 网站：LaTeX数学公式语法
> > https://www.wolai.com/qingming/fNBg3m5ry5qjygZgvqK4BE?theme=light
> > 问题：图标中fontawesome列表因为渲染的关系显示错误，请开发者帮忙看看如何排除掉。谢谢
> 
> 你这是登录状态么？我没有这个网站的账户，看不到你截图里的编辑界面。
> 
> 如果你一直在使用旧版本的备份数据，建议你在wolai网站上重置一次数据，然后重新设置一次，以使用最新的元素过滤规则，再试试看。特殊样式设置在 [这里 #104341](https://greasyfork.org/zh-CN/scripts/416688/discussions/104341) 中查找。

谢谢开发者的帮助，我申请了一个我来的账号，你可以登录这个账号进去，更滑一下图标试试，特殊的样式里面似乎没有。你可以登录进去更换一下font awesome图标，看看渲染是否有问题，平时主要用我来，希望能够解决这个问题，谢谢开发者了。
账号：19190249775
密码：56uyK24dN4PxfBN
链接：https://www.wolai.com/4Dn1PfLUyraWKxTD5ufMpb

**Comment by F9y4ng** [comment]
你说的是这个页面效果么？如果是，你一定没按我说的操作流程执行过呀。

![1](https://user-images.githubusercontent.com/15855068/141746514-f332d88e-a67a-466e-90cd-327e53f9ee06.png)

让你在这个网站上，打开字体渲染设置页面，点重置按钮，选择重置操作，把你之前设置过的字体、描边、阴影等参数，按你的需要重新设置一次，然后再 **排除渲染的HTML标签** 中追加 `,span *[class*='mord']` ，然后保存数据到站点独享，以使用最新的过滤规则。

> * _建议遇到样式问题，最好先重置数据重新设置一次，看看是否正常_
> * _如果你有备份设置数据，最好重新备份一次_

**Comment by Alex-wangwang** [comment]
嗯嗯，好的，真是麻烦你了。谢谢。
