### ISSUE TITLE
不知道为啥报错，bing现在打不开了都，出现框框后无法进行页面操作，只能滑动，我把油猴禁了都没用，淦！

### ISSUE THREAD

**Issue by brackct** [F9y4ng/GreasyFork-Scripts#140]
浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":"Chromium","version":"106"},{"brand":"Microsoft Edge","version":"106"},{"brand":"Not;A=Brand","version":"99"}],"mobile":false,"model":"","platform":"Windows","platformVersion":"10.0.0","uaFullVersion":"106.0.1370.37"}
脚本扩展信息：Violentmonkey 2.13.3
脚本版本信息：2022.10.05.1
当前访问域名：www.bing.com
错误信息：[Redundant Scripts]: 发现冗余安装的『字体渲染（自用脚本）』，请按 此清单#117 排查错误。刷新页面后如问题依旧，向作者反馈错误！

**Comment by F9y4ng** [comment]
1. 你刷新页面后依然出现此提示么？
2. 如果问题依旧你按错误提示排查问题了么？
