### ISSUE TITLE
能否增加该搜索引擎？https://www.ecosia.org/。

### ISSUE THREAD

**Issue by guangjieMVP** [F9y4ng/GreasyFork-Scripts#141]
**您的功能请求是否与问题有关？请描述。** （清晰简明地描述遇到的问题是什么)
能否增加该搜索引擎？https://www.ecosia.org/，用了一小段时间ecosia这个搜索，搜索结果挺好的

**描述您想要的解决方案** （清晰简明地描述您想要发生的事情）

**描述你考虑过的替代方案**  （清晰简洁地描述您所考虑的任何替代解决方案或功能）

**附加信息或屏幕截图**  （在此处添加任何附加信息或屏幕截图）

**Comment by F9y4ng** [comment]
www.ecosia.org 属于小众搜索引擎，且搜索结果由Bing提供，你觉得有必要增加么？（我觉得没必要😅）

**Comment by F9y4ng** [comment]
> 好的好的。3Q。我另寻办法

大概看了一下，除了CSP会造成图标显示问题，其他还好处理，下个月更新会增加ecosia.org. 懒癌晚期😁

**Comment by F9y4ng** [comment]
> > 好的好的。3Q。我另寻办法
> 
> 大概看了一下，除了CSP会造成图标显示问题，其他还好处理，下个月更新会增加ecosia.org. 懒癌晚期😁

更新至v2022.11.05.1
