### ISSUE TITLE
[新增功能] 搜索引擎跳转的关键词高亮增强可自定义颜色

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [F9y4ng/GreasyFork-Scripts#142]
**您的功能请求是否与问题有关？请描述。** （清晰简明地描述遇到的问题是什么)

_优雅的搜索引擎跳转助手_ 的 **搜索关键词高亮增强** 能不能改为可自定义颜色和背景色。

**描述您想要的解决方案** （清晰简明地描述您想要发生的事情）

默认的颜色过于亮，想改成自己用的，但更新又会被覆盖，需要可以自定义颜色和背景颜色。

**Comment by F9y4ng** [comment]
下个更新会添加该功能。

**Comment by F9y4ng** [comment]
> 下个更新会添加该功能。

更新至v2022.11.05.1
