### ISSUE TITLE
[发现错误] 飞书云文档PDF出现渲染问题

### ISSUE THREAD

**Issue by auniel** [F9y4ng/GreasyFork-Scripts#145]
飞书云文档PDF出现渲染问题，排除以下域名并重新打开PDF仍有复现。https://lzwdulijtp.feishu.cn/

如图所示，PDF出现重影。
![image](https://user-images.githubusercontent.com/37327100/200256151-d54cf3df-a8bd-4270-a0f8-abea198d1c71.png)

在油猴中关闭整个script后，问题消除。

**Comment by F9y4ng** [comment]
访问需要登录，能否提供测试账户？
