### ISSUE TITLE
发现冗余安装的『字体渲染（自用脚本）』

### ISSUE THREAD

**Issue by Achillesyaphets** [F9y4ng/GreasyFork-Scripts#146]
浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":"Microsoft Edge","version":"107"},{"brand":"Chromium","version":"107"},{"brand":"Not=A?Brand","version":"24"}],"mobile":false,"model":"","platform":"Windows","platformVersion":"10.0.0","uaFullVersion":"107.0.1418.52"}
脚本扩展信息：AdGuard 1.2.7
脚本版本信息：2022.11.17.1
当前访问域名：github.com
错误信息：[Redundant Scripts]: 发现冗余安装的『字体渲染（自用脚本）』，请按 此清单#117 排查错误。刷新页面后如问题依旧，向作者反馈错误！

**Comment by Achillesyaphets** [comment]
实验了，是与Adguard插件冲突了，Adguard插件关了就没影响了

**Comment by F9y4ng** [comment]
如果能使用浏览器扩展可能会较少的遇到此类问题。值得注意的是：使用adguard安装脚本只能使用快捷键操作脚本设置菜单。
