### ISSUE TITLE
[新增功能] Yandex and Russian language

### ISSUE THREAD

**Issue by stasink** [F9y4ng/GreasyFork-Scripts#147]
请添加俄语支持. 并且还请添加对 Yandex 的 .ru 域的支持。

**Comment by F9y4ng** [comment]
你访问Yandex.ru不需要登录么？

![2022-11-26 212656](https://user-images.githubusercontent.com/15855068/204091275-7f12315b-d375-42bc-a265-df4387be49e7.png)

**Comment by stasink** [comment]
我不是说没有登录（不是登录）。 我的意思是子域 yandex.ru 和 ya.ru  是的，我来自俄罗斯)))
![image](https://user-images.githubusercontent.com/5938602/204111249-daa5bd13-2beb-4998-bc18-c78ae738be60.png)

**Comment by stasink** [comment]
对集成和 CSS 感兴趣

**Comment by F9y4ng** [comment]
下个更新，我会将yandex.ru加入。

**Comment by stasink** [comment]
谢谢。 并考虑添加俄语。

**Comment by F9y4ng** [comment]
请更新至v2022.12.03.1，yandex.ru域已加入，可能需要我有多余的空闲时才会加入多国语言功能。
