### ISSUE TITLE
[发现错误] 搜索跳转助手的直链功能对必应国际版搜索结果失效

### ISSUE THREAD

**Issue by amitbha** [F9y4ng/GreasyFork-Scripts#148]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

使用 [必应](cn.bing.com) 搜索时，使用国内版搜索，可以去链接重定向，但切换到国际版后，则不能

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
国际版搜索也可以去重定向

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![ksnip_20221129](https://user-images.githubusercontent.com/4060625/204511198-e24c9544-270e-44a3-b989-09489fb0be54.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：linux
- 浏览器 [_如 Chrome_]：firefox
- 版本 [_如 106.0.5249.91_]：107
- 脚本扩展 [_如 Tampermonkey_]：暴力猴
- 脚本扩展版本 [_如 4.16.1_]：2.13.3
- 运行的脚本名称 [_如 字体渲染（自用脚本）_]：搜索跳转助手
- 运行的脚本版本 [_如 V2020.11.24.1_]：2022.11.17

**Comment by F9y4ng** [comment]
我测试了一下，Chrome下是正常的，Firefox下确实有问题，下个更新会解决该问题，谢谢反馈！😀
