### ISSUE TITLE
360安全浏览器 13.1 版本使用出现错误. 无法渲染字体问题，大小可以改变，其他出现bug

### ISSUE THREAD

**Issue by Acreate** [F9y4ng/GreasyFork-Scripts#149]
浏览器信息：mozilla/5.0 (windows nt 10.0; wow64) applewebkit/537.36 (khtml, like gecko) chrome/86.0.4240.198 safari/537.36
脚本扩展信息：Tampermonkey 4.18.1
脚本版本信息：2022.12.03.1
当前访问域名：m.babayu.tv
错误信息：[Redundant Scripts]: 发现冗余安装的『字体渲染（自用脚本）』，请按 此清单#117 排查错误。刷新页面后如问题依旧，向作者反馈错误！

**Comment by F9y4ng** [comment]
经测试360安全浏览器 13.1.6350.0 + Tampermonkey4.18.1 并未在 m.babayu.tv 出现异常。

请提示中 #117 排查本地扩展或脚本冲突。 

![屏幕截图 2022-12-04 192548](https://user-images.githubusercontent.com/15855068/205488021-b9e836de-7011-4dd9-8dbf-914b74b9f83c.png)
