### ISSUE TITLE
开启后国内网站都无法正常打开了

### ISSUE THREAD

**Issue by evilhentaro** [F9y4ng/GreasyFork-Scripts#15]
开始以为是chrome坏了，换了edge，并重装了一遍chrome好了，
但在edge里安装同步violentmonkey设置后edge也没法正常打开了，chrome也又变成了这样
排查了一遍各脚本，发现和这个有关。只要关闭就可以正常打开国内网站了。
麻烦排查一下，辛苦了。

**Comment by F9y4ng** [comment]
我排查了一下，脚本程序上没有问题，但有一种情况会造成你所遇到的问题：
[![h8jkHe.png](https://z3.ax1x.com/2021/08/29/h8jkHe.png)](https://imgtu.com/i/h8jkHe)
重复安装了两个 字体渲染（自用脚本）的脚本程序，会造成脚本冲突。请保留其中一个。

如果你已经在其他源安装过**字体渲染（自用脚本）**，那一定不要在 [https://openuserjs.org/scripts/f9y4ng/Font_Rendering_(Customized)](https://openuserjs.org/scripts/f9y4ng/Font_Rendering_(Customized)) 这个namespace定义页重复安装脚本，否则就会造成脚本冲突的问题。由于两个脚本的name命名不同，安装时会独立安装而非更新安装。（目前该页面已标记出明显的警示。）

建议你检查一下你的脚本列表是否有重复安装。

PS.由于浏览器或插件的缓存问题，建议你删除后清除缓存重新安装。

**Comment by evilhentaro** [comment]
没有重复安装。昨晚好像脚本更新了，那之后就变成了这样，并且我在edge和chrome里都产生这个情况

**Comment by F9y4ng** [comment]
> 没有重复安装。昨晚好像脚本更新了，那之后就变成了这样，并且我在edge和chrome里都产生这个情况

你尝试清空浏览器缓存后再尝试一次（最好重新安装一次试试）。
稍后我会更新一个版本来尝试修正一下，因为我本地只有在重复安装后才会出现，单一脚本下不能复现。

**Comment by evilhentaro** [comment]
greasyfork

**Comment by F9y4ng** [comment]
> chrome和edge官方最新版、violentmonkey、都会出现，你用的好像是tampermonkey

脚本已经更新新版本，你尝试更新试一试，注意清除本地缓存。

我本地发布前，会测试浏览器edge, chrome, ff，脚本插件tampermonkey, violentmonkey, greasemonkey，以上均为Release通道最新版，个别大版本更新会兼容测试safari, opera。

**Comment by evilhentaro** [comment]
气氛上应该是好了，感谢关注和费力修补。辛苦了。
