### ISSUE TITLE
在一些其它语种的网站中，这个脚本没有运行。应该怎么设置？

### ISSUE THREAD

**Issue by tup2339** [F9y4ng/GreasyFork-Scripts#150]
大部分网页都能正常使用，但有时候我会访问脚本不支持语种的网站，翻译成汉语后阅读。因为这个脚本没有运行，翻译后的汉语就没有渲染成想要的字体。
我在帮助页面里没找到方法，求助一下，怎么设置才能让这个脚本在俄语页面上运行。
我用的字体基本支持各类语言的字符所以不担心乱码之类的。
![20221206141016](https://user-images.githubusercontent.com/39553367/205837612-ded8f0fb-c423-4345-aa4f-2f7db14d1271.png)

**Comment by F9y4ng** [comment]
浏览器的翻译功能也会将脚本中的部分代码翻译为中文或其他语言，有时由于翻译造成的编码问题而使得脚本失效或样式失效。

从脚本本身而言应该是无解的。
