### ISSUE TITLE
有办法只不对弹幕网站的弹幕进行渲染吗

### ISSUE THREAD

**Issue by recycle007** [F9y4ng/GreasyFork-Scripts#151]
之前一直排除整个网站，最近发现b站的弹幕也被脚本渲染覆盖了
普通网页用脚本渲染能更清晰，但弹幕网站的弹幕一般本身就有描边而且更深让弹幕看得清，现在被脚本覆盖后在浅色和白色画面下弹幕基本都看不清了。。。

**Comment by F9y4ng** [comment]
脚本默认会重写一部分常用的中文字体，如宋体、新宋体、黑体、仿宋等等，而bilibili默认的弹幕字体使用的是黑体，你可以在bilibili弹幕高级设置中将默认弹幕字体设置为微软雅黑即可。

或者关闭脚本的字体替换功能，使用bilibili网站默认字体。

**Comment by recycle007** [comment]
我已经将b站默认字体改成微软雅黑了，我指的不是字体而是描边的问题，b站弹幕默认描边重墨，但用了脚本后网站的描边效果就没了，这样在视频白色背景下完全看不清弹幕了

**Comment by recycle007** [comment]
包括斗鱼、a站等所有弹幕视频网都是这个问题，网站自带的弹幕字体描边没了，脚本的描边和阴影在弹幕上效果约等于无，因为弹幕都是白色的，跟网页显示区别很大

**Comment by F9y4ng** [comment]
如果你使用的是Chrome或Chromium内核的浏览器，并且浏览器版本大于96.0，那么字体粗体+字体描边共同渲染时会出现渲染异常。

由于大部分国内的视频网站弹幕都使用了粗体，脚本默认的粗体修正功能会将弹幕的描边样式去除，所以才会出现你遇到的问题。

## 解决方法
* 脚本在**字体描边尺寸**右边放置了修正开关，将**粗体修正**开关关闭，保存为站点独享，可解决描边、阴影失效的问题。
* 或者在脚本菜单中，将以上你提到的视频站点添加进排除渲染列表。

**Comment by F9y4ng** [comment]
## 解决方法
* 默认设置下，尝试将在**需要渲染的网页元素**中，追加`:not(.b-danmaku-high-text)`，保存为站点独享。

效果如下：
![test](https://user-images.githubusercontent.com/15855068/206202021-26949ed5-b81d-48d1-85e6-af6f2e634be2.png)

**Comment by recycle007** [comment]
> ## 解决方法
> * 默认设置下，尝试将在**需要渲染的网页元素**中，追加`:not(.b-danmaku-high-text)`，保存为站点独享。
> 
> 效果如下： ![test](https://user-images.githubusercontent.com/15855068/206202021-26949ed5-b81d-48d1-85e6-af6f2e634be2.png)

![捕获](https://user-images.githubusercontent.com/82096497/206202371-a3990319-5733-411b-84fb-82aca3a7e9a4.JPG)
我这加入后显示效果是这样的，b站设置微软雅黑并关闭粗体，而且平时脚本字体描边我都是关闭的，弹幕就更看不清了
![K6YC{QXR0~CGWL6({TDU$IC](https://user-images.githubusercontent.com/82096497/206203188-5c72ffe7-8319-4428-bb42-b06fa00b6404.png)
将网站排除时的效果是这样的，但习惯了字体渲染后排除整个网站除弹幕外其他内容的字体渲染看不下去了。。

**Comment by F9y4ng** [comment]
> 我这加入后显示效果是这样的，b站设置微软雅黑并关闭粗体，而且平时脚本字体描边我都是关闭的，弹幕就更看不清了 !

你关闭或打开字体描边都没影响的。

还原你之前的字体参数设定，不需要更改任何参数，直接按 [上面](https://github.com/F9y4ng/GreasyFork-Scripts/issues/151#issuecomment-1341054568) 的修正设置填写应该可以达到你要的字体需求了。

**Comment by recycle007** [comment]
> * :not([class*='b-danmaku'])

那楼我也编辑了，b站我截图用的就是新的过滤规则，显示还是有问题，斗鱼我试了效果不错

**Comment by F9y4ng** [comment]
> 那楼我也编辑了，b站我截图用的就是新的过滤规则，显示还是有问题，斗鱼我试了效果不错

哔哩哔哩视频本身的字体也还原成默认的，只添加上面的修正规则，再试试看。

**Comment by F9y4ng** [comment]
> 视频本身弹幕恢复默认设置还是不行 !

快要被哔哩哔哩玩死了，你访问的是新版的bilibili，我访问的是旧版的bilibili，两个版本的样式完全不同，太坑了。

我已经更新了规则，你用上面的新规则应该就可以了。

**Comment by recycle007** [comment]
> 

ok了，谢谢大佬！
