### ISSUE TITLE
[发现错误] [Redundant Scripts]: 发现冗余安装的『字体渲染（自用脚本）』

### ISSUE THREAD

**Issue by tjzx** [F9y4ng/GreasyFork-Scripts#152]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":"Not?A_Brand","version":"8"},{"brand":"Chromium","version":"108"},{"brand":"Microsoft Edge","version":"108"}],"mobile":false,"model":"","platform":"Windows","platformVersion":"14.0.0","uaFullVersion":"108.0.1462.42"}
脚本扩展信息：Tampermonkey 4.19.6176
脚本版本信息：2022.12.03.1
当前访问域名：docs.qq.com
错误信息：[Redundant Scripts]: 发现冗余安装的『字体渲染（自用脚本）』，请按 此清单#117 排查错误。刷新页面后如问题依旧，向作者反馈错误！

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：
- 浏览器 [_如 Chrome_]：
- 版本 [_如 106.0.5249.91_]：
- 脚本扩展 [_如 Tampermonkey_]：
- 脚本扩展版本 [_如 4.16.1_]：
- 运行的脚本名称 [_如 字体渲染（自用脚本）_]：
- 运行的脚本版本 [_如 V2020.11.24.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
重复反馈，参照 #117 处理。
