### ISSUE TITLE
后台页面不渲染

### ISSUE THREAD

**Issue by zweidyx** [F9y4ng/GreasyFork-Scripts#158]
近日更新2022.12.17.1后，发现有时候通过鼠标中键打开在后台的页面没有渲染，选择到后台页面是原样，重新刷新页面后渲染，之前并无此问题

**Comment by F9y4ng** [comment]
反馈错误或bug，按错误反馈模板填写。

这好比去医院看病，只告诉医生头疼，剩下的让医生靠猜的？
