### ISSUE TITLE
启用脚本后CPU占用率飙升

### ISSUE THREAD

**Issue by ctrl-huangyq** [F9y4ng/GreasyFork-Scripts#16]
这个版本的脚本启用后CPU占用率会飙升，但先前的版本则无此问题。
启用前的任务管理器截图：
![image](https://user-images.githubusercontent.com/62862318/131252480-f85603f7-f90f-475f-aefc-f45dfe3ab4ae.png)
启用后的任务管理器截：
![image](https://user-images.githubusercontent.com/62862318/131252524-9c59f510-afb9-4085-97a3-24e802d2138d.png)
同时浏览网页时也会有明显的卡顿，如图：
![gif](https://user-images.githubusercontent.com/62862318/131252711-d356ade4-c384-4ae8-ba14-dc97268cf0e2.gif)
重装脚本和Edge浏览器后也有同样的问题。

环境：
OS：Windows 11 x64 （OS 内部版本 22000.168）
浏览器： Microsoft Edge 版本 95.0.997.0 (官方内部版本) canary (64 位)
脚本管理器：Tampermonkey

下载源：OpenUserJS

**Comment by F9y4ng** [comment]
我会跟进检查一下。

**Comment by ctrl-huangyq** [comment]
我刚刚测试了一下，在Edge正式版中也出现了此问题

**Comment by F9y4ng** [comment]
> 我刚刚测试了一下，在Edge正式版中也出现了此问题

version 2021.08.30.2 已修正CPU占用过高的问题。感谢反馈。

**Comment by ctrl-huangyq** [comment]
感谢作者的修补，辛苦了。

**Comment by ctrl-huangyq** [comment]
不过我发现问题依旧，2021.8.30.2版本启用后无法加载出任何网页。我测试了一下问题是从2021.8.28.1版本开始出现的，但是在注释了2021.8.30.2版本的第2132-2134行后则不再出现此问题。

第2132-2134行：
```JavaScript
if (qS(`.${defCon.class.rndStyle}`)) {
    reloadStyleTolastChild(1e3, true);
}
```

**Comment by F9y4ng** [comment]
与Dark Reader的兼容性问题已处理完成。

更新 version 2021.08.30.4 即可解决CPU高占用的问题。
