### ISSUE TITLE
开了脚本斗鱼在弹幕特别多的时候直播会整个卡住

### ISSUE THREAD

**Issue by recycle007** [F9y4ng/GreasyFork-Scripts#161]
新版旧版本都这样，测试了下关闭脚本没有复现过，看了下后台cpu占用并不算高，但直播就会整个卡住，不知道能否改善

**Comment by F9y4ng** [comment]
v2023.01.01.1 已针对直播弹幕型网站进行过优化，经过严格的本地测试，应该不会再出现高占用或卡顿的问题了。

## 建议
1. 排查一下是否与其他脚本或扩展冲突造成了页面卡顿。（尽量在仅使用此脚本情况下测试）
2. 如果计算机配置较差（比如CPU低于INTEL3代、或内存小于8G），可以考虑将“**粗体修正**”功能关闭。（仅chromium(BLINK)内核浏览器）

**Comment by F9y4ng** [comment]
我在低配的测试电脑上访问斗鱼，不论哪个房间基本百分之百会卡死，斗鱼的前端优化实在太差了。

推荐一个比较好的第三方：http://live.yj1211.work/index/home/recommend

**Comment by F9y4ng** [comment]
V2023.01.07.1 已对海量弹幕进行了优化，可以升级至最新版测试一下。

**Comment by F9y4ng** [comment]
直播平台海量弹幕造成卡顿或播放中断的处理方法 https://github.com/F9y4ng/GreasyFork-Scripts/discussions/160#discussioncomment-4738808
