### ISSUE TITLE
内置字体与自定义字体不可用

### ISSUE THREAD

**Issue by TC-Mits-Qine** [F9y4ng/GreasyFork-Scripts#162]
**描述错误信息**  
设置字体仅有「微软雅黑」与「微軟正黑體」可用，其余内置字体不在列表中可见，添加自定义字体后依然不可用，尝试重建字体列表全局缓存无果。

**错误再现**  （重现行为的步骤）

1. 打开「字体渲染设置」
2. 单击「设置字体」输入框，显示如下：

![图片](https://user-images.githubusercontent.com/32544907/210292837-7f5d7ca8-895e-474d-8724-1db8297cba86.png)

3. 尝试添加自定义字体后，依然只显示两种字体：

![图片](https://user-images.githubusercontent.com/32544907/210292901-561234c9-4b8a-48d3-9f81-5419d18fbd82.png)

**预期结果**  能够正常更换字体。

**客户端信息：**

- 操作系统 [Win 11 22622.290]：
- 浏览器 [Librewolf]：
- 版本 [108.0.1-1]：
- 脚本扩展 [Tampermonkey]：
- 脚本扩展版本 [4.18.1]：
- 运行的脚本名称 [字体渲染（自用脚本）]：
- 运行的脚本版本 [V2023.01.01.1]：
- 其他信息：浏览器安装方式：<https://github.com/ScoopInstaller/Extras/blob/master/bucket/librewolf.json>

- 是否同时运行了其他浏览器扩展？ 在关闭所有其他浏览器拓展的情况下问题依旧。

- 是否同时运行了其他油猴脚本？ 在禁用所有其他油猴脚本的情况下问题依旧。

**附加信息**  在同一台电脑上的 Chrome 浏览器中脚本工作正常，两者皆导入了相同的备份文件，配置完全相同。

以下为示例日志：
[console-export-2023-1-3_2-42-31.txt](https://github.com/F9y4ng/GreasyFork-Scripts/files/10334117/console-export-2023-1-3_2-42-31.txt)

**Comment by F9y4ng** [comment]
我查看了一下日志，没有发现相关的错误发生。

## 建议
开启脚本调试模式后，打开控制台，先通过脚本清空原有的字体缓存，然后重新打开脚本设置界面(Alt+P)，让字体缓存重建，然后将生成的日志重新上传。（我能预感到不会报错😓）

## 猜测
我个人感觉，应该是该浏览器的问题。每个浏览器对字体的解析是不同的，即使常用的Chrome和Firefox也有不同（比如屏显臻宋字体，Firefox下能识别出中英文字体名，但Chrome下只能识别中文字体名，个别小众魔改浏览器却无法通过脚本识别出该字体）。

**Comment by TC-Mits-Qine** [comment]
在经过建议的调试后，能够在列表中找到内置的字体和自定义字体了。

![图片](https://user-images.githubusercontent.com/32544907/210303882-9701b824-9a07-46d1-a08f-56141a59a9be.png)

但经过测试，「字体重写」功能不生效，日志在下方附上。
日志中可见报错语句：
```
Request for font "PingFang SC" blocked at visibility level 1 (requires 3)
ttTQ4eVvAtMUApscT-YizUOjk94.br.js:2:12106
```

[console-export-2023-1-3_5-14-33.txt](https://github.com/F9y4ng/GreasyFork-Scripts/files/10334426/console-export-2023-1-3_5-14-33.txt)

**Comment by F9y4ng** [comment]
从日志上看，脚本的字体检测都被浏览器block了，字体列表中罗列出来的也并非是真实结果。我曾经在另外一款极其小众（以至于我都没记住它的名字）的浏览器上遇到过同样的问题。而其他主流浏览器不会存在这样的问题。

如果字体没有获取到真实值，那字体重写肯定是无效的。

有关浏览器内核级别处理字体逻辑的问题，可能需要你提交ISSUES 到该浏览器的项目中。

**Comment by F9y4ng** [comment]
## 建议
在`about:config`中找到`privacy.resistFingerprinting`，修改其默认值，重启浏览器再试试。

**Comment by F9y4ng** [comment]
## 建议
进入`about:config`，修改`privacy.resistFingerprinting`，值为`false`，清空字体缓存后重启浏览器，再试试。
