### ISSUE TITLE
[新增功能] 能否支持下Android端的浏览器

### ISSUE THREAD

**Issue by Granado** [F9y4ng/GreasyFork-Scripts#164]
Android端浏览器例如 [iceraven](https://github.com/fork-maintainers/iceraven-browser) 或者kiwi browser，安装tampermonkey后再安装此插件，无法加载系统字体。

**Comment by F9y4ng** [comment]
抱歉，从未考虑过移动端的兼容。

你可以尝试一下考虑其他扩展或脚本。
