### ISSUE TITLE
[发现错误] HoYoLab评论显示为宋体

### ISSUE THREAD

**Issue by Weixiang** [F9y4ng/GreasyFork-Scripts#166]
**HoYoLab评论显示为宋体** 

**错误再现**  

1. _例如 https://www.hoyolab.com/article/14668149_
2. _滚动到评论区即可看到评论字体为宋体_
3. _关掉脚本后，为微软雅黑_

**预期结果**  
将字体渲染为设置的鸿蒙黑体

**屏幕截图**  
关闭脚本效果
https://ibb.co/RHsfwNm

打开脚本效果
https://ibb.co/vdrxTLb

**客户端信息：**  
- 操作系统 [_Win11_]：
- 浏览器 [_Chrome_]：
- 版本 [_108.0.5359.125_]：
- 脚本扩展 [_Tampermonkey_]：
- 脚本扩展版本 [_4.18.1_]：
- 运行的脚本名称 [_字体渲染（自用脚本）_]：
- 运行的脚本版本 [_2023.01.01.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
是，查看字体用的What's Font

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
否

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
## 建议
1. 访问 www.hoyolab.com 的请求遭到拒绝您未获授权，无法查看此网页。 **你提供的这个网站我访问不了。**
2. 从你提供的截图上来，应该是评论字体部分应用了等宽字体的设定。 建议你尝试一下：
> 在**排除渲染的HTML标签**中，找到并删除`,pre,pre *`,然后保存为站点独享。

如果没有生效，需要等待网站恢复访问后我再给你答复。
