### ISSUE TITLE
[新增功能] 设置取消错误弹窗

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [F9y4ng/GreasyFork-Scripts#167]
**您的功能请求是否与问题有关？请描述。** （清晰简明地描述遇到的问题是什么)
感谢作者无私的奉献与长期的更新

部分弹窗强制要求刷新所有标签页，比如看视频看得好好的，突然弹窗强制要求刷新页面重新缓冲

**描述您想要的解决方案** （清晰简明地描述您想要发生的事情）
设置中可以取消弹窗
弹窗时可以关闭，不刷新页面

**描述你考虑过的替代方案**  （清晰简洁地描述您所考虑的任何替代解决方案或功能）

**附加信息或屏幕截图**  （在此处添加任何附加信息或屏幕截图）

**Comment by F9y4ng** [comment]
没看懂你的意思。
