### ISSUE TITLE
[发现错误] 新年好，反馈下报错。

### ISSUE THREAD

**Issue by matocool** [F9y4ng/GreasyFork-Scripts#169]
## 1. 准备工作（确认预先完成的操作）

- [ x] 我确认使用的是当前脚本的最新版本。

- [ x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。

- [ x] 我在**仅开启脚本管理器扩展**，并且**仅运行此脚本**时复现了脚本出错的情况。

## 2. 描述错误信息（清楚而简洁地描述错误）

开启渲染之后，字库显示错误？ 关闭之后一切正常。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）

https://www.dianping.com/shop/G2RrPGplfygRwkTn
https://www.dianping.com/fuzhou/ch10/g25474

大众点评大多页面都有问题

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/83129369/213794984-3727c6a5-4fca-4b73-9c4d-d375310d7464.png)
![image](https://user-images.githubusercontent.com/83129369/213795930-9e6923a3-6221-448c-bbc8-3c2a772e64f3.png)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

想要错误修复
![image](https://user-images.githubusercontent.com/83129369/213795028-0c67a30b-5daf-493d-bf0a-5784ca24fec1.png)

## 6. 客户端信息（请务必认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Win10
- 浏览器 [_如:Chrome,Safari_]：360x64位极速浏览器
- 浏览器版本 [_如:108.0.5359.128_]：21.0.1180.0
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey_
- 脚本管理器版本 [_如:4.18.1_]：4.18.1
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.01.17.2
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）

- [ x] 是否同时运行了其他浏览器扩展？

脚本很多，已用排除法，关闭所有，均无效。

- [ x] 是否同时运行了其他第三方用户脚本？

## 8. 附加信息（在此处添加您认为有用的其他信息）
本人已关闭所有插件，脚本。经过测试依然无效。

**Comment by F9y4ng** [comment]
你确认“我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。”？

重复反馈 #42

**Comment by matocool** [comment]
抱歉，没搜到。感谢指点。
