### ISSUE TITLE
启用脚本后无法加载出网页

### ISSUE THREAD

**Issue by ctrl-huangyq** [F9y4ng/GreasyFork-Scripts#17]
2021.8.30.2版本启用后无法加载出任何网页，且仍然出现CPU占用过高的问题。我测试了一下问题是从2021.8.28.1版本开始出现的，但是在注释了2021.8.30.2版本的第2132-2134行后则不再出现此问题。

第2132-2134行：
```JavaScript
if (qS(`.${defCon.class.rndStyle}`)) {
    reloadStyleTolastChild(1e3, true);
}
```

环境：
OS：Windows 11 x64 （OS 内部版本 22000.168）
浏览器： Microsoft Edge 版本 95.0.997.0 (官方内部版本) canary (64 位)
脚本管理器：Tampermonkey

下载源：OpenUserJS

**Comment by F9y4ng** [comment]
很奇怪，我本地的测试中始终没有任何问题，无法复现你遇到的问题。

不能复现问题，我只能盲猜了。初步怀疑是否是浏览器或是脚本插件的设置原因造成的缓存问题。你可以尝试将原来的脚本删除，再清理浏览器缓存，然后重新安装一次，看是否依然存在问题。如果依然存在，你可暂时覆盖安装旧版本或暂时注释掉出问题的代码。

我会继续跟进此问题。

**Comment by F9y4ng** [comment]
我提交了一个新的版本，你再尝试一下，是否还有无法加载出任何网页，或CPU占用过高的问题。

**Comment by ctrl-huangyq** [comment]
我刚刚又尝试了一下，发现好像是和Dark Reader冲突了，把Dark Reader禁用了就好了。

**Comment by evilhentaro** [comment]
我昨天也提交了这个issue，更新之后还是有这个状况
怎么办，可是我两个都想要

**Comment by F9y4ng** [comment]
> 我刚刚又尝试了一下，发现好像是和Dark Reader冲突了，把Dark Reader禁用了就好了。

今晚我会就此问题研究一下解决办法。

**Comment by F9y4ng** [comment]
与Dark Reader的兼容性问题已处理完成。

@ctrl-huangyq @evilhentaro 更新 version 2021.08.30.4 即可解决CPU高占用的问题。

_不得不说一句，Dark Reader的流氓代码真的是让人无语（还好是开源的），为了实现自身效果，完全不考虑其他任何因素，监听所有的DOM操作，并对每次DOM操作都强制性的插入自身代码，对原始代码进行无底线的污染，实在是无语来形容此时此时的心情。_

**Comment by F9y4ng** [comment]
与Dark Reader的兼容性问题已处理完成。

@ctrl-huangyq @evilhentaro 更新 version 2021.08.30.4 即可解决CPU高占用的问题。

**Comment by evilhentaro** [comment]
排查辛苦了，感谢修复！
