### ISSUE TITLE
iOS上使用该脚本报错

### ISSUE THREAD

**Issue by easonnnone** [F9y4ng/GreasyFork-Scripts#171]
如下图报错

![F07B8F99-DF31-4EE8-AD27-6A52F01997CC](https://user-images.githubusercontent.com/8055993/216797927-68265318-ad63-48c2-9099-ed48cd7b78a2.png)

**Comment by F9y4ng** [comment]
检查一下你的网络或DNS，拾色器部分报错，十之八九是因为无法访问到Greasyfork.org 下载到拾色器代码造成的。多刷新几次或者更换DNS重试即可。如果暂时无法访问到Greasyfork.org ，就稍后一会儿再试。

**Comment by F9y4ng** [comment]
PS:你是用的脚本管理器是UserScripts吧？我看它的基础API问题到现在还没修复呢。🤭

**Comment by easonnnone** [comment]
> PS:你是用的脚本管理器是UserScripts吧？我看它的基础API问题到现在还没修复呢。🤭

我用的是Stay

**Comment by F9y4ng** [comment]
Stay的基础API问题更多。🫣

相对来说，在Safari下 Tampermonkey 还是首选项呐。

**Comment by easonnnone** [comment]
> Stay的基础API问题更多。🫣
> 
> 相对来说，在Safari下 Tampermonkey 还是首选项呐。

发觉Mac版的Stay更废，连选择字体的选项都弹不出来

**Comment by F9y4ng** [comment]
> > Stay的基础API问题更多。🫣
> > 
> > 相对来说，在Safari下 Tampermonkey 还是首选项呐。
> 
> 发觉Mac版的Stay更废，连选择字体的选项都弹不出来

已针对Tampermonkey for safari做过兼容优化，一般来说推荐使用TM。

其他的脚本管理器，尤其是基本的API都改得乱糟糟的，应该不会做兼容处理。
