### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by FeiLZX3Km** [F9y4ng/GreasyFork-Scripts#172]
脚本在[FreshRSS页面](https://rss.rssforever.com/)配置时，配置页面错位。出现在了页面的最底部。
![image](https://user-images.githubusercontent.com/21981195/216866252-7088c8b4-7c87-41a6-b05b-05b4c1583fd2.png)

**Comment by F9y4ng** [comment]
该网站应用了CSP策略，禁止第三方脚本的运行，如果你使用Tampermonkey，可以在设置中修改以下选项：（虽然可无视CSP，但存在安全问题，请酌情使用！）
![CSP](https://user-images.githubusercontent.com/15855068/216884423-e8e21ed7-afb0-41f2-992d-052ca0a48195.jpg)

**Comment by FeiLZX3Km** [comment]
> 该网站应用了CSP策略，禁止第三方样式的加载，如果你使用Tampermonkey，可以在设置中修改以下选项：（虽然可无视CSP，但存在安全问题，请酌情使用！） ![CSP](https://user-images.githubusercontent.com/15855068/216884423-e8e21ed7-afb0-41f2-992d-052ca0a48195.jpg)

谢谢~
