### ISSUE TITLE
[发现错误] 微信读书网页版字体渲染错误

### ISSUE THREAD

**Issue by NNGTHB** [F9y4ng/GreasyFork-Scripts#173]
## 1. 准备工作（确认预先完成的操作）

- [x ] 我确认使用的是当前脚本的最新版本。
- [x ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x ] 我在**仅开启脚本管理器扩展**，并且**仅运行此脚本**时复现了脚本出错的情况。

## 2. 描述错误信息（清楚而简洁地描述错误）
微信读书网页版渲染出现错误，如图

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. 打开微信读书网页版
2. 页面渲染字体出现错误

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/115760745/217785170-b10a71ac-aa95-4542-831f-76e06909c9a9.png)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
字体渲染成功

## 6. 客户端信息（请务必认真填写您的本地信息）
- 操作系统 [_Win10_]：
- 浏览器 [_Chrome]：
- 浏览器版本 [_109.0.5414.120_]：
- 脚本管理器 [_如:Tampermonkey_]：
- 脚本管理器版本 [_4.18.1_]：
- 所用的脚本名称 [_字体渲染_]：
- 所用的脚本版本 [_2023.02.04.1_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）

- [x ] 是否同时运行了其他浏览器扩展？

- [x ] 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
微信读书网页版正文不是文本，而是SVG画布，所以脚本无法渲染图像中的字体。

请使用微信读书网页版中内置的字体设置工具。

**Comment by F9y4ng** [comment]
下个月更新中已针对微信读书进行了特别处理，修正了微信读书字体无法渲染的问题。

**Comment by NNGTHB** [comment]
> 下个月更新中已针对微信读书进行了特别处理，修正了微信读书字体无法渲染的问题。

好的，非常感谢！
