### ISSUE TITLE
[新增功能] 修复bing 链接全变成紫色问题

### ISSUE THREAD

**Issue by spphinslove** [F9y4ng/GreasyFork-Scripts#179]
可以吸收这个脚本的功能吗？bing搜索结果链接全是紫色的，应该是点击后才变紫色。
下面有人做了一个
https://greasyfork.org/zh-CN/scripts/460573-bing-%E9%93%BE%E6%8E%A5%E9%A2%9C%E8%89%B2%E4%BF%AE%E5%A4%8D

**Comment by F9y4ng** [comment]
下个月更新中会增加Bing搜索的链接样式。

**Comment by spphinslove** [comment]
好像没有修复吧 我换浏览器和脚本管理器都没修复

**Comment by F9y4ng** [comment]
![屏幕截图 2023-03-21 195147](https://user-images.githubusercontent.com/15855068/226598179-81e6fbd1-fb7e-40fd-a332-c6806b100e6c.png)
