### ISSUE TITLE
建议增加第三个小按钮

### ISSUE THREAD

**Issue by gbsix** [F9y4ng/GreasyFork-Scripts#180]
工具很不错！

但是总感觉搜索引擎少了点，能否增加第三个小按钮，点击展开更多其他搜索引擎供选择？如下图。

![image](https://user-images.githubusercontent.com/98303833/224914420-f06c2620-c951-4d5c-a2f2-fce7935eb652.png)

如果能自定义添加搜索引擎就更完美了！

**Comment by F9y4ng** [comment]
请使用脚本菜单或快捷键呼出跳转列表。
