### ISSUE TITLE
[发现错误] -不出现菜单选项

### ISSUE THREAD

**Issue by newrain-zh** [F9y4ng/GreasyFork-Scripts#182]
## 1. 准备工作（确认预先完成的操作）

- [ ] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
<img width="290" alt="image" src="https://user-images.githubusercontent.com/13865814/225192069-cf81d5b4-e2e2-4e82-b727-9d6f66b53a8a.png">

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
所有网站

## 4. 错误日志
菜单一直加载，没有预期菜单
[mp.weixin.qq.com-1678846736734.log](https://github.com/F9y4ng/GreasyFork-Scripts/files/10975503/mp.weixin.qq.com-1678846736734.log)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 ：macOs
- 浏览器 ：Microsoft Edge
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.03.04.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
无

- 是否同时运行了其他第三方用户脚本？

无

**Comment by F9y4ng** [comment]
我在本地并不能复现你的问题，macOS13.2, Edge111.0，Tampermonkey4.18.1, 全新安装后无任何问题。

1. 请补充完整你的客户端信息。
2. 按Bug Report排查本地其他扩展或脚本的冲突。
3. 按[错误日志获取方法](https://github.com/F9y4ng/GreasyFork-Scripts#%E5%A6%82%E4%BD%95%E6%8F%90%E4%BE%9B%E8%84%9A%E6%9C%AC%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97-new)提供脚本运行日志。
