### ISSUE TITLE
[新增功能] brave搜索请求添加

### ISSUE THREAD

**Issue by qanyue** [F9y4ng/GreasyFork-Scripts#183]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
请求添加 brave搜索引擎 https://search.brave.com/
看到有人安利：
![image](https://user-images.githubusercontent.com/55617091/225640952-55b2b9d3-7df6-4715-b67d-945b113988c7.png)

**Comment by F9y4ng** [comment]
search.brave已做好，正在本地测试完，预计下个月更新中就会发布，请稍等一段时间。
