### ISSUE TITLE
[发现错误] echarts示例代码等宽字体替换为非等宽，代码编辑时无法精准定位

### ISSUE THREAD

**Issue by feileb** [F9y4ng/GreasyFork-Scripts#184]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
echarts示例界面等宽字体替换为非等宽字体，根据配置添加了等宽字体配置，也删除了`,pre,pre *,code,code *`，没有效果

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
下面两个网址都有类似问题：
https://echarts.apache.org/examples/zh/editor.html?c=bar-background
https://www.makeapie.cn/echarts_content/mix-timeline-finance.html

**Comment by F9y4ng** [comment]
无法定位、选取错位等问题是字体缩放功能造成的，针对文档、代码编辑型网站暂时禁用缩放功能（设置为1）。

**Comment by F9y4ng** [comment]
添加以下代码至**自定义等宽字体** 根域及元素选择器 文本域：
```css
@www.makeapie.cn##.ace_line *,.ace_gutter-cell
@echarts.apache.org##.ace_line *,.ace_gutter-cell
```
