### ISSUE TITLE
latex公式字体不够美观

### ISSUE THREAD

**Issue by caogle** [F9y4ng/GreasyFork-Scripts#185]
- 这是打开脚本时的，
![image](https://user-images.githubusercontent.com/8144256/225820615-7fbdf829-0d63-461a-b779-54771d121dad.png)

- 这是关闭脚本以后的
![image](https://user-images.githubusercontent.com/8144256/225820555-7bdfbb74-6c99-4178-ab95-5c1b4855da2b.png)

**Comment by F9y4ng** [comment]
在相应的页面找到对应的元素，添加到需要渲染或排除渲染的文本域中即可。#42 中已罗列了一些修正规则可以作为参考。
