### ISSUE TITLE
[新增功能] 增加Searx搜索的跳转

### ISSUE THREAD

**Issue by bimzcy** [F9y4ng/GreasyFork-Scripts#186]
希望能增加Searx搜索的跳转，主要以自己搭建Searx为主。

**Comment by F9y4ng** [comment]
有些无从下手的感觉，大部分都是自建站点，域名不稳定，服务不稳定，GM脚本需要匹配域名提供服务，如果三天两头的需要更换域名那不是很蛋疼？没想到什么比较合适的办法来应用这类网站，如果其他朋友有好想法可以提一提。

**Comment by bimzcy** [comment]
只需要能适配按钮和搜索栏位置，我们自行填写群晖或服务器的网址即可（我通常搭建在群晖或者购买的VPS主机上）

**Comment by F9y4ng** [comment]
测试了一段时间，感觉没有接入的必要。

1. Searx本身就是搜索集合，获取了多个搜索引擎的搜索结果。
2. 网络上公开的Searx搜索大部分都不稳定，域名也不固定。
3. 如果作为本地搭建的站点，域名匹配方面又是个问题。
4. 小众化产品，实在是太小众，再加上我比较懒。
