### ISSUE TITLE
[发现错误] 搜索建议被bing的功能栏遮挡

### ISSUE THREAD

**Issue by JacobLee0713** [F9y4ng/GreasyFork-Scripts#189]
在bing.com(非cn.bing)的搜索结果页面点击搜索栏查看搜索建议时会出现建议结果被bing的功能栏遮挡，测试关闭脚本以后恢复正常。
![BTTClipPreviewBA0DBF3D-CC44-42CC-82DA-F3453359C350](https://user-images.githubusercontent.com/127098708/229766595-c887d4f9-1c2a-4cc9-810a-ea9042f96f6c.png)

**Comment by JacobLee0713** [comment]
![](localfile:///var/folders/fr/r54383m94c34jvr4vn19xy9m0000gn/T/BTTClipPreview678D6DE1-D0D8-4FC1-BF5E-60AD3FA6E864.png)

**Comment by JacobLee0713** [comment]
![BTTClipPreviewBA0DBF3D-CC44-42CC-82DA-F3453359C350](https://user-images.githubusercontent.com/127098708/229766484-3ebb024f-303e-4156-96c3-9a265e900aae.png)

**Comment by JacobLee0713** [comment]
关闭后：
![BTTClipPreviewFCA7B0B1-3AA1-45F1-83E7-D0162BE430BE](https://user-images.githubusercontent.com/127098708/229767045-b9a24a37-5cdf-409b-8c48-ea2f8a30fcb7.png)

**Comment by F9y4ng** [comment]
嗯，我已经发现这个问题了，下个月更新中会修正它。

**Comment by F9y4ng** [comment]
请更新至v2023.04.08.1
