### ISSUE TITLE
[发现错误] 访问 Notion 网站网页崩溃

### ISSUE THREAD

**Issue by weepwoood** [F9y4ng/GreasyFork-Scripts#193]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在 Issues 或 Discussions 中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

访问 Notion 的编辑页面（不是官网而是笔记页面），网页崩溃

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. 访问 Notion 的笔记页面，例如 [Notion 测试用页面](https://weepwood.notion.site/Notion-3a534389d4e5468a9a8923149e1c2022) 该页面
2. 遇到页面崩溃，无法访问，浏览器控制台不断打印如下报错信息

![image](https://user-images.githubusercontent.com/83107784/230733253-7c09a146-b113-4b02-964b-4fc93dbcca1b.png)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统：Windows 11 22H2
- 浏览器：Microsoft Edge
- 浏览器版本：112.0.1722.34
- 脚本管理器：Tampermonkey
- 脚本管理器版本：4.18.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2023.04.08.1

**Comment by yw124** [comment]
我也是早上起来发现崩溃了，虽然不知道什么原因。个人笔记页面直接无法全部加载。Microsoft Edge， win10系统

**Comment by F9y4ng** [comment]
## 问题复现
此站点问题和"金山文档"中遇到的问题类似，Notion的脚本中有监视元素改变的代码，与脚本中粗体描边修正的功能相互冲突，造成死循环运行，从而使浏览器无响应。

## 解决办法
进入[Notion主页](https://www.notion.so/zh-cn)，打开脚本配置界面，找到**粗体修正**，取消勾选，保存为站点独享。
