### ISSUE TITLE
[新增功能] 

### ISSUE THREAD

**Issue by Jhesterccj** [F9y4ng/GreasyFork-Scripts#194]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
建议增加更多搜索引擎，而不是只有那四个，如知乎，知网等

**Comment by F9y4ng** [comment]
这类需求以前有用户提过，再次说明一下，搜索引擎跳转只提供搜索引擎站点的跳转，信息孤岛网站不在此中。如有其他需求，请使用其他同类脚本。

脚本提供了15个国内外常用搜索引擎，为什么你只能看到4个？如果要使用此脚本，建议你先认真阅读脚本使用说明。
