### ISSUE TITLE
[发现错误] 油管页面设置异常

### ISSUE THREAD

**Issue by Sakuzy0** [F9y4ng/GreasyFork-Scripts#198]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
油管点击字体渲染或高级核心  设置页面错位至网页左边

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去XX网址 "..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _遇到错误或问题 "..."_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
<img width="592" alt="3" src="https://user-images.githubusercontent.com/76892955/230814335-99c581b6-5621-4b2e-ad6c-b7ebd5224b7e.png">

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：win11-22621.1485
- 浏览器 [_如:Chrome,Safari_]：edge
- 浏览器版本 [_如:108.0.5359.128_]：112.0.1722.34
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：4.18.1
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.04.08.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

已尝试禁用所有其他扩展和脚本

- 是否同时运行了其他第三方用户脚本？

无

## 8. 附加信息（在此处添加您认为有用的其他信息）
暂未发现其他网页有此异常

**Comment by Sakuzy0** [comment]
[www.youtube.com-1681095069729.log](https://github.com/F9y4ng/GreasyFork-Scripts/files/11187261/www.youtube.com-1681095069729.log)

**Comment by F9y4ng** [comment]
从你反馈的日志中，我确实看到了错误信息，但这个问题在我本地不能复现。我在日志中发现你本地浏览器有执行另外一个JS脚本（desktop_polymer.js）,可能是它与字体渲染脚本有冲突，而出现此问题。我已尝试修复这个bug，并会在近期发布一个新版本 。

以下是我本地不能复现的截图：
![test](https://user-images.githubusercontent.com/15855068/230822842-0b34c99f-a053-46bb-9172-8f00f7ab6833.png)
