### ISSUE TITLE
B站评论不渲染怎么弄？那个公告栏里面没有对应的解决方式

### ISSUE THREAD

**Issue by cnxb01** [F9y4ng/GreasyFork-Scripts#199]

**Comment by F9y4ng** [comment]
重复反馈，参考 #195

**Comment by cnxb01** [comment]
多谢

**Comment by cnxb01** [comment]
![image](https://user-images.githubusercontent.com/73676357/230871792-4239655f-3f93-4385-8b58-f350b8fd01bf.png)
这个旧的反馈看不到哦

**Comment by cnxb01** [comment]
> 重复反馈，参考 #195

作者你好，我试了下，三个名称加上去之后还是没有用，然后我用以前备份的设置对比看了看，需要渲染和排除渲染的部分有区别，用旧版的就没问题了

**Comment by F9y4ng** [comment]
> 作者你好，我试了下，三个名称加上去之后还是没有用，然后我用以前备份的设置对比看了看，需要渲染和排除渲染的部分有区别，用旧版的就没问题了

建议你使用最新版的规则，它的兼容性更好，你之前添加过的自定义字体检查一下他们的postscript名称是否都正确。

你也可以直接下载使用 #46 中已推荐的自定义字体和字体代码。需要注意的是，要实现全局热替换字体必须填写postscript名称，也就是自定义字体代码中ps:的部分。

**Comment by cnxb01** [comment]
> > 作者你好，我试了下，三个名称加上去之后还是没有用，然后我用以前备份的设置对比看了看，需要渲染和排除渲染的部分有区别，用旧版的就没问题了
> 
> 建议你使用最新版的规则，它的兼容性更好，你之前添加过的自定义字体检查一下他们的postscript名称是否都正确。
> 
> 你也可以直接下载使用 #46 中已推荐的自定义字体和字体代码。需要注意的是，要实现全局热替换字体必须填写postscript名称，也就是自定义字体代码中ps:的部分。

我已经试过了，不改变自定义字体(三个名称)的情况下，使用新版的【需要渲染的网页元素】是不能渲染评论的(图3)，用旧版就可以(图1)，甚至旧版不需要postscript也正常渲染(图2)
![屏幕截图 2023-04-10 185038](https://user-images.githubusercontent.com/73676357/230888640-3e043da8-8197-4a0d-9793-401788f2fabf.png)
![屏幕截图 2023-04-10 185300](https://user-images.githubusercontent.com/73676357/230888647-aa11ee63-bc11-42fd-967c-98cdcd74f52d.png)
![屏幕截图 2023-04-10 184805](https://user-images.githubusercontent.com/73676357/230888634-176d09e3-26af-4a82-b1f9-b83d589fd923.png)

**Comment by cnxb01** [comment]
新旧版指【需要渲染的网页元素】的新旧，不是脚本版本，脚本都是最新版

**Comment by F9y4ng** [comment]
你的浏览器是？版本？根据检查一下你的浏览器兼容性。
![caniuse](https://user-images.githubusercontent.com/15855068/230896125-bc724945-7435-451f-9c90-ec3afa5a1b36.png)

字体的热替换与**需要渲染的网页元素**并没有太大的关系，如果原来的参数才能生效，你可以更换为旧版本的默认参数，如下：
```css
:not(i,head *):not([class*='glyph']):not([class*='icon']):not([class*='fa-']):not([class*='vjs-'])
```

**Comment by cnxb01** [comment]
> 你的浏览器是？版本？根据检查一下你的浏览器兼容性。 ![caniuse](https://user-images.githubusercontent.com/15855068/230896125-bc724945-7435-451f-9c90-ec3afa5a1b36.png)
> 
> 字体的热替换与**需要渲染的网页元素**并没有太大的关系，如果原来的参数才能生效，你可以更换为旧版本的默认参数，如下：
> 
> ```css
> :not(i,head *):not([class*='glyph']):not([class*='icon']):not([class*='fa-']):not([class*='vjs-'])
> ```

https://wwvw.lanzouy.com/iQm6p0smcrch
作者，我录了个视频你看看

**Comment by F9y4ng** [comment]
你的录屏我看了，很奇怪的情况，我在Edge v112 下不能复现你遇到的问题：

![录制_2023_04_10_20_42_57_589](https://user-images.githubusercontent.com/15855068/230903748-6f7376ab-3591-492a-8310-2c3c651df5e1.gif)


BTW. 你可以在高级设置中打开预览功能，这样就不需要每次保存刷新页面，点“预览”按钮就可以看到新效果了。

**Comment by cnxb01** [comment]
> 你的录屏我看了，很奇怪的情况，我在Edge v112 下不能复现你遇到的问题：
> 
> ![录制_2023_04_10_20_42_57_589](https://user-images.githubusercontent.com/15855068/230903748-6f7376ab-3591-492a-8310-2c3c651df5e1.gif) [ ![录制_2023_04_10_20_42_57_589](https://user-images.githubusercontent.com/15855068/230903748-6f7376ab-3591-492a-8310-2c3c651df5e1.gif) ](https://user-images.githubusercontent.com/15855068/230903748-6f7376ab-3591-492a-8310-2c3c651df5e1.gif) [ ](https://user-images.githubusercontent.com/15855068/230903748-6f7376ab-3591-492a-8310-2c3c651df5e1.gif)
> 
> BTW. 你可以在高级设置中打开预览功能，这样就不需要每次保存刷新页面，点“预览”按钮就可以看到新效果了。

视频里面有个细节，在37秒前后更换自定义字体后，视频的标题显示的字体是不变的，但是视频预览窗口中的播放量，时长，up名称这些是有变化的，看起来就是渲染规则有问题

**Comment by F9y4ng** [comment]
你遇到的这个问题只能在你本地计算机上复现，其他用户并没有遇到同样的问题。你最好是检查你本地计算机的设置、使用的字体、浏览器的设置、扩展、去广告软件等等任何能影响字体的因素你要去逐一排除。如果你排查后依然找不到原因，那你就用旧版本的过滤规则，记得备份数据。

**Comment by F9y4ng** [comment]
更新至v2023.04.10.2，重置数据后就可应用修正后的过滤规则了。
