### ISSUE TITLE
黑暗模式搞起来！

### ISSUE THREAD

**Issue by Alex-NKG** [F9y4ng/GreasyFork-Scripts#2]
可以把百度/Google 的黑暗模式搞起来，跟随系统

**Comment by F9y4ng** [comment]
已经有很多不错的扩展程序可以实现你想要的黑暗模式，比如：[Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=zh-CN)
