### ISSUE TITLE
[发现错误] 我的小站点击链接内容会消失的bug

### ISSUE THREAD

**Issue by qhq** [F9y4ng/GreasyFork-Scripts#204]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
点击页面分类链接后，显示空白页面，刷新网页后才能正常显示

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. 打开 https://pan666.net/
2. 点击左侧影视类链接
3. 页面不显示
4. 刷新页面后正常显示

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![QQ截图20230411195305](https://user-images.githubusercontent.com/3319385/231155088-c902a1b6-6bab-4fff-939f-4f9e68336c72.png)

![QQ截图20230411195348](https://user-images.githubusercontent.com/3319385/231155272-041c1503-cb05-44a5-9a72-f45723d40ef6.png)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：
- 浏览器 [_如:Chrome,Safari_]：
- 浏览器版本 [_如:108.0.5359.128_]：
- 脚本管理器 [_如:Tampermonkey_]：
- 脚本管理器版本 [_如:4.18.1_]：
- 所用的脚本名称 [_如:FontRendering_]：
- 所用的脚本版本 [_如:2020.11.24.1_]：
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
已经捕捉到这个问题所在了，下个更新会修复它。

## 临时的解决办法
在**高级核心功能设置**中关闭**视口单位修正**功能。

**Comment by qhq** [comment]
感谢答复。另有一个问题顺带问下，不知道是能修正的bug还是就是如此的。
有些网页使用字体缩放后，会导致原本能正常见到的内容超出范围无法可见，也不是那种通过滚动条可以滚动后查看操作的。
比如下图的，遇到这种的，是不是只能关闭缩放效果。
![QQ截图20230411204721](https://user-images.githubusercontent.com/3319385/231166917-a2820812-3245-4362-abe7-4423331a775f.png)

**Comment by F9y4ng** [comment]
这是字体缩放引起的问题，根本原因是站点自身的样式没有对缩放自适应或是在样式内写死了宽高度造成的，并非滚动条能解决的问题，而且无法修复。所以，此类站点上只能关闭字体缩放，使用浏览器缩放替代。
