### ISSUE TITLE
谢谢作者让我用到了这么舒服的插件。 

### ISSUE THREAD

**Issue by matocool** [F9y4ng/GreasyFork-Scripts#207]
太舒服了。。。。

关闭之后浏览器默认字体简直一坨答辩。。。

主要是之前用过别的插件效果都不如作者的插件。。。。

好比做过动车之后不想坐火车了。。。

非常感谢作者~

谢谢

**Comment by F9y4ng** [comment]
感谢使用脚本，欢迎积极提建议、反馈错误。


P.S. 非脚本错误、异常请发帖至Discussions.
