### ISSUE TITLE
[发现错误] 网站渲染出错

### ISSUE THREAD

**Issue by Waldenmuxi** [F9y4ng/GreasyFork-Scripts#208]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
https://www.mini4k.com/
该网站渲染出错

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
打开网站即出现问题
https://www.mini4k.com/

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![VeryCapture_20230423130432](https://user-images.githubusercontent.com/56295944/233820848-82f2714e-0822-456d-a4bd-4674bc5fec6c.jpg)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Windows11
- 浏览器 [_如:Chrome,Safari_]：Chrome 
- 浏览器版本 [_如:108.0.5359.128_]：113.0.5672.48
- 脚本管理器 [_如:Tampermonkey_]：Violent Monkey
- 脚本管理器版本 [_如:4.18.1_]：2.14.0
- 所用的脚本名称 [_如:FontRendering_]：
- 所用的脚本版本 [_如:2020.11.24.1_]：
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

否

- 是否同时运行了其他第三方用户脚本？

否

**Comment by F9y4ng** [comment]
#42 
```
旧版升级至新版的用户注意：在遇到样式问题时，请先尝试使用重置按钮重置数据，再重新配置相关参数，以使用最新过滤规则。
```
