### ISSUE TITLE
必应卡死并随后显示波浪线

### ISSUE THREAD

**Issue by hi-yiyang** [F9y4ng/GreasyFork-Scripts#209]
![image](https://user-images.githubusercontent.com/51028862/233868493-ce0d55eb-953e-409d-bacc-8be5271afbbc.png)

在多个浏览器、多个装载器中稳定复现。关闭“去除重定向跳转”后可以解决。

**Comment by F9y4ng** [comment]
##解决办法
1. 访问中国特供版。
2. 换个付费的高速的梯子访问全球版。
3. 关闭去除重定向。

**Comment by hi-yiyang** [comment]
肉身在国外，一直访问的是全球版。。。
另外，这一bug是在三月某一次更新后出现的。

**Comment by F9y4ng** [comment]
> 肉身在国外，一直访问的是全球版。。。
> 另外，这一bug是在三月某一次更新后出现的。

三月份的两次更新没有改动过重定向去除相关的代码，获取真实链接超时（默认8秒）的情况我有遇到过，一般刷新后恢复正常，但卡死的情况却没有复现过一次。

**Comment by hi-yiyang** [comment]
我用两台电脑，四个浏览器，以及两个插件装载器100%复现。



---Original---
From: ***@***.***&gt;
Sent at: 2023年4月24日(Mon) Early Morning0:10
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [F9y4ng/GreasyFork-Scripts] 必应卡死并随后显示波浪线 (Issue #209)




  
肉身在国外，一直访问的是全球版。。。
 另外，这一bug是在三月某一次更新后出现的。
  
三月份的两次更新没有改动过重定向去除相关的代码，获取真实链接超时（默认8秒）的情况我有遇到过，一般刷新后恢复正常，但卡死的情况却没有复现过一次。

**Comment by F9y4ng** [comment]
OK，将你本地浏览器环境参数按Bug issue填写一下，我看看在我本地能不能复现这个问题。

**Comment by F9y4ng** [comment]
在chromium内核浏览器中测试了一下，大概是xhr超时时长比较短，造成获取过多的真实链接时由于请求排队的问题而出现超时的问题，至于卡死的情况我却无法复现。

脚本程序在获取真实链接时使用异步操作，并不会对主进程造成阻塞，所以应该不会造成卡死的情况，即使全部连接都超时。下个更新我会增加国际版链接获取的超时时长，看是否会缓解该问题。

**Comment by F9y4ng** [comment]
更新至2023.05.06.1版本后再尝试访问www.bing.com，查看是否还能复现你本地遇到的问题。
