### ISSUE TITLE
[发现错误] you.com 搜索框左移

### ISSUE THREAD

**Issue by OrangeCatSleepless** [F9y4ng/GreasyFork-Scripts#211]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在 Issues 或 Discussions 中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
开启脚本后, YOU.com 搜索时,底部搜索框左移

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去 XX 网址 "..."_
2. _单击 YY 链接 / 按钮 "..."_
3. _向下滚动到 ZZ 位置 "..."_
4. _遇到错误或问题 "..."_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

搜索框左移

![xn12p2OAFl](https://user-images.githubusercontent.com/58691431/236145170-5cf3468d-a1e2-4fde-a33d-13daed8ccf57.png)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

默认情况下位居中

![EwbyPwzhqD](https://user-images.githubusercontent.com/58691431/236145313-aeccb6c8-b448-431e-a8e5-93d619b26344.png)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如：Win10,MacOS_]：
- 浏览器 [_如：Chrome,Safari_]：
- 浏览器版本 [_如：108.0.5359.128_]：
- 脚本管理器 [_如：Tampermonkey_]：
- 脚本管理器版本 [_如：4.18.1_]：
- 所用的脚本名称 [_如：FontRendering_]：
- 所用的脚本版本 [_如：2020.11.24.1_]：
- 其他补充信息 [_如：您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
这个问题已在新版本中修正，请等候更新即可。
