### ISSUE TITLE
开启字体渲染情况下github Trending界面卡顿严重

### ISSUE THREAD

**Issue by Lyn6969** [F9y4ng/GreasyFork-Scripts#212]
https://github.com/trending 在开启字体渲染之后，trending界面卡顿，无法点击项目链接，关闭渲染插件或者排除github.com之后恢复正常

**Comment by F9y4ng** [comment]
尝试将设置界面上`视口修正`取消勾选，保存为站点独享。

或在高级核心功能设置中`视口单位修正`关闭之并保存。

**Comment by F9y4ng** [comment]
我本地不能复现此问题，建议你排查一下你本地是否存在与其他扩展或脚本冲突的问题。

**Comment by Lyn6969** [comment]
> 我本地不能复现此问题，建议你排查一下你本地是否存在与其他扩展或脚本冲突的问题。

好的，谢谢您
