### ISSUE TITLE
新版本严重影响油管

### ISSUE THREAD

**Issue by pcitme** [F9y4ng/GreasyFork-Scripts#213]
以前都一切正常，最近不知道哪个版本开始的只要打开油管，CPU温度瞬间从40°涨到80多，然后油管一直转圈打不开还乱码，开始还以为是chrome最新内核强制油管走AV1解码了，我是AMD不支持，就换了百分浏览器是低内核打开油管一切正常，今天为了字体好看又安装了渲染脚本结果油管又不行了，停用脚本就正常，也不知道一个渲染脚本怎么会严重到影响油管的。。

**Comment by F9y4ng** [comment]
几个常用的浏览器和大部分网站我在发布新版本前，本地都有做过测试，都不能复现你所描述的情况。

感觉应该是脚本的某个功能与你本地的扩展或其他脚本有冲突。

## 建议你检查以下几个功能的冲突可能：
1. 视口修正功能，可在**高级核心功能设置**中关闭，也可在**字体渲染设置**中取消勾选**视口修正**保存为站点独享，然后再看是否能复现？
2. 粗体修正功能，可在**字体渲染设置**中取消勾选**粗体修正**保存为站点独享，然后再看是否能复现？

如果关闭后问题消失了，请帮忙检测一下是与你本地哪个扩展或脚本产生了冲突。

**Comment by pcitme** [comment]
> 

视口修正功能关闭无效，粗体修正功能关闭有效了，后续关闭所有其他脚本和扩展打勾粗体修正还是影响油管。此时只有一个暴力猴扩展和渲染脚本。。

**Comment by F9y4ng** [comment]
那应该是粗体修正与你本地的某个扩展或第三方脚本有冲突，造成程序无限循环执行而产生的CPU高占用。（排查方向：去广告的扩展、其他影响样式的扩展、其他第三方脚本、其他网页防火墙之类等等）

* 你需排查出影响脚本运行的其他扩展或脚本，将其停用后再试。
* 或者在油管中关闭粗体修正功能，或将字体描边设置为0（OFF），保存为站点独享数据。

**Comment by pcitme** [comment]
嗯嗯 感谢大佬了 描边设0也有效。 但还是排查不出来是哪个脚本扩展冲突了，我其他全部都关闭了的。。也可能是AMD的锅，就这样用吧能用就好。。

**Comment by F9y4ng** [comment]
> 嗯嗯 感谢大佬了 描边设0也有效。 但还是排查不出来是哪个脚本扩展冲突了，我其他全部都关闭了的。。也可能是AMD的锅，就这样用吧能用就好。。

AMD平台的问题不只一次有用户反应，之前也有使用AMD平台在个别站点出现高占用问题（#174)，感觉应该是驱动兼容问题。我本地没有AMD平台设备所以鞭长莫及，无法排查问题。你尝试将浏览器的硬件加速关闭再试试看？不保证有用。
