### ISSUE TITLE
`input`输入框的字体问题

### ISSUE THREAD

**Issue by aboutZZ** [F9y4ng/GreasyFork-Scripts#214]
我发现您对`input`输入框的字体进行了调整（`font-family`设置为了`initial`），这导致输入框的原始字体十分难看，且有锯齿（见下图）。希望能增加个开关，去掉这一设置
https://github.com/F9y4ng/GreasyFork-Scripts/blob/4be47f5e2b2e917f9b70c45d56fac4a272b277ea/Font%20Rendering.user.js#L879-L881

设置`font-family:initial`效果图：
![图片](https://user-images.githubusercontent.com/15063761/236656837-db49373b-ee66-45d3-8fbe-4b94c5690458.png)

去掉`font-family:initial`后的效果
![图片](https://user-images.githubusercontent.com/15063761/236656880-d1035670-4d9f-4505-9805-75c4ff1f88c0.png)

**Comment by F9y4ng** [comment]
该样式仅在Firefox中生效。Firefox的input标签会受到字体的字宽影响而造成input宽度被撑大，造成样式问题。

所以这并不是个问题。

字体初始值的设定会默认调用浏览器的默认字体，可通过关闭字体重写功能来禁用此功能。
