### ISSUE TITLE
[发现错误] QQ邮箱排除渲染后卡住

### ISSUE THREAD

**Issue by 114622309** [F9y4ng/GreasyFork-Scripts#215]
![Uploading image.png…]()
一直显示正在载入，网页卡住

**Comment by 114622309** [comment]
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/75884245/a0667417-8260-4568-9641-955e581e8cf4)

**Comment by F9y4ng** [comment]
目测一切正常。

![屏幕截图 2023-05-10 195646](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/85e402bd-14d3-48cd-a145-aa985a5e043a)

**Comment by F9y4ng** [comment]
建议你暂时使用新版QQ邮箱，新版没有这些问题，老版的QQ邮箱只能用屎山来形容，我不想去兼容它。

进入新版QQ邮箱的方法：
1. 进入设置，语言选择英文，保存。
2. 刷新页面就会自动进入新版QQ邮箱。
3. 右上角，点击下箭头下拉菜单中，点击setting进入设置页面。
4. 找到Language 语言，改为中文，正常使用。

![屏幕截图 2023-05-10 195646](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/94aeded7-f142-4dfc-89f9-1eb81267b9b5)
