### ISSUE TITLE
[发现错误] Steam 文字會消失不見

### ISSUE THREAD

**Issue by MrLuke1110** [F9y4ng/GreasyFork-Scripts#216]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去Steam网址 "[...](https://store.steampowered.com/)"_
2. _搜尋任意關鍵字 "例如: cuphead"_
3. _自訂字體消失不見，游標移過去才看得到 "..."_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/66194793/0d344bcb-0409-45f3-aa91-35c1c2ee5cfe)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
希望可以正確呈現字體

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 []：Win10
- 浏览器 []：Chrome
- 浏览器版本 []：113.0.5672.93
- 脚本管理器 []：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：4.18.1
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.05.06.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：無

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
無

- 是否同时运行了其他第三方用户脚本？
無

## 8. 附加信息（在此处添加您认为有用的其他信息）
以自訂義排除可暫時解決

**Comment by F9y4ng** [comment]
不能理解**错误再现**中你描述的操作流畅，我尝试了一下，似乎没有什么问题？

需要你再描述得详细一些。

![test](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/763b8a76-7f5d-45fb-8832-d82039cbe936)

**Comment by MrLuke1110** [comment]
**發現應該是更紗黑體的關係，原本預設的就可以正常呈現**

step1, 原本的網頁尚未變更前
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/66194793/951cd3ea-f214-42e1-9114-80ebdcbef107)

step2, 選擇字體「等距更紗黑體TC」
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/66194793/89fc3a1c-a456-4554-b7a6-2434fdece5d1)

step3, 選擇保存
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/66194793/42f33fd8-3280-4fa8-b44a-b8f8de3e1b1c)

step4, 字體消失不見
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/66194793/00a4d7bc-39cd-47f0-82a1-877f89f45a3f)

**Comment by F9y4ng** [comment]
我在本地测试了`{"ch":"等距更纱黑体 T SC","en":"Sarasa Mono T SC","ps":"Sarasa-Mono-T-SC-Regular"}
`，确实是该字体家族中等宽字体族的bug，而非等宽字体正常。

从脚本层面上无法处理字体的内部错误，你需要更换其他字体使用。

**Comment by MrLuke1110** [comment]
我是這樣設定 {"ch":"等距更紗黑體 TC","en":"Sarasa Mono TC"}，
看來只能依照您的建議去使用，那就只能再找其他等寬字體來使用，謝謝回覆。

**Comment by F9y4ng** [comment]
> 我是這樣設定 {"ch":"等距更紗黑體 TC","en":"Sarasa Mono TC"}， 看來只能依照您的建議去使用，那就只能再找其他等寬字體來使用，謝謝回覆。

使用第三方字体时最好将 `Postscript Name` 加入，字体的热替换需要使用 `Postscript Name`。

字体的 `Postscript Name` 信息可以到fontke.com去查询。（注意字体的名称和版本要与你本地一致） 具体操作参阅 #64

**Comment by F9y4ng** [comment]
深入看了一下，应该是Sarasa Mono T SC字体的字高与字宽造成元素文本超出而被隐藏造成的。

从根本上来说不是字体的bug，而是该字体的字高和字宽设定并不适合用于网页字体。

所以还是换个字体用吧。
