### ISSUE TITLE
[发现错误] youtube访问错误

### ISSUE THREAD

**Issue by elvensen** [F9y4ng/GreasyFork-Scripts#217]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
脚本导致YouTube页面无响应

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. 开着脚本访问YouTube即可

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
希望兼容YouTube

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Win11、Win10
- 浏览器 [_如:Chrome,Safari_]：edge
- 浏览器版本 [_如:108.0.5359.128_]：目前是113.0.1774.50，之前的几个版本就有这问题了
- 脚本管理器 [_如:Tampermonkey_]：暴力猴
- 脚本管理器版本 [_如:4.18.1_]：2.13.4
- 所用的脚本名称 [_如:FontRendering_]：字体渲染
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.05.20.1，之前的版本也有这个问题
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

扩展很多，估计有可能有关系的就是adblock，但排除过，关了症状依旧

- 是否同时运行了其他第三方用户脚本？

YouTube上生效的有5个脚本，全部禁用，能正常访问，测试单独开，只有开字体渲染时症状重现了

**Comment by F9y4ng** [comment]
看起来应该和 #213 是同一类问题。

由于我本地一直不能复现在油管上的问题，所以我并没有找到造成该问题的实际原因，但可以大概确定的是某些条件下（与某扩展冲突？与某脚本冲突？与某些网页防火墙冲突？或者其他的冲突？）与脚本的**粗体修正**功能产生冲突造成脚本死循环执行而页面无响应的情况。

按之前的处理方法，将字体设置界面中**粗体修正**功能去除勾选后保存为站点独享数据，或者将字体描边关闭（设置为0）保存为站点独享数据。

另外，你的本地计算机的CPU也是AMD平台的么？

**Comment by elvensen** [comment]
还真是粗体修正的问题，去掉了就好了，十分感谢！

不过过程有点曲折，由于我油管页面加载不出来，猴子上面脚本选项也出不来，所以我是随便开个网页，去掉粗体修正保存全局，然后打开YouTube，正常加载了，改粗体修正保存成网站数据，再回到别的页面重新存个有修正全局。

至于冲突，我的扩展和脚本都是20+，完整排查一波还挺费时，所以只做过部分排查，把自己觉得有可能有关系的排了一下。

硬件方面，我公司的笔记本CPU是AMD的，台式机和家里游戏本是Intel的，症状完全一样。

**Comment by F9y4ng** [comment]
通过Chrome添加新的本地账户来开启一个完全初始化的浏览器，在应用商店中仅安装Tampermonkey或Violentmonkey扩展，仅安装字体渲染脚本后再测试是否还能复现问题，如果一切正常，说明脚本肯定与你安装过的某个扩展或脚本有冲突。

可通过逐一安装扩展或脚本排查出产生冲突的问题所在。

**Comment by elvensen** [comment]
重新安装Chrome，仅安装暴力猴和脚本，症状略有不同，页面能加载出来，但是左侧内容加载不出来。
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/84362247/81632b9d-10f3-43be-931e-33ef7d45b570)

去掉粗体修正后正常访问。

同样情况用edge，则是卡住，空白页面出不来内容。去掉粗体修正后正常。但今天我用虚拟机测试了一下，同样环境下粗体修正可以开，不影响访问，这就很神奇。

思考了一下差别，虚拟机里基本上啥都没装，实机上则是装了很多办公、游戏相关软件。在浏览器外能产生影响的软件应该是卡巴斯基（单位电脑用的是火绒）和MacType，都停用过发现没有改变。剩下的可能就是硬件了，虚拟机虚拟的硬件尤其是显卡和物理设备还是差很大的，但这个好像也改变不了啥。

或者哪天我准备重装系统的时候，我每装一个软件就试试访问结果。

**Comment by F9y4ng** [comment]
感谢帮忙测试。

从你的描述来看，我猜测是否是杀毒软件的网页防火墙造成的问题？从造成页面卡死的现象本身来分析，一定是有某个程序在页面上注入了新的元素，并实时监视这个元素的状态，如果被修改就立刻重新写入，这时就会与粗体修正发生冲突。

目前已知的一部分在线编辑型网站（如Notion、金山文档等）会存在这样守护脚本，而这部分已知的网站已在脚本中做了排除。
