### ISSUE TITLE
[新增功能] 大佬，能不能加点淘宝京东之类的购物网站，方便买东西时候跳转

### ISSUE THREAD

**Issue by kfram** [F9y4ng/GreasyFork-Scripts#218]
## 1. 准备工作（确认预先完成的操作）

- [ ] 我确认使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

**Comment by F9y4ng** [comment]
没有这个计划。
