### ISSUE TITLE
发现有的页面需要刷新一次才能有效果

### ISSUE THREAD

**Issue by matocool** [F9y4ng/GreasyFork-Scripts#220]
https://www.douyu.com/g_KOEINOBU  

我的360极速浏览器在这个页面会这样，需要刷新一次才能有效果。

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/83129369/411313db-d656-499a-8a7c-ccd8bbfae053)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/83129369/24c9678f-4243-4850-b2bd-557d1696f450)

第二个问题是在GitHub代码编辑页面会出现重影  

https://github.com/matocool/GreasyFork-Scripts/blob/master/Font%20Rendering.user.js

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/83129369/79d0f6b3-aba2-4803-931d-44548fae9019)

**Comment by F9y4ng** [comment]
## 问题1
必定是其他第三方脚本引起的阻塞造成的，仅开启字体渲染脚本再试，或者停用本脚本。

## 问题2 
升级至脚本最新版，必要时重置数据后重试。

## 其他
反馈问题时，请按Bug Report模板内容填写，我不是神仙，什么都能猜的中。
