### ISSUE TITLE
[发现错误] Google Search Labs 中显示错误

### ISSUE THREAD

**Issue by fdoffo** [F9y4ng/GreasyFork-Scripts#222]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
在 Google Search Labs 中显示错误，挤占了输入框成为了极窄一条，见下文图

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _点击 Converse_
2. _输入任何内容后发送_
3. _遇到错误或问题_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
[https://i.imgur.com/mNCTEsa.png](https://i.imgur.com/mNCTEsa.png)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
感觉此处不需要跳转 Baidu/Bing 按钮，建议可以去掉

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：macos Ventura Version 13.4 (22F66)
- 浏览器 [_如:Chrome,Safari_]：Chrome
- 浏览器版本 [_如:108.0.5359.128_]：Version 113.0.5672.126 (Official Build) (arm64)
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：v4.18.1
- 所用的脚本名称 [_如:FontRendering_]：SearchEngine Assistant
- 所用的脚本版本 [_如:2020.11.24.1_]：v2023.05.13.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

全部禁用后仍有该问题

- 是否同时运行了其他第三方用户脚本？

无

## 8. 附加信息（在此处添加您认为有用的其他信息）
无

**Comment by F9y4ng** [comment]
我遇到了几个问题：
1. Google Search Labs 也需要加入waitlist，我所有的Google账户都没有申请过😂，只有Bard。
2. Google Search Labs 的访问地址是labs.google.com吗？ 如果是，你可以暂时通过脚本管理器排除该域名，下个更新中我会将该域名停止处理。

**Comment by fdoffo** [comment]
如下图，Search Labs 和 Bing AI 处理差不多，在搜索框底下加了个 Converse 按钮，点击后弹出 4. 屏幕截图 中的对话窗口，都是在当前搜索结果页 www.google.com/search? 下的，无法排除域名。

[https://i.imgur.com/4j1P5cA.png](https://i.imgur.com/4j1P5cA.png)

**Comment by F9y4ng** [comment]
请将你使用Converse功能出现问题后，完整的URL发出来，需要包含所有的参数。

**Comment by fdoffo** [comment]
https://www.google.com/search?newwindow=1&sxsrf=APwXEddzmqTXpQJuvrY9p8V3Ns-M5ZLL2w%3A1685514253344&source=hp&ei=Deh2ZMXjEo3PkPIP0r-B0Ac&iflsig=AOEireoAAAAAZHb2Hb3mSzaytk9V332Uml_hpCRu-DtL&uact=5&oq=test&gs_lcp=Cgdnd3Mtd2l6EAMyBwgjEIoFECcyBwgAEIoFEEMyCAgAEIoFEJECMgoIABCKBRCxAxBDMgcIABCKBRBDMgcIABCKBRBDMgcIABCKBRBDMhAIABCABBAUEIcCELEDEIMBMgcIABCKBRBDMgcIABCKBRBDOgcIIxDqAhAnOgsIABCABBCxAxCDAToRCC4QgAQQsQMQgwEQxwEQ0QM6BQgAEIAEOgsILhCABBCxAxCDAToWCC4QigUQsQMQgwEQxwEQ0QMQ1AIQQ1ChA1jQDGCPGGgCcAB4AoAB0AKIAaELkgEFMi00LjGYAQCgAQGwAQo&sclient=gws-wiz&cs=0&csui=1&gsas=1&q=test&ved=2ahUKEwj66Kn19Z7_AhVUIEQIHXxFBYsQ0pQJegQIDBAB&csuio=2&csuip=6&mstk=AVHsw5hplvk-05kFQOZnGWBxniUWOVl37Yr5DXEL9-16nrpkXZ-KX7rJxs9jI3Nb89utmQSLWEbSAgHgC9-gk332EqpS-tNb5zxmIsX7Kw9Z7oHPpsEncEeQYJ3oqOgbu7btaXlGj2ueVVR4P7vrq4z_8-YXPlAshX9dsY8i67iC-a0Z1g66-5wqmCgjTfaCMIznHIUpA4jW2Sg4mjZquXPUnDfwZEqh4v_DTqXJIWhp4996lmC_Dk-KLnKyL8y4JriV&csuir=1

**Comment by F9y4ng** [comment]
你尝试一下下面的地址，如果没有跳转到google labs的搜索界面，我会在下次更新时修复这个问题。

https://www.google.com/search?newwindow=1&sxsrf=APwXEddzmqTXpQJuvrY9p8V3Ns-M5ZLL2w%3A1685514253344&source=hp&ei=Deh2ZMXjEo3PkPIP0r-B0Ac&iflsig=AOEireoAAAAAZHb2Hb3mSzaytk9V332Uml_hpCRu-DtL&uact=5&oq=test&gs_lcp=Cgdnd3Mtd2l6EAMyBwgjEIoFECcyBwgAEIoFEEMyCAgAEIoFEJECMgoIABCKBRCxAxBDMgcIABCKBRBDMgcIABCKBRBDMgcIABCKBRBDMhAIABCABBAUEIcCELEDEIMBMgcIABCKBRBDMgcIABCKBRBDOgcIIxDqAhAnOgsIABCABBCxAxCDAToRCC4QgAQQsQMQgwEQxwEQ0QM6BQgAEIAEOgsILhCABBCxAxCDAToWCC4QigUQsQMQgwEQxwEQ0QMQ1AIQQ1ChA1jQDGCPGGgCcAB4AoAB0AKIAaELkgEFMi00LjGYAQCgAQGwAQo&sclient=gws-wiz&cs=0&gsas=1&q=test&ved=2ahUKEwj66Kn19Z7_AhVUIEQIHXxFBYsQ0pQJegQIDBAB&csuio=2&csuip=6&mstk=AVHsw5hplvk-05kFQOZnGWBxniUWOVl37Yr5DXEL9-16nrpkXZ-KX7rJxs9jI3Nb89utmQSLWEbSAgHgC9-gk332EqpS-tNb5zxmIsX7Kw9Z7oHPpsEncEeQYJ3oqOgbu7btaXlGj2ueVVR4P7vrq4z_8-YXPlAshX9dsY8i67iC-a0Z1g66-5wqmCgjTfaCMIznHIUpA4jW2Sg4mjZquXPUnDfwZEqh4v_DTqXJIWhp4996lmC_Dk-KLnKyL8y4JriV&csuir=1

**Comment by fdoffo** [comment]
是的，这个链接未跳到 search labs 界面。

**Comment by F9y4ng** [comment]
OK，你可以等待6月的更新，或自己手动修改一下代码（如果你知道如何操作的话，注意TM下修改代码会失去自动更新需要手动重新设置自动更新）

在源代码中找到以下位置：
https://github.com/F9y4ng/GreasyFork-Scripts/blob/62c71f4b3a696c4dc3f4d56b55f2215f2f0c4aa5/Google%20%26%20Baidu%20Switcher.user.js#L1787

将其修改为:
```js
(listCurrentSite.SiteTypeID === newSiteType.GOOGLE && (/^(lcl|flm|fin)$/.test(def.const.vim) || getUrlParam("csui"))) ||
```
