### ISSUE TITLE
最新版 Firefox Developer Edition 下所有字体渲染都不正常

### ISSUE THREAD

**Issue by shanoaice** [F9y4ng/GreasyFork-Scripts#224]
在最新版 Firefox Developer Edition 中（内核版本为115.0b2，与 Firefox Beta 相同），开启字体渲染脚本后所有字体都变得特别粗，似乎是字体描边多了一层，将字体描边设置为0可以暂时规避问题。在内核版本更旧的Waterfox中一切正常。

Firefox Developer Edition 内核版本：115.0b2
Waterfox 内核版本：G5.1.8

Firefox Developer Edition 截图（以下截图页面均为 Font Rendering 脚本的 GreasyFork 页面）：
![图片](https://github.com/F9y4ng/GreasyFork-Scripts/assets/25174488/513e253a-0259-4a22-b4c0-565192026fa5)
调试模式日志：
[console-export-2023-6-7_18-44-49.txt](https://github.com/F9y4ng/GreasyFork-Scripts/files/11676115/console-export-2023-6-7_18-44-49.txt)

Waterfox 截图：

![图片](https://github.com/F9y4ng/GreasyFork-Scripts/assets/25174488/4fbc7bb6-db31-4f4b-83cf-6494d7d7541e)
调试模式日志：
[console-export-2023-6-7_18-53-16.txt](https://github.com/F9y4ng/GreasyFork-Scripts/files/11676158/console-export-2023-6-7_18-53-16.txt)

**Comment by F9y4ng** [comment]
浓眉大眼的Firefox也开始学blink内核的chrome一样了？😂

Beta版本的内核临时性的改动很多，所以一般情况下不会去刻意兼容测试版本的浏览器或脚本管理器，因为谁也说不准下个测试版本更新后是不是又改回去了。我测试了前几天刚发布的V114.0正式版，没有复现你提到的问题。

我在脚本说明中也提到过，针对测试版本的兼容会很谨慎，建议使用正式版本。
![issues](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/4e5c413a-43d1-4e1a-a197-7798a97ab807)

**Comment by shanoaice** [comment]
明白了，我过几天等下一个beta更新推过来再看看
