### ISSUE TITLE
[发现错误]中文引号覆盖问题 

### ISSUE THREAD

**Issue by Rortenfeat** [F9y4ng/GreasyFork-Scripts#226]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
1. 引号字体不可控，小字号下的字体 Hinting 看起来很不和谐
2. 英文中的引号也都被换成中文引号了

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/63738576/bab0ce88-6178-4ec0-a17d-bd0dde22ea76)![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/63738576/96da442e-4136-4163-825a-9ab382027fa2)
设置的字体：Segoe UI，苹方

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
这两天才注意到的，貌似是新功能？希望可以选择关闭。

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Win10
- 浏览器 [_如:Chrome,Safari_]：Edge
- 浏览器版本 [_如:108.0.5359.128_]：114.0.1823.43
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：4.18.1
- 所用的脚本名称 [_如:FontRendering_]：FontRendering
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.06.10.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？否

- 是否同时运行了其他第三方用户脚本？否

**Comment by F9y4ng** [comment]
这是“中文双引号”，及‘单引号’的测试。

It's a test for "English quotes".

It's a test using “Chinese quotes（‘中文引号’）” in English.

我给出了三组引号的使用示例，分别是：

1. 全角中文引号；
2. 半角英文引号；
3. 在英文语句中使用全角中文引号的示例；
 
你应该能明白为什么会出现你遇到的问题了吧？

**Comment by Rortenfeat** [comment]
谢谢回复。
<br/><br/>

关于您引号方面的解释，我是了解的。但是这部分牵扯到的问题可能更为复杂。

1. 「“”/‘’」和「"/'」的区别并不是全角和半角的区别，在 Unicode 编码上它们都本意用于半角符号。
2. 准确地讲，前者叫「弯引号」，后者叫「直引号」。其中「弯引号」既用于中文排版，也用于英文排版。而「直引号」是英文打字机时代的产物，为了简便引号的输入（所以又被称为「傻瓜引号」），正式排版中不应出现。
3. 所以英文引号和中文引号是共用同一个码位的，视觉上全角和半角的分别完全取决于字体偏向哪一种。

> 参考
> https://www.zhihu.com/question/31424658
> https://www.zhihu.com/question/23008549

所以中英文引号的问题不仅是输入的问题，还是字体和编码的问题。我的想法是脚本不一定要参与到这场「混战」中去，如果没办法完美解决的话，还是提供一个选择为好。
<br/>

另外关于问题1，前端方面我真的不懂，但是只要开启脚本，不管设置的字体是什么，弯引号都会被渲染为宋体。这应该不是您说的热替换的问题吧？所以这是预期状况吗？
<br/><br/>

感谢您对开源社区的奉献。

**Comment by Rortenfeat** [comment]
感谢解惑🙏

**Comment by F9y4ng** [comment]
更新至v2023.06.17.1

**Comment by Zxis233** [comment]
在GitHub中这个问题似乎又出现了：
![image](https://github.com/user-attachments/assets/5a8654da-b3c9-4f06-9120-e08219eb7f8a)
请问有解决方法吗？

**Comment by F9y4ng** [comment]
> 在GitHub中这个问题似乎又出现了：
> ![image](https://github.com/user-attachments/assets/5a8654da-b3c9-4f06-9120-e08219eb7f8a)
> 请问有解决方法吗？
> 设置字体：MiSans

换其他字体。
