### ISSUE TITLE
安装的字体不显示

### ISSUE THREAD

**Issue by woboo110** [F9y4ng/GreasyFork-Scripts#227]
安装了苹方字体，但是字体选择那里不显示，重建缓存也没用

**Comment by F9y4ng** [comment]
你从哪里下载的苹方字体？是从 #46 么？ 安装完字体后有重启浏览器么？ #64 中注意事项的情况你要留意。 

多到[Discussions](https://github.com/F9y4ng/GreasyFork-Scripts/discussions)中找找很多问题都有答案。
