### ISSUE TITLE
[发现错误] Material Design页面侧边栏的图标变成文字了

### ISSUE THREAD

**Issue by nothingshiru** [F9y4ng/GreasyFork-Scripts#228]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. 打开[Material Design](https://m3.material.io/)页面

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![screenshot](https://github.com/F9y4ng/GreasyFork-Scripts/assets/79258245/c083e0ec-3c46-48a3-b5bf-020b8cca08e1)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
图标正常显示

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统：Windows 11
- 浏览器：Edge
- 浏览器版本：114.0.1823.43
- 脚本管理器：Tampermonkey
- 脚本管理器版本：4.19.0
- 所用的脚本名称：FontRendering
- 所用的脚本版本：2023.06.10.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

否

- 是否同时运行了其他第三方用户脚本？

否

**Comment by F9y4ng** [comment]
在**需要渲染的网页元素**中，追加`:not(.google-symbols)`，保存为独享数据。
