### ISSUE TITLE
[发现错误] 与MarkDownload - Markdown Web Clipper扩展产生冲突

### ISSUE THREAD

**Issue by PaulHerrero** [F9y4ng/GreasyFork-Scripts#23]
**描述错误信息**
当在少数派网站里启用该脚本时，会导致 [Markdownload](https://chrome.google.com/webstore/detail/markdownload-markdown-web/pcmpcfapbekmbjjkdalcgopdkipoggdi) 扩展无法剪藏文章正文

**错误再现**
重现行为的步骤：
1. 启用字体渲染脚本
2. 打开 https://sspai.com/post/68183
3. 点击markdownload扩展剪藏网页

**预期结果**
出现错误，无法识别到文章正文

**屏幕截图**
![Snipaste_2021-09-16_14-06-10](https://user-images.githubusercontent.com/56058332/133559032-faec312e-d05d-4ef3-aa47-eca557976365.png)

**客户端信息（请填写以下信息）：**
- 操作系统：Win10
- 浏览器：edge
- 版本：93.0.961.47
- 脚本扩展：TamperMonkey 
- 脚本扩展版本：4.13.6138 

**附加信息**
在此处添加有关此问题的任何附加信息。

**Comment by F9y4ng** [comment]
您好，导致该问题的代码已被确认，下次版本更新时将会修正这个bug。

感谢反馈。

：）
