### ISSUE TITLE
English Version when??[新增功能] 

### ISSUE THREAD

**Issue by lakshits11** [F9y4ng/GreasyFork-Scripts#230]
## 1. 准备工作（确认预先完成的操作）

- [ ] 我确认使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）

Your script is very very good, please provide a english version. It will help many more people in the world like me.
Thank You

**Comment by F9y4ng** [comment]
Font rendering userscript are more used to enhance the effect of Chinese font rendering, so the user group is mainly Chinese.

Search engine assistant userscript will use English interface by default in browsers with non-Chinese languages.

**Comment by lakshits11** [comment]
But since on windows, font rendering is not much great, I used your script, and it was nice. I just thought two things: 
1. There should be english version.
2. We should have option to change default Microsoft font and use some else font of our choice.

I am hoping to get your response on this matter soon.

**Comment by F9y4ng** [comment]
I'll consider this new feature about `Font Rendering` userscript multilingual if I have more free time.

**Comment by lakshits11** [comment]
Thank You for considering it!
