### ISSUE TITLE
[Report] Brave Browser's Anti-fingerprinting Breaks This Script / Brave 浏览器的抗指纹功能会使脚本无法正常工作

### ISSUE THREAD

**Issue by shanoaice** [F9y4ng/GreasyFork-Scripts#231]
这应该不算是个 bug report……毕竟这锅应该是 Brave 的，我估计他们在增加抗指纹识别追踪的功能时改动了一些关键的 Canvas API。发这个 Issue 是觉得这应该被加入到 README 帮助文件里，提醒下一个使用 Brave 浏览器且碰到这种情况的人关闭 Brave 的”阻止指纹识别“功能

**Comment by F9y4ng** [comment]
#109 ISSUE已提出过这类问题，善用搜索可快速定位到答案。
