### ISSUE TITLE
[发现错误] 字体渲染脚本 github在代码选中字体的时候显示有问题

### ISSUE THREAD

**Issue by freedomspiritJohn** [F9y4ng/GreasyFork-Scripts#233]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去XX网址 "..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _遇到错误或问题 "..."_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/129288685/915e3b57-7153-498a-9fe4-8ee0ebdc2c0e)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
关了这个脚本之后就显示正常

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：win10
- 浏览器 [_如:Chrome,Safari_]：cent浏览器
- 浏览器版本 [_如:108.0.5359.128_]：版本 5.0.1002.354（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)
- 脚本管理器 [_如:Tampermonkey_]：暴力猴 2.14
- 脚本管理器版本 [_如:4.18.1_]：2.14.0
- 所用的脚本名称 [_如:FontRendering_]：字体渲染
- 所用的脚本版本 [_如:2020.11.24.1_]：2323.6.17.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
这是新版UI的问题，我个人无法理解github为什么要用一个问题多多的CM6测试版本编辑器。

## 解决办法
双击**排除渲染的HTML元素**右边的🔔，打开自定义等宽字体开关后保存后即可。此外你可以使用脚本默认的自定义等宽字体，也可以使用自己喜欢的等宽字体。

另外需要注意的是，如果使用github代码编辑器，请勿打开字体缩放功能。这是CM6官方一直无法解决的问题。
