### ISSUE TITLE
[发现错误] 使用字体渲染脚本后，stylus的“修改复制字体颜色”脚本不生效

### ISSUE THREAD

**Issue by freedomspiritJohn** [F9y4ng/GreasyFork-Scripts#234]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去XX网址 "..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _遇到错误或问题 "..."_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/129288685/76f44064-6409-48c9-b6cc-bc58c84c7287)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
关闭字体渲染脚本后，stylus的脚本运行正常。打开字体渲染脚本后复制的字体颜色和背景没有改变

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：
- 浏览器 [_如:Chrome,Safari_]：
- 浏览器版本 [_如:108.0.5359.128_]：
- 脚本管理器 [_如:Tampermonkey_]：
- 脚本管理器版本 [_如:4.18.1_]：
- 所用的脚本名称 [_如:FontRendering_]：
- 所用的脚本版本 [_如:2020.11.24.1_]：
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
脚本默认设定在开启字体描边设置后会自动重写文本选取样式，如必须使用第三方样式请关闭字体描边功能，或停用本脚本。
