### ISSUE TITLE
[发现错误] 最近更新过后导致selection search 插件失效了

### ISSUE THREAD

**Issue by freedomspiritJohn** [F9y4ng/GreasyFork-Scripts#235]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
前几天还能用，这几天好像不行了，就是选中文字后，然后再点击一下选中的文字就会出现搜索列表。但是现在不知道什么原因失效了

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去XX网址 "..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _遇到错误或问题 "..."_

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：
- 浏览器 [_如:Chrome,Safari_]：
- 浏览器版本 [_如:108.0.5359.128_]：
- 脚本管理器 [_如:Tampermonkey_]：
- 脚本管理器版本 [_如:4.18.1_]：
- 所用的脚本名称 [_如:FontRendering_]：
- 所用的脚本版本 [_如:2020.11.24.1_]：
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
不尝试兼容其他扩展或脚本，请在该扩展或脚本提出Issues，或停用本脚本。
