### ISSUE TITLE
[新增功能] 需要斜杠零的开关选项

### ISSUE THREAD

**Issue by rolandzzj** [F9y4ng/GreasyFork-Scripts#237]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
使用更纱黑体SC之后发现所有的零都强制变成了斜杠零，简单定位了一下是因为字体平滑功能里的默认`font-feature-settings`是`zero`，改成`normal`的话即可恢复正常，斜杠0在普通网页中看起来很不习惯，能否在下次更新里提供一个开关或者自定义的选项？

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/38018291/2e4cc47f-32b9-4a80-a86d-abc332b22a95)

**Comment by F9y4ng** [comment]
我记得有重置过`font-feature-setting`的默认值为`normal`，但考虑到提升阿拉伯数字0的辨识率，所以添加了`zero`的属性值。

使用习惯问题吧，如果还有更多的用户希望恢复`font-feature-setting`的初始值，我会在下个月更新中修改它。

**Comment by Leonoves** [comment]
请问如何取消按alt+T键和自动跳转到GitHub界面？

**Comment by F9y4ng** [comment]
> 请问如何取消按alt+T键和自动跳转到GitHub界面？

高级核心功能设置，关闭**键盘快捷键功能**。

**Comment by Leonoves** [comment]
好的，谢谢回答。但是我设置了alt+t的快捷键，关闭之后也无法使用了吧？

从 Windows 版邮件发送

发件人: F9y4ng
发送时间: 2023年7月26日 14:32
收件人: F9y4ng/GreasyFork-Scripts
抄送: Hoshino; Comment
主题: Re: [F9y4ng/GreasyFork-Scripts] [新增功能] 需要斜杠零的开关选项 (Issue #237)

请问如何取消按alt+T键和自动跳转到GitHub界面？
高级核心功能设置，关闭键盘快捷键功能。

**Comment by F9y4ng** [comment]
> 好的，谢谢回答。但是我设置了alt+t的快捷键，关闭之后也无法使用了吧？
> 

关闭脚本快捷键功能仅对本脚本自身快捷键设置生效，不会影响其他脚本、扩展、软件的设置。
