### ISSUE TITLE
[发现错误] 网页内嵌PDF重影问题

### ISSUE THREAD

**Issue by CescMessi** [F9y4ng/GreasyFork-Scripts#239]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
之前 #145 提到飞书云文档中的pdf存在重影问题，但是似乎后面没有处理。我发现在其他一些存在网页内嵌PDF的网站上也同样存在该问题，看上去这个重影是在原来字体的下面加了一个黑体，一些非黑体的pdf显示重影就比较明显，和黑体接近大小的重影就不明显。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
复现该问题的网址
1. [复旦官网1](https://ssdpp.fudan.edu.cn/fe/98/c20786a458392/page.htm) [复旦官网2](https://faet.fudan.edu.cn/09/5c/c23815a461148/page.htm) ，1的重影比较轻，2的比较严重，看上去和字体有关。
2. [小雅alist](http://alist.xiaoya.pro/%E5%AE%89%E8%A3%85%EF%BC%8C%E9%85%8D%E7%BD%AE%EF%BC%8C%E4%BF%AE%E5%A4%8D%20xiaoya%20docker%20%E6%8C%87%E5%8D%97/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E5%92%8C%E7%BB%B4%E6%8A%A4xiaoya%20docker.pdf)，第一页的重影比较轻，放大了才比较明显，第二页的表格处可以明显看到英文的重影。
3. [Seafile](https://www.seafile.com/home/)，这个可以点击试用上传一个PDF观察效果。
4. [researchgate](https://www.researchgate.net/publication/333262625_Spatio-Temporal_Deep_Learning_An_Application_to_Land_Cover_Classification)，这个网站比较特殊，在未登录的情况下，PDF中的字体会被正常替换成黑体，没有重影问题，但是登录了之后就会出现和上面两个网站同样的问题。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
复旦官网1开启脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/d4d35647-2aa4-4f97-9edd-bf43a0922c0d)
复旦官网1关闭脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/52913d76-445f-42be-83f9-ea6a84f41f10)
复旦官网2开启脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/6fa76278-35e7-47c5-a697-d55f10710673)
复旦官网2关闭脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/948a9cee-e4d1-469d-9b20-521db5ab28bc)
小雅alist开启脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/38fb4f9f-50c8-41b4-9c33-26886945bc36)
小雅alist关闭脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/e83e9fdc-2636-4d5c-8534-8ebf378b273d)
seafile开启脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/739861c1-2a85-49e4-aacd-1bc413bf1b04)
seafile关闭脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/38a1588a-8b96-4f41-b54f-360c694b8a9a)
researchgate登录开启脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/4d60acec-87b0-48af-b758-65c5c841520b)
researchgate登录关闭脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/ee391bcd-0331-427b-95e5-8c6e555d972f)
researchgate未登录开启脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/df7e3498-6f48-4360-9cfe-b5f83c2823b6)
researchgate未登录关闭脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/b272a930-3f2f-4961-a5d4-b5c2e8466d2c)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
PDF文字不存在重影

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Win10
- 浏览器 [_如:Chrome,Safari_]：Chrome
- 浏览器版本 [_如:108.0.5359.128_]：114.0.5735.199
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：4.19.0
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.07.08.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
#145 没有账户登录去看到实际问题，神仙也救不了。

## 注意事项
很多反馈的问题所在的站点都需要账户登录才能访问，没有提供测试账户就意味着无法看到实际情况，于是就没有解决办法。

## 你提到的问题
1. 复旦大学相关：在**排除渲染的HTML标签**中追加`,.textLayer *`，保存为站点数据独享。
2. 小雅alist（iframe框架页）：需访问[https://alist-org.github.io/pdf.js/web/viewer.html?file=...](https://alist-org.github.io/pdf.js/web/viewer.html?file=https%3A%2F%2Ftpjf3-my.sharepoint.com%2Fpersonal%2Fxiaoya_tpjf3_onmicrosoft_com%2F_layouts%2F15%2Fdownload.aspx%3FUniqueId%3Df9b3c455-af27-40c1-9115-9d86ee6f7a46%26Translate%3Dfalse%26tempauth%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdHBqZjMtbXkuc2hhcmVwb2ludC5jb21ANTEyMmJlMWMtOTJmOS00ZDRmLWI5ZjItYTI4OWY3NzAxODBhIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTY5MDA4MzY4NSIsImV4cCI6IjE2OTAwODcyODUiLCJlbmRwb2ludHVybCI6IllPQVBrSkpZbXFDc2M2RmxZTXlJekM0N0VPQUZqS1NDMnZwTHFHY0dHbDQ9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNTciLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6InFrMEdkeHZhVkUyODVUMFBLYkVFMHc9PSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJaV1E1WTJKbVlqTXRZV0kxWkMwMFpqUTJMV0UxWVRVdE1EUTBNbVpsTjJaaU4yTTEiLCJhcHBfZGlzcGxheW5hbWUiOiJBbGlzdCIsImdpdmVuX25hbWUiOiJ4aWFveWEiLCJmYW1pbHlfbmFtZSI6ImxpdSIsInNpZ25pbl9zdGF0ZSI6IltcImttc2lcIl0iLCJhcHBpZCI6IjBhMjk5MWEzLTE2NzQtNDMzNC04NTYxLTY3MWNjNzM0OTk2MCIsInRpZCI6IjUxMjJiZTFjLTkyZjktNGQ0Zi1iOWYyLWEyODlmNzcwMTgwYSIsInVwbiI6InhpYW95YUB0cGpmMy5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDI0NDREQUY3NSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAyNDQ0ZGFmNzVAbGl2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy53cml0ZSIsInR0IjoiMiIsImlwYWRkciI6IjQwLjEyNi40LjQwIn0.hF1pgSsvZRHxChYxKC6-oacpvGTYbOw6HV8DBt_fczo%26ApiVersion%3D2.0)， 页面加载完成后，在**排除渲染的HTML标签**中追加`,.textLayer *`，保存为站点数据独享。
3. Seafile，提供测试账户。
4. researchgate，提供测试账户。

**Comment by CescMessi** [comment]
> #145 没有账户登录去看到实际问题，神仙也救不了。
> 
> ## 注意事项
> 很多反馈的问题所在的站点都需要账户登录才能访问，没有提供测试账户就意味着无法看到实际情况，于是就没有解决办法。
> 
> ## 你提到的问题
> 1. 复旦大学相关：在**排除渲染的HTML标签**中追加`,.textLayer *`，保存为站点数据独享。
> 2. 小雅alist（iframe框架页）：需访问[https://alist-org.github.io/pdf.js/web/viewer.html?file=...](https://alist-org.github.io/pdf.js/web/viewer.html?file=https%3A%2F%2Ftpjf3-my.sharepoint.com%2Fpersonal%2Fxiaoya_tpjf3_onmicrosoft_com%2F_layouts%2F15%2Fdownload.aspx%3FUniqueId%3Df9b3c455-af27-40c1-9115-9d86ee6f7a46%26Translate%3Dfalse%26tempauth%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvdHBqZjMtbXkuc2hhcmVwb2ludC5jb21ANTEyMmJlMWMtOTJmOS00ZDRmLWI5ZjItYTI4OWY3NzAxODBhIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTY5MDA4MzY4NSIsImV4cCI6IjE2OTAwODcyODUiLCJlbmRwb2ludHVybCI6IllPQVBrSkpZbXFDc2M2RmxZTXlJekM0N0VPQUZqS1NDMnZwTHFHY0dHbDQ9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNTciLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6InFrMEdkeHZhVkUyODVUMFBLYkVFMHc9PSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJaV1E1WTJKbVlqTXRZV0kxWkMwMFpqUTJMV0UxWVRVdE1EUTBNbVpsTjJaaU4yTTEiLCJhcHBfZGlzcGxheW5hbWUiOiJBbGlzdCIsImdpdmVuX25hbWUiOiJ4aWFveWEiLCJmYW1pbHlfbmFtZSI6ImxpdSIsInNpZ25pbl9zdGF0ZSI6IltcImttc2lcIl0iLCJhcHBpZCI6IjBhMjk5MWEzLTE2NzQtNDMzNC04NTYxLTY3MWNjNzM0OTk2MCIsInRpZCI6IjUxMjJiZTFjLTkyZjktNGQ0Zi1iOWYyLWEyODlmNzcwMTgwYSIsInVwbiI6InhpYW95YUB0cGpmMy5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDI0NDREQUY3NSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAyNDQ0ZGFmNzVAbGl2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy53cml0ZSIsInR0IjoiMiIsImlwYWRkciI6IjQwLjEyNi40LjQwIn0.hF1pgSsvZRHxChYxKC6-oacpvGTYbOw6HV8DBt_fczo%26ApiVersion%3D2.0)， 页面加载完成后，在**排除渲染的HTML标签**中追加`,.textLayer *`，保存为站点数据独享。
> 3. Seafile，提供测试账户。
> 4. researchgate，提供测试账户。

感谢，seafile使用`,.textLayer *`同样可以修复，researchgate需要使用`,.react-pdf__Page__textContent *`。目前还有个小问题是，选中文字时还是会出现重影的文字：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15847281/64f5296d-d254-45f8-8e04-02449a9c3593)

**Comment by F9y4ng** [comment]
处理选取文字几乎与处理Github代码选取一样非常棘手和麻烦，虽然可以勉强得到预期效果，但繁琐极度的繁琐。为了替换原站点使用的内联样式，必须使用自定义等宽字体强制覆盖，但不建议这样做。

**Comment by weavers1f** [comment]
我刚在公司的内网OA上也有同样的PDF渲染问题，来找找看发现上面老大的答案中，这个“小雅alist（iframe框架页）”的感觉就跟我这个情况一样，然后试了下在排除渲染的HTML标签中追加,.textLayer *，保存为站点数据独享，解决问题了
![VeryCapture_20240809143941](https://github.com/user-attachments/assets/47599bce-f1f8-4354-bbfa-a44f5b79b052)

**Comment by weavers1f** [comment]
添加后的渲染效果
![VeryCapture_20240809144650](https://github.com/user-attachments/assets/3d6b8bfe-1c3e-41fa-b45a-8b94b04a9d84)
