### ISSUE TITLE
safari浏览器无法添加自定义字体像霞鹜文楷

### ISSUE THREAD

**Issue by gdqsfuture** [F9y4ng/GreasyFork-Scripts#240]

**Comment by gdqsfuture** [comment]
大佬，您的插件非常好用，但safari浏览器里面就是无法添加字体，我已经按指南里面的代码把霞鹜文楷屏幕阅读版加进去，还是没法找到，但chrome浏览器就一切正常，您能否指教一下该怎么操作，谢谢

**Comment by F9y4ng** [comment]
Duplicate of #170
