### ISSUE TITLE
[发现错误] 会导致YouTube的剧场模式显示不完整，关闭脚本后显示正常

### ISSUE THREAD

**Issue by freedomspiritJohn** [F9y4ng/GreasyFork-Scripts#241]
## 1. 准备工作（确认预先完成的操作）

- [ ] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去XX网址 "..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _遇到错误或问题 "..."_

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：
- 浏览器 [_如:Chrome,Safari_]：
- 浏览器版本 [_如:108.0.5359.128_]：
- 脚本管理器 [_如:Tampermonkey_]：
- 脚本管理器版本 [_如:4.18.1_]：
- 所用的脚本名称 [_如:FontRendering_]：
- 所用的脚本版本 [_如:2020.11.24.1_]：
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
关闭实验性功能：**字体比例缩放**。

**Comment by freedomspiritJohn** [comment]
> 

但是我并没有开启字体缩放设置
![QQ截图20230727103516](https://github.com/F9y4ng/GreasyFork-Scripts/assets/129288685/963f4296-9b75-43ee-a9c5-72e7362370e7)

**Comment by freedomspiritJohn** [comment]
> 关闭实验性功能：**字体比例缩放**。

我的问题，别的YouTube脚本在作用
