### ISSUE TITLE
[新增功能] 希望可以添加设置字间距和行间距的功能

### ISSUE THREAD

**Issue by freedomspiritJohn** [F9y4ng/GreasyFork-Scripts#243]
因为不同的字间距和行间距也在一定程度下影响到美观和阅读观感。希望作者考虑一下

**Comment by F9y4ng** [comment]
字间距与行间距，和之前另外一位用户提出的字体颜色需求存在同样的问题：

1. 如何确定在整个页面中，哪些文字需要调整，哪些又不需要，这将是个极其繁琐的设置过程，一般用户根本无法完成。

2. 字体间距（字高、字宽）与行间距在特定的样式下（原站点样式），会造成各种不可预测的问题。如 #216 遇到的问题。

综上，该功能不会考虑添加。
