### ISSUE TITLE
[新增功能] 能不能针对内网IP+端口这种指定排除

### ISSUE THREAD

**Issue by LY5216** [F9y4ng/GreasyFork-Scripts#244]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
因为公司大部分网站是内网IP+端口模式(同一个IP下不同的端口，网页不一样)，如果进行排除 目前看排除的方式仅能使用域名或IP方式 而不能针对同一个IP下不同端口的网站进行排除 而是对整个IP下的所有网站进行排除，希望能针对IP+端口方式

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/49475455/1fc06850-fc24-4a6b-be97-aaa28fa18de5)

**Comment by F9y4ng** [comment]
在生产环境下几乎不存在多端口使用的情况，所以根本没考虑过这样的需求。

如果有更多用户有此需求，下个月更新中会添加该功能。

**Comment by F9y4ng** [comment]
更新至v2023.09.02.1
