### ISSUE TITLE
在Safari上的问题

### ISSUE THREAD

**Issue by easonnnone** [F9y4ng/GreasyFork-Scripts#245]
大佬好
 
在Safari上，使用时有个小问题，就是在描边选项旁边没有“粗体修正这个选项“，然而在Chrome上是有这个选项的（如下图所示）

<img width="320" alt="Snipaste_2023-08-09_10-28-26" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/16a641a4-4d51-49a0-a374-ae91891f1f9e">

<img width="315" alt="Snipaste_2023-08-09_10-31-28" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/446bc90b-a6d3-4556-929d-f9f2410347be">

**Comment by F9y4ng** [comment]
因为safari和firefox上根本不存在文字粗体描边样式渲染错误的问题，所以没有才是正常的。
