### ISSUE TITLE
[新增功能] 

### ISSUE THREAD

**Issue by Meonthb** [F9y4ng/GreasyFork-Scripts#246]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）

跳转Google引擎时会强制将语言设置为中文，即使手动改回英文下次跳转也会改回中文，这样会导致Google的一些新特性被屏蔽，如continuously scolling，希望能取消跳转Google搜索时的强制中文设定。

具体来说希望去除"hl=zh-CN"字段，或者至少可以增加一个去掉的选项。

**Comment by F9y4ng** [comment]
`hl=zh-CN`的URL参数是指定搜索结果页面显示文字的语言设置。

你说的是Google自己的不间断滚屏的功能吧，这功能只与访问国家的IP有关，与访问搜索界面设置的语言无关。要使用Google的各项试验性功能，需要将你的代理IP改为美国境内IP（需要全局代理）。

下个月更新，我会将搜索结果页面的语言设置改为跟随浏览器默认语言，这样就不会覆盖你手动修改显示语言的cookie信息了。
