### ISSUE TITLE
[发现错误]  ecosia 存在适配问题

### ISSUE THREAD

**Issue by spphinslove** [F9y4ng/GreasyFork-Scripts#247]
![图片](https://github.com/F9y4ng/GreasyFork-Scripts/assets/11383988/df7ce059-c4cc-47c5-ba39-af91ddedf701)

**Comment by F9y4ng** [comment]
一切正常。你选中常用搜索引擎了么？

![PS_2023-08-20_21-08-38](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/4de8d580-58cc-4043-8c55-746ca86fa18c)
