### ISSUE TITLE
新版本emoji显示不正确

### ISSUE THREAD

**Issue by steveleeCN87** [F9y4ng/GreasyFork-Scripts#250]
新版本emoji显示不正确，全是黑白的那种，没有任何颜色，不论任何字体，但，关闭这个脚本后就正常显示了

**Comment by F9y4ng** [comment]
如果你使用centBrowser等浏览器且已关闭dw是会造成emoji的渲染问题，而且在脚本层面无解。

其他情况请按bug report填写相关信息。

**Comment by Luban-No7** [comment]
去装个扩展吧。[Emoji Swap](https://chrome.google.com/webstore/detail/emoji-swap/ggjmjkeaeojfdcbafefloifeaepeaeah)
