### ISSUE TITLE
使用Safari上的Stay扩展后，点击字体渲染设置后会报错。

### ISSUE THREAD

**Issue by easonnnone** [F9y4ng/GreasyFork-Scripts#254]
用可以用，但点击设置后就报错了（如下图）

<img width="428" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/b31b9d03-9ac1-43a1-9c13-8eced0876483">

**Comment by F9y4ng** [comment]
从你的截图上来看，应该是不支持@require方法，无法获取拾色器代码造成的。Stay连几个最基本的API都没处理好，没有计划兼容这个半成品。

Userscripts已做兼容处理，但没有脚本菜单的API接口。（这个你可以到userscripts去提issues，好像有人提过，但迟迟未增加这个功能）

我个人不是很理解手机上使用字体渲染是需求是怎么来的。

**Comment by easonnnone** [comment]
这是在Mac上

**Comment by F9y4ng** [comment]
> 这是在Mac上

Mac safari上推荐Userscripts，我本地有加入测试调试，基本使用问题不大，菜单可以使用键盘快捷键呼出。TM4.20.6186新版本还是存在挺多问题的，暂不推荐。

**Comment by easonnnone** [comment]
> Userscripts

Userscripts的快捷键是啥呢

**Comment by F9y4ng** [comment]
> Userscripts的快捷键是啥呢

终于被我抓住了，用了这么久的脚本，你这家伙不会连脚本介绍说明一眼都没看过吧？！先自罚三杯吧。

https://github.com/F9y4ng/GreasyFork-Scripts/wiki/%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%EF%BC%88%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC%EF%BC%89#user-content-hotkey

**Comment by easonnnone** [comment]
> > Userscripts的快捷键是啥呢
> 
> 终于被我抓住了，用了这么久的脚本，你这家伙不会连脚本介绍说明一眼都没看过吧？！先自罚三杯吧。
> 
> https://github.com/F9y4ng/GreasyFork-Scripts/wiki/%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%EF%BC%88%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC%EF%BC%89#user-content-hotkey

抱歉抱歉

**Comment by easonnnone** [comment]
> > Userscripts的快捷键是啥呢
> 
> 终于被我抓住了，用了这么久的脚本，你这家伙不会连脚本介绍说明一眼都没看过吧？！先自罚三杯吧。
> 
> https://github.com/F9y4ng/GreasyFork-Scripts/wiki/%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%EF%BC%88%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC%EF%BC%89#user-content-hotkey

Option+P 按了没反应，是在哪个页面下按呢

**Comment by F9y4ng** [comment]
随便哪个页面都可以，前提是你没有在**高级核心功能设置**里关闭键盘快捷键。

（按快捷键`Option+P`前，确保焦点在当前页面，用鼠标点一下当前页面上的空白，然后再按快捷键）

**Comment by easonnnone** [comment]
> 随便哪个页面都可以，前提是你没有在**高级核心功能设置**里关闭键盘快捷键。
> 
> （按快捷键`Option+P`前，确保焦点在当前页面，用鼠标点一下当前页面上的空白，然后再按快捷键）

还有个小问题想问一下，苹方-简，如何进行加粗呢

**Comment by F9y4ng** [comment]
增加描边

**Comment by easonnnone** [comment]
> 增加描边

非常感谢大佬的指点

**Comment by F9y4ng** [comment]
@easonnnone ，你的Stay是哪个版本的？脚本用的又是哪个版本的？如果不是最新的，全部升级到最新版本。

我本地在最新版的Stay v2.5.4上测试最新版的脚本 v2023.09.03.1是完全没有问题的。

**Comment by F9y4ng** [comment]
@easonnnone 我在本地Mac上安装了Stay2.5.4，测试了v2023.09.03.1，并没有发现任何问题。我不确定是否是Stay2.5.4修复了大部分之前存在的问题，你最好在你的本地测试一下最新版。

**Comment by easonnnone** [comment]
> @easonnnone 我在本地Mac上安装了Stay2.5.4，测试了v2023.09.03.1，并没有发现任何问题。我不确定是否是Stay2.5.4修复了大部分之前存在的问题，你最好在你的本地测试一下最新版。

<img width="426" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/fa241f00-d704-451a-b3e3-319aebb67ca5">

还是报错了，估计2.5.4还是有问题

**Comment by F9y4ng** [comment]
那你要检查一下你的本地网络能不能正常访问www.greasyfork.org，拾色器的代码是从greasyfork调取的。

**Comment by easonnnone** [comment]
> 那你要检查一下你的本地网络能不能正常访问www.greasyfork.org，拾色器的代码是从greasyfork调取的。

www.greasyfork.org可以访问没问题呀

<img width="1949" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/bbceaf01-2d8e-4bc2-89b4-bb9354a40da4">

**Comment by F9y4ng** [comment]
那就奇怪了，你跟我本地MAC唯一的差别就是safari版本，我的是17.0,你的是17.1。

脚本管理器都是stay2.5.4，我看了一下它最新的更新，Stay更换了新的脚本引擎，之前的API问题大部分都解决了，其他小问题并不影响正常使用。（或者你可以尝试把Stay彻底删除，再重新安装一下，从它的评论区来看，似乎存在扩展缓存的问题，导致一些脚本报错。）

你尝试访问[https://github.com/F9y4ng/GreasyFork-Scripts/issues/254?whoami=F9y4ng #254](https://github.com/F9y4ng/GreasyFork-Scripts/issues/254?whoami=F9y4ng)，然后将控制台的信息上传一下。

**Comment by easonnnone** [comment]
> 那就奇怪了，你跟我本地MAC唯一的差别就是safari版本，我的是17.0,你的是17.1。
> 
> 脚本管理器都是stay2.5.4，我看了一下它最新的更新，Stay更换了新的脚本引擎，之前的API问题大部分都解决了，其他小问题并不影响正常使用。（或者你可以尝试把Stay彻底删除，再重新安装一下，从它的评论区来看，似乎存在扩展缓存的问题，导致一些脚本报错。）
> 
> 你尝试访问[https://github.com/F9y4ng/GreasyFork-Scripts/issues/254?whoami=F9y4ng #254](https://github.com/F9y4ng/GreasyFork-Scripts/issues/254?whoami=F9y4ng)，然后将控制台的信息上传一下。

<img width="1949" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/8fafea36-0e72-449f-adbf-74a0993fd1ea">

**Comment by easonnnone** [comment]
> 那就奇怪了，你跟我本地MAC唯一的差别就是safari版本，我的是17.0,你的是17.1。
> 
> 脚本管理器都是stay2.5.4，我看了一下它最新的更新，Stay更换了新的脚本引擎，之前的API问题大部分都解决了，其他小问题并不影响正常使用。（或者你可以尝试把Stay彻底删除，再重新安装一下，从它的评论区来看，似乎存在扩展缓存的问题，导致一些脚本报错。）
> 
> 你尝试访问[https://github.com/F9y4ng/GreasyFork-Scripts/issues/254?whoami=F9y4ng #254](https://github.com/F9y4ng/GreasyFork-Scripts/issues/254?whoami=F9y4ng)，然后将控制台的信息上传一下。

大佬，我完全卸载了Stay，再重装就可以用啦，谢谢大佬啦，再次感谢大佬的辛勤劳动！
