### ISSUE TITLE
开启描边后，字体边缘会有毛刺

### ISSUE THREAD

**Issue by easonnnone** [F9y4ng/GreasyFork-Scripts#255]
开启描边的字体
<img width="899" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/5e913533-85a5-4902-9860-d44c7b981220">

未开启描边的字体
<img width="836" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/56ea8523-03e7-4c73-a9a1-589ee7497826">

**Comment by F9y4ng** [comment]
用字体阴影覆盖毛刺，尺寸自己慢慢选，颜色一定要加透明度。

自己把数值调整到适合你的口味为止，你的审美观只有你自己能把握，谁也帮不了你。
