### ISSUE TITLE
开启脚本后，Google地图加载不完整。

### ISSUE THREAD

**Issue by Luban-No7** [F9y4ng/GreasyFork-Scripts#256]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
Google地图加载不完整，图层切换加载不出来，地图的右键菜单也无法加载，变成了普通网页的右键菜单，键入关键字搜索地图无法更新至目的地。

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去"[Google地图](https://www.google.com/maps)"_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![Snipaste_2023-09-08_02-39-58](https://github.com/F9y4ng/GreasyFork-Scripts/assets/130589387/d9eb81b8-56ec-4578-9e48-dfd7e1af8cc8)

![Snipaste_2023-09-08_02-44-02](https://github.com/F9y4ng/GreasyFork-Scripts/assets/130589387/14208ce9-02b5-4659-ac7b-107c2ec25747)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
正常加载网页。

**Comment by F9y4ng** [comment]
不能复现问题，请检查你本地的脚本冲突或网络原因。

![PS_2023-09-08_12-38-46](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/49974300-6fcf-4c78-b914-0e1ac1795d10)

**Comment by Luban-No7** [comment]
刚又试了下，chrome和EDGE没有问题。猫眼和百分浏览器有问题，开不开DW都一样。
同时EDGE，猫眼和百分浏览器有不同程度的网络错误。chrome没有。

这个怎么解决啊？
![Snipaste_2023-09-08_16-36-45](https://github.com/F9y4ng/GreasyFork-Scripts/assets/130589387/f635c91f-8dd6-4d6c-bcf8-2d316d791fa0)

**Comment by F9y4ng** [comment]
这种个人作者fork魔改的浏览器肯定会有各种各样的小问题，甚至有些问题是作者都无法解决的。既然选择了这么小众的浏览器，肯定是它有别的主流浏览器无可替代的东西，这时候就看你是选择吃沙拉面包片还是选择吃炒菜大米饭了，大致就是这个道理。
