### ISSUE TITLE
[搜索引擎跳转助手][DuckDuckGo] 按鈕風格

### ISSUE THREAD

**Issue by AkazaRenn** [F9y4ng/GreasyFork-Scripts#258]
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/8340896/ca8a7199-3002-4c0a-8d05-5324b24c5426)
目前的按鈕風格和網頁本身不是很一致，希望可以調整一下。

**Comment by F9y4ng** [comment]
未见异常。
![PS_2023-09-09_12-57-27](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/288ba249-88ef-4b4b-9019-1844a525b4ab)
