### ISSUE TITLE
[优雅的搜索引擎跳转助手] 百度搜索会导致整个浏览器变得很卡

### ISSUE THREAD

**Issue by pheotry** [F9y4ng/GreasyFork-Scripts#259]
使用百度搜索的话，会发现网页掉帧严重，CPU占用变高，此时如果点击浏览器界面元素会很卡（比如标签页，），很久才会动。
关闭百度搜索页面马上恢复。

bing和Google全部正常

环境：
暴力猴  v2.15.0
Edge 116.0.1938.76
Win11 Pro 22621.2215

复现：
关闭除暴力猴外的所有扩展
关闭百度页面生效的其他脚本

**Comment by F9y4ng** [comment]
我本地不能复现你遇到的情况。

你安装的是哪个版本的脚本？
是新安装还是从旧版本升级？
是否排除过与其他脚本的冲突？

**Comment by pheotry** [comment]
> 我本地不能复现你遇到的情况。
> 
> 你安装的是哪个版本的脚本？ 是新安装还是从旧版本升级？ 是否排除过与其他脚本的冲突？


脚本版本是这个 2023.09.11.1。
刚试着删除脚本重装还是一样卡
其他脚本我全关掉了也不行，百度页面还是会卡一会儿。不开这个脚本，百度就流畅了。

**Comment by F9y4ng** [comment]
如果你是新安装的，可以试试ViolentMonkey的BETA版本v2.15.3（VM近几个版本的更新在缓存处理上总有些小问题），或TamperMonkey4.19.0，看看是否还会有这个问题。

如果你是从低版本升级到最新版的，之前没问题，现在也不应该有问题。因为涉及到baidu的功能代码这次更新中没有任何改动。你需要检查你本地的环境是否发生了什么变化造成的这个问题。

**Comment by pheotry** [comment]
> 如果你是新安装的，可以试试ViolentMonkey的BETA版本v2.15.3（VM近几个版本的更新在缓存处理上总有些小问题），或TamperMonkey4.19.0，看看是否还会有这个问题。
> 
> 如果你是从低版本升级到最新版的，之前没问题，现在也不应该有问题。因为涉及到baidu的功能代码这次更新中没有任何改动。你需要检查你本地的环境是否发生了什么变化造成的这个问题。

v2.15.3也是卡，更低版本我就没试了，
我换了tampermonkey试了下，倒是不卡了。
应该是暴力猴的兼容问题吧。

平常基本用bing的，所以没发现，今天用了下百度发现的。

**Comment by F9y4ng** [comment]
在我本地，VM的正式版本和BETA版本都正常。你的这种情况大都是本地环境造成的脚本冲突（网页防火墙、去广告扩展/软件、其他脚本、或是其他扩展都有可能引起未知问题），而且在其他地方可能无法复现。

如果在意这些，可以考虑其他同类脚本使用。
