### ISSUE TITLE
[发现错误] sharepoint.com的Excel字体列表中字体名称出现乱码

### ISSUE THREAD

**Issue by SelfishSailfish** [F9y4ng/GreasyFork-Scripts#262]
## 1. 准备工作

- [x ] 我确认正在使用的是当前脚本的最新版本。
- [x ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息

Excel webapp 字体列表乱码。添加*.sharepoint.com到排除列表也无效果

## 3. 错误再现
在Excel webapp选择字体下拉菜单

## 4. 屏幕截图

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/38479206/26efe8b3-8b5b-4a34-89db-5130b6df21f9)

## 5. 预期结果
可以正确显示

## 6. 客户端信息
- 操作系统 [Win11]：
- 浏览器 [Edge]：
- 浏览器版本 [117.0.2045.36]：
- 脚本管理器 [TemperMonkey]：
- 脚本管理器版本 [4.19.0]：
- 所用的脚本名称 [Font Rendering (Customized)]：
- 所用的脚本版本 [2023.09.03.1]：
- 其他补充信息[字体为 更纱黑体 UI SC]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
ABP
1Password
合金H5播放器

- 是否同时运行了其他第三方用户脚本？
HTML5视频播放工具
框架网页全屏

## 8. 附加信息（在此处添加您认为有用的其他信息）

**Comment by F9y4ng** [comment]
我没有组织账户用于登录sharepoint.com，所以无法看到问题页面。

我相信你也无法提供测试账户，所以你遇到的这问题我无法帮助你解决。

>　不过你可以打开页面上字体选取列表后，按Ctrl+Shift+C打开元素选择器，选中不显示的字体名称，并将元素选择器截图上传至这里，我会尝试给你解决方案（不代表一定能解决）。

**Comment by F9y4ng** [comment]
尝试一下：
在**需要渲染的网页元素**中，追加 `:not(span[class*='ms-Button'])`,保存为站点独享数据。

如无效，请截图这部分内容：
![PS_2023-09-20_15-02-48](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/3b619763-906e-4077-834e-10118aa115a8)

**Comment by SelfishSailfish** [comment]
> 在**需要渲染的网页元素**中，追加 `:not(span[class*='ms-Button'])`,保存为站点独享数据。

求救如何追加？

**Comment by F9y4ng** [comment]
> 求救如何追加？

https://github.com/F9y4ng/GreasyFork-Scripts/wiki/%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%EF%BC%88%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC%EF%BC%89

**Comment by SelfishSailfish** [comment]
> :not(span[class*='ms-Button'])

![Untitled](https://github.com/F9y4ng/GreasyFork-Scripts/assets/38479206/fc2b97da-36a3-4a34-84b8-86cc5ee2f992)
是这个吗

**Comment by F9y4ng** [comment]
Try this:
```
:not([class*='ms-Button'])
```
