### ISSUE TITLE
使用脚本的还原功能还原旧设置后无法更换字体[发现错误] 

### ISSUE THREAD

**Issue by liuuuuu95** [F9y4ng/GreasyFork-Scripts#264]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
我在原浏览器的脚本菜单中备份了字体及相关网站的自定义设置，在新浏览器导入后，字体被锁定为苹方，选择新字体更换后刷新又回回到苹方，只有清空网站个性化设置数据列表才能成功更改字体

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去XX网址 "..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _遇到错误或问题 "..."_

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：win11
- 浏览器 [_如:Chrome,Safari_]：chrome
- 浏览器版本 [_如:108.0.5359.128_]：117.0.5938.92
- 脚本管理器 [_如:Tampermonkey_]：暴力猴
- 脚本管理器版本 [_如:4.18.1_]：2.15.0
- 所用的脚本名称 [_如:FontRendering_]： Font Rendering (Customized)
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.09.03.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

暴力猴
沉浸式翻译: 双语对照网页翻译 & PDF文档翻译
二管家
AutoVerify 、Better History 、Bypass Paywalls 、CLEAN crxMouse Gestures 、Dark Reader 、DeepL翻译：阅读写作翻译器 、IDM Integration Module  、iTab新标签页(免费ChatGPT) 、Save to Notion 、Tabs Fast Easy 、uBlock Origin 、Zotero Connector 

- 是否同时运行了其他第三方用户脚本？

自动展开全文、beautify、自动展开全文、网盘自动填写验证码

## 8. 附加信息（在此处添加您认为有用的其他信息）
[暴力猴](https://chrome.google.com/webstore/detail/jinjaccalgkegednnccohejagnlnfdag)	
[沉浸式翻译: 双语对照网页翻译 & PDF文档翻译](https://chrome.google.com/webstore/detail/bpoadfkcbjbfhfodiogcnhhhpibjhbnh)	
[二管家](https://chrome.google.com/webstore/detail/aajodjghehmlpahhboidcpfjcncmcklf)	
[AutoVerify](https://chrome.google.com/webstore/detail/jgcfgcdociopaedpeiacalnccfiaeeej)	
[Better History](https://chrome.google.com/webstore/detail/egehpkpgpgooebopjihjmnpejnjafefi)	
Bypass Paywalls
[CLEAN crxMouse Gestures](https://chrome.google.com/webstore/detail/mjidkpedjlfnanainpdfnedkdlacidla)	
[Dark Reader](https://chrome.google.com/webstore/detail/eimadpbcbfnmbkopoojfekhnkhdbieeh)	
[DeepL翻译：阅读写作翻译器](https://chrome.google.com/webstore/detail/cofdbpoegempjloogbagkncekinflcnj)	
[IDM Integration Module](https://chrome.google.com/webstore/detail/ngpampappnmepgilojfohadhhmbhlaek)	
[iTab新标签页(免费ChatGPT)](https://chrome.google.com/webstore/detail/mhloojimgilafopcmlcikiidgbbnelip)	
[Save to Notion](https://chrome.google.com/webstore/detail/ldmmifpegigmeammaeckplhnjbbpccmm)	
[Tabs Fast Easy](https://chrome.google.com/webstore/detail/falglioamaogaliloglbhkannkjlpjil)	
[uBlock Origin](https://chrome.google.com/webstore/detail/cjpalhdlnbpafiamejdnhcphjbkeiagm)	
[Zotero Connector](https://chrome.google.com/webstore/detail/ekhagklcjbdpajgpjgmbionohlpdbjgc)

**Comment by F9y4ng** [comment]
我有看到你在使用Violentmonkey 2.15.0，它们(v2.15.0 ~ v2.15.3 BETA)在某些禁用缓存的网站会出现无法读取保存数据的BUG，必须手动刷新。这个问题我已反馈至[VM#1899](https://github.com/violentmonkey/violentmonkey/issues/1899)，并在2.15.4 BETA版本中作了修复。你可以选择安装`Violentmonkey v2.15.4+BETA`或者`Tampermonkey v4.19.0`替代，或者等待VM在正式版中修复该问题。

不确定你遇到的问题是否属于这个情况，建议你安装TM4.19.0临时测试一下看看。
