### ISSUE TITLE
[发现错误] 在软路由的AdGuard Home控制界面,过滤器-自定义过滤规则处,文字显示重影

### ISSUE THREAD

**Issue by a15355447898a** [F9y4ng/GreasyFork-Scripts#265]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
在软路由的AdGuard Home控制界面,过滤器-自定义过滤规则处,文字显示重影

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. 去软路由的AdGuard Home控制界面
2. 单击过滤器-自定义过滤规则
3. 遇到错误或问题:文字重影

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/69517898-a4e4-4467-8eae-57a3b3212069)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
在浏览器隐私窗口,没有任何脚本的情况下
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/f662681e-541b-4ec5-89f4-9eea1e140912)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统: Windows11
- 浏览器: edge
- 浏览器版本: 117.0.2045.43
- 脚本管理器: Tampermonkey
- 脚本管理器版本: 4.19.0
- 所用的脚本名称 
- 所用的脚本版本: 字体渲染（自用脚本）

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
<img width="645" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/98feae96-57f6-419b-ae16-e3dc36a76d7d">
<img width="647" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/4418f304-f2c2-4a84-9260-d73dc5d2ed3b">
<img width="648" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/7a2c52b9-2a3d-4e6e-9c14-c157364456b8">

- 是否同时运行了其他第三方用户脚本？
<img width="726" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/1c7ee553-863b-4db7-a1c4-4d2df284b634">

## 8. 附加信息（在此处添加您认为有用的其他信息）
我只改了字体,其他全是默认设置

**Comment by F9y4ng** [comment]
这个问题之前有用户提过，不过我本地并没有Adguard Home，所以无法提供帮助。

不过你可以使用元素选择器选取元素后将元素代码部分截图上传，我会尝试解答。

**Comment by a15355447898a** [comment]
> 这个问题之前有用户提过，不过我本地并没有Adguard Home，所以无法提供帮助。
> 
> 不过你可以使用元素选择器选取元素后将元素代码部分截图上传，我会尝试解答。


![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/d229121b-772b-47ee-99eb-3f3b1ae284ff)

```
<div class="text-edit-container mb-4"><textarea class="form-control font-monospace text-input">@@||pan.quark.cn^$important
@@||uop.quark.cn^$important
@@||px.wpk.quark.cn^$important
@@||drive-pc.quark.cn^$important
@@||track.lc.quark.cn^$important
@@||drive.quark.cn^$important
@@||avatars.mds.yandex.net^$important
@@||a.xn--6nq44r2uh9rhj7f.com^$important
@@||dl.reg.163.com^$important
@@||spclient.wg.spotify.com^$important
@@||broccoli.uc.cn^$important
@@||xn--4gq62f52gdss.com^$important
@@||xn--4gq62f52gdss.xyz^$important
@@||1.xn--6nq44r2uh9rhj7f.com^$important
</textarea><code class="text-output font-monospace"><div class="text-transparent">@@||pan.quark.cn^$important</div><div class="text-transparent">@@||uop.quark.cn^$important</div><div class="text-transparent">@@||px.wpk.quark.cn^$important</div><div class="text-transparent">@@||drive-pc.quark.cn^$important</div><div class="text-transparent">@@||track.lc.quark.cn^$important</div><div class="text-transparent">@@||drive.quark.cn^$important</div><div class="text-transparent">@@||avatars.mds.yandex.net^$important</div><div class="text-transparent">@@||a.xn--6nq44r2uh9rhj7f.com^$important</div><div class="text-transparent">@@||dl.reg.163.com^$important</div><div class="text-transparent">@@||spclient.wg.spotify.com^$important</div><div class="text-transparent">@@||broccoli.uc.cn^$important</div><div class="text-transparent">@@||xn--4gq62f52gdss.com^$important</div><div class="text-transparent">@@||xn--4gq62f52gdss.xyz^$important</div><div class="text-transparent">@@||1.xn--6nq44r2uh9rhj7f.com^$important</div><div class="text-transparent">
</div></code><sider-quick-compose-btn data-gpts-theme="light"></sider-quick-compose-btn></div>
```

**Comment by F9y4ng** [comment]
尝试在**排除渲染的HTML标签**中，追加`,textarea`，保存为站点独享。

**Comment by a15355447898a** [comment]
> 尝试在**排除渲染的HTML标签**中，追加`,textarea`，保存为站点独享。

<img width="907" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/5216b136-16fa-4a2b-8cbb-57b1a1452b23">
不太行,看起来没起作用

**Comment by F9y4ng** [comment]
再试试这个`,.text-edit-container *`

**Comment by F9y4ng** [comment]
你右键上另存为...将网页，全部下载至本地，打包上传。

**Comment by a15355447898a** [comment]
[AdGuard Home.zip](https://github.com/F9y4ng/GreasyFork-Scripts/files/12751504/AdGuard.Home.zip)


> 你右键上另存为...将网页，全部下载至本地，打包上传。

**Comment by a15355447898a** [comment]
请问一下,我更新2023.11.04.1版本后此问题又再次出现了
在排除渲染的HTML标签中，追加,textarea或者追加,.text-edit-container *都没效果
重新开关自定义等宽字体也没有效果
<img width="1168" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/c6cdea34-f959-47b7-a33b-e08a0f6a815f">
<img width="1112" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/f0d14020-d341-4a9a-a976-b67264cbeaf0">

**Comment by F9y4ng** [comment]
我发现它了，下个热更新会解决这个小问题。
