### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by Suranow** [F9y4ng/GreasyFork-Scripts#268]
## 1. 准备工作（确认预先完成的操作）

- [X ] 我确认正在使用的是当前脚本的最新版本。
- [X ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [X ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
使用ScriptCat运行此脚本，版本更新-温馨提示无法关闭，打开新页面就会重新弹出

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1.打开任何一个页面

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
恢复正常

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Windows11
- 浏览器 [_如:Chrome,Safari_]：Liberwolf
- 浏览器版本 [_如:108.0.5359.128_]：118.0.1-1
- 脚本管理器 [_如:Tampermonkey_]：ScriptCat
- 脚本管理器版本 [_如:4.18.1_]：0.15.1
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.09.03.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

uBlock Origin
FoxyTab

- 是否同时运行了其他第三方用户脚本？

Steam Info

**Comment by F9y4ng** [comment]
Duplicate of #249

**Comment by F9y4ng** [comment]
Duplicate of #249.

**Comment by Suranow** [comment]
> Duplicate of #249.

并不是，就算设置不在弹出更新提示，关闭浏览器后选项就被重置了。
