### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by Suranow** [F9y4ng/GreasyFork-Scripts#269]
## 1. 准备工作（确认预先完成的操作）

-[x] 我确认正在使用的是当前脚本的最新版本。
-[x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
-[x 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

使用ScriptCat运行此脚本，版本更新-温馨提示无法关闭，打开新页面就会重新弹出
已经确认过 红色或绿色按钮表示已了解更新项目
就算在[高级核心功能设置]里选择[关闭更新提示功能]
关闭浏览器后，在重新打开浏览器
[关闭更新提示功能]会被重置为 OFF
[高级核心功能设置]里所有选项都会被重置
版本更新-温馨提示 也会反复弹出

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1.任何一个界面
2.关闭后重启浏览器

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
恢复正常

## 6. 客户端信息（请在冒号后认真填写您的本地信息）

    操作系统 [如:Win10,MacOS]：Windows11
    浏览器 [如:Chrome,Safari]：Liberwolf
    浏览器版本 [如:108.0.5359.128]：118.0.1-1
    脚本管理器 [如:Tampermonkey]：ScriptCat
    脚本管理器版本 [如:4.18.1]：0.15.1
    所用的脚本名称 [如:FontRendering]：字体渲染（自用脚本）
    所用的脚本版本 [如:2020.11.24.1]：2023.09.03.1
    其他补充信息[如:您对脚本管理器、浏览器或操作系统的特殊设置]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

uBlock Origin
FoxyTab

- 是否同时运行了其他第三方用户脚本？

Steam Info

## 8. 附加信息（在此处添加您认为有用的其他信息）
跟#249所反馈问题不一致。

**Comment by F9y4ng** [comment]
ScriptCat的GM_setValue指向了window.localStorage，这使得数据保存以站点为单位而非全局保存，所以进入不同站点就会反复提示。

建议你使用主流脚本管理器，这些小众的管理器问题多多。
