### ISSUE TITLE
[发现错误] 部分字符丢失，比如QQ邮箱的邮件编辑页面的工具栏。

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [F9y4ng/GreasyFork-Scripts#27]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
[](url)
![1](https://user-images.githubusercontent.com/8177108/137826501-18bf8686-c896-42c2-9603-0c18aa47e561.png)

**客户端信息：**  （请填写以下信息）
- 操作系统： [例如 Win10]
- 浏览器 [例如 Chrome, Firefox]
- 版本 [例如 93.0.4577.63]
- 脚本扩展 [例如 TamperMonkey ]
- 脚本扩展版本 [例如 4.13.6138 ]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by asnfohsdgfbkxcv** [comment]
其实不仅仅是本脚本有这个情况，用其他更改网页字体的浏览器扩展也会有这个情况。目前的建议是能不给在脚本加判断不替换这些字符，或者直接禁用脚本在该域名生效。

**Comment by F9y4ng** [comment]
正如你所说，字体替换肯定会导致某些站点的字体图标出现方框显示的问题。一般情况下，不建议在工具型网站（如邮箱、在线编辑器等）使用字体替换，尤其是国内网站。

遇到显示方框的情况，如果自己熟悉CSS就可以通过脚本的CSS排除选项进行过滤；如果不熟悉CSS就通过脚本菜单添加至禁止渲染的名单。

所以，这**并非**脚本bug，而是在所有网站上无法做到全部兼容，且脚本也尽可能给出了相应的处理方法。这也是称之为 **自用脚本** 的原因。
