### ISSUE TITLE
[发现错误] Firefox 115.3.1 ESR 脚本字体列表检测功能不可用

### ISSUE THREAD

**Issue by wicatfly** [F9y4ng/GreasyFork-Scripts#270]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

选择字体框显示数据源暂无数据, 即使已经添加了自定义字体也一样
以前添加自定义字体能成功, 今天添加数次都失败了, 比如苹方,按照这个格式添加失败: {"ch":"苹方-简","en":"PingFang SC","ps":"PingFangSC-Regular"}

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
1. _去XX网址 "..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _遇到错误或问题 "..."_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![屏幕截图 2023-10-08 233412](https://github.com/F9y4ng/GreasyFork-Scripts/assets/55010685/2cde1dc8-f445-46d9-9b54-497f4bbae744)
![屏幕截图 2023-10-08 233439](https://github.com/F9y4ng/GreasyFork-Scripts/assets/55010685/b4879747-0712-4c87-9772-7cc4e716a414)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
修复went

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Win11
- 浏览器 [_如:Chrome,Safari_]：Firefox
- 浏览器版本 [_如:108.0.5359.128_]：115.3.1esr (64 位)
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：v4.19.0
- 所用的脚本名称 [_如:FontRendering_]：字体渲染(自用脚本)
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.10.03.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

uBlock Origin,划词翻译,stylus,Autocopy,闪耀拖拽,MONKNOW,ZOOM page WE,sideberry,Gesturefy,万能图片下载助手
以上扩展均禁止过以测试bug

- 是否同时运行了其他第三方用户脚本？

沉浸式翻译, Super_preloaderplus_One_改
以上脚本均禁止过以测试bug

**Comment by F9y4ng** [comment]
1. ` {"ch":"苹方-简","en":"PingFang SC","ps":"PingFangSC-Regular"}` 这个字体已经存在于脚本内置的字体表中了，所以不论你在自定义字体里添加多少次，都会被自动过滤掉。

3. 从你的描述上看，感觉应该是Firefox 115.3.1 ESR的问题。（建议你安装FF正式版118.0.1试试看，在我本地FF正式版本没有遇到过此类问题。）

5. 在 #162 中提到过Librewolf(Gecko低版本内核)也存在兼容性问题，可以尝试以下方法：
```
进入about:config，修改privacy.resistFingerprinting，值为false，清空字体缓存后重启浏览器，重试。
```

**Comment by F9y4ng** [comment]
我可以确定是你本地的环境问题，需要你逐一排除。

我本地使用Firefox115.3.1ESR、Tampermonkey4.19.0、脚本2023.10.03.1完全正常。

![PS_2023-10-09_00-47-33](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/6590fd6c-7e1e-4d98-b2e3-d0e89bcff4f0)

**Comment by wicatfly** [comment]
感谢答复，我直接把 Firefox 翻新了，扩展一个没少，设置一项没变，目前脚本恢复正常了，奇怪

F9y4ng ***@***.***>于2023年10月9日 周一00:50写道：

**Comment by F9y4ng** [comment]
FF确实会有这种奇怪的问题。长时间使用后各种设置项目会随着热更新搞出各种无厘头的问题，这时候如果重新覆盖安装一次，所有的疑难杂症就莫名其妙的好了。而扩展、配置会随账户登录自动更新安装。

**Comment by wicatfly** [comment]
是的，考虑到扩展和脚本我已经禁用过了，再逐一排除工作量太大，翻新一下也好 🤣

F9y4ng ***@***.***>于2023年10月9日 周一02:00写道：
