### ISSUE TITLE
[文心一言不能渲染] 

### ISSUE THREAD

**Issue by LY-must-win** [F9y4ng/GreasyFork-Scripts#271]
## 1. 准备工作（确认预先完成的操作）

-  我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
打开文心一言后字体无法渲染
## 3. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/103368413/3c6668af-ff2c-4c73-ae25-ec2e4b47367f)
## 4. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win11_]：
- 浏览器 [_Edge_]：
- 脚本管理器 [Tampermonkey_]：

**Comment by F9y4ng** [comment]
不能复现问题，请检查你本地的脚本或扩展冲突，逐一排查。
![搜索引擎](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/faffb494-2b2d-4924-a847-db7d774d66f7)
![官方站点](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/8d121755-8e23-4256-b9cc-edfc6fb78766)
