### ISSUE TITLE
某些页面会出现文字错乱

### ISSUE THREAD

**Issue by mx4994** [F9y4ng/GreasyFork-Scripts#272]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
Android文档页面会出现文字错乱 [link](https://source.android.com/docs/core/architecture/bootloader?hl=zh-cn)

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
只开这个脚本，打开页面就能复现。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/52325833/071ac9b7-418b-453a-b327-ce66424aa4e9)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
正常是这样
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/52325833/b4360d05-110a-4afb-ab88-6210d9eafc9e)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：Win10
- 浏览器 [_如:Chrome,Safari_]：chrome
- 浏览器版本 [_如:108.0.5359.128_]：118.0.5993.71
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：4.19.0
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.10.03.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

测试已关闭其他拓展、脚本运行，确定就是字体渲染（自用脚本）引起。

- 是否同时运行了其他第三方用户脚本？

测试已关闭其他拓展、脚本运行，确定就是字体渲染（自用脚本）引起。

**Comment by F9y4ng** [comment]
参阅 #42 中developer.android相关的规则，应该是通用的。
