### ISSUE TITLE
Mobile problem

### ISSUE THREAD

**Issue by Ebaharloo** [F9y4ng/GreasyFork-Scripts#273]
I tested the on an android phone using Firefox as the browser. I noticed that the buttons were too large and occupied the entire field.
![Screenshot_20231025-001225_Firefox](https://github.com/F9y4ng/GreasyFork-Scripts/assets/6277970/279b9edd-6e86-455b-8f33-a968b8536fad)

**Comment by F9y4ng** [comment]
Sorry, because I rarely use browsers on mobile, this script is not compatible with mobile devices, you can try other similar scripts.
