### ISSUE TITLE
[发现错误] 报告`w.frColorPicker is not a constructor`的错误，无法打开设置界面

### ISSUE THREAD

**Issue by wwmbao** [F9y4ng/GreasyFork-Scripts#274]
## 1. 准备工作（确认预先完成的操作）

- [√] 我确认正在使用的是当前脚本的最新版本。
- [√] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [√] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
点击字体渲染按钮，出现报错弹框

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
任何网址

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
none

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
想要进入字体渲染设置

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：win11
- 浏览器 [_如:Chrome,Safari_]：edge
- 浏览器版本 [_如:108.0.5359.128_]：118.0.2088.57
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey_
- 脚本管理器版本 [_如:4.18.1_]：4.19.0
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.10.03.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：none

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

none

- 是否同时运行了其他第三方用户脚本？

none

## 8. 附加信息（在此处添加您认为有用的其他信息）

```log
浏览器信息：{"engine":"Blink","brand":"Edge","brandversion":"118","os":"Windows","trust-engine":"Blink","credit":"Tampermonkey 4.19.0","cheat-ua":false}
脚本扩展信息：Tampermonkey 4.19.0
脚本版本信息：2023.10.03.1
当前访问域名：www.bilibili.com /
错误信息列表：
1、[Fonts shadowColor]: TypeError: w.frColorPicker is not a constructor
```

**Comment by F9y4ng** [comment]
看起来与 #254 是同样的报错。

一般情况下，报w.frColorPicker方法的错误，大都是程序无法正常访问greasyfork.org，造成无法从greasyfork中下载拾色器代码。而 #254 的问题是该脚本管理器的bug.

## 处理方法
* 检查本地网络是否能够正常访问greasyfork.org，如果不能，尝试全局翻墙将代码正常下载后可关闭即可。如果可以正常访问，那么在Tampermonkey脚本管理界面，点击脚本名称进入脚本管理，在“外部”标签内查看资源是否下载成功(如图)。
* 尝试将脚本删除后，注意清空垃圾箱，重新安装。
* 检查本地浏览器是否安装过其他破解的Dll，如chrome++等，会造成浏览器或脚本管理器异常的第三方插件。
