### ISSUE TITLE
[发现错误] bing.com(真 国际版,不是cn.bing.com),搜索框字体重叠

### ISSUE THREAD

**Issue by a15355447898a** [F9y4ng/GreasyFork-Scripts#278]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
搜索框中字会重叠

## 3. 错误再现（重现行为步骤，直至复现您遇到的问题）
输入字,再删除

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![截图_20231029232629](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/5b43994f-708c-4040-a874-accb934e507e)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
![截图_20231029232827](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/0cb28e94-4dae-43fe-be40-bc2b6c530b75)

## 6. 客户端信息（请在冒号后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：win11
- 浏览器 [_如:Chrome,Safari_]：edge
- 浏览器版本 [_如:108.0.5359.128_]： 118.0.2088.69
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：4.19.0
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2023.10.03.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/2c00770f-122c-4258-b610-f3c3aa594def)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/dc48edbc-5fc6-452e-bd03-149c1f12535c)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/827cae39-f325-4859-9bc1-8d30f223d036)

- 是否同时运行了其他第三方用户脚本？

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/270fd8b9-ee65-4241-a9ce-379e95f6e562)

**Comment by a15355447898a** [comment]
这是网页源代码
<img width="868" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/3aa3fa81-01f8-4469-8cbf-7e4fdd5d0d7f">
```
<div id="sb_form_c" class="sb_form_c "><div class="sb_form_ic" data-replicated-value=""><div class="qfc"><div class="user-prefix">测试</div><div class="ghost"></div></div><textarea id="sb_form_q" class="sb_form_q sb_form_ta" name="q" type="search" inputmode="search" maxlength="2000" autocomplete="off" autofocus="" aria-autocomplete="both" placeholder="問我任何問題..." aria-label="Character limit: 2000. Current character count: 0" spellcheck="false" autocorrect="off" autocapitalize="none" rows="1" enterkeyhint="search" style="width: 464px;" data-bm="125" value="" aria-activedescendant="sa_5004"></textarea></div></div>
```

**Comment by F9y4ng** [comment]
Duplicate of #42
