### ISSUE TITLE
字体添加辅助工具的弹窗界面

### ISSUE THREAD

**Issue by FeiLZX3Km** [F9y4ng/GreasyFork-Scripts#280]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
建议在字体添加辅助工具的弹窗界面添加一个网址链接，这个链接可以帮助用户查询复制粘贴所要填写的字体英文名称、字体家庭这些信息。因为有许多信息大小写、英文名称用户不会知道，但查找起来不一定能找得到。
另外建议为该弹窗添加一个切换网页不会自动关闭的特性。因此用户复制粘贴时要切换网页。

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）
无

**Comment by F9y4ng** [comment]
#64 #261 有相关的使用说明和介绍。

你提到的弹窗关闭是浏览器本身性质决定的，失去Tab窗口焦点焦点就会自动关闭。复制到记事本再操作吧。
