### ISSUE TITLE
请问下，这个搜索之后很多波浪线的功能能否做个开关或者去除？

### ISSUE THREAD

**Issue by sundaqiang** [F9y4ng/GreasyFork-Scripts#282]
![微信截图_20231107100257](https://github.com/F9y4ng/GreasyFork-Scripts/assets/34206512/7db933eb-8dd0-4881-92db-ea7d351a3b2b)

**Comment by F9y4ng** [comment]
目测脚本冲突，二选一关闭重定向功能可解决你遇到的问题（要么关闭ac~baidu的重定向，要么关闭本脚本的重定向）。
