### ISSUE TITLE
[发现错误] 文字变为方块

### ISSUE THREAD

**Issue by tuwulin365** [F9y4ng/GreasyFork-Scripts#283]
![2023-11-07_100423](https://github.com/F9y4ng/GreasyFork-Scripts/assets/33275750/b149518d-1b59-43af-809f-b92bd87651ec)

360极速浏览器X v22.1.1024
tampermonkey v4.19.0
文字变成了方块。我发现源码里就是方块，可能是编码错误导致的。

**Comment by F9y4ng** [comment]
建议你检查一下本地环境，浏览器本身、脚本冲突等等。Blink内核非魔改的浏览器应该是正常的，你可以试试看，比如chrome或Edge。

**Comment by tuwulin365** [comment]
解决了。360极速浏览器X 关闭directwrite就会导致emoji显示成方块。
这个脚本里使用了一些特别的字符，如𝐁𝐚𝐢𝐝𝐮，非ascii字符，会有类似问题。

**Comment by weavers1f** [comment]
> 解决了。360极速浏览器X 关闭directwrite就会导致emoji显示成方块。 这个脚本里使用了一些特别的字符，如𝐁𝐚𝐢𝐝𝐮，非ascii字符，会有类似问题。

我也是360极速浏览器X ，昨天装了跟你这个一模一样，好像这个浏览器关闭dw的效果一直都没有百分的好，总是有个别时不时会变成方块
