### ISSUE TITLE
[新增功能] 允许只插入为备用字体

### ISSUE THREAD

**Issue by hi-yiyang** [F9y4ng/GreasyFork-Scripts#287]
## 1. 准备工作（确认预先完成的操作）

- [x ] 我确认使用的是当前脚本的最新版本。
- [ x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
大部分情况下，一些网站的自定义字体效果较好。（只有微软雅黑为一大痛点。）因此，希望能够只将设置的字体插入为备用字体。目前似乎会忽略所有的字体设置并另行插入variable，是否能仅将选定的中文字体添加至网站字体列表的serif/sans-serif前方呢？

**Comment by F9y4ng** [comment]
我至少读了5遍，才似乎读懂你要表达的意思。**我不得不再次重申，提问前请将脚本说明认真看一下。** [Wiki](https://github.com/F9y4ng/GreasyFork-Scripts/wiki)

1. 脚本设置过字体后，会覆盖网站默认设置的字体，如果不想使用自定义字体，请将**字体重写**功能关闭，保存为站点独享数据，即在该站点停止字体替换效果。

2. 浏览器的字体样式的应用没有备用字体一说，在CSS字体设置样式中存在多个中文或英文字体是防止本地系统中不存在指定的字体而fallback所设置的，直到匹配到系统上存在的字体（无匹配则调用浏览器默认字体）。

3. 脚本设定的字体已经完整的设置好fallback字体，包含你所提到的serif/sans-serif字体族。
