### ISSUE TITLE
[发现错误] 微博、淘宝、京东网站部分功能图标变成方框或不可见

### ISSUE THREAD

**Issue by kokobk** [F9y4ng/GreasyFork-Scripts#29]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
一开始是新版PC端微博，点赞、评论、转发图标均会变成方块
更新版本后，淘宝、京东等购物网站的收藏商品图标也变成方块了
排除渲染后，恢复正常

**错误再现**  （重现行为的步骤）

进入新版微博PC端页面或电商网站

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
![image](https://user-images.githubusercontent.com/25819821/141146595-14344c0a-0d32-4f4f-bd73-51c93b3f857c.png)

**实际结果**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/25819821/141146494-a44a8264-ee12-43ab-83ed-5c14684b5945.png)

**客户端信息：**  （请填写以下信息）
- 操作系统：Win10
- 浏览器：Edge beta
- 版本  96.0.1054.13
- 脚本扩展 Tampermonkey BETA
- 脚本扩展版本 4.14.6146
- 运行的脚本名称 字体渲染（自用脚本）
- 运行的脚本版本 V2021.11.07.1 

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等 ]
- 否
- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
- 否
 

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
建议下次遇到这样的问题，先点击配置页面上右上角渲染的问号看看使用帮助，可能会更快的解决你的问题。
[![IwK08U.png](https://z3.ax1x.com/2021/11/11/IwK08U.png)](https://greasyfork.org/scripts/416688/discussions/104341)

[关于个别网站样式错误修正的设置分享，请勿跟帖回复，自取自用。](https://greasyfork.org/scripts/416688/discussions/104341)
