### ISSUE TITLE
会导致notion网页崩溃

### ISSUE THREAD

**Issue by ASIjacket** [F9y4ng/GreasyFork-Scripts#290]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
会导致notion网页崩溃，无法打开nontion

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
1. 禁用所有插件，仅启用tampermokey
2. 仅启用该脚本
3. 脚本菜单显示正在载入菜单
4. notion网页卡住无法打开
5. 一段时间后提示网页无响应 点击结束崩溃

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：win
- 浏览器：chrome
- 浏览器版本：119.0.6045.124
- 脚本管理器：Tampermonkey 
- 脚本管理器版本：最新
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：[v2023.12.02.1]

## 7.其他
最近两三个月更新后出现的，最近才排查到脚本问题

**Comment by F9y4ng** [comment]
notion上脚本冲突的问题已经在 #193 修正过了，可能是与你本地其他扩展或网页防火墙有冲突。

## 解决办法
与 #193 提到的临时处理办法一样，在notion站点上关闭**粗体修正**功能，保存为站点独享数据。

**Comment by F9y4ng** [comment]
请更新至 v2023.12.12.1 即可解决冲突问题。
