### ISSUE TITLE
FIrefox在后台google界面自动打开新标签页

### ISSUE THREAD

**Issue by actforjason** [F9y4ng/GreasyFork-Scripts#291]

**Comment by F9y4ng** [comment]
关闭**Google国际站跳转**即可。

**Comment by actforjason** [comment]
![图片](https://github.com/F9y4ng/GreasyFork-Scripts/assets/57058325/39a311aa-b186-476c-b835-c922141de0d4)
已关闭了，有时候全关闭也会，关闭插件好像就不会了

**Comment by F9y4ng** [comment]
> 已关闭了，有时候全关闭也会，关闭插件好像就不会了

**优雅的搜索引擎跳转助手**脚本在开启**Google 国际站跳转**功能后，在访问google时如果访问地址不是www.google.com，则在后台打开google.com/ncr来强制访问google.com，并且脚本会在刷新当前页面后自动关闭新开的后台窗口。(greasymonkey需手动关闭)

脚本中后台弹出新窗口的功能仅此项，如果关闭后依然弹出新窗口，请检查其他脚本，或清除你的浏览器全部缓存后重试。

### 特殊情况
有时因为你的网络原因，比如访问速度慢，会造成后台开启的页面还未加载完就被关闭，这时会出现重复打开的问题。建议你更换付费的VPN服务来改善网络条件。

**Comment by actforjason** [comment]
![图片](https://github.com/F9y4ng/GreasyFork-Scripts/assets/57058325/10daebd2-524e-40a5-8724-5540a10b478a)

代理的速度没问题，访问的也一直是国际站。又观察了一阵，还会出现这种情况，尤其是在google搜索后把FIrefox放到后台会触发，有时一下子弹出十几个新标签页。
使用的是FIrefox Dev最新版

**Comment by F9y4ng** [comment]
在我本地无法复现你提到的情况，你提供的有用信息太少了，请按（Bug report）格式排查异常并提供本地环境信息。

1. 建议你尝试使用Firefox正式版本或其他内核浏览器如Chrome看是否复现此问题。

2. 或按 #270 的方法尝试修复本地环境的异常。

**Comment by F9y4ng** [comment]
这是Tampermonkey的bug [#1935](https://github.com/Tampermonkey/tampermonkey/issues/1935)，已在BETA 5.0.6191中修复。可更新至BETA版本TM来解决此问题。

**Comment by cknimasb** [comment]
你这傻逼杂种死全家的玩意儿，搞这病毒，对得起你躺在乱葬岗的一家老小的杂种尸体么？
真你妈逼的坏种，你这王八野驴操的逼样的杂种玩意儿
世世代代你都癌症晚期不得好死的贱种！
