### ISSUE TITLE
[新增功能] 能不能给bing添加一个搜索框浮动的功能

### ISSUE THREAD

**Issue by QianMoXi** [F9y4ng/GreasyFork-Scripts#292]
## 1. 准备工作
- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议
谷歌、百度，在搜索列表中往下滚动，会把搜索框一直显示在最上方，可以直接点击按钮切换搜索引擎，但是bing会隐藏掉，意味着切换搜索引擎还得滚动到顶部，比较麻烦，如果能实现bing也是显示在顶部就好了（或者说只把切换搜索引擎的按钮浮动到界面上？）

## 3. 附加信息或屏幕截图

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/26250460/2bab3359-3a22-439c-8e54-c8d5cd932169)

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/26250460/996376bc-6d05-48b1-af3a-536fd972b7d8)

**Comment by F9y4ng** [comment]
Bing.com 一直都在灰度测试滚动搜索框，所以，一部分用户能看到滚动效果，一部分用户看不到，如果你非常想用，不如直接向Bing发起公测滚动搜索框的建议。

PS, Bing需要手动开启暗黑模式（外观改为“系统默认值”）才能生效。
