### ISSUE TITLE
非中文字体信息如何添加？

### ISSUE THREAD

**Issue by ZackAu** [F9y4ng/GreasyFork-Scripts#293]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）

是否能添加自定义日语字体的支持，我无法在自定义字体添加日文字体，字体fontFamily和preferredFamily都显示只有ja，而没有ch。

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）
![微信截图_20231219132839](https://github.com/F9y4ng/GreasyFork-Scripts/assets/110708134/9f16b270-0f72-422f-adde-4c72af7be43f)

**Comment by F9y4ng** [comment]
当新增字体没有中文信息时，可以将ch部分的信息填写为其他语言信息如英文、日文、韩文等。

你当前的字体可使用以下设置：

```JSON
{"ch":"ja部分", "en":"en部分", "ps:":"postScriptName"}
```
