### ISSUE TITLE
[发现错误] 开启字体渲染后，百度百科多个义项显示不全。

### ISSUE THREAD

**Issue by Axian86** [F9y4ng/GreasyFork-Scripts#295]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x]  我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
开启字体渲染后，百度百科多个义项显示不全。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
开启字体渲染后，百度百科多个义项显示不全。关闭字体渲染后，可以正常显示

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![微信截图_20231225151502](https://github.com/F9y4ng/GreasyFork-Scripts/assets/29697853/52270dda-e26e-4071-8906-0891ca5ced80)

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：win11
- 浏览器：Edge
- 浏览器版本：120.0.2210.77
- 脚本管理器：Tampermonkey
- 脚本管理器版本：5.0.6190
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2023.12.12.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
ADguard

- 是否同时运行了其他第三方用户脚本？
Mactype助手

**Comment by F9y4ng** [comment]
1. 国内烂厂的屎山代码绝非鹅厂一家，定义 `overflow: hidden; text-overflow: ellipsis;` 后不指定最大宽度就会直接隐藏超出的文字。你使用脚本更换了网站默认字体后，新字体的字宽使得文本长度超出样式定义后就会被隐藏。如图，添加最大宽度后样式就会恢复正常。
 
![shit](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/c39f7618-8f98-4315-9d55-6bb0350d0828)

2. 你使用了“Mactype助手”这个脚本为什么还要用此脚本？不怕样式冲突么？意义何在？
