### ISSUE TITLE
[发现错误] www.google.com搜索结果页面，ctrl加鼠标点击链接，在前台打开标签页面。

### ISSUE THREAD

**Issue by byteatom** [F9y4ng/GreasyFork-Scripts#296]
## 1. 准备工作（确认预先完成的操作）

- [ x] 我确认正在使用的是当前脚本的最新版本。
- [ x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
www.google.com 的搜索结果页面，ctrl加鼠标点击链接，在前台打开标签页面。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
  1. www.google.com
  2. 搜索任意词
  3. 在结果页面，按住ctrl键，鼠标点击任意链接
  4. 链接在前台打开

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
不需要

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
在ctrl加鼠标点击链接的情况下，浏览器默认行为，或者禁用本脚本，或者其他站点，都是在后台打开。

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win10
- 浏览器：Edge
- 浏览器版本：120.0.2210.91 (正式版本) (64 位)
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.0.0
- 所用的脚本名称：优雅的搜索引擎跳转助手
- 所用的脚本版本：2023.12.02.1
- 其他补充信息：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
否

- 是否同时运行了其他第三方用户脚本？
否

## 8. 附加信息（在此处添加您认为有用的其他信息）
最近版本更新引入的，以前没有问题。

**Comment by F9y4ng** [comment]
用鼠标中键试试，由于开启了强制开新窗口，左键点击的行为均默认为开新窗口了。
