### ISSUE TITLE
[新增功能] 允许手动设定脚本界面语言

### ISSUE THREAD

**Issue by shanoaice** [F9y4ng/GreasyFork-Scripts#299]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
由于Firefox浏览器的指纹保护功能，本脚本似乎无法正常识别到系统语言为中文，导致其默认使用英语显示界面。希望能添加一个选项来切换中英文界面以应对这种情况

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）
![图片](https://github.com/F9y4ng/GreasyFork-Scripts/assets/25174488/44b25f41-bb83-452f-860a-c8dbe6130a97)

**Comment by F9y4ng** [comment]
脚本识别的是浏览器网页显示的语言设置，不是操作系统的语言设置。

以 Firefox 121.0 (64-bit) 为例：
![Pic_2024-01-01_16-06-18](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/09279331-b3c5-4239-bd21-6ce15c6511b2)

**Comment by shanoaice** [comment]
> 脚本识别的是浏览器网页显示的语言设置，不是操作系统的语言设置。
> 
> 以 Firefox 121.0 (64-bit) 为例： ![Pic_2024-01-01_16-06-18](https://private-user-images.githubusercontent.com/15855068/293574928-09279331-b3c5-4239-bd21-6ce15c6511b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwOTY4NTUsIm5iZiI6MTcwNDA5NjU1NSwicGF0aCI6Ii8xNTg1NTA2OC8yOTM1NzQ5MjgtMDkyNzkzMzEtYjNjNS00MjM5LWJkMjEtNmNlMTVjNjUxMWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA4MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YjJiY2M2NDE4YmUwZjdiNmY2MWZhMzFjMTFlOGViNmFkMDU5Yjg0YjY4OTY2NGJkMzFiYWU0MDE5MjYyODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BmOK9MEK4RxU6uc98mSIpzUiSo59s-a3toQ6Bz5Xs4E)

即使如此我可能也需要这两者不一致（防止指纹追踪/绕开cn.bing.com之类的检测）等情形

**Comment by F9y4ng** [comment]
浏览器语言设置与 （防止指纹追踪/绕开cn.bing.com之类的检测） 没有多少必要联系：
- 浏览器语言设置对于前者数十项的指纹检测标的而言，可有可无；
- 后者对Bing及相关全域全局翻是解决之道。

**Comment by YunfangHou** [comment]
曲线救国的方法是将脚本第 82 行 `const IS_CHN` 的值强行修改为 `true`。缺点是每次脚本更新都需要再手动更改一次。
<img width="931" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/53991651/b38f1444-47d8-406b-a701-9ce528dd7816">
