### ISSUE TITLE
更新太频繁了

### ISSUE THREAD

**Issue by pluveto** [F9y4ng/GreasyFork-Scripts#3]
![image](https://user-images.githubusercontent.com/50045289/121360095-ae1e4a80-c966-11eb-8bf3-b56e5302749a.png)
还有就是会被拦截

**Comment by F9y4ng** [comment]
由于新增需要远程测试的功能、检测脚本源、修正BUG，所以最近几天更新测试较为频繁。现在全部功能都已完成，除非有重大问题发生，最近几个月应该不会有什么更新了。

关于*.user.js下载的问题：

1. tampermonkey 扩展会自动识别所有的 user.js 结尾的js脚本，并自动启动安装界面，基本不会由浏览器接管下载，请检查你的浏览器设置或 tampermonkey 扩展设置。
2. 一般情况下，所有的js脚本文件的浏览器下载操作都会被 Win10 标记为可能有害而禁止保存。
