### ISSUE TITLE
[发现错误] Bing搜索添加百度和Google后新添加的搜索定位异常

### ISSUE THREAD

**Issue by caibingcheng** [F9y4ng/GreasyFork-Scripts#30]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

Bing搜索添加百度和Google后新添加的搜索定位异常, 水平不对齐

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_  https://cn.bing.com/search?q=dnotify
2. _单击YY链接/按钮 "..."_  NA
3. _向下滚动到ZZ位置 "..."_  NA
4. _查看错误_  NA

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

定位正常, 水平对齐

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

![Screenshot from 2021-11-15 17-05-37](https://user-images.githubusercontent.com/15170019/141756371-e8a4694d-b446-4ea9-a7e2-6006fea6d4d8.png)

**客户端信息：**  （请填写以下信息）
- 操作系统： [例如 Win10]   18.04.1-Ubuntu
- 浏览器 [例如 Chrome, Firefox]  Chrome
- 版本 [例如 93.0.4577.63]  94.0.4606.54
- 脚本扩展 [例如 TamperMonkey ]  TamperMonkey
- 脚本扩展版本 [例如 4.13.6138 ]  v4.13
- 运行的脚本名称 [例如 字体渲染（自用脚本） ]  搜索引擎跳转工具
- 运行的脚本版本 [例如 V2021.10.10.1 ]  Version 3.8.20211114.1

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等 ]    NA
- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]    NA
 

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
我本地没有Ubuntu的系统环境，我会尝试修正一个版本，然后你来帮忙测试一下。

**Comment by F9y4ng** [comment]
[Google & Baidu Switcher.user.js.zip](https://github.com/F9y4ng/GreasyFork-Scripts/files/7538849/Google.Baidu.Switcher.user.js.zip)

覆盖安装压缩包中的 Google.Baidu.Switcher.user.js, 在你本地Ubuntu环境Chrome下测试一下，如果没有问题，我会同步更新新版本。

**Comment by caibingcheng** [comment]
感谢, 这个版本定位正常了, 切换到其他搜索引擎也是正常的
![Screenshot from 2021-11-16 10-05-09](https://user-images.githubusercontent.com/15170019/141882627-4f193085-49bb-4b3e-9be1-95cd1ff76f53.png)

**Comment by cesaryuan** [comment]
![image](https://user-images.githubusercontent.com/35998162/218289974-34826985-6c60-4793-887c-550514c0dc92.png)

同样出现了这个问题：
- 操作系统： [例如 Win10] 18.04.1-Ubuntu
- 浏览器：Chrome
- 版本:102.0.5005.167
- 脚本扩展：暴力猴
- 脚本扩展版本：2.13.9
- 运行的脚本名称：优雅的搜索引擎跳转助手
- 运行的脚本版本：2023.02.04.1

在无痕模式问题依然存在（没有其他扩展和脚本在运行）

**Comment by F9y4ng** [comment]
> ![image](https://user-images.githubusercontent.com/35998162/218289974-34826985-6c60-4793-887c-550514c0dc92.png)
> 
> 同样出现了这个问题：
> 
> * 操作系统：Windows 10
> * 浏览器：Chrome
> * 版本:102.0.5005.167
> * 脚本扩展：暴力猴
> * 脚本扩展版本：2.13.9
> * 运行的脚本名称：优雅的搜索引擎跳转助手
> * 运行的脚本版本：2023.02.04.1
> 
> 在无痕模式问题依然存在（没有其他扩展和脚本在运行）

v2023.02.04.1的样式问题我已经发现了，并已在下个版本的更新中已修复了这个样式问题，请等待下个更新发布即可。
