### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by FeiLZX3Km** [F9y4ng/GreasyFork-Scripts#300]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。

## 2. 描述错误信息（清楚而简洁地描述错误）
https://flk.npc.gov.cn/detail2.html?ZmY4MDgxODE3OWY1ZDI0ODAxNzlmYTNiMmQ5MzA0Mjc%3D
通过脚本自带的排除渲染功能排除渲染如上网站后，网站文件显示文字依旧出现重影。
但在通过油猴关闭本脚本后，重影完全消失。
建议修复。

**Comment by F9y4ng** [comment]
1. 打开 https://wb.flk.npc.gov.cn/sfjs/html/8eea50a88ca80135013722e8216f9ca7ba63a6eb.html
2. 打开 字体渲染设置 界面，在 **排除渲染的HTML标签** 中，追加 `,.rGroup *`，保存为站点独享。

**Comment by FeiLZX3Km** [comment]
> 1. 打开 https://wb.flk.npc.gov.cn/sfjs/html/8eea50a88ca80135013722e8216f9ca7ba63a6eb.html
> 2. 打开 字体渲染设置 界面，在 **排除渲染的HTML标签** 中，追加 `,.rGroup *`，保存为站点独享。

 抱歉，似乎未能解决问题？
![微信截图_20240103133335](https://github.com/F9y4ng/GreasyFork-Scripts/assets/21981195/3ea2d243-6f39-4484-bd26-a4938388ed9c)

**Comment by F9y4ng** [comment]
你没有认真、仔细的按照说明操作。

我给出的地址和你操作的地址一样么？不要想当然啊。🫠

**Comment by FeiLZX3Km** [comment]
> 你没有认真、仔细的按照说明操作。
> 
> 我给出的地址和你操作的地址一样么？不要想当然啊。🫠

感谢提醒，问题已经解决！
