### ISSUE TITLE
关于Safari上使用字体的问题

### ISSUE THREAD

**Issue by easonnnone** [F9y4ng/GreasyFork-Scripts#301]
大佬，想了解一下，为啥在Safari上只能选择这几个字体呢，我安装了字体也无法进行选择呢

<img width="312" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/8055993/d06ecaa4-0dc0-41b9-a39a-5207360d6c1e">

**Comment by F9y4ng** [comment]
参考 #260
