### ISSUE TITLE
[发现错误]  在使用kibana页面的开发工具中输入框出现光标定位偏移问题

### ISSUE THREAD

**Issue by fu7100** [F9y4ng/GreasyFork-Scripts#303]
问题现象如下，当我使用安装了字体渲染油猴插件的firefox浏览器访问kibana并使用开发工具调试的时候输入的代码定位偏移，如下图光标的位置实际是在字母s的后面中间并没有空格

![图片](https://github.com/F9y4ng/GreasyFork-Scripts/assets/59348973/865678f4-954d-4bf1-9cc7-17d51b7c68ef)

当我关闭字体渲染后光标定位恢复。

**Comment by F9y4ng** [comment]
如果你没有开启字体缩放功能的话，那必定是字体的字宽问题造成的。

由于更换过网页默认字体，会造成字体宽度不一致从而是编辑工具的样式发生错误。

## 解决办法
1. 尝试开启自定义等宽字体功能，具体如何开启、如何设置请在[Discussions](https://github.com/F9y4ng/GreasyFork-Scripts/discussions)中搜索。
2. 如果以上方法无效，请关闭字体重写功能，以停止对网页默认字体的替换；或排除渲染该站点。

**Comment by fu7100** [comment]
非常感谢！ 关闭字体重写功能后正常了。

F9y4ng ***@***.***> 于2024年1月5日周五 12:54写道：
