### ISSUE TITLE
[发现错误] 在一个网站上,字体渲染脚本反复提示检测到本地数据异常

### ISSUE THREAD

**Issue by a15355447898a** [F9y4ng/GreasyFork-Scripts#304]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/604b46fd-7ae9-4584-8ed5-f4fe5da83c80)

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

  1. _去网址: "[https://ww7.manganelo.tv/](https://ww7.manganelo.tv/)"_
  2. _遇到错误或问题: 如上图所示_

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

脚本应该正常运行

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统 [_如:Win10,MacOS_]：win11
- 浏览器 [_如:Chrome,Safari_]：edge
- 浏览器版本 [_如:108.0.5359.128_]： 118.0.2088.69
- 脚本管理器 [_如:Tampermonkey_]：Tampermonkey
- 脚本管理器版本 [_如:4.18.1_]：5.0.1
- 所用的脚本名称 [_如:FontRendering_]：字体渲染（自用脚本）
- 所用的脚本版本 [_如:2020.11.24.1_]：2024.01.01.1
- 其他补充信息[_如:您对脚本管理器、浏览器或操作系统的特殊设置_]：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/2c00770f-122c-4258-b610-f3c3aa594def)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/dc48edbc-5fc6-452e-bd03-149c1f12535c)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/827cae39-f325-4859-9bc1-8d30f223d036)

- 是否同时运行了其他第三方用户脚本？

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/62456287/d624c673-4b5c-4c1a-9457-667ca7852ee0)

**Comment by F9y4ng** [comment]
感谢反馈，我在本地也可以复现此问题。而且不但在TM中存在，在VM中也同样有这个问题，反复测试后我发现是脚本管理器对JSON.parse的解析在这个特定的站点中会报错，所以我已将这个issue反馈至TM [#1980](https://github.com/Tampermonkey/tampermonkey/issues/1980)， VM [#2012](https://github.com/violentmonkey/violentmonkey/issues/2012)，请关注该issue的进展。

**Comment by F9y4ng** [comment]
下个版本更新时，我会修复这个Bug.

在这段时间内，建议你通过脚本管理器在 "https://ww7.manganelo.tv/" 网站上排除字体渲染脚本的执行。

**Comment by Xia0xia0Xia0** [comment]
唉，手贱，访问了一下，配置都给清空了，还好有备份。😂😂😂

**Comment by F9y4ng** [comment]
请更新至v2024.02.03.1版本即可。
