### ISSUE TITLE
高级核心功能保存之后重启浏览器又会回到原来的初始设置状态

### ISSUE THREAD

**Issue by ShigaHaruki** [F9y4ng/GreasyFork-Scripts#305]
高级核心功能保存不了

**Comment by ShigaHaruki** [comment]
出现的现象是：每次打开页面都会跳出脚本更新-温馨提示。高级功能里面关闭更新状态，在重启浏览器之后又会重置，希望修复

**Comment by F9y4ng** [comment]
请按 错误报告（Bug report） 格式要求填写ISSUE，详细说明你的本地环境。

**Comment by ShigaHaruki** [comment]
Chrome版本：122.0.6261.6（正式版本）beta （64 位）
脚本管理器：ScriptCat 0.16.0

**Comment by F9y4ng** [comment]
> Chrome版本：122.0.6261.6（正式版本）beta （64 位）
> 脚本管理器：ScriptCat 0.16.0

推荐你使用Tampermonkey或violentmonkey。
