### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by coloraven** [F9y4ng/GreasyFork-Scripts#306]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
左侧目录出现问题

1. 去网址 https://cloud.google.com/spanner/docs/working-with-jsonb?hl=zh-cn

**Comment by F9y4ng** [comment]
参阅 [#42 网站样式错误修正的设置分享，不定期更新，自取自用](https://github.com/F9y4ng/GreasyFork-Scripts/discussions/42#:~:text=%E5%9F%9F%E5%90%8D%EF%BC%9A-,cloud.google.com,-%2D%20google%20Cloud)
