### ISSUE TITLE
[发现错误] 部分屏蔽词会导致Google所有结果被屏蔽

### ISSUE THREAD

**Issue by Direct5dom** [F9y4ng/GreasyFork-Scripts#307]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

在拦截关键词处添加一些关键词或网址（如`百度`、`baidu\\.com`），搜索某些关键词（如：`使命召唤`、`使命召唤系列`、`郑好`等），Google的所有搜索结果均被拦截。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

  1. _打开`google.com`_
  2. _如错误信息中所描述的添加好拦截关键词`baidu\\.com`_
  3. _搜索`使命召唤`_
  4. _结果均被拦截_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![屏幕截图 2024-02-12 000649](https://github.com/F9y4ng/GreasyFork-Scripts/assets/59590732/1542f2c1-22ff-4f4e-8563-a38de5991cb1)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

应只拦截`baidu.com`网址的结果。

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Windows 11 专业版 22631.3085
- 浏览器：Edge
- 浏览器版本：121.0.2277.112
- 脚本管理器：Tampermonkey
- 脚本管理器版本：5.0.1
- 所用的脚本名称：优雅的搜索引擎助手
- 所用的脚本版本：2024.02.03.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

否

- 是否同时运行了其他第三方用户脚本？

否

## 8. 附加信息（在此处添加您认为有用的其他信息）
使用Chrome浏览器同样复现了该问题。

**Comment by F9y4ng** [comment]
经测试发现是Google对搜索结果相关的代码有了新的变动，稍后请更新至最新版 v2024.02.12.1 即可。
