### ISSUE TITLE
[发现错误] In google search page 

### ISSUE THREAD

**Issue by Rnreck** [F9y4ng/GreasyFork-Scripts#308]
## 1. 准备工作（确认预先完成的操作）

- [ yes ] 我确认正在使用的是当前脚本的最新版本。
- [ yes ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ yes ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
in google search page  "https://www.google.com/search?q="  input some special string will occurs  Ghosting 
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/12d08ecb-2358-425a-aabc-b12a33b97415)
close the script will not occurs this Ghosting ,i totally sure is the script lead to Blurred font
##  3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
###when input "内緒のいちゃらぶ ～年下少女は本音を伝えたい!  jan" it will be ok and everything is clear 
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/3da6e920-d77b-4420-947c-325f6d9de9be)
###when input Lower case letters follow that ,it would be  Ghosting from " ～年下少女は本音を伝えたい!  janp"
"qwtyuioasdfghjklzxcbm" may occurs ,and "erpvn" may not
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/076760db-624d-4d15-bac3-8d6512a4b023)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/4e674a1a-4ae4-4b5b-be78-637b6095c6d5)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/61808495-0548-4b35-ac92-32568da00f94)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/ea997215-d4b5-42ae-bd50-56f3e900100b)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/aa08846b-8746-4594-bfdd-ba82deb8e524)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/f1f6db83-31dc-420d-b8dd-3dc53090e091)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/fe88afce-ac5d-428b-9dfc-c07b6ce57a2d)

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/dea983c3-fae4-44db-b4c0-48edaaa9b06d)
### IF input uppercase letters follow "内緒のいちゃらぶ ～年下少女は本音を伝えたい!  jan"
"WRPKN" will occurs and other letters may not
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/77df7174-9e04-4c6c-9e42-80fe23cda7dd)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/270f466f-a80e-4d65-bb4e-c20ddac21ad6)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/c0fc43fd-8564-4d15-bf88-e5ca30c15e68)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/1757b9a1-8f93-497c-a788-b80940e7dca3)

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/31aeb10f-c782-42f3-be4b-a0454dc82ebd)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/705d4e81-5fc3-4873-8520-51221dfee49e)
,and others string not 

###if input uppercase letter over three it would become normal
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/c4a392a2-9663-466f-918b-f3f029f81927)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/bd0e2271-3b03-4d29-9c44-d40ede944c66)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/add4c787-4c46-4474-a3f0-a727c96fd335)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/114719186/4797c0f6-65ca-4169-a11d-dc99b8bda0c6)
 

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

Already added screenshots in  description

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

Maybe it is fixable ？It would not occur in the vast majority of cases, and it would have minimal impact on the user experience, so even if it doesn't get fixed, I guess it doesn't matter. // I can't even think of how I triggered this bug.

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统 win11 22h2 Pro version 
- 浏览器 Chrome 
- 浏览器版本 121.0.6167.161（Offical-build） （64 bit）
- 脚本管理器 Tampermonkey beta version 
- 脚本管理器版本 v5.0.6192
- 所用的脚本名称  字体渲染（自用脚本）
- 所用的脚本版本   2024.02.03.1
- 其他补充信息：
   none

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

 uBlock Origin

- 是否同时运行了其他第三方用户脚本？

none

**Comment by F9y4ng** [comment]
在 #42 中搜索www.google.com

**Comment by Rnreck** [comment]
Thanks
