### ISSUE TITLE
[新增功能] 非常好的插件，如果能将设置项迁移下那更好不过了！

### ISSUE THREAD

**Issue by sundaqiang** [F9y4ng/GreasyFork-Scripts#31]
**您的功能请求是否与问题有关？请描述。** （清晰简明地描述遇到的问题是什么)
并不是都需要游猴之类的插件来启用此类脚本的。比如adGuard电脑版。这样就会无法设置选项了！

**描述您想要的解决方案** （清晰简明地描述您想要发生的事情）
能否考虑将设置项添加到baidu，google之类的页面上？

**描述你考虑过的替代方案**  （清晰简洁地描述您所考虑的任何替代解决方案或功能）
https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97
这个脚本就是把设置项做在页面上，这样可以轻松的使用非游猴之类插件的设置

**附加信息或屏幕截图**  （在此处添加任何附加信息或屏幕截图）

**Comment by F9y4ng** [comment]
1. 网页上的显示空间是很宝贵的，如果所有三方脚本都要争夺那点方寸之地，最后的解决必然是两败俱伤呀。所以，附加更多的设置按钮到页面上这事应该不会轻易去做。

2. adGuard电脑版的用户应该是小众用户，如果仅仅是需要可操作菜单项目，我倒是有个想法：**增加键盘快捷键的方式来帮助没有菜单的用户**

3. 这个快捷键的功能应该会在未来的版本上更新，应该不会太久。

**Comment by F9y4ng** [comment]
[Version 4.0.20211120.2](https://github.com/F9y4ng/GreasyFork-Scripts/blob/master/Google%20%26%20Baidu%20Switcher.user.js) 已增加了**键盘快捷键**的触发机制，可升级后使用。

> 脚本菜单项新增了键盘快捷键(Alt+字母)操作脚本菜单的配置项。`New`
> * 功能设置开关 → `Alt+E` / `Command+E`
> * 开启/关闭 Bing 搜索跳转 → `Alt+B` / `Command+B`
> * 从服务器实时检查/重新开启版本更新 → `Alt+V` / `Command+V`
> ##### 防止多次触发，键盘快捷键每次点击之间有不同时间的间隔要求，多次快速触发快捷键将被忽略。

**Comment by sundaqiang** [comment]
> 

感谢！！！
