### ISSUE TITLE
[发现错误]  自定义等宽字体后，代码块会被设置 text-shadow

### ISSUE THREAD

**Issue by cuiko** [F9y4ng/GreasyFork-Scripts#310]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
关闭了**字体阴影尺寸**后，代码块仍然设置了 `text-shadow`，导致代码块内字体显示效果就好像加粗了

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
设置了**自定义英文等宽字体**，例如：`CaskaydiaCove Nerd Font Propo`
即使关闭了字体阴影尺寸，代码块仍然会设置 `text-shadow`

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
未手动关闭 `text-shadow`
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/33982919/83067315-1bad-4267-96e8-c7957ec3acf8)
---
手动关闭 `text-shadow`
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/33982919/aeaabf45-7d31-4f91-a629-9debabd6065b)
---
设置
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/33982919/4b7ed2f7-6c2c-4020-a414-d12015754b7a)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/33982919/04586d56-5716-49f7-bee5-6d7f6b18f71e)
---
相关 css
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/33982919/558df74e-f231-44bd-ba28-a2874395afa1)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/33982919/3e7dc6b9-db41-42d8-8811-aa2bd11d040f)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
代码块不设置 `text-shadow`

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：MacOS
- 浏览器：Arc
- 浏览器版本：121.0.6167.184
- 脚本管理器：Tampermonkey
- 脚本管理器版本：5.0.1
- 所用的脚本名称：Font Rendering (Customized)
- 所用的脚本版本：2024.02.03.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

无相关扩展

- 是否同时运行了其他第三方用户脚本？

无

**Comment by F9y4ng** [comment]
在渲染等宽字体时，使用了Blink内核对text-shadow的一个hack方法，即`text-shadow: 0 0 0 currentcolor;`。以上CSS样式在语法直译上应该不会显示任何阴影效果，在实际浏览器解析中却渲染出阴影效果，这个效果比0.1像素的阴影更锐利一些。但，不同的Blink内核浏览器，如chrome,edge,以及你提到的arc浏览器会有不同的渲染效果。这个效果在低分屏1080P及以下分辨率差异不是特别明显，但在高分屏且应用了缩放后会出现一些视觉差异。

比如，我本地低分屏测试机chrome的效果明显会比你的arc要好，虽然它们都是相同内核：（建议点开看大图）

![test](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/3116284a-6223-49a0-ade9-1947e2213588)

**Comment by cuiko** [comment]
噢，感谢解惑！

**Comment by Parsifa1** [comment]
想请问一下这个有什么解决方法么 我可以用什么特殊方法手动关闭text-shadow么

**Comment by Parsifa1** [comment]
我现在是暂时修改了源代码，希望作者能提供一个选项
![image](https://github.com/user-attachments/assets/01783de1-321a-41c3-89c2-a59f389fd0d6)

**Comment by F9y4ng** [comment]
> 想请问一下这个有什么解决方法么 我可以用什么特殊方法手动关闭text-shadow么

正如我在上面的提到的，`text-shadow: 0 0 0 currentcolor;`是一个CSS hack，该样式在所有内核的浏览器中都呈现内部阴影，使得文字字重增加，效果比stroke更平滑。由于绝大部分英文等宽字体的字体较细，所以强制应用该CSS Hack。

此外，建议使用最新版本的主流官方浏览器。
