### ISSUE TITLE
[发现错误] 2023.10.03以后的版本无法和bilibili旧播放页脚本一起使用

### ISSUE THREAD

**Issue by CocoaTakasaki** [F9y4ng/GreasyFork-Scripts#312]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
**2023.10.03以后的版本和bilibili旧播放页脚本一起使用时无法正常替换字体和渲染，打开控制台后提示“站点CSP策略阻止警告:
当前站点CSP阻止内部样式的加载与解析，可尝试通过“Disable-CSP”扩展获取相应权限。”但安装并打开Disable-CSP后仍然没有效果，重装2023.10.03版本可以正常渲染

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
1、
2、
3、

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![脚本新](https://github.com/F9y4ng/GreasyFork-Scripts/assets/158039229/7bb32d4e-e1ed-4e08-8f06-635e4ebc59a7)
如图，这是使用新版脚本，打开Disable-CSP后的渲染效果
![脚本旧](https://github.com/F9y4ng/GreasyFork-Scripts/assets/158039229/b473fc16-7e75-4d0f-85fd-f7dd82022f26)
如图，这是使用2023.10.03版本，也不打开Disable-CSP后的渲染效果

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
使用新版脚本也可以正常和bilibili旧播放页脚本一起使用

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：windows11 23h2
- 浏览器：Edge
- 浏览器版本：121.0.2277.128 (正式版本) (64 位)
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.0.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.02.03.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

Disable-CSP

- 是否同时运行了其他第三方用户脚本？

bilibili旧播放页，链接如下：https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5

## 8. 附加信息（在此处添加您认为有用的其他信息）
浏览器本身的字体设置中也已经改成了自定义字体

**Comment by F9y4ng** [comment]
抱歉，不会主动兼容第三方脚本，尤其是这些疯狂重写原生函数的。请选择其他同类脚本使用吧。
