### ISSUE TITLE
[发现错误] 优雅的搜索引擎助手，「去除链接重定向跳转」与「谷歌图片」页面冲突

### ISSUE THREAD

**Issue by Thomas-Harrell** [F9y4ng/GreasyFork-Scripts#314]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

- 开启「优雅的搜索引擎助手」的「去除链接重定向跳转」后，在「谷歌图片」页面点击图片，图片变成在新标签页打开

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

- 开启「优雅的搜索引擎助手」的「去除链接重定向跳转」

- 谷歌图片：https://www.google.com/search?q=google&gl=us&udm=2

- 点击任意图片

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

- 现在的效果
<img width="1499" alt="SCR-20240223-qyry" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/106761803/308caa8f-da16-40e2-9ced-d08a96faf123">

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

- 原先的效果
<img width="1908" alt="SCR-20240223-qyou" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/106761803/dd3a38e8-32e5-4915-a3d7-50eb3e13d1ad">

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：macOS
- 浏览器：Chrome
- 浏览器版本：121.0.6167.184
- 脚本管理器：Violentmonkey BETA
- 脚本管理器版本：2.17.1
- 所用的脚本名称：优雅的搜索引擎助手
- 所用的脚本版本：V2024.02.12.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 已关闭其他扩展

- 是否同时运行了其他第三方用户脚本？

- 已关闭其他脚本

**Comment by F9y4ng** [comment]
我本地不能浮现你遇到的这个问题，建议你升级一下Chrome和MacOS到最新版本后再试试。

![PIC_2024-02-23_19-55-18](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/e049279a-d25c-4f32-a9e9-d76ba78a15b3)

**Comment by F9y4ng** [comment]
> @F9y4ng
> 
> 开发者你好
> 
> 我发现了一些遗漏的地方
> 
> 这个问题是在登陆「谷歌账号」后才会出现的
> 
> 我 Chrome 现在已经更新到最新了

在我本地登录后也是正常的。

![PIC_2024-02-24_13-19-30](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/610e11d2-3c75-4f1e-9788-033766f23ab7)

**Comment by F9y4ng** [comment]
在最近的几个版本更新中，都没有对「去除链接重定向跳转」的相关功能有过任何改动，所以如果你之前使用上没有问题，而是突然出现此状况，建议你考虑一下是否是其他扩展、脚本、或浏览器、MacOS的更新有关，可能需要你逐一去排查一下本地环境的原因。

当然不排除是Google又给出了新的A/B Test的情况，这种情况下只有我的账户也被列入内测后才能看到。

**Comment by F9y4ng** [comment]
果然，Google在不同浏览器，不同操作系统，不同版本下放了新的A/B Test，你遇到的问题，我已经在本地复现出来了。

预计下个更新中会修复这个Bug，感谢反馈。

**Comment by F9y4ng** [comment]
请更新至新版本v2024.03.02.1即可。
