### ISSUE TITLE
[发现错误] Bing

### ISSUE THREAD

**Issue by qhq** [F9y4ng/GreasyFork-Scripts#315]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![PixPin_2024-03-01_15-14-02](https://github.com/F9y4ng/GreasyFork-Scripts/assets/3319385/84a45e2a-47f3-4a6f-bd57-dc9d3565d21a)

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：
- 浏览器：
- 浏览器版本：
- 脚本管理器：
- 脚本管理器版本：
- 所用的脚本名称：
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
这是cn.bing.com搞的A/B Test，效果极其渣，清除浏览器缓存后刷新就会恢复原始样式。

BTW. cn.bing.com越来越难用，如果条件允许，还是直接使用www.bing.com。
