### ISSUE TITLE
[发现错误] 查看GitHub代码页存在严重虚影

### ISSUE THREAD

**Issue by 971230** [F9y4ng/GreasyFork-Scripts#316]
## 1. 准备工作（确认预先完成的操作）

- ✅ 我确认正在使用的是当前脚本的最新版本。
- ✅ 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- ✅ 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
就是在查看GitHub项目中的代码，字体会严重虚影，只在GitHub中出现

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
下载本插件，使用【苹方-简】字体，字体描边尺寸开0.1000，字体阴影尺寸开0.75，粗体修正，其余都是默认，访问任意GitHub项目的代码查看页

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
<img width="1020" alt="issue" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/37500200/53c8749c-6d16-483c-9d5e-63b63ec0de40">
<img width="412" alt="PixPin_2024-03-03_12-03-33" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/37500200/789234c4-647f-4760-9013-ef018158bf61">

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
定位该问题，尝试解决，懒得烦亦可

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：
- 浏览器：
- 浏览器版本：
- 脚本管理器：
- 脚本管理器版本：
- 所用的脚本名称：
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

无，仅开启本脚本，无任何扩展和其他脚本也有该问题

- 是否同时运行了其他第三方用户脚本？

无

## 8. 附加信息（在此处添加您认为有用的其他信息）
字体电脑有安装MacType软件

**Comment by F9y4ng** [comment]
Duplicate of #42

**Comment by 971230** [comment]
感谢回复💖
