### ISSUE TITLE
在https://www.reddit.com/用会导致网页卡或出错，关闭就没有问题。

### ISSUE THREAD

**Issue by szrock66** [F9y4ng/GreasyFork-Scripts#317]
## 1. 准备工作（确认预先完成的操作）

- [ ] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：
- 浏览器：
- 浏览器版本：
- 脚本管理器：
- 脚本管理器版本：
- 所用的脚本名称：
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
取消勾选**粗体修正**，保存为站点独享数据。
