### ISSUE TITLE
[发现错误] NGA 标题字号错误

### ISSUE THREAD

**Issue by WntFlm** [F9y4ng/GreasyFork-Scripts#319]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
打开脚本后，NGA 帖子标题的 h1 标签字号错误。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
  1. 开启脚本
  2. 打开 [NGA 论坛](https://bbs.nga.cn/) 任意帖子
  3. 帖子 `<h1>` 标题字号被错误的覆盖为 user agent stylesheet 设定的 `2em`
  4. 关闭脚本，刷新界面，标签正常显示

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
* 脚本设置
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/34620278/7ebaf249-c9f7-491f-8505-57183b101396)
* 错误的标题字号 [示例帖子](https://bbs.nga.cn/read.php?tid=32349645)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/34620278/a0981d03-3452-4237-b12e-bb0a52b3584e)
* 此时浏览器渲染规则
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/34620278/61303be4-516e-4a4f-abc2-66342e9941e7)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
* 关闭脚本后正常的标题字号
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/34620278/2aa5d24e-b6e8-44bb-bf8a-770f08d5dd00)
* 关闭脚本后正常的渲染规则
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/34620278/1cf20655-dff4-405c-bcae-19c52071d13c)

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win11
- 浏览器：Chrome
- 浏览器版本：122.0.6261.96
- 脚本管理器：Tampermonkey 
- 脚本管理器版本：v5.0.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.03.02.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
  * uBlock Origin

- 是否同时运行了其他第三方用户脚本？
  * 无

## 8. 附加信息（在此处添加您认为有用的其他信息）
* 脚本设定
[FontRendering-backup-chrome-2024-03-08T07-44-39Z.sqlitedb.zip](https://github.com/F9y4ng/GreasyFork-Scripts/files/14531381/FontRendering-backup-chrome-2024-03-08T07-44-39Z.sqlitedb.zip)

**Comment by F9y4ng** [comment]
无法复现你遇到的问题，请检查你本地其他脚本或扩展造成的样式冲突。

![test](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/e6930cc5-9f9c-407b-b06d-6cd33d294a29)

**Comment by F9y4ng** [comment]
取消勾选**粗体修正** 或 将字体描边设置为0（OFF），可以解决你遇到的问题。

**Comment by F9y4ng** [comment]
更新至v2024.04.06.1后，重新打开**粗体修正**功能，访问 https://bbs.nga.cn/read.php?tid=32349645&lazyload=true 即可。

注意：清除浏览器所有缓存(包含：Cookies及其他网站数据)，会导致以上站点设置失效，需重新访问以上链接，或在URL上自行添加`&lazyload=true`，访问一次即可。

**Comment by F9y4ng** [comment]
更新至v2024.07.06.1后，可重新打开粗体修正功能，并**启用修正延迟加载**，保存为站点独享数据。
