### ISSUE TITLE
duckduckgo

### ISSUE THREAD

**Issue by GuShaocheng** [F9y4ng/GreasyFork-Scripts#32]
能否新增duckduckgo搜索?或者可以自定义某个搜索引擎?这将极大丰富本插件的功能. 望采纳

**Comment by F9y4ng** [comment]
之前也有用户提出过此类需求，我先讲讲我的考虑:

1. 搜索按钮不宜添加太多，毕竟按钮的空间很有限，目前的两个基本已经是极限了，太宽很容易造成其他的问题。
2. 必须要考虑的是美观问题，一排跳转，不如只给有限的跳转。
3. 曾经也考虑过提供多个搜索引擎，供用户选择其中两个作为跳转搜索引擎使用，但由于我实在是……太懒了，就一直拖着。😓
4. 如果你有好的想法，可以提供给我，如果我能安排出更多时间，我会考虑附加复杂的新功能。

**Comment by GuShaocheng** [comment]
第三点挺好的,如能任选两三个就好了. 若有时间望考虑添加此功能

**Comment by F9y4ng** [comment]
> 第三点挺好的,如能任选两三个就好了. 若有时间望考虑添加此功能

新版本 V2022.08.04.2 已实现该功能，请升级体验。
