### ISSUE TITLE
[发现错误] 小米云服务加载不了脚本导致页面卡死

### ISSUE THREAD

**Issue by g1fts** [F9y4ng/GreasyFork-Scripts#322]
## 1. 准备工作（确认预先完成的操作）

- [ ] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
https://i.mi.com/#/
小米云服务加载不了脚本导致页面卡死

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：
- 浏览器：
- 浏览器版本：
- 脚本管理器：
- 脚本管理器版本：
- 所用的脚本名称：
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
无法复现问题，我本地可正常打开页面，无卡顿卡死的情况。

如需继续处理问题，请完整填写你的本地信息以及排查本地冲突的问题（确认：**我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。**）。

**Comment by g1fts** [comment]
小米笔记截图
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/20061353/56fd493f-b031-412a-a2c0-9365bb49c056)
扩展截图
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/20061353/1ac3ca48-d1ca-447b-b154-dc9eccbabbb7)
脚本加载截图
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/20061353/c5cdb793-ef02-473d-b041-ffa27003c8d5)

**Comment by F9y4ng** [comment]
依然无法复现，检查你本地的扩展或脚本冲突，如动图：

![screenshot_2024-03-17_17-01-21](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/bbfd3a7e-f810-4976-8b3b-1a75e15808bf)

**Comment by F9y4ng** [comment]
折腾了半天，终于复现了，问题出在粗体修正与编辑器本身产生冲突。

## 解决办法
在没有出现卡顿的页面上，打开设置界面，取消勾选**粗体修正**后，保存为站点独享数据即可。

**Comment by F9y4ng** [comment]
下个月更新我会优化一下回调冲突检查的方法，或许会自动规避掉大部分冲突的问题。

**Comment by F9y4ng** [comment]
更新至v2024.04.06.1后，可重新打开**粗体修正**功能。
