### ISSUE TITLE
[发现错误] wikipedia 编辑页字体重影

### ISSUE THREAD

**Issue by o-liverkk** [F9y4ng/GreasyFork-Scripts#323]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
编辑页字体重影

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

1. 以 https://zh.wikipedia.org/w/index.php?title=SpaceX%E7%AC%AC%E4%B8%89%E6%AC%A1%E6%98%9F%E8%89%A6%E8%BB%8C%E9%81%93%E8%A9%A6%E9%A3%9B%E4%BB%BB%E5%8B%99&veaction=editsource 为例，编辑区域的文字重影。
2. 我对wikipedia的编辑工具不熟悉，维基百科有许多编辑方式和工具，此错误只有在登录账号且在使用源代码编辑时出现。注意，不登录账号进入的编辑页面是 https://zh.wikipedia.org/wiki/SpaceX%E7%AC%AC%E4%B8%89%E6%AC%A1%E6%98%9F%E8%89%A6%E8%BB%8C%E9%81%93%E8%A9%A6%E9%A3%9B%E4%BB%BB%E5%8B%99?action=edit&veswitched=1 ；不选择“源代码编辑”即“可视化编辑”的情况下，均显示正常。
3. 已开启自定义等宽字体

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/65083224/dff1693c-8a81-495d-85db-fa3dc1257f26)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
字体显示正常

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win11
- 浏览器：Chrome
- 浏览器版本：122.0.6261.129
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.0.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.03.02.1
- 其他补充信息：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

无

- 是否同时运行了其他第三方用户脚本？

无

## 8. 附加信息（在此处添加您认为有用的其他信息）
附上网页的源代码 https://gist.github.com/o-liverkk/2324a792311774db5c4f19d0a36de598

**Comment by F9y4ng** [comment]
没有账户登录来实时的找到关键节点，所以只能尝试以下是否生效？

在**排除渲染的HTML标签**中，追加`,mw-body-content *`，保存为站点独享数据。

**Comment by F9y4ng** [comment]
终于进入编辑页面了，但我并没有复现你遇到的问题，我猜想大概是你使用的自定义字体的原因。比如，在Blink内核浏览器下，微软雅黑字体在描边开启时会出现渲染错误。建议你更换另外一个字体再试试。

![screenshot_2024-03-20_19-48-52](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/0a08a317-1969-486b-b294-595e38ab81ee)
