### ISSUE TITLE
[发现错误] GitHub Issues 等界面搜索框字体变为有衬线字体

### ISSUE THREAD

**Issue by YunfangHou** [F9y4ng/GreasyFork-Scripts#326]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
GitHub Issues、Pull requests 等界面搜索框字体，以及提交 Issue 界面的 title 输入框字体，变为了有衬线字体。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
开启脚本即可复现，关闭脚本即可恢复。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
<img width="725" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/53991651/ac01c9f9-9f3a-41c5-a7ab-be0bd01ab0a7">
<img width="511" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/53991651/2bdb5b71-f571-4891-ace6-90b4cd16bd84">

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
恢复为无衬线字体。

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：macOS Ventura
- 浏览器：Firefox
- 浏览器版本：124.0.1 (64-bit)
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.1.0
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.03.02.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

其他扩展已关闭

- 是否同时运行了其他第三方用户脚本？

其他脚本已关闭

**Comment by F9y4ng** [comment]
这个问题只会出现在Firefox上，而且是有意为之；其他Blink、WebKit内核浏览器没有此问题。

因为Firefox在处理input标签时存在一些已知的问题，即不同字体由于字宽的不同，会在没有定义width的input标签上出现撑开表格的问题造成页面样式错误。所以，在Firefox上应用了字体替换功能后，自动将input的字体样式强制定义为initial，以解决其后遗症及与其他功能相互干扰的问题。
