### ISSUE TITLE
[发现错误] Emoji 渲染错位、偏移

### ISSUE THREAD

**Issue by YunfangHou** [F9y4ng/GreasyFork-Scripts#328]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
开启脚本后，所有的 emoji 符号均错位。此处错位不是指在文字中的位置变了，而是渲染为了另一个 emoji，比如「😀」会被渲染为「😬」。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
开启脚本即可复现，关闭即可恢复正常。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
以 [emojipedia](https://emojipedia.org/smileys) 为例。
<img width="1821" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/53991651/dce082e8-d85f-495e-a600-215948e3b635">
<img width="1786" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/53991651/1b391e88-fb5b-4a65-aacd-6028d663bbb5">

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
恢复正常。是否可以不渲染 emoji，只渲染文字？

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：macOS Sonoma 14.4.1
- 浏览器：Firefox
- 浏览器版本：124.0.1 (64-bit)
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.1.0
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.03.02.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

## 8. 附加信息（在此处添加您认为有用的其他信息）
怀疑和 unicode 有关，但是不清楚具体原因。
如图，偏移量是一个定值 `0x2c`。
<img width="950" alt="image" src="https://github.com/F9y4ng/GreasyFork-Scripts/assets/53991651/b35ff69c-0f24-4a2c-b4fc-ca1a78a82722">

仅在 Firefox 上出现，在 Google Chrome 上正常。同时，我刚刚更新到 macOS Sonoma，此前在 macOS Ventura 时，则没有这个问题。

**Comment by F9y4ng** [comment]
该站点依然使用的是自定义字体图标集作为emoji font的fallback，所以当全局替换为第三方字体时，系统不存在的emoji或者沿用了第三方字体集设定的emoji font的fallback时就会出现你遇到的问题。

## 解决办法
在 **需要渲染的网页元素** 中，追加`:not([class*='__variable_'])`,保存为站点独享数据。
