### ISSUE TITLE
语雀开启脚本后图片内容会出现文字

### ISSUE THREAD

**Issue by MonoiF** [F9y4ng/GreasyFork-Scripts#329]
语雀开启渲染脚本后图片会在有文字的地方出现图示的重影问题：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/73887119/d72b4642-02e5-48f9-a24c-e5d48db08c53)
排除渲染脚本则显示正常
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/73887119/69393a69-3af3-467f-a4f1-d3ff02628669)

**Comment by F9y4ng** [comment]
Duplicate of #42
