### ISSUE TITLE
[发现错误] macOS占用快捷键

### ISSUE THREAD

**Issue by BlinVin** [F9y4ng/GreasyFork-Scripts#33]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
在网页内使用command+v组合键报错
**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![Snipaste_2021-11-22_16-14-06](https://user-images.githubusercontent.com/67635827/142827088-6cfc3638-27f4-45e5-9a4e-4307c4059038.jpg)

同时运行的插件和脚本
![Snipaste_2021-11-22_16-20-48](https://user-images.githubusercontent.com/67635827/142827017-e8611ccd-4f60-4218-b8e3-f638551956a8.jpg)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：MacOS 10.14.4
- 浏览器 [_如 Chrome_]：Chrome
- 版本 [_如 93.0.4577.63_]：版本 95.0.4638.69（正式版本） (x86_64)
- 脚本扩展 [_如 TamperMonkey_]：Tampermonkey
- 脚本扩展版本 [_如 4.13.6138_]：最新版本
- 运行的脚本名称 [_如 Font Rendering_]：搜索引擎跳转工具
- 运行的脚本版本 [_如 V3.8.20210101.1_]：4.0.20211120.2
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
Dark Reader

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
AC-baidu

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
应该是我疏忽了，MacOS下，`Command + V` 是粘贴的快捷键，你可以临时修改以下代码，第1439行
```javascript
      if (e.keyCode === 86 && ekey && checkUpdate) {
```
改为
```javascript
      if (e.keyCode === 74 && ekey && checkUpdate) {
```
对应的快捷键从`Command + V`改成`Command + J`，应该无冲突了。

下个版本更新，我会同步修改此bug，谢谢你的反馈。

**Comment by F9y4ng** [comment]
version 4.0.20211123.1 `@ 修正MacOS下Command+字母与浏览器快捷键冲突的问题。`

请及时更新。
