### ISSUE TITLE
FlowUs文件夹的文档页面 出现 字体重叠显示。填，div[class*='image']等 也不管用[发现错误] 

### ISSUE THREAD

**Issue by Bluemohb** [F9y4ng/GreasyFork-Scripts#332]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
Edge浏览器上打开 FlowUs的文件夹的文档页面，出现 字体重叠显示。填，div[class*='image']等 也不管用。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/121513988/92d175b2-bdfa-49e9-b6fc-ec7b7ef46cd2)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/121513988/d74e4782-0537-44f4-af89-72c51eaa118d)
![Clip_20240411_150543](https://github.com/F9y4ng/GreasyFork-Scripts/assets/121513988/ca2cbf74-c702-481e-bdf5-bba444d57155)

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：
- 浏览器：
- 浏览器版本：
- 脚本管理器：
- 脚本管理器版本：
- 所用的脚本名称：
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
为什么提问总是要挤牙膏呢？

1. 你觉得我能花多长时间猜出你访问的网址？
2. 这个网站访问是否需要登录账户？
3. 你能不能提供测试账户？
4. 你的浏览器是什么？
5. 你用的什么版本的脚本？
6. ……

推荐看看： https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by Bluemohb** [comment]
抱歉了以后我好好填。我填完整了。

操作系统：HP Development Company, L.P. - System - 7.0.22.3
浏览器：Edge
浏览器版本：123.0.2420.81 (正式版本) (64 位)
脚本管理器：Tampermonkey
脚本管理器版本：v5.1.0
所用的脚本名称：字体渲染（自用脚本）
所用的脚本版本：2024.04.06.1
出现问题的网站：https://flowus.cn/
需要登录账户
测试页面：https://flowus.cn/share/ad112fac-dc6b-4bdd-9156-d7d16728e4db?code=8C4ATF
【FlowUs 息流】土地利用总体规划实施评估方法研究_洪武扬.pdf
其他扩展：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/121513988/27128874-ed62-4c8d-be53-2956b83a64c0)
其他脚本：
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/121513988/4d0495f7-f0e5-40ff-8d7e-e6c5f51a9629)

**Comment by F9y4ng** [comment]
在 **排除渲染的HTML标签** 中，追加`,.textLayer *`，保存为站点独享数据。

**Comment by Bluemohb** [comment]
太感谢了！可以了！

**Comment by Bluemohb** [comment]
太感谢了！












寒兵
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月11日(周四) 晚上7:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [F9y4ng/GreasyFork-Scripts] FlowUs文件夹的文档页面 出现 字体重叠显示。填，div[class*='image']等 也不管用[发现错误]  (Issue #332)




 
在 排除渲染的HTML标签 中，追加,.textLayer *，保存为站点独享数据。
