### ISSUE TITLE
[发现错误] 在Jenkins页面上的字体替换失效

### ISSUE THREAD

**Issue by HRPF** [F9y4ng/GreasyFork-Scripts#333]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。
  - 不关闭其他扩展时，打开Jenkins页面后刷新一次才会失效；关闭其他扩展时，总是失效

## 2. 描述错误信息（清楚而简洁地描述错误）

字体替换失败，恢复为浏览器默认字体微软雅黑，且描边等均失效

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

1. 访问Jenkins前端页面，例如 [Gerrit-ci](https://gerrit-ci.gerritforge.com/) 
2. 观察页面字体

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

:( 不知道啥原因上传不了图片

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

不论在何时都能正确替换Jenkins页面字体

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win11 22H2
- 浏览器：Edge
- 浏览器版本：124.0.2478.67 (正式版本) (64 位)
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.1.0
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.04.06.1

- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

    - Adblock
    - Replace Google CDN
    - Deepl翻译

- 是否同时运行了其他第三方用户脚本？

    - CSDNGreener
    - 知乎增强
    - 注：在出问题的网页上仅启用了字体渲染（自用脚本）

## 8. 附加信息（在此处添加您认为有用的其他信息）

首次发现在内网部署的Jenkins上有该问题（且扩展设置窗口不正确显示，位于页面底部，纯文字，无任何样式），后尝试能通过互联网访问的Jenkins也有该问题（仅字体替换有问题）

**Comment by F9y4ng** [comment]
Everything works fine!

你可能需要提供截图来描述你遇到的问题，至少在我能看到的页面中，所有的文字渲染都是正常的。

![screenshot_2024-04-29_13-57-10](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/a3c96d34-0129-4f8f-a31e-ec73bb2f7b6f)
![screenshot_2024-04-29_13-57-45](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/d77ee609-f571-491e-a51b-e662c055292d)
