### ISSUE TITLE
[新增功能] 字体渲染脚本添加白名单功能

### ISSUE THREAD

**Issue by KonakaSigma** [F9y4ng/GreasyFork-Scripts#334]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）

白名单功能

由于目前只对某几个特定网址（目前只有B站）有渲染需求，所以希望加入此功能

（顺便问一句，为什么我从greasy fork上下载的脚本安装后语言为英文，系统为Arch Linux, 环境为中文，使用的浏览器是edge浏览器124.0.2478.67版本）

**Comment by F9y4ng** [comment]
Duplicate of #121 

## 快捷设置方法
打开 **[高级核心功能设置](https://github.com/F9y4ng/GreasyFork-Scripts/wiki/%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93%EF%BC%88%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC%EF%BC%89#%E9%AB%98%E7%BA%A7%E6%A0%B8%E5%BF%83%E5%8A%9F%E8%83%BD%E8%AE%BE%E7%BD%AE)**，下拉至最后，点击**关闭全局**按钮。

---

脚本语言选择跟随浏览器的语言设置，与操作系统无关。
