### ISSUE TITLE
访问 Grist 时字体渲染设置中的所有输入框都无法获取焦点

### ISSUE THREAD

**Issue by 1wingedangel** [F9y4ng/GreasyFork-Scripts#335]
问题站点：https://docs.getgrist.com/

打开这个demo站点之后，打开字体渲染设置，无论是`需要渲染的网页元素`还是`排除渲染的HTML标签`、点击无法获取焦点，也就无法修改。

**Comment by F9y4ng** [comment]
此类编辑工具型站点一般都会强制劫持所有表单元素（如input,textarea等）的所有的事件监听，并重写监听事件的处理机制。

如果通过脚本反向劫持势必会造成编辑工具原始的方法出错，而且修改的效果也是事倍功半。

所以，建议在此类工具型站点排除渲染，或通过其他同域页面进行参数修改。

**Comment by F9y4ng** [comment]
在下个月更新中会尝试修复这个问题，但需要在多个编辑型站点进行测试，以防止触发异常。

**Comment by F9y4ng** [comment]
> 感谢作者的反馈。
> 
> grist 这个域名中几乎所有的页面好像都被劫持不能触发，结果我随便输了一个URL打开了他的404页面，才能够正常输入后应用站点配置。

在任意模板页面，点击`Add New`选择`Add Empty Table`，弹出蒙层窗口后就可以进行参数配置了。

![screenshot_2024-05-05_21-23-46](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/77f8164e-35f1-4e00-9591-c8deeb51a491)


BTW. 脚本已经热修复该站点上的事件劫持问题，由于需要在更多同类站点上进行测试，所以这个修复将会随下个月更新一起发布。

**Comment by F9y4ng** [comment]
请更新至 v2024.06.01.1 即可。
