### ISSUE TITLE
[新增功能] 对已有功能的优化:允许添加单个搜索引擎框

### ISSUE THREAD

**Issue by Temparo** [F9y4ng/GreasyFork-Scripts#336]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
希望作者可以考虑添加一个搜索引擎框(两个搜索引擎)
可能是由于美观考虑,作者不提供添加单个搜索引擎框(两个搜索引擎)功能,但我认为可以只保留右侧部分,可以让搜索引擎保持比较美观
好像作者额外为不同搜索引擎做了不同的样式,修改工作比较繁杂,如果需要,我也可以提交PR来协助
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/164712201/668d6b4d-59b0-4400-9e79-f1bfaf4c10c9)

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/164712201/41b55df1-0a1e-403a-8690-d92159b180f2)
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/164712201/ef1d7ffa-4bf1-47ff-8809-d2f4a8fd7ea2)

**Comment by F9y4ng** [comment]
**优雅的搜索引擎助手**中搜索引擎之间的跳转仅仅是最基础的功能，脚本的主要功能是在其他高级功能的使用上。

你所提到的自定义新的跳转引擎的添加功能在很早之前就有用户提到过 #132 ，其中的难点并不是搜索引擎的添加及相应按钮的样式，而是其他高级功能的附加与调试，比如去广告、去重定向、搜索结果过滤等等大大小小多个功能点，这些并非一般用户能处理得了的；而且随着Manifest V3的应用，eval()等有风险的执行函数都将被限制使用。所以，为了避免不必要的麻烦，自定义添加新引擎的功能就不被支持了。

如果你仅需要可自定义跳转功能的脚本，目前已经有很多其他第三方脚本支持，比如[搜索酱](https://greasyfork.org/scripts/445274)等优秀的跳转脚本推荐你尝试使用。

**Comment by F9y4ng** [comment]
两个跳转按钮的设置也是多次调整后才确定的，单一按钮以及更多的按钮需求之前也有用户提到过，但过于个性化的设置并不符合该脚本的初衷。该脚本从诞生至今差不多更新快10年了，目前只求稳定，不求更多功能了。并且，同类脚本非常之多，没必要重复的造轮子。所以你的这个需求不被采纳，但感谢你的建议。
