### ISSUE TITLE
[发现错误] 火狐浏览器上显示的字体边缘破碎、失真、模糊、锯齿严重

### ISSUE THREAD

**Issue by S45618** [F9y4ng/GreasyFork-Scripts#339]
## 1. 准备工作（确认预先完成的操作）

- [ ✅] 我确认正在使用的是当前脚本的最新版本。
- [ ✅] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ✅] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

在火狐上渲染的字体模糊、破碎、笔画混在一起。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

火狐>油猴拓展>打开字体渲染

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![屏幕截图 2024-05-20 211457](https://github.com/F9y4ng/GreasyFork-Scripts/assets/170120833/e79acdf2-9a2e-4d89-8773-8f25aaaac365)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

应该圆润光滑的显示

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Windows 11（22631.3668）
- 浏览器：火狐
- 浏览器版本：126
- 脚本管理器：Tampermonkey
- 脚本管理器版本：5.1.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.05.04.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
浏览器字体的显示效果与太多的参数和环境因素有关，这也是为什么脚本设定了如此多的参数项目要进行设置，这也是脚本说明中反复强调的 `使用本项目不是使用AI程序，不是品尝神奇小饼干，需要一定的认知能力和动手能力……默认的字体渲染参数并不能完美适配于你的计算机。`。

你所提供的截图中出现字体渲染问题更多与字体本身有关，而非靠第三方参数可以修正的；如果不论如何调整参数都不能实现你想要的效果，建议你更换其他字体再试试。

最后，推荐你阅读一下 [如何正确地对不同显示器、浏览器设定字体渲染参数](https://github.com/F9y4ng/GreasyFork-Scripts/discussions/160) ，或许对你配置字体渲染参数有帮助。
