### ISSUE TITLE
设置了字阴影影后，点击预览有效果，保存刷新页面后丢失阴影效果。

### ISSUE THREAD

**Issue by caolist** [F9y4ng/GreasyFork-Scripts#34]
如题

**Comment by caolist** [comment]
刷新的一瞬间阴影还在，刷新完毕，阴影效果丢失。

**Comment by caolist** [comment]
但是字体描边效果正常

**Comment by F9y4ng** [comment]
反馈问题最好按照问题模板的格式来填写，就像这里你只说个结果，其他的一切靠我猜，我不是算命的，只能依靠数据解决问题，所以，请按Bug issues的反馈格式将必要的信息填写，我会尽快处理。

**Comment by caolist** [comment]
没有不敬的意思，我稍后按格式提一个issue，谢谢。
