### ISSUE TITLE
[发现错误] 优雅的搜索引擎助手去除重定向导致谷歌搜索翻页在新标签页打开

### ISSUE THREAD

**Issue by jdjxk** [F9y4ng/GreasyFork-Scripts#340]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
优雅的搜索引擎助手去除重定向导致谷歌搜索翻页在新标签页打开

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

  1. 去谷歌网址
  2. 搜索关键词
  3. 点击页码/下一页按钮
  4. 页码在新标签页打开

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
谷歌默认逻辑是在当前页面翻页

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win11
- 浏览器：Chromium
- 浏览器版本：125.0.6422.113
- 脚本管理器：Violentmonkey
- 脚本管理器版本：v2.19.0
- 所用的脚本名称：优雅的搜索引擎助手
- 所用的脚本版本：v2024.05.04.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

关闭其余扩展，问题复现

- 是否同时运行了其他第三方用户脚本？

关闭其余脚本，问题复现

**Comment by F9y4ng** [comment]
这应该是Google的A/B Test，我在本地也遇到过，你可以暂时清除浏览器缓存刷新重试。

BTW. 该问题已在下个月更新版本中修复。

**Comment by F9y4ng** [comment]
请更新至 v2024.06.01.1 即可。
