### ISSUE TITLE
[发现错误] 字体渲染脚本启用后，cubing.com网页上的日历组件不能点击

### ISSUE THREAD

**Issue by zhaobudaomingzi** [F9y4ng/GreasyFork-Scripts#341]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
字体渲染脚本启用后，[cubing.com网页](https://cubing.com/register/2)上“生日”的日历组件点击第一行的年月份选择没有反应

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
（1）打开[cubing.com网页](https://cubing.com/register/2)
（2）向下滚动到“生日”填写的位置
（3）点击填写框
（4）尝试点击弹出的日历组件的第一行按钮无反应

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![屏幕截图 2024-06-06 220919](https://github.com/F9y4ng/GreasyFork-Scripts/assets/54617500/9973e819-57e6-4481-a5ea-c67dff45488c)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
修复错误

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win10
- 浏览器：Chrome
- 浏览器版本：125.0.6422.142
- 脚本管理器：Tampermonkey
- 脚本管理器版本：5.1.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.06.01.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

关闭其余扩展，问题复现

- 是否同时运行了其他第三方用户脚本？

关闭其余扩展，问题复现

**Comment by F9y4ng** [comment]
不能复现问题，建议你排查一下本地的脚本冲突。

![screenshot_2024-06-06_22-27-32](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/d6aedabb-a3f0-40e8-9c0f-d099ae6a8374)

**Comment by F9y4ng** [comment]
打开**字体渲染设置**界面，取消勾选**粗体修正**，保存为站点独享数据。

该站点此日期插件与粗体修正功能有冲突，在此站点停用该功能后可以解决。
