### ISSUE TITLE
[新增功能] 能不能允许用户添加自定义搜索引擎

### ISSUE THREAD

**Issue by langzigyq** [F9y4ng/GreasyFork-Scripts#344]
经常用手势拖拽的方式搜索第三方网站内容，比如豆瓣、github、stackoverflow等等，
优雅搜索引擎助手可不可以实现让用户自由添加自定义搜索引擎。

豆瓣读书：https://search.douban.com/book/subject_search?search_text=%s&cat=1001
豆瓣电影：https://search.douban.com/movie/subject_search?search_text=%s&cat=1002
github：https://github.com/search?q=%s&type=repositories
stackoverflow：https://stackoverflow.com/search?q=%s

**Comment by F9y4ng** [comment]
Duplicate of #132

如果你想使用自定义搜索功能，推荐你使用[搜索酱](https://greasyfork.org/zh-CN/scripts/445274-searchjumper)脚本。
