### ISSUE TITLE
CSDN 公式渲染问题

### ISSUE THREAD

**Issue by ncwuguo** [F9y4ng/GreasyFork-Scripts#347]
测试网页: https://blog.csdn.net/Elenstone/article/details/105677886

CSDN的公式也会被自定义的字体渲染，怎么屏蔽掉，自定义的字体不适合显示公式

**Comment by F9y4ng** [comment]
在**需要渲染的网页元素**中，追加`:not(.katex *)`，保存为站点独享数据。
