### ISSUE TITLE
[发现错误]  该脚本导致微信公众号后台文章排版中，图片工具栏错位

### ISSUE THREAD

**Issue by FeiLZX3Km** [F9y4ng/GreasyFork-Scripts#348]
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/21981195/baf6dadc-8a06-4b13-b428-3116da2cad2c)

**Comment by F9y4ng** [comment]
不建议在工具编辑型网站（如编辑器页面），使用**字体比例缩放**这个实验性功能。

关闭**字体比例缩放**（设置为1）。

在此类工具编辑型网站，如需缩放，请使用浏览器缩放替代。
