### ISSUE TITLE
[发现错误] 搜索引擎助手错误：谷歌浏览器使用bing搜索时影响右侧功能区响应

### ISSUE THREAD

**Issue by Arwenleo** [F9y4ng/GreasyFork-Scripts#349]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
使用google浏览器时，我固定了bing、google和duckduckgo作为引擎切换选项，其中使用bing时如果我将页面放大至100%（并不需要确切是这个缩放程度，具体来说是放大至“账号信息和设置按钮”  与  “搜索框”成为两行显示的时候），右侧的功能区无法点击。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
在谷歌浏览器下使用bing搜索引擎时，下图1是缩放程度95%，图片右侧功能区和搜索框在同一行，右侧功能区可以响应，我无法在鼠标保持悬浮的时候完成截图，这里鼠标hover时会变成手型：
![屏幕截图 2024-06-22 013240](https://github.com/F9y4ng/GreasyFork-Scripts/assets/71969794/21c2b325-7824-4528-87f8-f98941eff536)

下图是缩放程度100%，图片右侧功能区和搜索框变成两行显示，此时右侧功能区不可以响应，点击头像或语言切换选项或者设置键无反应，鼠标hover时仍然是箭头：
![屏幕截图 2024-06-22 013424](https://github.com/F9y4ng/GreasyFork-Scripts/assets/71969794/1913a9cd-b884-4fe6-adb8-94e49fcc5bdb)

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
详见步骤三。

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
我在edge浏览器同样重复了步骤三，即使用bing搜索引擎，使用页面缩放使搜索设置与搜索框处于或不处于同一行，一切运行正常，期望达到此效果。

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Windows 11 专业版 23H2
- 浏览器：Chrome
- 浏览器版本：  126.0.6478.115（正式版本） 
- 脚本管理器：Tampermonkey 
- 脚本管理器版本：5.1.1
- 所用的脚本名称：优雅的搜索引擎助手
- 所用的脚本版本：2024.06.01.1
- 其他补充信息：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

已经关闭。

- 是否同时运行了其他第三方用户脚本？

已经全部禁用其他脚本。

**Comment by F9y4ng** [comment]
我猜测你应该使用的是笔记本吧。

由于屏幕尺寸、分辨率或缩放问题造成宽度不足而出现折行（Bing的样式自适应特性）。因nav导航栏元素层覆盖到右边的按钮，从而造成无法点击。

下个月更新中会处理这个问题，在折行后使得右边按钮恢复正常点击。

**Comment by Arwenleo** [comment]
是的，我是用笔记本的时候出现这个问题。大致理解了，感谢作者答复跟进。（好奇一下，这个问题不会在edge浏览器出现是因为它对必应有做更好的适配吗..?）

**Comment by F9y4ng** [comment]
会的，只不过在Edge上右上角按钮区或搜索框位置默认显示的内容会稍有不同，由于宽度未超出而没有折行。你可以按F12呼出控制台，人为的造成浏览器宽度减少的情况，这时候你会发现相同的情形。

**Comment by F9y4ng** [comment]
请更新至v2024.07.06.1.
