### ISSUE TITLE
[发现错误] 设置字体阴影效果没有变化

### ISSUE THREAD

**Issue by caolist** [F9y4ng/GreasyFork-Scripts#35]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
设置了字体阴影的大小和颜色，点击保存后，页面自动刷新，刷新的一瞬间出现了阴影效果，待页面刷新完毕后，阴影效果消失，但是字体描边的效果正常。

**错误再现**  （重现行为的步骤）

1. 访问任意网址
2. 点击油猴中的脚本界面，设置字体阴影参数和颜色，参数尽量调大
3. 点击保存后等待页面刷新
4. 刷新完毕后没有阴影效果

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
公司内不太方便上传图片

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：Win10
- 浏览器 [_如 Chrome_]：最新稳定版edge
- 版本 [_如 93.0.4577.63_]：最新版
- 脚本扩展 [_如 TamperMonkey_]：最新版
- 脚本扩展版本 [_如 4.13.6138_]：最新版
- 运行的脚本名称 [_如 Font Rendering_]：
- 运行的脚本版本 [_如 V3.8.20210101.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
没有使用页面效果类的扩展，我可以关闭所有扩展再试一次

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
关闭了其他所有油猴脚本

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by caolist** [comment]
关闭了所有扩展后，阴影效果出来了......
还不知道是哪个扩展和脚本冲突了，你可以先关闭issue了，我试出来告诉你。

**Comment by caolist** [comment]
找到了，是 Font Rendering Enhancer 这个扩展影响了脚本的阴影效果。

**Comment by F9y4ng** [comment]
你不能同时开着两个有关字体渲染的工具让他们内斗。尝试关闭其中一个再继续使用。
