### ISSUE TITLE
Add top search button request

### ISSUE THREAD

**Issue by Essayage** [F9y4ng/GreasyFork-Scripts#350]
Now many bloggers will choose to do video to explain the knowledge points rather than write easily plagiarized articles, these videos are published in the platform of the content is not easy to search for knowledge points in the search engine retrieval, resulting in the phenomenon that often have to be switched from the search engine to the video site to search for related content in the country is particularly serious. 
Hope that the top search button on the right side of the new optional  BILIBILI's search button to replace the Google search button!

**Comment by F9y4ng** [comment]
**Search Engine Assistant** only works for search engines, not individual sites. Please use other third-party userscripts.
