### ISSUE TITLE
[发现错误] Bing搜索结果重定向出错

### ISSUE THREAD

**Issue by B-22** [F9y4ng/GreasyFork-Scripts#352]
## 1. 准备工作
- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 错误描述
在 Bing 中搜索任意关键词时，搜索结果部分超链接重定向出现错误，变为 `https://www.bing.com/undefined`。
超链接上方的地址重定向正常。
这主要出现在第一个搜索结果，但其他位置搜索结果也出现过。（第一页中）
出现概率不稳定，可能是每星期有一天，出现后复现概率较高，但无法稳定复现。
关键词为~~有权重优化~~较容易出现，重定向出现错误的网站国内外均有。

## 3. 错误复现步骤
1. 在 Bing 中搜索任意关键词
2. 点击搜索结果中的超链接
3. 发现超链接重定向出现错误

## 4. 屏幕截图
![tmp868E](https://github.com/F9y4ng/GreasyFork-Scripts/assets/68846704/3849e1b2-ee73-48ec-8599-f7588205a67f)
![ff608670d93faba8ab0d1f7b38d4ca26](https://github.com/F9y4ng/GreasyFork-Scripts/assets/68846704/a887d904-c743-4c44-925e-c411770775d0)
![6d6afbacd7ad866fc9540818399a806e](https://github.com/F9y4ng/GreasyFork-Scripts/assets/68846704/3b100b44-4dcb-4399-ade2-af93b3aa646e)

## 5. 预期结果
重定向地址正常

## 6. 客户端信息
- 操作系统：Win10
- 浏览器：Edge
- 浏览器版本：126.0.2592.68 (正式版本) (64 位)
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.1.1
- 所用的脚本名称：优雅的搜索引擎助手
- 所用的脚本版本：2024.06.01.1
- 其他补充信息：使用代理，bing地区，在InPrivate中复现，已清除浏览器缓存

## 7. 脚本运行环境排查
- 是否同时运行了其他浏览器扩展？均已禁用，并重启浏览器
- 是否同时运行了其他第三方用户脚本？均已禁用，并重启浏览器

## 8. 附加信息
在 Chrome 中疑似正常。

**Comment by F9y4ng** [comment]
在我本地无法复现出这个问题。

你可以提供触发问题时你的本地环境么？比如代理所在国家、搜索关键词、你的Bing账户是否有其他的搜索设置等等。

从你目前的反馈来看像是遇到了Bing的灰度测试，只有进入A/B Test后会出现问题。但要想处理这样问题只能等我的账户也随缘进入A/B Test后才能处理了。

**Comment by B-22** [comment]
使用InPrivate，未登陆，无代理 

![bandicam 2024-06-25 17-10-54-336](https://github.com/F9y4ng/GreasyFork-Scripts/assets/68846704/64484a22-8bf7-460c-96ab-2bc1e7984b65)
确实很难复现，第一次点击标题，进入https://www.bing.com/undefined，第二点击上方黑色地址，重定向正常，网址正常

**Comment by B-22** [comment]
关键词：这确实是一个谷歌，重定向刷新后恢复正常，关闭代理后地区中国，语言中国

**Comment by F9y4ng** [comment]
隐私模式下依然无法复现你遇到的问题。

![screenshot_2024-06-25_17-34-35](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/4486d884-382a-457b-824e-cc2079d5c12f)

你可以访问以下链接 [https://cn.bing.com/search?q=这确实是一个谷歌&whoami=F9y4ng](https://cn.bing.com/search?q=%E8%BF%99%E7%A1%AE%E5%AE%9E%E6%98%AF%E4%B8%80%E4%B8%AA%E8%B0%B7%E6%AD%8C&whoami=F9y4ng)，按F12打开Edge的控制台，看看是否有报错信息，并找到其中链接为 `https://www.bing.com/undefined` 的节点。

**Comment by F9y4ng** [comment]
正常情况下，cn.bing.com的搜索结果链接是没有重定向链接的，只有全球版www.bing.com有重定向，或使用FF访问cn.bing.com时国际版有重定向。

在隐私模式下，www.bing.com的搜索结果链接也是正常的，如图：
![screenshot_2024-06-25_17-47-35](https://github.com/F9y4ng/GreasyFork-Scripts/assets/15855068/c4a2fb05-3e12-4274-9aff-426ea218f102)

你更换一个高速代理再试试看？

**Comment by F9y4ng** [comment]
@B-22 我已经找到问题所在了，这是Tampermonkey5.2.0及以下版本中存在的BUG，在隐私模式下5.1.1及5.2.0都存在这个问题，刷新页面后问题会消失。

## 建议
在TM5.3正式版本发布前，请使用TM v5.3.6202 BETA 或 Violentmonkey 替代。

**Comment by F9y4ng** [comment]
这个问题我会在下个月更新做临时修复，针对MsEdge隐私模式下www.bing.com的重定向链接获取undefined的问题。

**Comment by F9y4ng** [comment]
请更新至v2024.07.06.1.

**Comment by cjahv** [comment]
我使用的是2024.07.09.1在bing中发现还有该问题

重现步骤：
1. 使用国际bing搜索关键字
2. 点搜索后面的“搜索优化”
3. 这时候出现的搜索结果还有这个问题

提供一下我当时的链接
https://www.bing.com/search?q=CursorUlViewService%E5%8D%A1&qs=n&form=QBRE&sp=-1&ghc=1&lq=0&pq=cursorulviewservice%E5%8D%A1&sc=11-20&sk=&cvid=9D702569280842F79527E8A1AD38CC41&ghsh=0&ghacc=0&ghpl=

https://www.bing.com/search?q=CursorUlViewService%E5%8D%A1&shm=cr&form=DEEPSH&shmgid=A68DF4D423B2454F9DA41B08AB90EEBD&shajax=1

**Comment by F9y4ng** [comment]
@cjahv 应该不是每次都发生吧，在个别网络不是特别通畅的时候会有一定概率出现这个问题？我专门针对最近的网络延迟较大的情况更新过一次阈值。

## 临时解决
**注意：在TM，VM中直接修改代码会造成自动更新失效，下次更新需要手动点击更新按钮恢复。**

你尝试找到以下代码位置：

https://github.com/F9y4ng/GreasyFork-Scripts/blob/6c99f9b8513c6f80dd302e75dd5701a19e9305bc/Google%20%26%20Baidu%20Switcher.user.js#L2106

将其修改为
```js
   const observer = new MutationObserver(deBounce({ fn: getGlobalParameter, delay: 50, timer: "globalParameter", immed: true }));
```

如果测试没有问题，下次更新时我会将这个修正加入，感谢反馈。

**Comment by F9y4ng** [comment]
## 临时解决
**注意：在TM，VM中直接修改代码会造成自动更新失效，下次更新需要手动点击更新按钮恢复。**

你尝试找到以下代码位置：

https://github.com/F9y4ng/GreasyFork-Scripts/blob/6c99f9b8513c6f80dd302e75dd5701a19e9305bc/Google%20%26%20Baidu%20Switcher.user.js#L2097

将其修改为
```js
   const currentUrl = top.location.href.replace(/&shajax=\d/, "");
```

你测试一下，如果没有问题，下个更新中我会将这个修正加入。
