### ISSUE TITLE
使用阴影开启渲染的时候选定字体会有加粗字体的现象，但是我不确定这是否是刻意设计

### ISSUE THREAD

**Issue by jehovlo** [F9y4ng/GreasyFork-Scripts#354]
我选用的字体是自定义添加的 鸿蒙黑体light（HarmonyOS Sans SC Light），后来尝试了 微软雅黑light（Microsoft YaHei Light）
在大部分网站都会出现，选定字体，同一行的字体会加粗一点点，但是同一段的另一行的字体无变化，除非选定的部分涉及到了那一行。
当关闭字体阴影时，大部分网站的这一现象会消失。
但是少部分黑底白字的页面白字在关闭字体阴影后，被选定的一行也会加粗，即表现为亮度稍稍提高了部分（相对于未选定的行）。
我并不确定这是否算一个BUG，或许是作者刻意设计的。在使用中也并无不适，有时甚至算是一个优势，突出了我正在看的那一行。

最后我得说感谢作者，这个工具帮了大忙了，非常感谢！

**Comment by jehovlo** [comment]
补充一下情况出现时的详细设定，
字体是自定义添加的，鸿蒙黑体Light或者微软雅黑Light；
字体重写和字体平滑均开启；
字体比例缩放1.01
描边0.1；
阴影0.1；
阴影颜色#666666FF。

**Comment by F9y4ng** [comment]
Chromium在内核版本128+修复了这个问题，但FF问题依旧。

请关注下月新版本的发布。
