### ISSUE TITLE
[发现错误] GitHub代码展示有重影Bug

### ISSUE THREAD

**Issue by AkarinLiu** [F9y4ng/GreasyFork-Scripts#355]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
在查看GitHub源代码的时候，发现字体重影

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

1. 安装字体重影脚本
2. 启用脚本
3. 访问GitHub
4. 查看源代码
## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/58081491/e4345e72-ac8d-4f75-9a1e-b5d57b9aca4f)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
显示正常

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Windows 11
- 浏览器：Microsoft Edge
- 浏览器版本：126.0.2592.87 
- 脚本管理器：Tampermonkey
- 脚本管理器版本：5.1.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.06.01.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/58081491/8870a8ec-203f-4a2a-b5db-164cc8c2ea76)

- 是否同时运行了其他第三方用户脚本？

![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/58081491/57a2bec0-ec42-4ad8-9960-213d4d3eb92a)

**Comment by F9y4ng** [comment]
Duplicate of #266
