### ISSUE TITLE
与Cubox的网页直接标注功能冲突

### ISSUE THREAD

**Issue by hzwlux** [F9y4ng/GreasyFork-Scripts#356]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
Cubox的网页标注功能，与此插件冲突，二者同时启用，cubox直接在网页标注后，鼠标hover在标注处，无法再编辑（取消高亮等）

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

1. Cubox进行网页标注
2. 网页标注后，想直接在网页处编辑，失效

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/F9y4ng/GreasyFork-Scripts/assets/32216917/ff89c556-baa2-4293-a8a2-671131143407)

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win11
- 浏览器：Edge
- 浏览器版本：126.0.2592.87
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.1.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.07.06.1

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
Cubox

**Comment by F9y4ng** [comment]
打开脚本设置界面，取消勾选**粗体修正**功能，保存为全局数据（由于该扩展也对所有站点生效），个别独立站点数据需要单独设置再次保存数据。

P.S. 已经找到具体冲突的代码，但是否能够兼容修正，还需要测试在其他站点或扩展下是否存在修正后冲突的情况。如果测试没问题，那么会在下个月更新中，修复它。

**Comment by F9y4ng** [comment]
请更新至 v2024.08.03.1，即可恢复**粗体修正**功能。
