### ISSUE TITLE
[注意] Tampermonkey manifest v3 所有版本某些条件下存在 GM_getValue 的缓存问题，建议暂用 Tampermonkey Legacy v5.1.1 或 Violentmonkey 替代。

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [F9y4ng/GreasyFork-Scripts#357]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
排除渲染需要点两次才会生效。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
1. 访问 www.ithome.com
2. 打开菜单点击排除渲染；（自动刷新但无效）
3. 再次打开菜单点击排除渲染；（自动刷新后生效）
4. 恢复渲染操作也是一样，必须操作两次才生效。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![a](https://github.com/user-attachments/assets/1475ee8c-3121-43d3-9403-1ef0663a60ca)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
恢复原来点击一次就生效。

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：WIN 11
- 浏览器：CHROME
- 浏览器版本：126.0.6478.127
- 脚本管理器：Tampermonkey 
- 脚本管理器版本：5.2.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.07.06.1
- 其他补充信息：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

没有

- 是否同时运行了其他第三方用户脚本？

没有

**Comment by F9y4ng** [comment]
这是 Tampermonkey 在 manifest v3 所有版本上的一个Bug，我已经向TM反馈了该问题，需要等待TM修复它。

在TM修复完成前，建议使用 [Tampermonkey Legacy v5.1.1](https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn) 或 Violentmonkey 替代。

**Comment by Xia0xia0Xia0** [comment]
收到，感谢！暂时换VM用用了。

**Comment by F9y4ng** [comment]
请更新至 v2024.07.16.1，暂时在脚本层面修复了 `GM Value` 缓存更新不及时的问题。

**Comment by Xia0xia0Xia0** [comment]
> 请更新至 v2024.07.16.1，暂时在脚本层面修复了 `GM Value` 缓存更新不及时的问题。

太感谢了，确实OK了！

**Comment by Zzzzz-Haha** [comment]
Hello,请问您这是什么字体呀，很好看想换来用hhh

**Comment by F9y4ng** [comment]
> Hello,请问您这是什么字体呀，很好看想换来用hhh

目测是“屏显臻宋”。

**Comment by Xia0xia0Xia0** [comment]
> Hello,请问您这是什么字体呀，很好看想换来用hhh
@Zzzzz-Haha 

> > Hello,请问您这是什么字体呀，很好看想换来用hhh
> 
> 目测是“屏显臻宋”。
@F9y4ng 

猜对啦，就是**屏显臻宋**，`{"ch":"屏显臻宋","en":"Clear Han Serif","ps":"ClearlHanSerif"}`

**Comment by Zzzzz-Haha** [comment]
首先很感谢您回复，但是貌似字体名称不太对的上？
这是您的：![image](https://github.com/user-attachments/assets/1da207c5-53f4-4558-af08-e56a09c4d2da)
这是我更换「屏显臻宋」字体后的对比图：
![image](https://github.com/user-attachments/assets/596099db-63e5-4843-98ea-8506bbf770d0)
感觉这个「P」的字体对不上

**Comment by Xia0xia0Xia0** [comment]
> 首先很感谢您回复，但是貌似字体名称不太对的上？ 

应该是这个 `{"ch":"仓耳今楷01","en":"TsangerJinKai01","ps":"TsangerJinKai01-W03"}`

你到 #46 去下载吧。

**Comment by Zzzzz-Haha** [comment]
Ohh感谢感谢哈哈哈~~
