### ISSUE TITLE
[新增功能] 字体阴影的颜色使用字体的颜色

### ISSUE THREAD

**Issue by lucas-57blocks** [F9y4ng/GreasyFork-Scripts#36]
**您的功能请求是否与问题有关？请描述。** （清晰简明地描述遇到的问题是什么)
字体阴影的颜色是固定的，在显示非黑色字体的时候看起来很怪异。

**描述您想要的解决方案** （清晰简明地描述您想要发生的事情）
使用字体的显示颜色作为阴影颜色。

**描述你考虑过的替代方案**  （清晰简洁地描述您所考虑的任何替代解决方案或功能）

**附加信息或屏幕截图**  （在此处添加任何附加信息或屏幕截图）
这里红色和绿色的数字的显示看起来就不是很舒服。
![image](https://user-images.githubusercontent.com/62318708/142997666-8abc251b-3700-4976-9b13-f33057738c1c.png)

**Comment by F9y4ng** [comment]
你可以将颜色选择器的滑动到左上角，即#FFFFFF，就可以调用currencolor的值，也就是你说的“**字体的显示颜色**”。

**Comment by lucas-57blocks** [comment]
Very nice, thanks.
