### ISSUE TITLE
[发现错误] B站弹幕看不清

### ISSUE THREAD

**Issue by Trudeau566** [F9y4ng/GreasyFork-Scripts#360]
已添加:not(.bili-dm,.bili-dm *)
edge，chrome都不行，Brave浏览器却可以

edge
![PixPin_2024-07-17_16-50-27](https://github.com/user-attachments/assets/2e51cf61-9ebb-40c8-98fe-6c49118c6125)

Brave
![PixPin_2024-07-17_16-49-54](https://github.com/user-attachments/assets/20b6985d-c6f7-46c8-af85-482319959b46)

**Comment by F9y4ng** [comment]
因为哔哩哔哩的弹幕样式名称总是改来改去的，还酷爱折腾灰测。

将原来的`:not(.bili-dm,.bili-dm *)` 改为 `:not(.bili-dm,.bili-dm *,.bili-danmaku-x-dm,.bili-danmaku-x-dm *)`，重新保存为站点独享数据。

该规则已更新至 #42
