### ISSUE TITLE
[发现错误] github浏览脚本页面脚本字体阴影影响阅读

### ISSUE THREAD

**Issue by wingswing1** [F9y4ng/GreasyFork-Scripts#361]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
github浏览脚本页面脚本字体阴影影响阅读

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
见附图
![屏幕截图 2024-07-20 170245](https://github.com/user-attachments/assets/8edfe2ba-ba22-444c-91ae-f40b73809b10)
## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：win11
- 浏览器：360极速浏览器
- 浏览器版本：122.0.6261.95
- 脚本管理器：Tampermonkey
- 脚本管理器版本：5.1.1
- 所用的脚本名称：字体渲染（自用脚本）默认设置
- 所用的脚本版本：2024.07.16.1
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
Duplicate of #266
