### ISSUE TITLE
[发现错误] 脚本和b站的字幕设置冲突,比如描边方式

### ISSUE THREAD

**Issue by Han1eing** [F9y4ng/GreasyFork-Scripts#363]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
关闭字体渲染脚本.b站的字幕描边设置调整和显示都是正常的,打开后,字幕描边消失,且调整脚本的描边设置,b站的字幕也不会被生效渲染

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
见第二项错误信息描述

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![屏幕截图(12)](https://github.com/user-attachments/assets/059e25e5-3b77-43a0-bc98-9b9379925195)
![屏幕截图(13)](https://github.com/user-attachments/assets/fa6278f1-9646-4cf1-be83-1d8177f952e0)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
解决冲突,使b站字幕能够描边以提升浅色视频背景下的可见度

**Comment by F9y4ng** [comment]
Duplicate of #42.

**Comment by Han1eing** [comment]
是视频里上传的CC字幕,不是弹幕,况且添加了弹幕排除依旧是有问题的
![Uploading 屏幕截图(14).png…]()

**Comment by Han1eing** [comment]
![屏幕截图(14)](https://github.com/user-attachments/assets/1a2432bb-a955-4505-8a65-23d947df05f9)

**Comment by Han1eing** [comment]
@F9y4ng

**Comment by F9y4ng** [comment]
哔哩哔哩的视频CC字幕本身就是背景颜色设置，字母颜色设置，看不清就自己设置一下。

另外，bilibili的CC字幕字体设置是有问题的（竟然是空值），这是脚本层面上无法解决的。
