### ISSUE TITLE
[发现错误] 【字体渲染】学信网的学信档案的学籍信息无法正常显示。

### ISSUE THREAD

**Issue by HumanMus1c** [F9y4ng/GreasyFork-Scripts#364]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
学信网的学信档案的学籍信息无法正常显示，所有文字信息显示为"□□□"。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
启用该脚本的情况下打开学校档案页面，学籍信息文字均显示为□。

  1. _去学信网网址 "my.chsi.com.cn"_
  2. _单击c查看学籍信息 "my.chsi.com.cn/archive/gdjy"_
  3. _遇到错误或问题 "..."_

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/user-attachments/assets/01c526ff-376f-4eab-a29c-d7fbd0d9e4a2)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
一切正常

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Windows 11 专业版
- 浏览器：Egde 
- 浏览器版本：127.0.2651.74 (正式版本) (64 位)
- 脚本管理器：Tampermonkey 
- 脚本管理器版本：v5.2.3
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：v2024.07.16.1
- 其他补充信息：
- 
![image](https://github.com/user-attachments/assets/7d2d1321-060f-4d84-8837-c164a1b2bff7)

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

![image](https://github.com/user-attachments/assets/98230674-731b-4bab-b1e1-9d55b3a5e12e)

- 是否同时运行了其他第三方用户脚本？

![image](https://github.com/user-attachments/assets/77954119-bb08-4f4c-8170-6233f4116235)

**Comment by F9y4ng** [comment]
在 **需要渲染的网页元素** 中，追加 `:not(.chsi-font *)`，保存为站点独享数据。
