### ISSUE TITLE
b站弹幕渲染问题

### ISSUE THREAD

**Issue by Ba-YH** [F9y4ng/GreasyFork-Scripts#365]
## 1. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
         使用字体渲染脚本在观看B站时，在白底背景的视频中弹幕几乎和背景色重合，调整描边和阴影也会显的很怪。是否能解决这个问题，或者如何屏蔽掉弹幕字体渲染呢。

**Comment by F9y4ng** [comment]
Duplicate of #42

**Comment by Ba-YH** [comment]
反馈很及时👍👍 顺便把github重叠的问题也解决了，现在对我来说已经完美了，给个star
