### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by Mingyu2333** [F9y4ng/GreasyFork-Scripts#366]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
无法滑动选中评论区文字（无法多换选中，超出本行范围即失效）
详细见图片

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
1.打开b站
2.打开任意视频
3.翻到评论区
4.滑动选中

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![recording](https://github.com/user-attachments/assets/3c212b78-d08a-4d1c-9fd6-bac93f5b3967)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
可以正常多行选中，效果同视频简介

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：win11
- 浏览器：firefox
- 浏览器版本：129.0.2
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.1.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.08.03.1
- 其他补充信息：在Chromium内核浏览器上没有问题，仅在Gecko内核上发现问题如：firefox、floorp浏览器

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

关闭其他所有拓展及脚本后仍然出现

- 是否同时运行了其他第三方用户脚本？

关闭其他所有拓展及脚本后仍然出现

**Comment by F9y4ng** [comment]
这是Firefox的特有的选取bug，至少有仅几十个版本没有修复了。以FF的性格，基本上在等个几年应该也是可能的。

**Comment by F9y4ng** [comment]
1 FF在伪元素样式 `：：selection` 中的 `-webkit-text-stroke` 属性是无效的，这是FF一直遗留的问题，至今未修复。
2 FF的选取中断问题（尤其是在ShadowRoot中问题更甚），这个BUG一直未修复。
3 除选取中断外，还存在选取后无法取消的问题，造成被选取文本一直保持选取状态无法清除，这个BUG也一直未修复。

所以字体渲染脚本针对FF的问题特意更改了默认的选取样式，但无法完全修复所有的问题，如问题2，3。
