### ISSUE TITLE
[发现错误] bookfusion 无法渲染正文

### ISSUE THREAD

**Issue by XU-Nuo** [F9y4ng/GreasyFork-Scripts#369]
## 1. 准备工作

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息
无法渲染 bookfusion 的在线 epub 阅读器内的正文字体, 可能和自带字体功能冲突

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
打开任意一本 上传到 bookfusion 的 epub 书籍, 发现正文无法渲染, 示例: https://reader.bookfusion.com/books/4819271-how-linux-works?type=epub_reflowable

## 4. 屏幕截图

![image](https://github.com/user-attachments/assets/f7cb6ab9-8576-47f6-8979-ba9da38d486d)

## 5. 预期结果
正文字体也被插件字体覆盖

## 6. 客户端信息
- 操作系统：Windows 11
- 浏览器： Edge

## 7. 脚本运行环境排查
- 是否同时运行了其他浏览器扩展？
无

- 是否同时运行了其他第三方用户脚本？
无

**Comment by F9y4ng** [comment]
该网站需要账户才可访问，请提供测试账号。

**Comment by XU-Nuo** [comment]
换了一本可以公开访问的书: https://reader.bookfusion.com/books/2790370-the-big-four?type=epub

**Comment by F9y4ng** [comment]
已经捕获到未渲染的问题，并且可以修复，但这样的情况下字体完全替换会造成以下问题：

1. 原本的阅读器字体更换功能将失效；（因被样式覆盖替换）
2. 由于阅读器本身的宽度限制，使用某些字宽较大的字体会造成文本超出的问题。如图：
![test](https://github.com/user-attachments/assets/d5eeb83a-7a95-4139-a5d5-4f0e055743fe)
（也就是说需要找到字宽相同的字体使用才能避免此问题。）

`iframe.srcdoc 未渲染的问题` 会在本次月更新中修复。

**Comment by XU-Nuo** [comment]
感谢修复! 阅读器自带的字体切换对中文无效, 所以问题不大, 英文我用插件载入的就是bookerly, 原本阅读器也自带这个字体, 宽度应该是一致的

**Comment by F9y4ng** [comment]
请及时更新至 v2024.09.07.1
