### ISSUE TITLE
开启字体平滑后，某些网页显示有问题！

### ISSUE THREAD

**Issue by Easonnnone** [F9y4ng/GreasyFork-Scripts#37]
开启字体平滑后，打开“IT之家”，此时页面上的时间就会显示错位（如图所示）
<img width="1867" alt="Snipaste_2021-11-30_21-40-33" src="https://user-images.githubusercontent.com/8055993/144058533-794898ce-275f-46c4-9d60-fef5981886a5.png">

关闭字体平滑后就恢复了正常
<img width="1867" alt="Snipaste_2021-11-30_21-46-54" src="https://user-images.githubusercontent.com/8055993/144058788-102dcf4e-9d2d-4d68-8bc4-4c910107f77b.png">

有什么解决办法么，既能平滑又不会错位呢？

**Comment by F9y4ng** [comment]
记得你反馈过类似的issues #11 ,请更新至最新版 V2021.12.01.1 ，此版本有修正平滑渲染的问题。

**Comment by Easonnnone** [comment]
谢谢大佬
