### ISSUE TITLE
[新增功能] 默认字体列表增添思源黑体、思源宋体系列的另一个ps名称

### ISSUE THREAD

**Issue by 7890qwaszx** [F9y4ng/GreasyFork-Scripts#370]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）

思源黑体在Github上的Adobe仓库中名称Source Han Sans，但如果从fonts.google.com中单独搜索字体并下载，下载下来的字体名Noto Sans SC，思源宋体同理，Noto Serif SC。

在部分支持中文语言的Linux发行版中，默认字体集通常安装Noto Fonts CJK，例如[arch软件仓库](https://archlinux.org/packages/extra/any/noto-fonts-cjk/)，又例如[Fedora软件仓库](https://packages.fedoraproject.org/pkgs/google-noto-sans-cjk-fonts/google-noto-sans-cjk-fonts/)此时思源黑体的名字可能为Noto Sans CJK SC，思源宋体可能为Noto Serif CJK SC。

希望在默认的字体列表中能够增加这两种ps名称。

```
{"ch":"思源黑体Noto","en":"Noto Sans SC","ps":"Noto Sans SC"}
{"ch":"思源宋体Noto","en":"Noto Serif SC","ps":"Noto Serif SC"}
{"ch":"思源黑体Noto CJK","en":"Noto Sans CJK SC","ps":"Noto Sans CJK SC"}
{"ch":"思源宋体Noto CJK","en":"Noto Serif CJK SC","ps":"Noto Serif CJK SC"}
```

**Comment by F9y4ng** [comment]
可以根据需要自行添加至自定义字体表。
