### ISSUE TITLE
[发现错误] 2024.09.07.1版本，渲染overleaf页面时，pdf预览部分显示异常

### ISSUE THREAD

**Issue by typeyang** [F9y4ng/GreasyFork-Scripts#373]
![屏幕截图 2024-09-11 154938](https://github.com/user-attachments/assets/a990eaa8-7b7c-4cb4-b81c-e8ddd76d4db4)

**Comment by F9y4ng** [comment]
与 #372 的问题相同，部分PDF文档采用了修改版的字体，字体替换换后出现乱码问题。 这与某些小说网站防抓取而采取的字体修改方法雷同。

暂时在该站点排除渲染来解决乱码问题吧。

**Comment by F9y4ng** [comment]
请更新至 v2024.09.11.1 ，在脚本设置界面取消勾选 **画布渲染**，保存为站点独享数据即可。

![not render](https://github.com/user-attachments/assets/9143dd76-8b21-41c0-aeb5-b54da7fc5805)

**Comment by weavers1f** [comment]
同款错误，又找到答案了
