### ISSUE TITLE
[发现错误] 2024.09.07.1版本关闭渲染某一个页面无效，依然会渲染。

### ISSUE THREAD

**Issue by fu7100** [F9y4ng/GreasyFork-Scripts#374]
![图片](https://github.com/user-attachments/assets/f811cf27-d883-49bd-a0f4-4b9e3dd45692)

web版vscode的terminal终端中的字体，m，@等字符会出现重叠，其他有些字符间距忽大忽小，关闭渲染该页面后无效，只有关闭这个插件才恢复正常显示。

**Comment by F9y4ng** [comment]
1. 不建议在工具型网站使用字体替换功能，不同字体的字宽与自高的不同会造成各种无法修复的问题。

2. 排除渲染不生效，你需要按ISSUES模板提供本地信息。

**Comment by F9y4ng** [comment]
你可以尝试打开自定义等宽字体功能，并添加相应的节点过滤规则。

我不确定这样做是否能解决你遇到的问题。

**Comment by F9y4ng** [comment]
测试后发现与 #373 是同样的问题，都是Canvas字体渲染造成的新问题。

看来需要在中秋节前后发布一个紧急修复版本啦。😅

**Comment by F9y4ng** [comment]
请更新至 v2024.09.11.1 ，在脚本设置界面取消勾选 **画布渲染**，保存为站点独享数据即可。

![not render](https://github.com/user-attachments/assets/9143dd76-8b21-41c0-aeb5-b54da7fc5805)

**Comment by fu7100** [comment]
ok，问题解决，感谢！
