### ISSUE TITLE
[发现错误] Firefox 添加自定义字体无效

### ISSUE THREAD

**Issue by cxw620** [F9y4ng/GreasyFork-Scripts#375]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

如题, 已确定本地字体安装到位:

![图片](https://github.com/user-attachments/assets/6f41977e-62ac-448b-89b6-230203c4b0ec)

添加字体:

```
{"ch":"霞鹜文楷 GB 屏幕阅读版","en":"LXGW WenKai GB Screen","ps":"LXGWWenKaiGBScreen"}
```

刷新字体缓存或重启浏览器后仍然看不到可选. 甚至连自带的 "霞鹜文楷" 也没有

![图片](https://github.com/user-attachments/assets/1edb4126-7e9c-4176-abe1-671ded43ef4a)

手动修改 CSS 可见字体是存在的:

![图片](https://github.com/user-attachments/assets/4b6230ef-afdc-46f1-a241-685c1ba62c1e)

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

-

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

-

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）

-

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Windows 11 专业工作站版 24H2 26100.1742 Windows Feature Experience Pack 1000.26100.18.0
- 浏览器：Firefox
- 浏览器版本：131.0 (20240923135042)
- 脚本管理器：Tampermonkey
- 脚本管理器版本：v5.1.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.09.11.1
- 其他补充信息：

已完全重置插件

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

Dark Reader, 沉浸式翻译

已测试全部关闭其他插件.

- 是否同时运行了其他第三方用户脚本？

无

## 8. 附加信息（在此处添加您认为有用的其他信息）

-

**Comment by F9y4ng** [comment]
从截图上看，大概是隐私模式，或关闭浏览器指纹检测造成的问题，请按照 #160 中综述部分Firefox相关操作检查你本地Firefox浏览器的设置数据。
