### ISSUE TITLE
备份后的文件名超长

### ISSUE THREAD

**Issue by perthun** [F9y4ng/GreasyFork-Scripts#377]
我使用的是 Firefox + Violentmonkey，并通过 webdav 备份到坚果云。
将坚果云的文件同步到本地目录后，我发现这个脚本的文件名是 vm@2-https-3a-2f-2fopenuserjs.org-2fscripts-2ff9y4ng-2fGoogle_baidu_Switcher_(ALL_in_One)-0aGoogle-20&-20baidu-20Switcher-20(ALL-20in-20One)-0a
长的出乎意料，其他软件同步时报错了。
有些奇怪，为什么文件名会这么长，足有 140+个字符
![图片](https://github.com/user-attachments/assets/c55ed5d9-b4c0-43d3-9229-fa7c7c4dedfa)

**Comment by F9y4ng** [comment]
这个备份操作不是脚本触发的，为什么要问我呢？你应该去问VM才对呀。
