### ISSUE TITLE
感觉在Safari上已经无解了。

### ISSUE THREAD

**Issue by Easonnnone** [F9y4ng/GreasyFork-Scripts#38]
更新到1201版本，Safari上还是无解的存在。Edge上是正常了。
<img width="1968" alt="image" src="https://user-images.githubusercontent.com/8055993/144179225-d9cba668-c3cf-4939-859b-4d0d9dd8fe3c.png">

**Comment by F9y4ng** [comment]
还是之前的答案，那是你更换了网站的默认字体才会造成这个问题。这也是为什么网站会使用自己定义的字体，而非浏览器默认的。因为每个网站都会针对它定义的字体而优化页面容器的宽度和高度，你通过三方脚本变更了原字体，由于新字体的宽度、高度和网站原来定义的字体不同，必定会造成某些异常。所以，解决你遇到的这样的问题，只能是**通过关闭字体重写来关闭字体替换功能，使用网站原有字体** 或者 **更换一个不会出现超出容器尺寸的字体**。

**Comment by Easonnnone** [comment]
这坑货网站

**Comment by F9y4ng** [comment]
> 这坑货网站

这种情况的发生也和你使用的操作系统和浏览器有关系，同样的网站，在Windows系统下，使用chrome、firefox更换多种字体很少会出现超出容器的问题。你可以使用Chrome for Mac 试试看是否还有此问题。

**Comment by Easonnnone** [comment]
测试了一下Microsoft Edge，打开了重写与平滑，没有此问题（如图所示）
<img width="1954" alt="image" src="https://user-images.githubusercontent.com/8055993/144180576-28a64250-8935-44c4-a814-b5490ea37e68.png">

**Comment by Easonnnone** [comment]
Safari我就把平滑关了吧，这样就OK了

还是非常感谢大佬解答了。

**Comment by F9y4ng** [comment]
推荐你参考 [这个方法 #40](https://github.com/F9y4ng/GreasyFork-Scripts/issues/40#issuecomment-985253690) 试一试，可能会有效果。
