### ISSUE TITLE
[发现错误] 深色外观的Bing搜索结果链接显示不明显

### ISSUE THREAD

**Issue by iaston** [F9y4ng/GreasyFork-Scripts#381]
可能脚本主要考虑的是浅色主题的显示，在深色主题下，链接显示还是深蓝色，不容易看清楚。
![QQ20241017-153601](https://github.com/user-attachments/assets/3ce3ddab-acfb-4688-9d5b-6f26dc495a50)

**Comment by F9y4ng** [comment]
脚本代码是跟随浏览器的外观渲染设置而变化的，使用网站的强制样式并不会激活脚本的外观检测机制。

如要使脚本外观检测自动判定生效，需要将你截图当前设置为 “系统默认值”，通过 **直接更改浏览器的外观设定** 或 **设置浏览器外观随系统外观设置变化**，即可使脚本外观检测生效（Bing的外观模式切换需要手动刷新）。

（如下图）

![dark](https://github.com/user-attachments/assets/23cf1914-67f7-421d-831e-f23dbaac1ba0)

**Comment by F9y4ng** [comment]
补充说明：浏览器外观设置功能在Chrome下存在缓存问题，而其他Chromium浏览器功能正常，如Edge, Brave等。

**Comment by iaston** [comment]
好的，用系统默认+系统暗主题，确实可用
