### ISSUE TITLE
[发现错误] uad.getHighEntropyValues会造成 Violentmonkey 在document-start 加载脚本出现延迟

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [F9y4ng/GreasyFork-Scripts#383]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
我在https://github.com/violentmonkey/violentmonkey/issues/2213 中报告了脚本加载延迟的问题，经过分析得出是uad.getHighEntropyValues这个方法会造成VM在document-start加载脚本时出现延迟，我尝试注释掉`// const vmuad = voucher.startsWith("Violentmonkey") && GMinfo.platform ? await getVMUserAgentData(GMinfo.platform) : null;`使得脚本可以快速加载。 与 @tophf 讨论了一些相关的内容，看看您能否解决这个问题，十分感谢。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）

使用VM2.26.0，打开`同步 page 模式`， 访问greasyfork.org，点击任意链接，页面样式加载延迟。
注释掉语句后，恢复正常。

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
无

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统： win 11
- 浏览器： chrome
- 浏览器版本： 130
- 脚本管理器： violentmonkey
- 脚本管理器版本： 2.26.0
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：2024.10.05.1
- 其他补充信息：无

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

无

- 是否同时运行了其他第三方用户脚本？

无

**Comment by F9y4ng** [comment]
嗯，这确实存在延迟问题，如果不考虑完美的情况下，可以放弃`GM_info.userAgentData.getHighEntropyValues()`，而只使用`GM_info.platform`和`GM_info.userAgentData`来解决加载延迟的问题。

我先在本地测试一下，如果能完美处理那最好，如果不行，就退而求其次，优先解决加载延迟的问题。

**Comment by Xia0xia0Xia0** [comment]
感谢，https://github.com/violentmonkey/violentmonkey/issues/2213#issuecomment-2435163556 这个办法可供参考，我觉得可以和版本号比较并行处理增加有效率。

**Comment by F9y4ng** [comment]
这个问题会在下个月更新中修正，并可以完美解决。

**Comment by F9y4ng** [comment]
请更新至 2024.11.02.1
