### ISSUE TITLE
[发现错误] 最近更新导致英文字体渲染异常，之前没有该问题

### ISSUE THREAD

**Issue by ssc777** [F9y4ng/GreasyFork-Scripts#384]
https://www.uptodate.com/
uptodate数据库文本显示异常，更换很多字体均无法解决，本截图为脚本默认设置：
![bug](https://github.com/user-attachments/assets/bc918c9e-7b59-4490-a607-af98b4e9a6ab)

异常文本无法于chrome内检索，经复制粘贴到文本文档发现，渲染页面为乱码文本
停用脚本后文本可以正常显示

**Comment by ssc777** [comment]
操作系统： windows 10 LTSC
浏览器： chrome
浏览器版本： 130.0.6723.91 (Official Build) (64-bit)
脚本管理器： Tampermonkey
脚本管理器版本： 5.3.2
所用的脚本名称：字体渲染（自用脚本）
所用的脚本版本：2024.10.05.1
其他补充信息：无

**Comment by ssc777** [comment]
是否同时运行了其他浏览器扩展？
无，运行环境没有修改

是否同时运行了其他第三方用户脚本？
无，一直只用这一个脚本，之前一直很好用，除了reddit那边要取消打勾，默认设置可以完美兼容各种页面

**Comment by ssc777** [comment]
您这边需要测试我可以给您提供登录账号密码，方便调试页面，辛苦！

**Comment by F9y4ng** [comment]
最好能提供一下具体的URL，以及详细的操作步骤，如果需要登录才能访问到请提供测试账号。

https://www.uptodate.com/ 国内会跳转到 https://www.uptodate.cn/home ，国外会跳转到https://www.wolterskluwer.com/en

**Comment by ssc777** [comment]
https://www.uptodate.com/contents/immunizations-in-patients-with-inborn-errors-of-immunity?search=Common+variable+immunodeficiency+live+vaccine&source=search_result&selectedTitle=1%7E150&usage_type=default&display_rank=1

账号我这边邮箱发您可以？

**Comment by F9y4ng** [comment]
是在编辑状态下出现的问题吗？

可以发到`f9y4ng(#)gmail.com`

**Comment by ssc777** [comment]
编辑状态是指？
账号刚发您了，请查收

**Comment by F9y4ng** [comment]
大部分文献站点、小说站点都会有类似的操作，防止爬虫或人为拷贝。

之前没有遇到可能是站点未启用该功能或者是你的账户触发了某种规则而使得站点启用了字符替换功能等等，可以确定的是网站防拷贝规则的原因，而非脚本造成的问题。即使排除脚本渲染，你复制到的字符串依然是混合了unicode字符的。

**Comment by ssc777** [comment]
我遇到的问题不是要把文本粘贴出来用
而是没办法F3检索关键词，乱码的单词无法被浏览器正常识别
这个情况关闭脚本就正常了
如果我需要粘贴文本可以不开脚本的，现在是开脚本影响F3检索内容

**Comment by ssc777** [comment]
为了检索反复开启关闭渲染脚本，也是非常影响体验的操作，会比较折腾

**Comment by F9y4ng** [comment]
我关闭脚本渲染依然得到的是混合有unicode字符的单词，你可以试试看，搜索它 “immսոοԁеfiϲiеոcу”

![screenshot_2024-10-30_23-37-50](https://github.com/user-attachments/assets/ab33fa29-f5e6-423b-9bf2-a3d53c9b5311)

**Comment by F9y4ng** [comment]
`immսոοԁеfiϲiеոcу` 和 `immunodeficiency`

**Comment by ssc777** [comment]
用Incognito反复测试了一下，还真是您讲这样
眼睛被字符的形态欺骗了，看起来文本没问题，但确实是插入了unicode的单词
应该是Wolters Kluwer他们公司又花香蕉的钱请猴子做网页了
打扰您了，抱歉
