### ISSUE TITLE
[发现错误] 导致一些招标网站内嵌的pdf显示乱码

### ISSUE THREAD

**Issue by FLYSONG9902** [F9y4ng/GreasyFork-Scripts#385]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
全国招投标公共服务平台发布的内嵌pdf显示乱码，禁用脚本就正常，期待改进

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
可打开网站 https://ctbpsp.com/#/bulletinDetail?uuid=64087313-9f17-4fd0-b9e4-0cddf6df8246&inpvalue=%E5%8D%97%E4%BA%AC%20%E7%9B%91%E6%8E%A7&dataSource=1&tenderAgency= 复现问题

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win11.26100.2152
- 浏览器：Catsxp浏览器
- 浏览器版本：版本 4.10.3 Kernel: 130.0.6723.62（正式版本） （64 位）
- 脚本管理器：暴力猴
- 脚本管理器版本：2.27.0
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本： 2024.10.05.1 版本
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

有安装uBlock Origin，但无关

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
Duplicate of #373
