### ISSUE TITLE
[发现错误] 青柠起始页二级菜单显示的默认图标变暗

### ISSUE THREAD

**Issue by Acetab** [F9y4ng/GreasyFork-Scripts#386]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
青柠起始页二级菜单显示的**默认图标**变暗，取消当前扩展后（取消当前页面渲染）图标颜色回复正常。如图，前两行的图标为网站自带。第三行的虎牙和斗鱼图标为自行添加。

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
打开青柠起始页https://limestart.cn/
右键页面显示二级菜单

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![1](https://github.com/user-attachments/assets/2ef72984-c836-4b42-8c36-e60050366559)
![2](https://github.com/user-attachments/assets/1f04246e-d7c7-405c-a8e4-a61834a06c9f)

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win11
- 浏览器： Edge
- 浏览器版本：130.0.2849.56 (正式版本) (64 位)
- 脚本管理器：Tampermonkey 
- 脚本管理器版本： 5.1.1
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

AdGuard

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
脚本中没有任何相关样式会影响文本字体以外的元素样式，我也不能复现你所提到的问题，如下图，有区别么？

**未开启字体渲染脚本：**
![screenshot_2024-10-31_14-07-39](https://github.com/user-attachments/assets/360c7f79-dcda-4118-8e38-5e64fdc70d20)

**已开启字体渲染脚本：**
![screenshot_2024-10-31_14-08-28](https://github.com/user-attachments/assets/c6eedbaf-df21-48d3-a308-299e5e3ece53)

**Comment by F9y4ng** [comment]
终于明白你要表达的意思了，是图标的颜色对吗？

在**排除渲染的HTML标签**中，追加`,i`,保存为站点独享。
