### ISSUE TITLE
[新增功能] Google 搜索下一页按钮样式错误

### ISSUE THREAD

**Issue by huanfe1** [F9y4ng/GreasyFork-Scripts#387]
## 1. 准备工作（确认预先完成的操作）

- [X] 我确认使用的是当前脚本的最新版本。
- [X] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）

Google 搜索底部下一页按钮样式错误，网上也有 [解决方案](https://chromewebstore.google.com/detail/%E8%AE%A9google%E6%90%9C%E7%B4%A2%E4%B8%8B%E4%B8%80%E9%A1%B5%E6%8C%89%E9%92%AE%E7%9C%8B%E8%B5%B7%E6%9D%A5%E8%88%92%E6%9C%8D%E4%B8%80%E4%BA%9B/lgjloiegnpcgjgmgoojdciknbpbhmmlf)，但感觉为一行样式安装一个插件有点笨重了

不知道能不能在优雅的搜索引擎助手里加上一行 css 样式

`#pnnext > span:nth-child(2) { clear: left; }`

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）

![image](https://lh3.googleusercontent.com/uRbG_R0FrN6t7afCGKdS8ELmydbfHJutaNiUZO-trK7VSNKlOqP7UBI9UjW3PvhWbl-VmHb4cZQkorXtg5PkDRWKUA=s1280-w1280-h800)

**Comment by F9y4ng** [comment]
没问题，下个更新中会加入它。
注意：只有选中Google作为常用引擎时样式才会生效。

**Comment by F9y4ng** [comment]
请更新至 2024.11.02.1
