### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by FRAOTIAC** [F9y4ng/GreasyFork-Scripts#39]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
出现乱码字符

**错误再现**  （重现行为的步骤）

1. _[tv](https://developer.android.com/tv/release/12)"_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
左侧出现类似乱码的字符

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

![image](https://user-images.githubusercontent.com/16257151/144363915-b85b4b25-fb07-4fe8-88a7-313268f23410.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_Window11_]：
- 浏览器 [_Chrome_]：
- 版本 [_如 2021.12.01.1_]：

**Comment by F9y4ng** [comment]
在 **需要渲染的网页元素** 中追加：

```:not(.devsite-nav-toggle:before)```

保存为站点独享，即可解决乱码问题。
