### ISSUE TITLE
[新增功能] ChatGPT搜索

### ISSUE THREAD

**Issue by fangyuan99** [F9y4ng/GreasyFork-Scripts#391]
希望新增ChatGPT搜索选项，目前我只能自己把搜狗的简单替换:

https://chatgpt.com/?hints=search&ref=ext&temporary-chat=true&q=

**Comment by F9y4ng** [comment]
**优雅的搜索引擎助手** 目前只针对搜索引擎站点提供跳转服务，如果需要其他站点或自定义需求，推荐你考虑使用“[搜索酱](https://greasyfork.org/scripts/445274)”脚本来使用。
