### ISSUE TITLE
[发现错误] B站的动态页，往下滚轮，只能滚动刷新两到三次，就无法自动展开卡住了。排除渲染此页面，可以正常一直滚动下去

### ISSUE THREAD

**Issue by kNHiGUzq** [F9y4ng/GreasyFork-Scripts#394]
## 1. 准备工作（确认预先完成的操作）

- [ X] 我确认正在使用的是当前脚本的最新版本。
- [ X] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ X] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）

B站的动态页，往下滚轮，只能滚动刷新两到三次，就无法自动展开卡住了。排除渲染此页面，可以正常一直滚动下去

**Comment by F9y4ng** [comment]
请按 https://github.com/F9y4ng/GreasyFork-Scripts/discussions/267#discussioncomment-7161615 方法进行修正。
