### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by Ba-YH** [F9y4ng/GreasyFork-Scripts#395]
## 1. 准备工作（确认预先完成的操作）

- [ ] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
头歌实践平台的代码编辑器出现异常排版

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/user-attachments/assets/2653501f-f2ee-40db-aa33-6d3be9b7827f)

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：
- 浏览器：
- 浏览器版本：
- 脚本管理器：
- 脚本管理器版本：
- 所用的脚本名称：
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

uBlock Origin

- 是否同时运行了其他第三方用户脚本？

**Comment by Ba-YH** [comment]
力扣代码编译器也出现类似问题
![image](https://github.com/user-attachments/assets/06a6a671-852c-435a-9cd4-d82bff8cb5ab)

**Comment by F9y4ng** [comment]
我在使用说明中提到过，不建议在各种编辑型工具站点开启渲染，会造成各种各样的问题。

如果在关闭字体缩放、和开启自定义等宽字体后问题依然存在，请排除渲染该站点。
