### ISSUE TITLE
字体表数据格式错误

### ISSUE THREAD

**Issue by xiaolousir** [F9y4ng/GreasyFork-Scripts#398]
![123](https://github.com/user-attachments/assets/a08466df-c084-4945-a695-a9542f21f974)
添加字体
{"ch":"华康POP HandelGotD-Cxibei","en","POP HandelGotD-Cxibei","ps":"POPHandelGotDCxibei"}

**Comment by F9y4ng** [comment]
## 建议使用“字体添加辅助工具”来添加自定义字体
```JSON
{"ch":"华康POP HandelGotD-Cxibei","en":"POP HandelGotD-Cxibei","ps":"POPHandelGotDCxibei"}
```
