### ISSUE TITLE
[发现错误] 百度贴吧字体渲染无效果

### ISSUE THREAD

**Issue by xiaolousir** [F9y4ng/GreasyFork-Scripts#399]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
百度贴吧字体渲染没有效果

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）

![111](https://github.com/user-attachments/assets/e42fa076-a4ac-42ca-9e8a-7a6f9b08a8c0)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
贴吧字体渲染有效果

我使用Stylus的字体样式是有效果的

**Comment by F9y4ng** [comment]
不能复现问题，请按Bug report格式填写内容。

此外，新手用户先认真阅读[Wiki](https://github.com/F9y4ng/GreasyFork-Scripts/wiki)了解脚本使用方法后再提问。

**Comment by xiaolousir** [comment]
> 不能复现问题，请按Bug report格式填写内容。
> 
> 此外，新手用户先认真阅读[Wiki](https://github.com/F9y4ng/GreasyFork-Scripts/wiki)了解脚本使用方法后再提问。
// ==UserScript==
// @namespace   VA_i
// @version     4.2.0.20190901
// @grant       unsafeWindow
// @include     /^https?://(?:(?:c\.)?tieba\.baidu\.com|www\.tieba\.com|dq\.tieba\.com|jump2?\.bdimg\.com)//
// @run-at      document-start
// @name        Baidu Tieba: No Login
// @name:zh-CN  百度贴吧：不登录即可看贴
// @name:zh-TW  百度贴吧：不登入即可看貼
// @description View Baidu Tieba without login.
// @description:zh-CN 百度贴吧看贴（包括楼中楼）无须登录。
// @description:zh-TW 百度贴吧看貼（包括樓中樓）無須登入。
// ==/UserScript==

unsafeWindow.Object.freeze = null;

document.addEventListener('DOMContentLoaded', function (event) {
  try {
    unsafeWindow.PageData.user.is_login = 1;
  } catch (error) {
    //alert(error);
  }
}, true);

这个脚本导致的 不知道是否能兼容下

**Comment by F9y4ng** [comment]
此类侵入性脚本无法兼容，二选一吧。

**Comment by xiaolousir** [comment]
> 此类侵入性脚本无法兼容，二选一吧。



> 此类侵入性脚本无法兼容，二选一吧。

好的
