### ISSUE TITLE
[发现错误] 起点中文网文字排版错误

### ISSUE THREAD

**Issue by scalpelx** [F9y4ng/GreasyFork-Scripts#40]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
起点中文网小说最新章节的更新时间排版错误，出现了换行，关闭字体重写后正常

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_https://book.qidian.com/info/1979049
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_最新章节
4. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
![微信截图_20211203001404](https://user-images.githubusercontent.com/12198804/144460038-a5f720ba-3530-402b-b1bb-102cb27dd218.png)

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![微信截图_20211203001424](https://user-images.githubusercontent.com/12198804/144460087-ccddd849-d3d8-4b57-9351-cfca21229419.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：Windows 11
- 浏览器 [_如 Chrome_]：Chrome
- 版本 [_如 93.0.4577.63_]：96.0.4664.45
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：
- 运行的脚本名称 [_如 Font Rendering_]：
- 运行的脚本版本 [_如 V3.8.20210101.1_]：
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
此类问题请参阅 [#11](https://github.com/F9y4ng/GreasyFork-Scripts/issues/11#issuecomment-880148509) 及 [#38](https://github.com/F9y4ng/GreasyFork-Scripts/issues/38#issuecomment-983313825)

**Comment by F9y4ng** [comment]
推荐一个变通的方法来使用新的中文字体渲染：

1. 打开自定义字体，添加`{"ch":"Arial","en":"Arial"}`至自定义字体表。
2. 然后在配置界面先选择Arial，再选择你想要渲染的中文字体。如此这样，英文/数字和中文就分别定义了。

这样，英文和数字就使用网站默认的字体，中文字体使用你定义的字体，就不会出现因字宽过大而换行的问题了。

**Comment by Easonnnone** [comment]
> 推荐一个变通的方法来使用新的中文字体渲染：
> 
> 1. 打开自定义字体，添加`{"ch":"Arial","en":"Arial"}`至自定义字体表。
> 2. 然后在配置界面先选择Arial，再选择你想要渲染的中文字体。如此这样，英文/数字和中文就分别定义了。
> 
> 这样，英文和数字就使用网站默认的字体，中文字体使用你定义的字体，就不会出现因字宽过大而换行的问题了。
> 
> **如图所示：**
> 
> ![qidian](https://user-images.githubusercontent.com/15855068/144556632-b90691b0-ea06-4516-b945-c4afbd996355.jpg)

好的，我来试试看，谢谢大佬的辛勤劳动。

**Comment by scalpelx** [comment]
> 

谢谢，我试试看
