### ISSUE TITLE
[发现错误] Github Copilot窗口开启“自定义等宽字体”后仍有重影

### ISSUE THREAD

**Issue by Zxis233** [F9y4ng/GreasyFork-Scripts#403]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [ ] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
选择字体时出现重影，显示字体被替换为自定义字体，但重影为等宽字体

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
  1. 开启GitHub Copilot窗口
  2. 任意输入英文字符

## 4. 屏幕截图（如有屏幕截图，请添加以帮助解释您的问题）
![image](https://github.com/user-attachments/assets/03c9b192-d679-4fe6-8d1a-09ce32add5b0)

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
中英文字体均被换为自定义字体（非等宽），且框选字体后阴影也为非等宽自定义字体

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统 Win11
- 浏览器 Chromium
- 浏览器版本 131.0.6764.0 x64
- 脚本管理器 Tampermonkey
- 脚本管理器版本 5.3.2
- 所用的脚本名称 字体渲染（自用脚本）
- 所用的脚本版本 2024.11.02.1
- 其他补充信息 浏览器“自定义字体” 设置为与替换字体一样

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？
无

- 是否同时运行了其他第三方用户脚本？
无

## 8. 附加信息（在此处添加您认为有用的其他信息）
浏览器中关闭“自定义字体”后发现Copilot窗口字体替换不生效

**Comment by F9y4ng** [comment]
请提供GitHub Copilot的测试账户，我并没有开通GitHub Copilot权限，所以无法看到此页面。

**Comment by Zxis233** [comment]
目前发现Copilot的输入框HTML标签为`<textarea>`，但是缺被渲染了，而脚本设置内已设置`textarea`标签不被渲染

```html
<span class="TextInputWrapper__TextInputBaseWrapper-sc-1mqhpbi-0 dWIiON copilot-chat-textarea"><textarea aria-invalid="false" rows="7" cols="30" id="copilot-chat-textarea" autocomplete="off" autocorrect="off" spellcheck="false" role="textbox" aria-multiline="true" placeholder="Ask Copilot" class="Textarea__StyledTextarea-sc-1lf8it-0 izgWfj" style="height: 30px;">test word</textarea>
</span>
```

**Comment by Zxis233** [comment]
找到问题了，是输入框字体和预览的字体不一致。
```html
<div id="copilot-chat-textarea-preview" aria-hidden="true" class="Box-sc-g0xbh4-0 kjZFtT textarea-preview" role="presentation" style="height: 30px;">test word</div>
```
但在“需要渲染的网页元素”中加入`:not([id^='copilot-chat-textarea'])`后没有效果。

**Comment by F9y4ng** [comment]
> 找到问题了，是输入框字体和预览的字体不一致。
> 
> ```
> <div id="copilot-chat-textarea-preview" aria-hidden="true" class="Box-sc-g0xbh4-0 kjZFtT textarea-preview" role="presentation" style="height: 30px;">test word</div>
> ```
> 
> 但在“需要渲染的网页元素”中加入`:not([id^='copilot-chat-textarea'])`后没有效果。

试试在排除渲染的HTML标签中，追加`,.textarea-preview`，保存为站点独享数据。

最好是能将相关代码的上下文都拷贝出来才好分析。

**Comment by Zxis233** [comment]
```html
<div class="Box-sc-g0xbh4-0 clktIq" style="height: 30px;">
    <div class="InlineAutocomplete-module__container--UwGMb InlineAutocomplete-module__fullWidth--X6eXo"><span
            class="TextInputWrapper__TextInputBaseWrapper-sc-1mqhpbi-0 dWIiON copilot-chat-textarea"><textarea
                aria-invalid="false" rows="7" cols="30" id="copilot-chat-textarea" autocomplete="off" autocorrect="off"
                spellcheck="false" role="textbox" aria-multiline="true" placeholder="Ask Copilot"
                class="Textarea__StyledTextarea-sc-1lf8it-0 izgWfj"
                style="height: 30px;">TEST WORD</textarea></span></div>
    <div id="copilot-chat-textarea-preview" aria-hidden="true" class="Box-sc-g0xbh4-0 kjZFtT textarea-preview"
        role="presentation" style="height: 30px;">TEST WORD</div>
</div>
```

**Comment by F9y4ng** [comment]
### 尝试将该输入文本域字体统一替换为等宽字体：

双击排除渲染的HTML标签旁的🔔，在第一个文本域中追加：
```js
@github.com###copilot-chat-textarea-preview
```
保存数据后刷新再试试。

**Comment by Zxis233** [comment]
> ### 尝试将该输入文本域字体统一替换为等宽字体：
> 双击排除渲染的HTML标签旁的🔔，在第一个文本域中追加：
> 
> ```js
> @github.com###copilot-chat-textarea-preview
> ```
> 
> 保存数据后刷新再试试。

问题解决。感谢您的帮助！

**Comment by F9y4ng** [comment]
OK，该规则已加入 “[自定义等宽字体](https://github.com/F9y4ng/GreasyFork-Scripts/discussions/74)” 推荐规则。
