### ISSUE TITLE
[发现错误] 其他搜索引擎换到bing后有广告

### ISSUE THREAD

**Issue by actforjason** [F9y4ng/GreasyFork-Scripts#405]
其他搜索引擎换到bing后有广告
![图片](https://github.com/user-attachments/assets/261b5e39-47c8-461d-82dd-a96bfbba8b52)

**Comment by F9y4ng** [comment]
都已经翻墙出来了，为什么还要用 cn.bing.com ？这个操作确实没看懂。

广告的问题，下个更新会处理它。

**Comment by F9y4ng** [comment]
更新至 v2024.12.07.1 即可。
