### ISSUE TITLE
[BUG] 未开启字体缩放功能时，无法正确保存数据。

### ISSUE THREAD

**Issue by Sionyyy** [F9y4ng/GreasyFork-Scripts#407]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [x] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
修改配置无法保存（点击保存按钮没有反应）

## 3. 错误过程再现（请按示例填写行为步骤，直至复现您遇到的问题）
尝试了知乎、谷歌搜索、chatgpt，修改配置都无法保存
卸载重装也没有用

## 5. 预期结果（清晰明了地描述您所期待想要什么样的结果）
希望配置修改能够保存

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：Win10
- 浏览器：Edge,Firefox都尝试了
- 浏览器版本：均最新版本
- 脚本管理器：Tampermonkey
- 脚本管理器版本：最新版本
- 所用的脚本名称：字体渲染（自用脚本）
- 所用的脚本版本：最新版本
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

禁用其他扩展后依然无效

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
在我本地无法复现该问题，如果条件允许请提供动图或录屏操作。

**Comment by F9y4ng** [comment]
oops… 我已经捕捉到这个Bug，紧急发布一个新版本来修复它。感谢反馈。

**Comment by F9y4ng** [comment]
请及时更新至`v2024.12.08.2`.
