### ISSUE TITLE
[发现错误] 字体渲染，在渲染 duckduckgo时，页面滚动条消失，无法翻页

### ISSUE THREAD

**Issue by HueyZhang** [F9y4ng/GreasyFork-Scripts#408]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认正在使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
- [ ] 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。

## 2. 描述错误信息（清楚而简洁地描述错误）
在渲染 duckduckgo时，页面滚动条消失，无法翻页,更换字体依旧，停止渲染页面后正常，此前无此问题

## 6. 客户端信息（请在“**冒号**”后认真填写您的本地信息）
- 操作系统：
- 浏览器：
- 浏览器版本：
- 脚本管理器：
- 脚本管理器版本：
- 所用的脚本名称：
- 所用的脚本版本：
- 其他补充信息：

## 7. 脚本运行环境排查 （请确认环境条件并填写相关信息）
- 是否同时运行了其他浏览器扩展？

- 是否同时运行了其他第三方用户脚本？

**Comment by F9y4ng** [comment]
不能复现你遇到的问题，估计是Duckduckgo的某些灰测引起的问题，建议你清除浏览器缓存后重试。

![screenshot_2024-12-14_13-22-36](https://github.com/user-attachments/assets/9ae85d51-d4f5-436d-b680-541945fa5446)

**Comment by HueyZhang** [comment]
您好，大概率是浏览器问题，我用的是firefox，用edge一切正常

**Comment by F9y4ng** [comment]
> 您好，大概率是浏览器问题，我用的是firefox，用edge一切正常

Firefox、Safari下也都是正常的。
