### ISSUE TITLE
[发现错误] iai.sh.cn公式无法正常显示

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [F9y4ng/GreasyFork-Scripts#41]
**描述错误信息** 
网站上的公式无法正常显示

**错误再现** 
打开 http://iai.sh.cn/problem/496 （任意题目）即可看到题目中的公式

**预期结果**
![image](https://user-images.githubusercontent.com/64064866/144702717-1af4e8fc-40d9-48d5-88ab-fb2214b45f30.png)

**屏幕截图**
![image](https://user-images.githubusercontent.com/64064866/144702709-8853e1f2-c6c0-4f43-92e1-f88a3a0f8712.png)

**客户端信息：** 
- 操作系统：Windows 11 Version 21H2 (Build 22000.348)
- 浏览器：Microsoft Edge
- 版本：96.0.1054.43
- 脚本扩展：TamperMonkey
- 脚本扩展版本：4.13.6138
- 运行的脚本名称：Font Rendering
- 运行的脚本版本：2021.12.02.2

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
测试表明其它脚本无影响

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
测试表明其它脚本无影响

**Comment by F9y4ng** [comment]
同学，我没看到哪里有公式啊？你用红框标注出来？

如果需要登录才可显示，请提供一个临时账户。

**Comment by Galaxy-Studio-Code** [comment]
az，就是这上面的tex公式，http://iai.sh.cn/article/43 这篇文章拉到最下面

**Comment by Galaxy-Studio-Code** [comment]
其实就是公式的字体不太一样遇到复杂的公式就叠在一起了

**Comment by F9y4ng** [comment]
> az，就是这上面的tex公式，http://iai.sh.cn/article/43 这篇文章拉到最下面 ![image](https://user-images.githubusercontent.com/64064866/151643704-349b099c-25e4-46fa-9238-9e54e9e7f1df.png) 正常的话应该是：![image](https://user-images.githubusercontent.com/64064866/151643721-11fd3624-3f28-4f01-b9bd-a7a11ad56db5.png)

在 **需要渲染的网页元素** 中，追加 `:not([class*='katex-'] *)` ，保存为站点独享。
