### ISSUE TITLE
[发现错误] 网站图标变成方框问题

### ISSUE THREAD

**Issue by sky540** [F9y4ng/GreasyFork-Scripts#411]
https://www.chiphell.com/forum-146-1.html
该网站开始脚本，字体为雅黑，图标会变成方框问题，问题截图
![1](https://github.com/user-attachments/assets/3b0ed270-99a2-4a1e-9fa0-df8053d03576)

关闭脚本正常图标
![2](https://github.com/user-attachments/assets/4c4582ad-27b5-48f4-951d-05a17cb9ece8)

**Comment by F9y4ng** [comment]
在**需要渲染的网页元素**中，追加`:not([class*='ico_'])`，保存为站点独享数据。
