### ISSUE TITLE
[发现错误] Adguard Home自定义规则页面输入框文字重叠

### ISSUE THREAD

**Issue by yyysuo** [F9y4ng/GreasyFork-Scripts#43]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_     http://10.10.10.100:89/#custom_rules
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/10081071/145531463-1c1dd1cc-8127-44c5-8750-6b5657448614.png)
****

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：windows 1121H2 Windows 功能体验包 1000.22000.348.0
- 浏览器 [_如 Chrome_]：Chrome 
- 版本 [_如 93.0.4577.63_]：96.0.4664.93
- 脚本扩展 [_如 TamperMonkey_]：Tampermonkey
- 脚本扩展版本 [_如 4.13.6138_]：V4.13
- 运行的脚本名称 [_如 Font Rendering_]：GreasyFork-Scripts
- 运行的脚本版本 [_如 V3.8.20210101.1_]：<html>
<body>

2021.12.10.1
--

</body>
</html>
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
请在内网环境的设置界面内使用脚本菜单排除渲染。（对应快捷键为Alt+X）
