### ISSUE TITLE
建议新增一个去掉打印台信息的按钮

### ISSUE THREAD

**Issue by bring-down-the-hammer** [F9y4ng/GreasyFork-Scripts#44]
![image](https://user-images.githubusercontent.com/72541282/145770414-0e52bc55-7ef2-49fd-864e-fce92220c52f.png)
如果需要用到控制台调试功能 脚本信息很碍事..

可以考虑新增一个按钮可以去掉打印台信息

![image](https://user-images.githubusercontent.com/72541282/145770559-ce15dc55-d7a7-44f7-b156-160643622a24.png)
去掉此段代码确实可以 但加个按钮方便一些

**Comment by F9y4ng** [comment]
既然你需要在本地调试代码，为什么还要加载第三方脚本来产生干扰呢？实在不能理解。😕

**Comment by bring-down-the-hammer** [comment]
好吧 是我的问题😭

**Comment by XHXIAIEIN** [comment]
+1
