### ISSUE TITLE
关于等宽字体中中文的渲染问题

### ISSUE THREAD

**Issue by bring-down-the-hammer** [F9y4ng/GreasyFork-Scripts#45]
![image](https://user-images.githubusercontent.com/72541282/145771224-ca0bffd7-89a1-410f-a621-50806d38efab.png)
代码片段中的中文字体好糊..
我该如何改善目前的状况

**Comment by bring-down-the-hammer** [comment]
我浏览器设置
![image](https://user-images.githubusercontent.com/72541282/145774659-ebc366c8-9463-438e-a46e-792aaaa4dbca.png)
脚本设置
![image](https://user-images.githubusercontent.com/72541282/145774746-1b029f26-f7dd-43a8-a46e-504d6fbc22b7.png)

**Comment by F9y4ng** [comment]
在 **排除渲染的HTML标签** 中默认了 `pre,pre *,code,code *` 来过滤网页端的代码片段，并使用了英文等宽字体的重新渲染，字体CSS如右所示 `font:normal 400 14px/150% 'Operator Mono Lig','Fira Code','Roboto Mono',Monaco,monospace,Consolas!important;`，由于未定义中文字体，网页会使用默认的浏览器的字体设置或网站的字体设置，所以会出现代码片段内中文字体效果不佳的情况。

你可以尝试去掉这段CSS代码来忽略字体渲染脚本对代码片段的重新渲染，再看看是否符合你要的效果。

最好将你访问的代码网址提供，以方便我追踪问题所在。

**Comment by bring-down-the-hammer** [comment]
感谢你的解答 我将浏览器字体设置为苹方后 英文字体和中文字体都能顺利解析
可能是代码片段中的中文字体按照你所设置的字体来渲染 `Fira code` 但其对中文的支持效果不佳才造成上述问题
目前已解决
![image](https://user-images.githubusercontent.com/72541282/145780640-270662f4-d6ec-42e8-b19e-73f5abfcc039.png)

**Comment by F9y4ng** [comment]
下个版本更新我会尝试将自定义的中文字体加入网页中代码片段的渲染中来解决代码片段的中文字体效果不佳的问题。

由于很多代码网站自带代码颜色着色功能，以防产生新问题，可能会需要测试一段时间才会发布。😃
