### ISSUE TITLE
[发现错误] 天猫超市首页购物车显示为“㑶”

### ISSUE THREAD

**Issue by xytech** [F9y4ng/GreasyFork-Scripts#47]
天猫超市首页购物车显示为“㑶”。

1. 网址：https://chaoshi.tmall.com/
2. 向下滚动到首页推广区以下位置

希望正常显示购物车图标……

**屏幕截图** 
https://s4.ax1x.com/2021/12/20/TmOU0I.png

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：Windows 10 20H1 Enterprise 
- 浏览器 [_如 Chrome_]：Chrome x64
- 版本 [_如 93.0.4577.63_]：86.0.4240.198
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey_
- 脚本扩展版本 [_如 4.13.6138_]：4.13
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染（自用脚本）
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2021.12.17.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
是

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
是

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
在 **需要渲染的网页元素** 文本域中 追加 `:not([class*='-font'])` ，解决字体图标不正确的问题。
