### ISSUE TITLE
[发现错误] 部分字体，数字0异常显示，会比其它数字更占空间

### ISSUE THREAD

**Issue by 7peanuts** [F9y4ng/GreasyFork-Scripts#48]
部分字体的数字0可能比较宽，渲染后占空间导致后续数字显示不全，我发现的有微软雅黑，汉仪旗黑，苹方。
思源黑体、方正简体508R等字体的0较瘦长，所以不会出现该问题。
其实这也不算很大的问题，很少有论坛会在用户头像下显示注册日期。
如下图：
![优效截图20211225190238](https://user-images.githubusercontent.com/82173614/147383757-41ffcb10-1567-431b-8a4a-54d4817c71e5.png)

**错误再现**  （重现行为的步骤）
1. 帖子地址：[https://www.52pojie.cn/thread-1567086-1-1.html](url)
2. 此帖楼主的注册日期是2020-10-14，渲染后导致后面的数字看不见了，而楼层中注册日期中不带0的则显示正常。
![优效截图20211225184213](https://user-images.githubusercontent.com/82173614/147383761-09846b52-4470-4611-bb42-10fa353982e0.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [Win11]：
- 浏览器 [Cent Browser 版本 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)]：
- 脚本扩展 [TamperMonkey]：
- 脚本扩展版本 [4.13]：
- 运行的脚本名称 [字体渲染（自用脚本）]：
- 运行的脚本版本 [2021.12.24.1]：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
- 如上图所示，上述扩展已关闭

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
- 如上图所示，上述脚本已关闭

**Comment by F9y4ng** [comment]
你可以尝试分别定义中文与英文字体来解决此类问题。

分别设置中英文字体的方法：[#94256](https://greasyfork.org/zh-CN/scripts/416688/discussions/94256)

关于英文字体的选择可以参照 [#40](https://github.com/F9y4ng/GreasyFork-Scripts/issues/40#issuecomment-985253690)  的方法。

**Comment by 7peanuts** [comment]
> 

感谢大佬，请问有适合阅读的英文字体推荐吗？😄

**Comment by F9y4ng** [comment]
> 感谢大佬，请问有适合阅读的英文字体推荐吗？😄 在字客网上找到了一些，但我发现有些同家族英文字体不同粗细的家族名称相同，这样添加进去，脚本还能识别粗中细吗？

绝大部分网站默认的英文字体是`Arial, Helvetica`.

同家族英文字体不同粗细的家族名称相同的英文字体，可以用 **字体全名** 来调用。

**Comment by 7peanuts** [comment]
大佬新年好，问个问题：
Chromium内核浏览器的DirectWrite是否需要开启？
我发现关闭dw后，网页中的彩色字符变成黑白了，比如油猴脚本设置前面那三个彩色字符，🌓、⛔、和💎，脚本选项里的🔔。
但是开启dw脚本渲染效果貌似不如关闭好。

**Comment by F9y4ng** [comment]
> 大佬新年好，问个问题：
> Chromium内核浏览器的DirectWrite是否需要开启？
> 我发现关闭dw后，网页中的彩色字符变成黑白了，比如油猴脚本设置前面那三个彩色字符，🌓、⛔、和💎，脚本选项里的🔔。
> 但是开启dw脚本渲染效果貌似不如关闭好。

这是因为新版本的浏览器内核对粗体字体图标进行了重绘，造成彩色图标变为黑框图标，解决办法是去掉粗体设置，脚本样式已做过处理。

DW是否开启对脚本的影响只是参数上的差异，当然不排除极个别的特殊情况。根据自己的需求取舍就好。
