### ISSUE TITLE
[发现错误] 微博展开评论区，会导致微博主内容和评论区内容的字体变得非常模糊

### ISSUE THREAD

**Issue by FlechazoPh** [F9y4ng/GreasyFork-Scripts#49]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
微博点击展开评论区，会导致微博主内容和评论区内容的字体变得非常模糊，不点开评论区，字体显示正常

**错误再现**  （重现行为的步骤）

1. 进入微博主页， weibo.com ,  （新版主页）
2. 随便点开一个微博的评论区
3. 字体变模糊
4. 

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
![image](https://user-images.githubusercontent.com/22955480/147905854-b8bc42c5-c169-4134-bae7-4fe8649035ef.png)

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/22955480/147905950-63ac9804-65eb-4dbf-895a-26e4868c33e8.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：windows 10
- 浏览器 [_如 Chrome_]：chrome
- 版本 [_如 93.0.4577.63_]：版本 96.0.4664.110（正式版本） （64 位）
- 脚本扩展 [_如 TamperMonkey_]：Tampermonkey
- 脚本扩展版本 [_如 4.13.6138_]：beta版 4.14.6151
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染（自用脚本）
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.01.01.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
ADBlock

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
1.  你觉得评论模糊是因为微博评论的字体字号太小造成的，你使用 **字体比例缩放** 到`1.200`以上再看看，多动手调试一下。
2.  遇到渲染问题建议你先仔细看看帮助文档，[关于个别网站样式错误修正的设置分享，不定期更新，自取自用。](https://github.com/F9y4ng/GreasyFork-Scripts/discussions/42#discussioncomment-1842482)

**Comment by FlechazoPh** [comment]
> 1. 你觉得评论模糊是因为微博评论的字体字号太小造成的，你使用 **字体比例缩放** 到`1.200`以上再看看，字体描边、阴影尺寸多动手调试调试。_（如果从是较旧的版本升级到最新版的，最好重置一次设置数据，重新配置。）_
> 2. 如果配置了阴影颜色后出现字体边缘模糊，可以使用 currentcolor 来进行渲染。
> 3. 遇到渲染问题建议你先仔细看看帮助文档，[关于个别网站样式错误修正的设置分享，不定期更新，自取自用。](https://github.com/F9y4ng/GreasyFork-Scripts/discussions/42#discussioncomment-1842482)

对于 1,2 我这边是完全去掉了阴影和描边，字体缩放我试试再看

**Comment by FlechazoPh** [comment]
> 1. 你觉得评论模糊是因为微博评论的字体字号太小造成的，你使用 **字体比例缩放** 到`1.200`以上再看看，字体描边、阴影尺寸多动手调试调试。_（如果从是较旧的版本升级到最新版的，最好重置一次设置数据，重新配置。）_
> 2. 如果配置了阴影颜色后出现字体边缘模糊，可以使用 currentcolor 来进行渲染。
> 3. 遇到渲染问题建议你先仔细看看帮助文档，[关于个别网站样式错误修正的设置分享，不定期更新，自取自用。](https://github.com/F9y4ng/GreasyFork-Scripts/discussions/42#discussioncomment-1842482)

主要是你看图2，点开评论区的时候，微博主内容的字也突然变模糊了， “刚刚，李现......” 这一行内容，这个字体字号是和没点开是一样大的，不仅是评论区内的小字体变模糊

**Comment by F9y4ng** [comment]
你所提到的这些问题应该是和你本地的显示器、浏览器设置、扩展、其他脚本有关，没有你本地的详细数据我也爱莫能助，需要你自己慢慢的调试相关的参数来解决问题。

以下是我本地的截图，没有出现你说的情况，点击看大图：
![test](https://user-images.githubusercontent.com/15855068/148032184-4cdf7ade-8e6b-47ac-9e89-bac265f02f60.jpg)
