### ISSUE TITLE
macOS上，设置字体区域无法选择相应的字体，已安装了字体

### ISSUE THREAD

**Issue by Easonnnone** [F9y4ng/GreasyFork-Scripts#5]

**Comment by Easonnnone** [comment]
我知道什么原因了，与某个扩展冲突了，删除即可！

**Comment by evilhentaro** [comment]
macOS上渲染之后简直没法看了
就用默认设置
感觉以前的版本好些

**Comment by evilhentaro** [comment]
![image](https://user-images.githubusercontent.com/17069107/123030327-3d226c80-d415-11eb-99a7-7159e1411a1d.png)
可怕

**Comment by Easonnnone** [comment]
吓死人

**Comment by Easonnnone** [comment]
> ![image](https://user-images.githubusercontent.com/17069107/123030327-3d226c80-d415-11eb-99a7-7159e1411a1d.png)
> 可怕

把描边关掉后 应该还可以

**Comment by evilhentaro** [comment]
平滑、重写和描边都关了也是这样，尤其是英文和数字的部分，基本没法看了。

**Comment by F9y4ng** [comment]
> 平滑、重写和描边都关了也是这样，尤其是英文和数字的部分，基本没法看了。

新版本已经修正字体阴影渲染的问题，由于新版正在做兼容性测试，需要稍等几天才会发布。

> - 样例字体：更纱黑体，附加描边和阴影的效果

![New](https://z3.ax1x.com/2021/06/23/RuIbgx.png)

**Comment by evilhentaro** [comment]
修复之后很棒，感谢作者的辛勤付出。辛苦了。
