### ISSUE TITLE
谷歌搜索框输入会出现重影

### ISSUE THREAD

**Issue by bring-down-the-hammer** [F9y4ng/GreasyFork-Scripts#50]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
谷歌搜索框输入超过一定字数会出现重影

**错误再现**  （重现行为的步骤）

1. _去https://www.google.com.hk/?hl=zh_CN网址 ..."_
2. _输入长度超过十出现重影 "..."_

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/72541282/148013756-7ee9c0ad-bd8b-45b0-8747-81a2277d61cf.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器：edge
- 版本：96.0.1054.62
- 脚本扩展：Tampermonkey
- 脚本扩展版本：4.13.6138

- 是否同时运行了其他浏览器扩展？
否

- 是否同时运行了其他油猴脚本？
否

**附加信息**  （在此处添加有关此问题的任何附加信息）
chrome也会出现此问题

**Comment by F9y4ng** [comment]
此问题只在Blink内核的浏览器存在，如Chrome, Edge, 新版Opera ，原因是Google在input上附加了一个div层造成的。

解决方法：
在 **排除渲染的HTML标签** 中，追加 `,div[jsname='vdLsw'],div[jsname='vdLsw']>span`，保存为站点独享。

**Comment by bring-down-the-hammer** [comment]
好的 谢谢
