### ISSUE TITLE
当长度超过一定字数 百度一下按钮会错位

### ISSUE THREAD

**Issue by bring-down-the-hammer** [F9y4ng/GreasyFork-Scripts#51]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
当长度超过一定字数 百度一下会错位

**错误再现**  （重现行为的步骤）

1. _谷歌搜索 ..."_
2. _输入长度超过一定字数"..."_
3. _百度一下按钮错位 "..."_

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![image](https://user-images.githubusercontent.com/72541282/148153240-f8eda7e1-5df4-4483-89e7-e56a435216c0.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10 
- 浏览器：edge
- 版本：96.0.1054.62
- 脚本扩展：Tampermonkey
- 脚本扩展版本：4.13.6138
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
- 否
- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
- 否

**Comment by F9y4ng** [comment]
新版本中已修复这个bug，等待周更新吧。
