### ISSUE TITLE
怎样才能渲染粗体字呢？

### ISSUE THREAD

**Issue by canlanhelios** [F9y4ng/GreasyFork-Scripts#52]
常规字体渲染成鸿蒙黑体，粗体字依然是微软雅黑，请问作者应该如何解决呢？

![QQ截图20220107054011](https://user-images.githubusercontent.com/33181251/148456057-e0ac6693-db8f-4454-b76a-5691bec7efe0.png)

**Comment by F9y4ng** [comment]
- 判断脚本是否成功的渲染的当前网站的字体，建议最好使用 `华文行楷、华文琥珀、方正姚体` 这类字形变动较大的字体进行测试。如图：
![test](https://user-images.githubusercontent.com/15855068/148495473-57757173-1026-46d9-be68-53851cc03aea.jpg)

- 其次，你需要排除其他脚本的干扰，例如某脚本也对页面字体进行了定义，而且强制优先级，这样会产生结果干扰。
- 再次，某些字体由于一些特殊原因会造成字体重写问题，比如`OPPOSans`。
- 最后，珍惜生命、远离百毒。很少能在大厂代码中见到滥用!important优先级的案例，百毒那是**前无古人后无来者**。
