### ISSUE TITLE
淘宝、天猫 所有页面都会一加载就页面无响应。 

### ISSUE THREAD

**Issue by mantianfx** [F9y4ng/GreasyFork-Scripts#53]
淘宝买家后台。商家后台和生意参谋所有页面，都会无响应。 其他页面都正常。
但是这几个网站每天都在大量使用。还请帮忙查看一下。谢谢！

**Comment by F9y4ng** [comment]
1. 有 **错误报告（Bug report）** 反馈模板为什么你不用啊？
2. 常用网站大都通过测试，你还是需要排除你本地的脚本或扩展冲突。
3. 建议你按错误反馈模板描述逐一排除本地问题后，再发起ISSUSE。

**Comment by mantianfx** [comment]
好滴。 之前没有用过github 。不了解规则。 还请多包涵啊!
