### ISSUE TITLE
页面里的emoji也被渲染了，有办法过滤掉么？

### ISSUE THREAD

**Issue by rebron1900** [F9y4ng/GreasyFork-Scripts#55]
如题，emoji上有白色描边。
![image](https://user-images.githubusercontent.com/7929884/149692932-632d857c-5fd5-4cdd-a469-4c6e11bf9c45.png)

**Comment by rebron1900** [comment]
正常情况应该是这样
![image](https://user-images.githubusercontent.com/7929884/149695764-509046d4-7ce9-4ac8-b73b-951d35083d8c.png)

**Comment by F9y4ng** [comment]
你信不信，我能在100年内准确的猜到你说的这个页面的URL。

**Comment by rebron1900** [comment]
这个是emoji以标签形式嵌入的：https://github.com/justmemos/memos
这个是emoji直接以文本形式显示的：http://1900.live/build_your_own_flomo_applications/

这两种类型都有白色描边的情况。

**Comment by rebron1900** [comment]
第一种情况可以通过选择器排除，
第二种文本形式的不知道怎么排除。

**Comment by F9y4ng** [comment]
> 第一种情况可以通过选择器排除， 第二种文本形式的不知道怎么排除。

第二种文本形式确实让人头疼，你可以尝试：

- 适当增加字体阴影颜色的透明度，或减少阴影尺寸来减少阴影渲染效果，甚至关闭字体阴影来消除影响。
- 或将包含EMOJI图标的父级元素添加至 **排除渲染的HTML标签**，甚至整个网站添加至排除渲染列表，禁止脚本对字体进行渲染。
