### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by SapphireEcho** [F9y4ng/GreasyFork-Scripts#57]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
还原了下备份就出错了

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：
- 浏览器 [_如 Chrome_]：
- 版本 [_如 93.0.4577.63_]：
- 脚本扩展 [_如 TamperMonkey_]：
- 脚本扩展版本 [_如 4.13.6138_]：
- 运行的脚本名称 [_如 Font Rendering_]：
- 运行的脚本版本 [_如 V3.8.20210101.1_]：
- 其他信息：
                    浏览器信息：mozilla/5.0 (windows nt 10.0; win64; x64; rv:96.0) gecko/20100101 firefox/96.0

                    脚本扩展信息：Tampermonkey 4.13.6136

                    脚本版本信息：2022.01.22.1

                    当前访问域名：mail.qq.com

                    错误信息：[operateConfigure]: TypeError: str is undefined
                  

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
无

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
无

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
强烈建议，不要再腾讯邮箱这座屎山上使用脚本。

更换到其他任意网站再还原备份数据。
