### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by chNg1o** [F9y4ng/GreasyFork-Scripts#58]
浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":" Not;A Brand","version":"99"},{"brand":"Google Chrome","version":"97"},{"brand":"Chromium","version":"97"}],"mobile":false,"model":"","platform":"Windows","platformVersion":"15.0.0","uaFullVersion":"97.0.4692.99"}

                    脚本扩展信息：Tampermonkey 4.14

                    脚本版本信息：2022.01.22.1

                    当前访问域名：www.zhihu.com

                    错误信息：[Redundant Scripts]: 发现冗余安装的“字体渲染（自用脚本）”脚本，请删除重复脚本保留其一。

**Comment by F9y4ng** [comment]
`[Redundant Scripts]` 错误：是由于程序检测到你的本地浏览器中存在重复的“字体渲染（自用脚本）”脚本而触发的警告。

造成重复脚本的问题可能是以下原因：

1. 重复安装了“字体渲染（自用脚本）”的脚本两次。（解决办法：在脚本管理器中删除其中之一）
2. 部分网站后退，由于浏览器缓存造成的重复加载引发问题。（解决办法：强制刷新当前页面 或 清空浏览器缓存 后重试）
3. 在脚本管理器中删除“字体渲染（自用脚本）”脚本后又重新安装，由于脚本管理器缓存未及时更新引发问题。（解决办法：[#105905](https://greasyfork.org/zh-CN/scripts/416688-%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93-%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC/discussions/105905)）
