### ISSUE TITLE
新标签页字体改不回来了

### ISSUE THREAD

**Issue by g401676988** [F9y4ng/GreasyFork-Scripts#59]
使用脚本后还是习惯原版字体，发现新建标签页的字体改不回来了，用的是iTab，而且另外的浏览器也出现了同样的问题。请问改如何解决。

**Comment by F9y4ng** [comment]
想使用网站定义的原始字体，将 **字体重写** 功能关闭后保存为全局数据或当前网站数据即可。

新手使用脚本前请**仔细**阅读 [脚本使用说明](https://greasyfork.org/zh-CN/scripts/416688-%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93-%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC#guide) 和 [注意事项](https://greasyfork.org/zh-CN/scripts/416688-%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93-%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC#warning)。

**Comment by g401676988** [comment]
原因找到了，是应为安装了苹方体使浏览器默认字体改变，删除后解决问题了，谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "F9y4ng/GreasyFork-Scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月28日(星期五) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [F9y4ng/GreasyFork-Scripts] 新标签页字体改不回来了 (Issue #59)





 
想使用网站定义的原始字体，将 字体重写 功能关闭后保存为全局数据或当前网站数据即可。
 
新手使用脚本前请仔细阅读 脚本使用说明 和 注意事项。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
