### ISSUE TITLE
请求添加HarmonyOS Sans字体。

### ISSUE THREAD

**Issue by mx4994** [F9y4ng/GreasyFork-Scripts#6]
HarmonyOS Sans是华为鸿蒙的默认字体，本地我已经添加了，这几天用下来，还不错，但怕下次更新就覆盖了，恳请添加进脚本。

还有就是我系统已经安装苹方字体，但是拓展却没有识别出来，其他网站还可以调用。就很奇怪。。。

[下载HarmonyOS Sans](https://communityfile-drcn.op.hicloud.com/FileServer/getFile/cmtyPub/011/111/111/0000000000011111111.20210625173609.38562507005181826523284427982626:50520624100704:2800:5D13C177F26F284FCB18C3E150EEBE4BD6192643F2A83DC55BC65627754D4C1A.zip?needInitFileName=true)

**Comment by F9y4ng** [comment]
网络上很多windows下的苹方字体都是修改版或hack版，从而使得字体的英文名称不是PingFang SC，所以请选择安装正确的版本。你可以下载我导出的 [PingFang SC](https://file.io/ATYcxTDe6X9b) 字体，随后试一试。

```字体表TODO``` 已增加 苹方-繁```PingFang TC```，苹方-港```PingFang HK```，以及鸿蒙黑体```HarmonyOS Sans```，下个版本更新时会加入。

**Comment by F9y4ng** [comment]
网络上很多windows下的苹方字体都是修改版或hack版，从而使得字体的英文名称不是PingFang SC，所以请选择安装正确的版本。你可以下载我导出的 [PingFang SC](https://file.io/ATYcxTDe6X9b) 字体，随后试一试。

```字体表TODO``` 已增加 苹方-补充```PingFangSC-Regular```，思源黑体 Google```Noto Sans CJK SC```，以及鸿蒙黑体```HarmonyOS Sans SC```，下个版本更新时会加入。

**Comment by mx4994** [comment]
> 网络上很多windows下的苹方字体都是修改版或hack版，从而使得字体的英文名称不是PingFang SC，所以请选择安装正确的版本。你可以下载我导出的 [PingFang SC](https://file.io/ATYcxTDe6X9b) 字体，随后试一试。
> 
> `字体表TODO` 已增加 苹方-补充`PingFangSC-Regular`，思源黑体 Google`Noto Sans CJK SC`，以及鸿蒙黑体`HarmonyOS Sans SC`，下个版本更新时会加入。

好的，感谢。

**Comment by mx4994** [comment]
烦请再加个Medium字重，全称是HarmonyOS Sans SC Medium
麻烦了。

**Comment by F9y4ng** [comment]
> 烦请再加个Medium字重，全称是HarmonyOS Sans SC Medium
> 麻烦了。

增加字重可以使用脚本中的字体描边功能，实现的效果与字重增加一致，你可以试一试看。

**Comment by mx4994** [comment]
> > 烦请再加个Medium字重，全称是HarmonyOS Sans SC Medium
> > 麻烦了。
> 
> 增加字重可以使用脚本中的字体描边功能，实现的效果与字重增加一致，你可以试一试看。
这个描边在低分辨率下表现还行，在4K、5K分辨率下，显示就有点发虚，不够锐利。

**Comment by mx4994** [comment]
这是Medium字重，没开描边、阴影。![Medium](https://user-images.githubusercontent.com/52325833/125476421-7f6dea39-ae6a-4d67-b8f6-74bc000e34a1.png)

这是Regular字重，描边开0.2，尽量和Medium粗细一致，明显显示会虚一些。![Regular](https://user-images.githubusercontent.com/52325833/125476438-8d3c7c6c-cfee-46bd-ac94-37bc78c0b646.png)
图片有压缩，但还是看得出来。

**Comment by F9y4ng** [comment]
没在图片上看出什么区别😅

你有这类个性化需求可以自行在代码中添加你需要的新字体。

**Comment by mx4994** [comment]
这还真不是写轮眼，这个图片有压缩，然后是缩放显示的，点击查看原尺寸是看的出来的。

那我怎么在保持更新脚本的情况下，自行添加的字体不被覆盖呢？

**Comment by F9y4ng** [comment]
预计下个大版本更新全功能后，就会进入稳定期，更新频率会非常低，除非有重大bug出现。所以，你可以先自行修改代码，更新后再修改一次吧。🤭

**Comment by mx4994** [comment]
🤣已经复制了一份本地脚本了。

**Comment by standritsu** [comment]
上一个版本我能用鸿蒙，但7.17的版本又不能显示了，而且Chrome canary和Edge canary显示出来的字体数量不一样，Edge多了一个字体

**Comment by F9y4ng** [comment]
> 上一个版本我能用鸿蒙，但7.17的版本又不能显示了，而且Chrome canary和Edge canary显示出来的字体数量不一样，Edge多了一个字体

个人时间有限，不会对dev, canary版本的浏览器或扩展做兼容性测试。
