### ISSUE TITLE
数据源暂无数据

### ISSUE THREAD

**Issue by SapphireEcho** [F9y4ng/GreasyFork-Scripts#60]
![QQ图片20220204190104](https://user-images.githubusercontent.com/84564849/152518071-273b4a0a-9c87-4052-8a60-1dfa508b06d4.png)

**Comment by F9y4ng** [comment]
数据源无数据表示程序未检测到你本地有安装字体表的字体。如果是首次使用该脚本，建议仔细阅读一下“脚本使用说明”及“注意事项”。

在仔细阅读使用说明后，仍不能解决问题，请使用“错误ISSUES”模板按模板提示及操作流程发起新的ISSUES。
