### ISSUE TITLE
[发现错误] 创世中文网小说阅读页出现无法识别的乱码和方块

### ISSUE THREAD

**Issue by sunshuaiyin** [F9y4ng/GreasyFork-Scripts#61]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

创世中文网小说阅读页出现无法识别的乱码和方块，并且不知道为什么，在阅读页没办法复制黏贴‘需要渲染的网页元素’和‘排除渲染的HTML标签’。

**错误再现**  （重现行为的步骤）

1. 随意点开创世中文网上的一本小说进行阅读，比如
https://chuangshi.qq.com/bk/xx/AGwENF1oVjIAMlRkATUBZA-r-12.html
点开以后在阅读页面上会发现许多无法识别的符号和乱码
如图
<img width="688" alt="搜狗截图20220209170107" src="https://user-images.githubusercontent.com/99322251/153161858-29f2b8ec-9fe9-4137-a38d-f125eaf305de.png">

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
关闭脚本后的正常情况应该是这样
<img width="676" alt="搜狗截图20220209170208" src="https://user-images.githubusercontent.com/99322251/153161990-7c0a1e95-2863-43ef-bc22-5be677e43b27.png">

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器 [_如 Chrome_]：360极速浏览器
- 版本 [_如 93.0.4577.63_]：13.0.2290.0（chrome内核版本86.0.4240.198）
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：4.14
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染（自用脚本）
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.01.29.1

**Comment by F9y4ng** [comment]
1. 不能复制粘贴是**创世中文网**本身的脚本限制，你可以搜索其他去除该限制的脚本来解决此问题。
2. 解决乱码问题：在 **需要渲染的网页元素** 中，追加 `:not([class*='txtwrap'] *)` ，来解决**文章正文乱码**的问题。（由于该站点的限制，手动输入以上代码保存为站点独享即可）

**Comment by sunshuaiyin** [comment]
> 1. 不能复制粘贴是**创世中文网**本身的脚本限制，你可以消除这个其他问题的脚本来解决这个限制。
> 2. 解决渲染**的网页元素**中，附加`:not([class*='txtwrap'] *)`，来解决**乱码**的问题。

按照你说的办法操作后，乱码没有了，但是网页上许多字体错乱了？
并且每刷新一次错字都会变化一次，选择排除渲染整个域名都不行，照样有错字。把整个脚本关闭才会一切正常

**Comment by sunshuaiyin** [comment]
@F9y4ng

**Comment by sunshuaiyin** [comment]
搞清楚了，是网页限制解除脚本的问题，不关字体渲染脚本的事

**Comment by F9y4ng** [comment]
- 先重置当前网站的设置数据后，再重新配置字体渲染数据。

- 建议你使用前能认真阅读一下 **[注意事项](https://greasyfork.org/zh-CN/scripts/416688-%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93-%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC#warning)** 和 **[使用说明](https://greasyfork.org/zh-CN/scripts/416688-%E5%AD%97%E4%BD%93%E6%B8%B2%E6%9F%93-%E8%87%AA%E7%94%A8%E8%84%9A%E6%9C%AC#guide)**，能减少你遇到的很多问题。

![屏幕截图 2022-02-09 185226](https://user-images.githubusercontent.com/15855068/153183769-c2b079a0-99cf-44df-b897-41c54b5b691b.jpg)
