### ISSUE TITLE
网页里的输入框，论坛贴子里的回复框中输入的文字，还有网页某些地方的下拉框中的文字不渲染。

### ISSUE THREAD

**Issue by jiaminxun** [F9y4ng/GreasyFork-Scripts#62]
网页里的输入框，论坛贴子里的回复框中输入的文字，还有网页某些地方的下拉框中的文字不渲染,如图
edge加渲染脚本
![edge加渲染脚本](https://user-images.githubusercontent.com/57553009/153692165-cf80344e-e382-4e9f-b2cc-b6b8b4669b25.jpg)
百分浏览器关闭DW加mactype渲染
![百分浏览器关闭DW加mactype渲染](https://user-images.githubusercontent.com/57553009/153692168-16109b56-aa8b-4afd-ab37-a16a7f41b271.jpg)
edge加渲染脚本
![edge加渲染脚本2](https://user-images.githubusercontent.com/57553009/153692252-bcaa50ad-eddb-4035-927a-ddc547c38a0f.jpg)
百分浏览器关闭DW加mactype渲染
![百分浏览器关闭DW加mactype渲染2](https://user-images.githubusercontent.com/57553009/153692206-8d47e722-ce8b-44f1-9f2c-46c3482891e0.jpg)
edge加渲染脚本
![edge加渲染脚本3](https://user-images.githubusercontent.com/57553009/153692279-a9f9fd72-0490-47de-acb7-67ab1adde5bc.jpg)
百分浏览器关闭DW加mactype渲染
![百分浏览器关闭DW加mactype渲染3](https://user-images.githubusercontent.com/57553009/153692366-017b1e4b-20c3-4ac6-a573-c04f88879db9.jpg)

**Comment by F9y4ng** [comment]
在 **排除渲染的HTML标签**中，**找到并删除** `input,select,button,textarea,` ，即可对以上标签进行渲染。

但由于不同内核的浏览器对这些HTML标签的渲染逻辑不同，会造成一些不可预料的问题，是否取消例外排除请自行斟酌。

**Comment by jiaminxun** [comment]
这样设置以后，网页输入框和论坛贴子回复框输入的文字可以渲染了，但下拉框下拉弹出的其他文字没法渲染
![edge加渲染脚本](https://user-images.githubusercontent.com/57553009/153700664-18071d78-5805-419d-b898-f886db423641.jpg)

**Comment by F9y4ng** [comment]
HTML标签中select -> option的样式是无法自定义的，想要自定义样式就需要重写select -> option的样式或重新定义select标签来完成，而这不是该脚本的功能。

**Comment by F9y4ng** [comment]
HTML标签中select -> option的样式是无法自定义的，想要自定义样式就需要重写select -> option的样式或重新定义select标签来完成，而这不是该脚本的功能。

**Comment by jiaminxun** [comment]
好的，感谢解答，非常棒的脚本。
