### ISSUE TITLE
[发现错误] 仓耳今楷01 W03自定义字体无法识别到

### ISSUE THREAD

**Issue by bigdeer** [F9y4ng/GreasyFork-Scripts#63]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
字体地址：
https://www.fontke.com/font/166895047/download/

**错误再现**  （重现行为的步骤）

按页面参数设置
中文名：仓耳今楷01
英文名：TsangerJinKai01
{"ch":"仓耳今楷01","en":"TsangerJinKai01"}
重启浏览器后，列表未出现

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：windows 11
- 浏览器 [_如 Chrome_]：Edge
- 版本 [_如 93.0.4577.63_]：版本 100.0.1163.1 (官方内部版本) dev (64 位)
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey_
- 脚本扩展版本 [_如 4.13.6138_]：4.13.6138
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染（自用脚本）
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.02.20.2
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
uBlock Origin

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
无

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
系统安装新字体后，**重启浏览器**是为了使**操作系统的字体缓存**在浏览器中生效。

值得注意的是，脚本程序将**已通过检测**的字体表信息做过缓存，时效为七天。重启浏览器后需要重建字体表缓存。

- 你需要在**核心功能设置**中，重置**当前网站**的字体表缓存，以使程序再次检测新字体后重新为当前网站缓存新的字体表信息。

- 或者手动清除浏览器**所有**缓存信息后(Ctrl+Shift+Del)，可使**所有站点**的字体表缓存重新自动创建。
