### ISSUE TITLE
[发现错误] 一直显示加载中，无法正确启动脚本

### ISSUE THREAD

**Issue by helleon** [F9y4ng/GreasyFork-Scripts#65]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
一直显示加载中，无法正确启动脚本
已升级2月20的最新版本
具体请看截图

有启用其他脚本和adguard，但是禁用后故障依旧

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

![2](https://user-images.githubusercontent.com/3538768/155124602-2f14154c-3523-4fd4-b9a2-8d9b86178bca.png)
![1](https://user-images.githubusercontent.com/3538768/155124614-e1999a18-42d3-4015-bfa1-dfe6d1be3686.png)
![3](https://user-images.githubusercontent.com/3538768/155124619-9a4db2a1-feaa-47b0-b20b-fe5ef675a63a.png)

**Comment by helleon** [comment]
补充，同一台电脑下firefox和edge正常，只是chrome的异常

**Comment by F9y4ng** [comment]
所有网站都会出现这个问题，还是只在个别网站出现？

尝试刷新一次页面，看是否还会出现此问题。

**Comment by helleon** [comment]
> 所有网站都会出现这个问题，还是只在个别网站出现？
> 
> 尝试刷新一次页面，看是否还会出现此问题。

所有网站，刷新过无数次了，缓存也请过，chrome也重启过，脚本删了重装过

这个问题应该有一段时间了，今天看到更新了但是还是异常才想起来报issue

**Comment by F9y4ng** [comment]
脚本菜单的加载会受到以下几个方面的影响：

1. 脚本菜单本身延时1秒载入；
2. 脚本菜单会等待访问网站的远程字体载入后再加载；
3. 如果访问的网站中有自身脚本或其他第三方脚本执行中出现阻塞/排队，脚本菜单也会被延时执行。

如果所有网站都有这个问题，请尝试，只开TamperMonkey扩展，只执行字体渲染（自用脚本）一个脚本，试试看是否是其他扩展或是脚本有冲突造成的。每台计算机的本地环境都不同，只能逐一排查一下。

> 在我本地WIN10环境中，主流浏览器edge,chrome,firefox,opera,safari，脚本管理器Tampermonkey, Violentmonkey, Greasemonkey，都通过测试。

**Comment by helleon** [comment]
尝试禁用所有插件只留Tampermonkey，只装这个脚本，清空所有缓存重试还是不行

看样子不光是菜单，渲染也是没成功的

https://user-images.githubusercontent.com/3538768/155132074-031f5d29-705d-4bac-ac92-1fa4cb29b1cb.mp4

其他浏览器又是好的，奇怪

**Comment by helleon** [comment]
[news.sina.com.cn-1645533714065.zip](https://github.com/F9y4ng/GreasyFork-Scripts/files/8116664/news.sina.com.cn-1645533714065.zip)

辛苦大佬排查了

**Comment by helleon** [comment]
试了切到windows11下问题一样，也是只有chrome有问题。另外我在墙外，应该没啥区别吧，除非某个服务器在墙名单上

**Comment by F9y4ng** [comment]
如果有时间，你试一下（暴力猴）violentmonkey这个脚本管理器看看是否还有问题，Tampermonkey对Chrome兼容性没有对FF好。

**Comment by helleon** [comment]
> 如果有时间，你试一下（暴力猴）violentmonkey这个脚本管理器看看是否还有问题，Tampermonkey对Chrome兼容性没有对FF好。

换暴力猴ok了，汗

**Comment by F9y4ng** [comment]
看来是Tampermonkey对Chrome的兼容性问题造成的，Tampermonkey的ISSUES中一直都有对chrome兼容性问题反馈，但一直没有很好的处理，再Tampermonkey没有更新此问题之前，建议你还是使用暴力猴用一段时间吧。

**Comment by helleon** [comment]
> 看来是Tampermonkey对Chrome的兼容性问题造成的，Tampermonkey的ISSUES中一直都有对chrome兼容性问题反馈，但一直没有很好的处理，再Tampermonkey没有更新此问题之前，建议你还是使用暴力猴用一段时间吧。

好的，感谢你花时间解答

**Comment by F9y4ng** [comment]
兼容性警告：**Tampermonkey** 在 **Chrome** 浏览器中存在兼容性问题，请Chrome用户使用 **Violentmonkey（暴力猴）**替代。

**Comment by F9y4ng** [comment]
[tampermonkey_beta_4_15_6153.zip](https://github.com/F9y4ng/GreasyFork-Scripts/files/8150722/tampermonkey_beta_4_15_6153.zip)
