### ISSUE TITLE
阿里邮箱企业版中邮件正文无法渲染

### ISSUE THREAD

**Issue by alaya129** [F9y4ng/GreasyFork-Scripts#68]
在Firefox下没有问题，Chrome中无法渲染，均使用暴力猴

**Comment by F9y4ng** [comment]
我没有阿里邮箱企业版的账户，如果能提供测试账户，请回复。

**Comment by alaya129** [comment]
> 我没有阿里邮箱企业版的账户，如果能提供测试账户，请回复。

谢谢回复。请用这个链接登录：https://qiye.aliyun.com/alimail/auth/login
用户名：test1@robertet.cn
密码：Robertet123456

**Comment by F9y4ng** [comment]
> > 我没有阿里邮箱企业版的账户，如果能提供测试账户，请回复。
> 
> 谢谢回复。请用这个链接登录：https://qiye.aliyun.com/alimail/auth/login 用户名：[test1@robertet.cn](mailto:test1@robertet.cn) 密码：Robertet123456

感谢你的反馈，已捕捉到该bug，本周更新时会发布。

**Comment by alaya129** [comment]
多谢多谢

**Comment by F9y4ng** [comment]
v2022.03.12.1 版本已更新，[可手动更新至最新版](https://github.com/F9y4ng/GreasyFork-Scripts/raw/master/Font%20Rendering.user.js)

> 测试账户请及时回收，避免不必要的问题，感谢合作。
