### ISSUE TITLE
[发现错误] QQ邮箱显示小方块

### ISSUE THREAD

**Issue by MartinYuan1995** [F9y4ng/GreasyFork-Scripts#69]
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/47047658/158052636-b1092863-c835-4dc3-a967-1f1165babcf6.png">

**Comment by F9y4ng** [comment]
请参考 #57 ，不要在QQ邮箱使用“字体渲染脚本”，很多浏览器下QQ邮箱无法正常兼容本脚本。
