### ISSUE TITLE
渲染設置給個側邊滾動條吧

### ISSUE THREAD

**Issue by ifermi** [F9y4ng/GreasyFork-Scripts#7]
不然得縮放頁面才能點到確定鈕。

**Comment by ifermi** [comment]
不然得縮放頁面才能點到確定鈕。

**Comment by F9y4ng** [comment]
新版已经提供最下文本域输入框的收缩功能，以便系统缩放比例造成的页面过长而不能保存的问题。

!["收缩按钮"](https://i.postimg.cc/XvmM0frs/2021-07-04-182515.png "收缩按钮")

经测试，1080P分辨率在新版本脚本样式至少要放大150%以上才会影响到保存按钮，更高分辨率至少放大175%以上才会影响。

**Comment by F9y4ng** [comment]
version 2021.07.06.2

已增加自适应滚动条。

**Comment by ifermi** [comment]
感謝！
