### ISSUE TITLE
[发现错误] 进入B站时，更改浏览器UA为Safari后字体渲染功能失效

### ISSUE THREAD

**Issue by westjmoon** [F9y4ng/GreasyFork-Scripts#70]
**描述错误信息**  
进入B站时，更改浏览器UA为Safari后字体渲染功能失效

**错误再现**  
1. _去B站网址 “www.bilibili.com”
2. 使用浏览器扩展“User Agent Switcher and Manager”更换UA为Safari 14.1（Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15）
3.更换UA后刷新B站页面，页面字体渲染功能失效

**预期结果**  
希望可以兼容在切换浏览器UA的情况下使用

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
未切换UA时渲染效果图：
![未切换UA](https://user-images.githubusercontent.com/33957370/158584859-e68ba48f-7a2b-4ba8-a2eb-8b6224e66f7e.png)

切换UA后页面显示效果图：
![切换UA](https://user-images.githubusercontent.com/33957370/158584888-c14b5191-3af6-4e6c-a598-f92c2b8f4abe.png)

**客户端信息：**
- 操作系统 ：Windows10 LTSC 2021
- 浏览器 ：MicroSoft Edge
- 版本 ：99.0.1150.39 (正式版本) (64 位)
- 脚本扩展 ：Violentmonkey
- 脚本扩展版本 ：v2.13.0
- 运行的脚本名称 ：Font Rendering (Customized)
- 运行的脚本版本 ：2022.03.12.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ 
是，User Agent Switcher and Manager

- 是否同时运行了其他油猴脚本？
否，测试时禁用了其他所有脚本

**Comment by F9y4ng** [comment]
这并非代码的bug，因为Font Rendering (Customized)的代码已对BLINK内核平台启用了最新的navigator.userAgentData来取代navigator.userAgent。Chromium 101版本开始将全面启用navigator.userAgentData，这是大势所趋。

User Agent Switcher and Manager 插件无法更改navigator.userAgentData数据，强制修改会使程序报错。

你所遇到的这个错误会在下次版本更新时做简单的兼容处理（脚本运行不报错），但不保证功能的完整性，因为Font Rendering (Customized)脚本对浏览器navigator.userAgentData的数据读取是功能应用的重要依据。

**Comment by F9y4ng** [comment]
version [2022.03.19.1](https://github.com/F9y4ng/GreasyFork-Scripts/raw/master/Font%20Rendering.user.js) should fix.
