### ISSUE TITLE
代码块里面字体渲染异常

### ISSUE THREAD

**Issue by lqllife** [F9y4ng/GreasyFork-Scripts#72]
未开启渲染的情况下：
![image](https://user-images.githubusercontent.com/23254569/158966641-1f1aab26-6192-4c6d-a7e7-4e8a48a90631.png)

开启后：
![image](https://user-images.githubusercontent.com/23254569/158966697-c1ffe115-576e-4ae9-8623-e0bf076e03bd.png)

**Comment by lqllife** [comment]
包含代码块的文章都会出现的问题，我截图中的文章是csdn的：https://blog.csdn.net/ITlanyue/article/details/122492519

**Comment by F9y4ng** [comment]
### 提交错误/异常请使用“错误报告(Bug report)”来进行反馈，先排除你本地与其他扩展或脚本的冲突。

页面中包含`pre, code`的代码片段会由程序重新定义等宽英文字体，如果希望使用网站定义的字体，按如下操作：

在**排除渲染的HTML标签**中，找到并删除 `,pre,pre *,code,code *`，保存为站点独享。

> 以下是我本地的情况，似乎一切正常，应该是你本地计算机缺少相应的等宽字体如 _'Operator Mono Lig','Fira Code','Source Code Pro','Roboto Mono',Monaco,monospace,Consolas_ 造成的。
> 
> ![ok](https://user-images.githubusercontent.com/15855068/158977101-80b869ad-8ccd-4262-bf2d-64c80f7454c1.png)
