### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by alaya129** [F9y4ng/GreasyFork-Scripts#75]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
维格表内容无法渲染
https://vika.cn/

![jPDvZOOCH2](https://user-images.githubusercontent.com/15197674/159150063-5caace84-c023-4a8a-8043-5fdd440d270f.png)

**Comment by F9y4ng** [comment]
1. 不是太建议在这类工具型网站开启字体渲染功能，毕竟Word,Excle,Powerpoint等功能都需要对正文字体进行再编辑，除非你自己会手动排除或允许相应的元素进行渲染操作。

2. 该站点需要登录账户，请提供**测试账户**，再进一步受理。

**Comment by alaya129** [comment]
测试网址：https://vika.cn/workbench/dst1FbuobpRFRCExpN/viwlahZYP0QEw
账号：xafqwexwrojbsvtojp@kvhrr.com
密码：Hello_123

谢谢

**Comment by F9y4ng** [comment]
vika 是使用canvas来绘制表格数据的，你可以理解这是一张画布，而不是文本。所以字体渲染脚本对canvas中的文字是无法进行渲染的。

而其他标题栏上的button,input,textarea元素，可以通过以下方式获得渲染：

在**排除渲染的HTML标签**中，找到并删除`input,`，`button,`，`textarea,`，保存为站点独享。

**Comment by F9y4ng** [comment]
vika 是使用canvas来绘制表格数据的，你可以理解这是一张画布，而不是文本。脚本暂不能对canvas元素进行二次渲染。

而其他标题栏上的button,input,textarea元素，可以通过以下方式获得渲染：

在**排除渲染的HTML标签**中，找到并删除`input,`、`button,`、`textarea,`，保存为站点独享。
