### ISSUE TITLE
微软网站预览图左右翻页箭头图标显示错误

### ISSUE THREAD

**Issue by 7peanuts** [F9y4ng/GreasyFork-Scripts#77]
微软网站，包括应用商店、服务等页面里的预览图左右翻页箭头图标显示错误。
已关闭其它扩展和脚本，在几个月之前的版本就有这个问题。切换字体，如Arial、微软雅黑，还是会出现错误。
举例网站：
https://www.microsoft.com/zh-cn/p/files-file-manager-for-windows/9nghp3dx8hdx?activetab=pivot:overviewtab#
错误的箭头图：
![flip1](https://user-images.githubusercontent.com/82173614/160220588-2744c219-50d4-4d74-b1cd-7ba9690d6821.png)
![flip2](https://user-images.githubusercontent.com/82173614/160220589-a5970311-8fa3-4f69-942c-5c5e03fb24f3.png)

- 操作系统：Win11
- 浏览器：360极速浏览器X，百分浏览器 Cent Browser
- 版本：
- 360极速X 版本号：21.0.1082.0，内核版本：95.0.4638.69
- Cent Browser 版本 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
- 脚本扩展 ：TamperMonkey
- 脚本扩展版本：360极速X安装的油猴版本 v4.13，百分安装的油猴版本 v4.15 
- 运行的脚本版本：version 2022.03.19.1

**Comment by F9y4ng** [comment]
在**需要渲染的网页元素**中，追加 `:not([class*='c-flipper'])`，保存为站点独享。

**Comment by 7peanuts** [comment]
> 在**需要渲染的网页元素**中，追加 `:not([class*='c-flipper'])`，保存为站点独享。
> 
> > 一般情况下，某些网站中个别字体图标显示错误就不需要报脚本错误报告啦，此类问题甚至可以到 **[Discussions](https://github.com/F9y4ng/GreasyFork-Scripts/discussions/categories/%E9%97%AE%E7%AD%94%E4%B8%93%E5%8C%BA)** 中来提问，我一样及时给与解答。😂

大佬给力！ 😍
