### ISSUE TITLE
汉仪旗黑有多种字重啊

### ISSUE THREAD

**Issue by spphinslove** [F9y4ng/GreasyFork-Scripts#8]
![图片](https://user-images.githubusercontent.com/11383988/124380517-8ca74900-dcef-11eb-96ee-00b15393b356.png)
希望能选择 因为现在是默认50字重，50是light的，太细了。60是regular。 55是book的。我用的60，55也不错

**Comment by F9y4ng** [comment]
汉仪旗黑字体，从最细的25到最粗的105，共计15个字重，不可能把所有的字重都放进去。

通过改变字体描边尺寸来控制字重可以解决字体粗细问题。

关于字重的修正，下次更新会改为regular/60为默认。感谢。
