### ISSUE TITLE
[发现错误] Chrome++ 1.5.0 可能造成脚本报告错误

### ISSUE THREAD

**Issue by linsuperr** [F9y4ng/GreasyFork-Scripts#80]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
暴力猴点击字体渲染设置提示错误

**错误再现**  （重现行为的步骤）

所有网站暴力猴点击字体渲染设置提示错误

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![x2scrap2.png](https://xxx.imgurl.ps/2022/04/07/eee366a040611.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win10
- 浏览器 [_如 Chrome_]：chrome
- 版本 [_如 93.0.4577.63_]：版本 100.0.4896.75（正式版本） （64 位）Chrome++ 1.5.0 inside
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：2.13.0

- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
否

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
否

**附加信息**  （在此处添加有关此问题的任何附加信息）
安装了作者提供的所有自定义字体

**Comment by F9y4ng** [comment]
从你的数据上来看，如果每次操作都发生此错误，且确认没有其他扩展或脚本冲突的情况下，大概率出在`Chrome++ 1.5.0 inside`这上面。

因为我本地Chrome的运行环境与你反馈的数据几乎一致，除了你使用了Chrome++的破解DLL，所以需要你提供更多的数据。

***

建议你进行以下操作并将日志发送到这里：

1. 打开脚本管理器，编辑脚本，在脚本第54行找到下面位置，开启脚本调试功能：
```javascript
const IS_OPEN_DEBUG = false; // set "true" to debug scripts, May cause script response slower.
```
修改为
```javascript
const IS_OPEN_DEBUG = true; 
```
2. 清空浏览器缓存，ctrl+shift+del 清除所有时间缓存，重启浏览器。
3. 打开任意网站，按F12,进入控制台。
4. 刷新网页，再次进行你之前出现错误提示的操作，直至再次出现错误提示。
5. 再控制台中点右键另存为，将错误日志打包上传至这里。

**Comment by F9y4ng** [comment]
长时间未反馈更多信息，转为无效反馈。

**Comment by F9y4ng** [comment]
version [2022.05.15.1](https://github.com/F9y4ng/GreasyFork-Scripts/raw/master/Font%20Rendering.user.js) should be fixed.
