### ISSUE TITLE
网页加载完成后等一小会儿才会刷新展示效果

### ISSUE THREAD

**Issue by zdzqianmu** [F9y4ng/GreasyFork-Scripts#81]
chrome浏览器 win11

加载网页后显示默认页面，跳变成渲染后的页面

**Comment by F9y4ng** [comment]
如果访问所有网站都会出现延迟渲染的问题，在排除其他扩展及其他第三方脚本的冲突后，请按照 **错误报告(Bug report)** 模板提交ISSUES 。

> 如果脚本管理器使用的是Tampermonkey，建议更换Violentmonkey试试，从Tampermonkey4.14版本开始兼容性问题挺多。

但如果只是个别网站出现延迟，必定是该网站自身脚本（或其他第三方脚本）有阻塞/排队的问题而引起所有脚本都必须等待阻塞处理完成后才会执行。
