### ISSUE TITLE
[发现错误] 设置字体渲染选项后无法保存

### ISSUE THREAD

**Issue by xushet** [F9y4ng/GreasyFork-Scripts#84]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

**错误再现**  （重现行为的步骤）

1. _去XX网址 ..."_
2. _单击YY链接/按钮 "..."_
3. _向下滚动到ZZ位置 "..."_
4. _查看错误_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
字体按照设置正常渲染

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![QQ截图20220417225754](https://user-images.githubusercontent.com/34502902/163720133-46d8ba6c-1006-4b42-b22b-9683983b84db.png)
改动设置界面任意选项点击保存后都会出现如下提示
![QQ截图20220417225641](https://user-images.githubusercontent.com/34502902/163720080-4e76e059-af3a-48c8-8775-d2f9bf8f35c3.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：windows7x64
- 浏览器 [_如 Chrome_]：chrome canary
- 版本 [_如 93.0.4577.63_]： 103.0.5008.0
- 脚本扩展 [_如 TamperMonkey_]：Violentmonkey BETA
- 脚本扩展版本 [_如 4.13.6138_]：v2.13.0.18
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染（自用脚本）
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.04.16.2
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
已排除
![QQ截图20220417225902](https://user-images.githubusercontent.com/34502902/163720191-98b56644-a22f-4991-a427-620bbbdb5a45.png)

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
已排除
![QQ截图20220417225911](https://user-images.githubusercontent.com/34502902/163720197-6297d5a5-865a-433e-a50b-e3c9ed29dda7.png)

**附加信息**  （在此处添加有关此问题的任何附加信息）

浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":" Not;A Brand","version":"99"},{"brand":"Google Chrome","version":"103"},{"brand":"Chromium","version":"103"}],"mobile":false,"model":"","platform":"Windows","platformVersion":"0.1.0","uaFullVersion":"103.0.5008.0"}
脚本扩展信息：Violentmonkey 2.13.0.18
脚本版本信息：2022.04.16.2
当前访问域名：f9y4ng.github.io
错误信息：[manageDomainsList]: TypeError: Cannot read properties of undefined (reading 'replace')
[submitData]: TypeError: domainValue.push is not a function

**Comment by F9y4ng** [comment]
由于精力有限，不会对Beta、Canary、Nightly等测试分支版本的浏览器或脚本管理器做兼容测试，因**非正式版本**的浏览器或脚本管理器会有各种不可预见的问题或兼容性错误。

如果在使用正式版本后依然出现错误提示，请重新发起ISSUES。
