### ISSUE TITLE
teams 网页版 无法使用 

### ISSUE THREAD

**Issue by in-out** [F9y4ng/GreasyFork-Scripts#85]
版本：2022.04.16.2
插件：暴力猴 2.13.0
![image](https://user-images.githubusercontent.com/3615775/164347874-059aafb3-46b2-4492-b52c-61293aab7dd5.png)

**Comment by F9y4ng** [comment]
已捕捉到Violentmonkey2.13在teams.live中因`trustedTypes createPolicy`设置的报错，下个周更新版本将会修复此bug.

**Comment by F9y4ng** [comment]
version [2022.04.23.1](https://github.com/F9y4ng/GreasyFork-Scripts/raw/master/Font%20Rendering.user.js) should be fixed.
