### ISSUE TITLE
瀏覽器提示錯誤信息上報

### ISSUE THREAD

**Issue by jkle112** [F9y4ng/GreasyFork-Scripts#89]
脚本在运行过程中发生了重大异常或错误，请及时告知作者，感谢您的反馈！以下信息会自动保存至您的剪切板：

浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":" Not A;Brand","version":"99"},{"brand":"Chromium","version":"101"}],"mobile":false,"model":"","platform":"Linux","platformVersion":"5.15.0","uaFullVersion":"101.0.4951.41"}　
脚本扩展信息：Tampermonkey 4.16　
脚本版本信息：2022.05.01.1　
当前访问域名：cn.bing.com　
错误信息：[Redundant Scripts]: 发现冗余安装的“字体渲染（自用脚本）”脚本，请删除重复脚本保留其一。

脚本在运行过程中发生了重大异常或错误，请及时告知作者，感谢您的反馈！以下信息会自动保存至您的剪切板：

浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":" Not A;Brand","version":"99"},{"brand":"Chromium","version":"101"}],"mobile":false,"model":"","platform":"Linux","platformVersion":"5.15.0","uaFullVersion":"101.0.4951.41"}　
脚本扩展信息：Tampermonkey 4.16　
脚本版本信息：2022.05.01.1　
当前访问域名：www.kpkuang.xyz　
错误信息：[Redundant Scripts]: 发现冗余安装的“字体渲染（自用脚本）”脚本，请删除重复脚本保留其一。

**Comment by F9y4ng** [comment]
参阅 #58 排查问题。
