### ISSUE TITLE
发现一个缺陷

### ISSUE THREAD

**Issue by spphinslove** [F9y4ng/GreasyFork-Scripts#9]
![图片](https://user-images.githubusercontent.com/11383988/124408800-98d7e880-dd79-11eb-8204-cc670ca5a834.png)
启动时候恢复的标签页没有修改字体，必须刷新才行。

**Comment by F9y4ng** [comment]
我本地Firefox(89.0.2,TamperMonkey/ViolentMonkey/GreaseMonkey)同样设置下，均不能复现出你描述的问题。重新打开FF后，页面会自动重新载入。

可能是由于你的FF本地设置、其他扩展或脚本的冲突造成的，尝试关闭其他扩展和油猴脚本，只保留此脚本，再尝试一下。

如果还有其他用户反馈此问题，我会进一步跟进。
