### ISSUE TITLE
[发现错误] 字体渲染设置时报错

### ISSUE THREAD

**Issue by ddvcx** [F9y4ng/GreasyFork-Scripts#90]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
字体渲染设置时报错

**错误再现**  （重现行为的步骤）
任何网站只要打开字体渲染设置都会报错

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
能正常进行设置

*浏览器信息：{"architecture":"x86","bitness":"64","brands":[{"brand":" Not A;Brand","version":"99"},{"brand":"Chromium","version":"99"},{"brand":"Google Chrome","version":"99"}],"mobile":false,"model":"","platform":"Windows","platformVersion":"10.0.0","uaFullVersion":"99.0.4844.84"}
脚本扩展信息：Violentmonkey 2.13.0
脚本版本信息：2022.05.01.1
当前访问域名：github.com
错误信息：[Fonts shadowColor]: SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

- 是否同时运行了其他浏览器扩展？
uBlock Origin，关闭仍然报错

- 是否同时运行了其他油猴脚本？
AC-baidu、关闭仍然报错

**附加信息**  （在此处添加有关此问题的任何附加信息）
1. 重装脚本无法修复错误
2. 同台电脑，百分浏览器正常

**Comment by F9y4ng** [comment]
是否使用了 Chrome++ 这类的破解dll，或是绿色修改版的Chrome？如果是请参阅 #80 的处理办法。原则上不会对魔改后浏览器报错进行处理。

建议使用正式版本的浏览器，非正式版或修改版的浏览器和脚本管理器没时间精力去兼容。

**Comment by F9y4ng** [comment]
### 尝试将代码第19行(Greasyfork源)或第21行（Github源）

```javascript
// @require            https://greasyfork.org/scripts/437214-frcolorpicker/code/frColorPicker.js?version=1045723
```
改为
```javascript
// @require            https://greasyfork.org/scripts/437214-frcolorpicker/code/frColorPicker.js?version=1047988
```

### 然后，清空浏览器缓存后，重新尝试打开之前出错的站点，看是否还有报错？

### 如仍旧报错，请按 #80 的错误捕捉方式将日志打包上传至github。

**Comment by F9y4ng** [comment]
version [2022.05.15.1](https://github.com/F9y4ng/GreasyFork-Scripts/raw/master/Font%20Rendering.user.js) should be fixed.
