### ISSUE TITLE
兼容性问题：金山文档在线版

### ISSUE THREAD

**Issue by LuoZIren** [F9y4ng/GreasyFork-Scripts#91]
具体问题：使用了字体渲染的在线金山文档页面，文档中的图片会疯狂闪动，作者可以参考以下[这个界面](https://kdocs.cn/l/cc8vCO4vr4kc)，如果能修复一下，万分感谢♥

**Comment by F9y4ng** [comment]
昨天[version 2022.06.04.2](https://github.com/F9y4ng/GreasyFork-Scripts/raw/master/Font%20Rendering.user.js)的紧急更新已修复该问题，请及时升级。

**Comment by F9y4ng** [comment]
先看看是否是字体缩放功能造成此问题？（如果是，请及时升级至 v2022.06.04.2 版本）

你给出的那个URL在我本地是没有你描述的图片闪动问题，建议你排除一下你本地脚本或是插件冲突的情况。

**Comment by F9y4ng** [comment]
本周更新版本已针对工具型网站（如在线文档、在线编辑器、在线IDE等）增添了“**文字粗体附加描边时样式错误的修正开关**”。

如在工具型网站遇到图片闪烁、页面明显卡顿等情况，可打开脚本设置界面（Alt+P）,找到 **粗体修正** 复选框，将 **√** 去掉，保存为站点数据独享即可。
