### ISSUE TITLE
[新增功能] 作者菌可以在【搜索引擎跳转工具】中增加对F搜 fsoufsou.com的支持吗？

### ISSUE THREAD

**Issue by build233** [F9y4ng/GreasyFork-Scripts#92]
【搜索引擎跳转工具】脚本很实用，感谢制作！作者菌可以增加对F搜 fsoufsou.com的支持吗？最近这款搜索引擎又复出了，而且感觉不错的亚子。

**Comment by F9y4ng** [comment]
等它稳定运营之后再考虑，好吧？不好说还会不会被封掉（不是被墙而是被关服），否则既浪费时间又对不起观众。

**Comment by F9y4ng** [comment]
升级v2022.08.04.2版本即可体验.
