### ISSUE TITLE
始终无法添加这个自定义字体

### ISSUE THREAD

**Issue by qhq** [F9y4ng/GreasyFork-Scripts#93]
尝试了很多次，页面也确认过，不知道是不是名字中带有2.0，导致程序判断这个名字是错误的，保存就会被删除。
而其他名字怎么试，都无法在列表中看到
https://www.fontke.com/font/173816379/detail/

{"ch":"阿里巴巴普惠体","en":"Alibaba PuHuiTi"}
{"ch":"阿里巴巴普惠体 2","en":"Alibaba PuHuiTi 2","ps":"AlibabaPuHuiTi_2_55_Regular_J"}

**Comment by F9y4ng** [comment]
1. 确认一下你的脚本版本是否是最新版version 2022.06.04.2？ 如果不是，请升级至最新版，然后刷新重试。
2. 如果已是最新版，请按Bug Report模板重新填写ISSUE，以排除本地脚本或扩展冲突的问题。

> 我在本地按你提供的自定义字体代码添加后是没什么问题的，如图：
> ![test](https://user-images.githubusercontent.com/15855068/172888396-7d555f38-0669-442c-93ca-860f3a8e90c3.png)

**Comment by qhq** [comment]
添加只要不按页面上的首选家族名称Alibaba PuHuiTi 2.0，改用Alibaba PuHuiTi 2是可以添加的。但字体列表中不显示这个字体。无法选择的。
