### ISSUE TITLE
[发现错误] 

### ISSUE THREAD

**Issue by qhq** [F9y4ng/GreasyFork-Scripts#94]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
https://github.com/F9y4ng/GreasyFork-Scripts/issues/93
在此反馈中描述的，维护自定义字体可以维护，只要不带.，但实际字体列表中不显示
{"ch":"阿里巴巴普惠体","en":"Alibaba-PuHuiTi-Medium"}
{"ch":"阿里巴巴普惠体 2","en":"Alibaba PuHuiTi 2"}
第一个是阿里巴巴普惠体1版本，可以正常在字体列表中显示选择。
但第二个2.0版本，维护后，不显示字体选择。

**错误再现**  （重现行为的步骤）
任何网站

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
![image](https://user-images.githubusercontent.com/3319385/172970368-b92e3da1-67fc-4369-ba99-5a99d294572c.png)
字体选择界面应该可以选择普惠体2

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：win11
- 浏览器 [_如 Chrome_]：Edge
- 版本 [_如 93.0.4577.63_]：104.0.1278.2
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：v4.17.6161
- 运行的脚本名称 [_如 Font Rendering_]：Font Rendering (Customized)
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.06.04.2
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
已捕捉到字体名称检测函数对半角句号的遗漏，下个周更新会修正该bug，感谢反馈。
