### ISSUE TITLE
[发现错误] 天猫超市，替换字体后，部分「按钮/图标」显示异常

### ISSUE THREAD

**Issue by oahnaLiew** [F9y4ng/GreasyFork-Scripts#95]
**描述错误信息**  （清楚而简洁地描述了错误是什么）

天猫超市，替换字体后，部分「按钮/图标」显示异常

**错误再现**  （重现行为的步骤）

1. 天猫超市，搜索任意商品
2. 商品列表，「购物车」按钮显示异常，无法正确显示「购物车」图标
3. 脚本设置，添加排除元素「`a.addCart.j_AddCart`」，不起作用

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
希望替换自定义字体的同时，保持图标的正常显示

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）
![图片](https://user-images.githubusercontent.com/26448604/173227972-83f3bf4d-fc2c-4169-8f7b-4c8215f7a937.png)

**客户端信息：**  （请填写以下信息）
- 操作系统：Win10
- 浏览器：Firefox Developer Edition
- 版本：102.0b6 (64 位)
- 脚本扩展：TamperMonkey
- 脚本扩展版本：4.17.6161
- 运行的脚本名称：字体渲染（自用脚本）
- 运行的脚本版本：2022.06.12.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
否

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]
否

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
在 **需要渲染的网页元素** 中，追加 `:not([class*='j_AddCart'])`，保存为站点独享。
