### ISSUE TITLE
[发现错误] 字体渲染脚本在MDN网站巨卡

### ISSUE THREAD

**Issue by lvzhenbo** [F9y4ng/GreasyFork-Scripts#96]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
脚本在MDN Web Docs上出现严重的性能问题，网页巨卡

**错误再现**  （重现行为的步骤）

1. _去[MDN](https://developer.mozilla.org/zh-CN/)网址_
2. _网页发生卡顿现象_

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）
网页流畅运行

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

**客户端信息：**  （请填写以下信息）
- 操作系统：Win10 21H2
- 浏览器 ：Chrome 
- 版本 ：102.0.5005.115
- 脚本扩展 ：TamperMonkey
- 脚本扩展版本 ：4.16.1
- 运行的脚本名称 ：字体渲染（自用脚本）
- 运行的脚本版本 ：2022.06.12.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by lvzhenbo** [comment]
可能是这个旋转动画导致的，这个动画用了各种符号
![image](https://user-images.githubusercontent.com/32427677/173321959-9ae77d09-c784-4abb-bfb5-a65a9f90723e.png)

**Comment by F9y4ng** [comment]
## 问题原由
由于字体阴影的设定与svg的旋转动画、透明度变化效果进行效果叠加，造成页面不断重绘，使得性能降低而卡顿。

## 解决办法：
关闭字体渲染的字体阴影（设置为0）即可恢复。

（P.S. 这个首页基本很少会访问，似乎可以忽略它了。）

**Comment by F9y4ng** [comment]
## 问题原由
由于字体阴影的设定与svg的旋转动画、透明度变化效果进行效果叠加，造成页面不断重绘，使得性能降低而卡顿。

## 解决办法：
在**排除渲染的HTML标签**中，追加`,.dark *`，保存为站点独享即可。
