### ISSUE TITLE
Safari浏览器，使用Tampermonkey，点击菜单无法弹出设置页面

### ISSUE THREAD

**Issue by Jacob-god** [F9y4ng/GreasyFork-Scripts#97]
Safari 版本15.5 
Tampermonkey : 4.17.6162

<img width="386" alt="image" src="https://user-images.githubusercontent.com/51256143/174495386-08a19024-dbc9-40c2-a294-b4b699d66f9c.png">

**Comment by F9y4ng** [comment]
> Tampermonkey : 4.17.6162

是所有网站均打不开设置页面，还是仅此一个站点打不开？ 

MAC不在身边，暂时处理不了。
