### ISSUE TITLE
[发现错误] Firefox数据源暂无数据

### ISSUE THREAD

**Issue by acctZCW** [F9y4ng/GreasyFork-Scripts#99]
**描述错误信息**  （清楚而简洁地描述了错误是什么）
在Firefox的字体渲染脚本当中，无法选取自定义字体，显示“数据源暂无数据”

**错误再现**  （重现行为的步骤）
使用Firefox安装脚本即可。

已根据说明文档进行了重建缓存，仍然无效。
且在新edge浏览器上试验后edge浏览器能够成功获取字体列表，故有可能是Firefox上的特殊问题。

**预期结果**  （清晰明了地描述你所期待想要什么样的结果）

**屏幕截图**  （如果适用，请添加屏幕截图以帮助解释您的问题）

![图片](https://user-images.githubusercontent.com/40493551/176576389-3fa707fa-e162-4668-a17f-9e6a4c868051.png)

**客户端信息：**  （请填写以下信息）
- 操作系统 [_如 Win10_]：Windows11 22000.778
- 浏览器 [_如 Chrome_]：Firefox 
- 版本 [_如 93.0.4577.63_]：101
- 脚本扩展 [_如 TamperMonkey_]：TamperMonkey
- 脚本扩展版本 [_如 4.13.6138_]：4.17.6161
- 运行的脚本名称 [_如 Font Rendering_]：字体渲染
- 运行的脚本版本 [_如 V3.8.20210101.1_]：2022.6.25.1
- 其他信息：

_请预先排除与你本地其他扩展或脚本的冲突，尽量在仅运行本脚本的情况下测试_
- 是否同时运行了其他浏览器扩展？ [例如 Dark Reader、uBlock Origin等]
运行有privacy badge和ublock origin，关闭后仍然存在问题。
且在edge同环境下测试运行正常

- 是否同时运行了其他油猴脚本？ [例如 AC-baidu、Github Acceleration等]

**附加信息**  （在此处添加有关此问题的任何附加信息）

**Comment by F9y4ng** [comment]
外出，暂无法测试。

你试试 Violentmonkey 是否还存在此问题？
